### ISSUE TITLE
add nushell completion

### ISSUE THREAD

**Issue by melMass** [prefix-dev/pixi#1000]
### Problem description

I wanted to PR it but did not find the time yet, here is the output from clap generate I did recently: [nushell completion for pixi](https://github.com/nushell/nu_scripts/blob/main/custom-completions/pixi/pixi-completions.nu)

**Comment by baszalmstra** [comment]
This has recently been added with:

- https://github.com/prefix-dev/pixi/pull/1625
- https://github.com/prefix-dev/pixi/pull/1627
