### ISSUE TITLE
Windows ARM64 build

### ISSUE THREAD

**Issue by chawyehsu** [prefix-dev/pixi#1008]
### Problem description

Don't know how much work is needed to bring pixi to Windows ARM but I believe it's certainly worth a try when I see https://conda.anaconda.org/conda-forge/win-arm64/, definitely not high priority though.

I might investigate it since I just got a Windows ARM machine.

**Comment by ruben-arts** [comment]
Cool we're definitely open to this. However we have not development machine we can try this on. So If you would take on some of the testing that would be great!

**Comment by pavelzw** [comment]
You could run a Windows arm VM using Parallels on an arm MacBook.

**Comment by baszalmstra** [comment]
@chawyehsu I created a pixi ARM build in this PR: https://github.com/prefix-dev/pixi/pull/1053

You can download a version from CI here: https://github.com/prefix-dev/pixi/actions/runs/8418054925/artifacts/1355116844

If you can I would love for you to give it a try!

**Comment by pavelzw** [comment]
<img width="1377" alt="image" src="https://github.com/prefix-dev/pixi/assets/29506042/1168f30c-ef8e-4517-a500-1ff4d59c558b">
seems to work for me

**Comment by chawyehsu** [comment]
@baszalmstra It works great!

<img width="960" alt="image" src="https://github.com/prefix-dev/pixi/assets/5764917/7358cb46-c59b-459b-a44b-acf90ad860c8">
