### ISSUE TITLE
Allow defining a default manifest-path which is used by all `pixi` commands irrespective of what folder you happen to be in

### ISSUE THREAD

**Issue by dhirschfeld** [prefix-dev/pixi#1011]
### Problem description

Sometimes you want your Python/conda environment to be available when you're not in the project folder, and it's very cumbersome to have to manually specify `--manifest-path` in the CLI for every single command.

This is particularly the case where you start a subshell for a specific project - my expectation would be that all commands would be associated to the prroject the subshell was started for, irrespective of where I cd.

***xref:*** https://discord.com/channels/1082332781146800168/1214676647526146128

**Comment by synapticarbors** [comment]
This might be tangentially related, but attempts to solve a similar problem. I've wondered (and mentioned on the discord) if it would be possible to expose an environment variable that acted like setting the `--manifest-path`. The comment on the discord was that this could create some confusion when the env variable is set to one project, but then you cd into a different project in terms of determining what gets precedence. 

I think @dhirschfeld is asking for something more limited, which would be to lock in a manifest path whenever you run `pixi shell` that persists for the life of that shell. I just wanted to throw out another idea that gets at the same issue. I also wanted to give my formal +1 to thinking about workflows that don't just live in a particular project directory. My use cases include:

- environments that are common to multiple projects/repos
- basic data analysis where I want access to an environment, but may be working in some directory where data lives outside of the project or a scratch directory where I'm playing around with code snippets or a jupyter notebook.

**Comment by pavelzw** [comment]
How about `alias pixi="pixi --manifest-path=/path/to/pixi.toml`? Creating an extra config option seems a bit over the top IMO and incentivizes bad (sorry if i'm stepping on someone's toes here 😅) workflows.

**Comment by dhirschfeld** [comment]
I have exactly the same usecases and would actually like this feature for that reason - running in a subshell would be ~same as running in an activated environment.

I also agree an env var (e.g. `PIXI_MANIFEST_PATH`) could be a good way to implement it. It could default to `.` if not set to recover the existing behaviour and then a subshell would just set this emv var for the manifest path it was started for.

**Comment by dhirschfeld** [comment]
I think that the directory based projects workflow is an awkward fit for interactive data analytics use cases so am very keen to see both supported.

I think this change could enable that without any big changes required to the default project based workflow.

**Comment by dhirschfeld** [comment]
The confusion about operating in a different environment than the one defined by the current directory is a valid concern but one that could in large part be eliminated by having your shell prompt display the active pixi manifest path.

**Comment by ruben-arts** [comment]
To avoid confusing names, the setting of the manifest path in a `pixi shell` instance will be worked on for sure. 

For the rest of this issue I think it's better to continue in [this](https://github.com/prefix-dev/pixi/discussions/1021) discussion, as it is not just a feature request but a change in the vision we have for pixi.
