### ISSUE TITLE
Add found global configuration files to `pixi info`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1013]
### Problem description

![image](https://github.com/prefix-dev/pixi/assets/29506042/89213b34-d38d-4aa5-a1af-a0b6a38124c0)
would be nice to see the config file here if it exists and is used.

**Comment by wolfv** [comment]
That should already be the case, actually.

**Comment by pavelzw** [comment]
i'm using the latest build from #988 (https://github.com/prefix-dev/pixi/pull/988/commits/208f38a9385ce286fdffebd4d15eef3f893dfd35)
![image](https://github.com/prefix-dev/pixi/assets/29506042/407433b0-4c98-4a4a-a11b-72e575c7f1c5)
