### ISSUE TITLE
Please provide a specific exit code when downloading conda pkg failed.

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#1023]
### Problem description

When I use pixi to install conda pkgs in GitLab CI, I received the following error, and it might succeed if retry.

<img width="923" alt="image" src="https://github.com/prefix-dev/pixi/assets/38552291/cf0463c5-b3e9-4cf6-bd7b-e87e8ddcb398">

I hope pixi can provide a specific exit code for this situation, so I can make pipeline retry automatically.

**Comment by zen-xu** [comment]
Additionally, I'm not clear on why the connection is closed; all the requests I see in the server-side nginx are successful.
<img width="1681" alt="image" src="https://github.com/prefix-dev/pixi/assets/38552291/ee0f5a53-1a6f-4d9c-9244-470f46755a99">

**Comment by wolfv** [comment]
Thanks @zen-xu! I am wondering if there is some form of rate-limiting on the server side? We are parallelizing the requests and we should also be retrying for 3 times. Is it always failing or sometimes failing?

**Comment by zen-xu** [comment]
This occurs occasionally, but upon retrying, it is mostly successful.

**Comment by ruben-arts** [comment]
Closing this issue as there is not industry standard for the exit code.
