### ISSUE TITLE
0.17.0 regression: ~ in pip version name is not supported anymore

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#1031]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I uploaded the problematic lock file to https://gist.github.com/traversaro/88ad3a7c878cb2b743c5330f01d52aad .

```shell
git clone https://gist.github.com/traversaro/88ad3a7c878cb2b743c5330f01d52aad pipversionpixi017
cd pipversionpixi017
curl -fsSL https://pixi.sh/install.sh | PIXI_VERSION=v0.16.1 bash
pixi run echo
rm -rf .pixi
curl -fsSL https://pixi.sh/install.sh | PIXI_VERSION=v0.17.0 bash
pixi run echo
```

The first `pixi run echo` works, the second fails with:
~~~
traversaro@IITBMP014LW012:~/reproduce-pixi017-regr$ pixi run echo
⠁ updating pypi packages in 'default'
thread 'main' panicked at /home/runner/work/pixi/pixi/src/install_pypi.rs:385:58:
could not create site-packages: Failed to read metadata: from /home/traversaro/reproduce-pixi017-regr/.pixi/envs/default/lib/python3.12/site-packages/yarp-3.9.0~dev.dist-info

Caused by:
    after parsing 3.9.0, found "~dev" after it, which is not part of a valid version
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
~~~

### Issue description

See the example.

### Expected behavior

I would expect the `pixi run echo` to work.

**Comment by traversaro** [comment]
The workaround is either to use an older pixi version like 0.16.1. In my specific case the problem was in a package I controlled (and I was aware of the problem, I just had procrastinated fixing it): https://github.com/conda-forge/yarp-feedstock/issues/42 . 

However, this problem may be annoying if you do not control the packages you are trying to install as in theory this legacy version style are still supported by pip, even if unsupported: https://github.com/pypa/pip/issues/12063 .

**Comment by tdejager** [comment]
Okay so I've investigated it a bit and it happens when the `pypi` install part of pixi scans the site-packages folder and tries to create a uv `SitePackages` mapping, i.e:

```rust
    let installed = SitePackages::from_executable(&venv).expect("could not create site-packages");
```
which is needed even though there are no pypi-packages, e.g old ones can still be left in the environment, that need to be removed.

So to fix we have to provide a filtered list of packages, that are installed by `uv-pixi` so to say, but that would imply either constructing that `SitePackages` struct ourselves or making a PR to work on a filtered version e.g filtered by INSTALLER. 
I don't think we can convince uv to accept the `~` in the version specifier for now, also if its not allowed any longer by  pep-440, a PEP from 2013, maybe that's a good thing :)

**Comment by traversaro** [comment]
> I don't think we can convince uv to accept the `~` in the version specifier for now, also if its not allowed any longer by pep-440, a PEP from 2013, maybe that's a good thing :)

Ack, I imagined that. Anyhow, I think it was useful at least to have this issue for people experiencing the same problem. Just to understand, as uv was integrated in pixi 0.16.0 (https://github.com/prefix-dev/pixi/releases/tag/v0.16.0), do you have any idea why this worked in pixi 0.16.1 and not anymore in 0.17.0 ?

**Comment by tdejager** [comment]
Hmm could be that they changed the `VersionSpecifier` code, they vendor the pep440 parsing in uv currently. We would need to do some code excavation to be sure 🤠

**Comment by traversaro** [comment]
> I don't think we can convince uv to accept the `~` in the version specifier for now, also if its not allowed any longer by pep-440, a PEP from 2013, maybe that's a good thing :)

Just to frame a bit more the problem, pep-440 may be from 2013, but as far as I know the warning complaining about this was added in https://github.com/pypa/pip/pull/11945, that was release in summer 2023.

**Comment by traversaro** [comment]
> Hmm could be that they changed the `VersionSpecifier` code, they vendor the pep440 parsing in uv currently. We would need to do some code excavation to be sure 🤠

Ahh, that make sense, thanks!

**Comment by traversaro** [comment]
If you think the issue is `wontfix` (and probably that make sense), feel free to close it, thanks!

**Comment by tdejager** [comment]
Let's do that for now and re-open if more people experience this issue.

> > I don't think we can convince uv to accept the `~` in the version specifier for now, also if its not allowed any longer by pep-440, a PEP from 2013, maybe that's a good thing :)
> 
> Just to frame a bit more the problem, pep-440 may be from 2013, but as far as I know the warning complaining about this was added in [pypa/pip#11945](https://github.com/pypa/pip/pull/11945), that was release in summer 2023.

For sure! Thanks for the carification.
