### ISSUE TITLE
Problem to install black[jupyter]

### ISSUE THREAD

**Issue by partrita** [prefix-dev/pixi#1041]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
❯ pixi global install black
✔ Installed package black 24.3.0 py312h7900ff3_0 from conda-forge
  These executables are now globally available:
   -  black
   -  blackd
```

```shell
❯ pixi global install black-jupyter
⚠️No executable entrypoint found in package black-jupyter, are you sure it exists?
✔ Installed package black-jupyter 24.3.0 hd8ed1ab_0 from conda-forge
```

```shell
❯ pixi global list
Global install location: /home/fkt/.pixi
├── glances 3.4.0.3
|   └─ exec: glances
├── black 24.3.0
|   └─ exec: black, blackd
├── jupyter-black 0.3.4
├── nb_black 1.0.7
├── git 2.42.0
|   └─ exec: git-upload-pack, scalar, git, gitk, git-upload-archive, git-receive-pack, git-cvsserver, git-shell
├── cowpy 1.1.5
|   └─ exec: cowpy
├── pre-commit 3.5.0
|   └─ exec: pre-commit
├── ruff 0.0.292
|   └─ exec: ruff
├── black-jupyter 24.3.0
└── git-lfs 3.4.0
    └─ exec: git-lfs

```

```shell
❯black .
Skipping .ipynb files as Jupyter dependencies are not installed.
You can fix this by running ``pip install "black[jupyter]"``
No Python files are present to be formatted. Nothing to do 😴
```

### Issue description

I've tried to install black linter for my jupyter notebook.

### Expected behavior

Seamless install.

**Comment by ruben-arts** [comment]
You'll need a feature mentioned in https://github.com/prefix-dev/pixi/issues/342. We've yet to fix this. But the gist is that we currently have no way to add libraries to a global executable env.

**Comment by ruben-arts** [comment]
For the time being the best experience you can get is adding black to the project you're using. I'll close this issue for now to avoid duplicate tracking.
