### ISSUE TITLE
$XDG_CONFIG_HOME on macOS has an unexpected behaviour

### ISSUE THREAD

**Issue by anjos** [prefix-dev/pixi#1049]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
# on a macOS system, execute the following:
$ cat "change_ps1 = false" >> $HOME/.config/pixi/pixi.toml
$ pixi shell
# should not change one's prompt to include the environment name
```

### Issue description

My understanding is that `$XDG_CONFIG_HOME`, if unset, defaults to `$HOME/.config` [as per specifications](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html).

However, I see that on macOS pixi searches at `INFO pixi::config: Global config not found at /Users/userid/Library/Application Support/pixi/config.toml`

I checked the package [xdg-base-dirs](https://pypi.org/project/xdg-base-dirs/), and it reports `~/.config` as the default on macOS as well.

### Expected behavior

If `$XDG_CONFIG_HOME` is set, then pixi should look for its configuration at that base directory.

Otherwise, it should use the default which is `$HOME/.config` on macOS.

**Comment by chawyehsu** [comment]
There you go #1050 ;)
