### ISSUE TITLE
Proposal for `pixi global add` vs `pixi install`

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#106]
It was unclear to people what the difference was between 

```shell
pixi add
# and 
pixi install
```

We based this design on cargo which has the same semantics. 

It was unclear to people that one command acted on the local project whereas the other acts on your system. We propose to change the `pixi install` command to be nested under a new subcommand `global`. This resembles [`yarn global`](https://classic.yarnpkg.com/lang/en/docs/cli/global/). The result would be:

```
pixi global add python
```

`global` signifies that we're running a command that works globally and `add` is the same name used for adding a dependency to a project.

This also opens the door to some more subcommands that we might want to add that act on the system- instead of the project level.

```
pixi global ls # List all installed commands
pixi global remove # Remove a globally installed command
pixi global run python -m "bla" # Run a command in a temporary prefix with python installed
pixi global bin # Prints the binary location of globals
```

This issue is here to start a discussion on whether or not we should make this change.

**Comment by ruben-arts** [comment]
#113

**Comment by ruben-arts** [comment]
Closed by #113

**Comment by ruben-arts** [comment]
We're not fully sure about the name `add` in the global level as we're actually installing binaries. What do you think?

**Comment by pavelzw** [comment]
`pixi global install` is could also work imo.

**Comment by pavelzw** [comment]
Another problem with `pixi global run`: only because a feedstock is named `xyz`, it doesn't mean that it provides a binary called `xyz`. We should also think about what happens if it provides other binaries. Maybe something like `pixi global run <feedstock-name>/<binary-name>` if the binary is not clear defaulting to `pixi global run <feedstock-name>/<feedstock-name>`?

**Comment by ruben-arts** [comment]
Yeah, you're right. The `run` command needs some extra thought as the rest of the global commands will. We just added the idea of global so it is good to think about these ergonomics. Do you @pavelzw  have more thoughts on the install commands?

**Comment by traversaro** [comment]
> We're not fully sure about the name `add` in the global level as we're actually installing binaries. What do you think?

I also prefer `pixi global install`. `pixi add` technically does not install anything, so it make sense to use a different verb for `pixi global install` that does something quite different.

**Comment by pavelzw** [comment]
I think that `pixi global install` works better. But if this is the only place where `install` is used as a command, this is also suboptimal.
What about using `pixi install xyz` for the local environment and `pixi global install abc` for the global environment?

**Comment by dhirschfeld** [comment]
maybe it could just as an argument rather than a command? i.e.
```
pixi install --global xyz
```

**Comment by ruben-arts** [comment]
Thanks for your reactions/input. The `--global` might be confusing as it will not exist on all commands. I'll change it to `global install` as the consensus seems to be that that is better than `global add` 

For now, I'll keep `pixi add xyz` as it is the same for `yarn`, `cargo`, and `poetry` so I think it is still the best option for that out of familiarity.
