### ISSUE TITLE
"Decorated" progress report should be disabled when stdout is not a TTY

### ISSUE THREAD

**Issue by vlad-ivanov-name** [prefix-dev/pixi#1060]
### Problem description

Kind of a follow-up from the example in https://github.com/prefix-dev/pixi/issues/1004 : when two commands are run in the same pixi environment, one piped into another, the output is often mangled as both processes are trying to output "interactive" messages that erase the command line in-place. The output then becomes a random combination of different message lines.

```
pixi run --frozen --manifest-path pixi.toml echo | pixi run --frozen --manifest-path pixi.toml cat
⠁ updating packages in 'default'
⠁ updating packages in 'default'
⠁ updating packages in 'default'
```

Solution: detect whether stdout/stdin is a tty with https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html or https://crates.io/crates/is-terminal and disable "interactive" output accordingly

**Comment by baszalmstra** [comment]
Yeah thats a bit annoying, especially the errors being overwritten. 

We always output interactive messages to stderr. In your example, stderr would still be interactive right? Since you only pipe stdout.

**Comment by baszalmstra** [comment]
I think `pixi info --json` is an example where that might not be the case. 

I implemented a `--no-progress` flag in https://github.com/prefix-dev/pixi/pull/1105 which removes all decorated progress bars. I hope that can help with this problem?
