### ISSUE TITLE
Show path for pypi source dependencies in `pixi list`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1085]
### Problem description

<img width="886" alt="image" src="https://github.com/prefix-dev/pixi/assets/29506042/e7c75254-78ad-4695-ab04-42b3738f3e7d">

We could add the path there.

**Comment by pavelzw** [comment]
And maybe an editable identifier? for example `-> .`

**Comment by tdejager** [comment]
Yes, totally, should be relatively straight-forward.
