### ISSUE TITLE
Add descriptions to tasks

### ISSUE THREAD

**Issue by roaldarbol** [prefix-dev/pixi#1113]
### Problem description

Suggestion is two-fold: 1) Adding a "description" field for tasks, and 2) echoing those descriptions on `pixi task list`.

Quite a lot of use-cases, there's **for future others**: if you have colleagues that need to use your project, it might be useful to have those descriptions. **For current self**: for oneself to remember what each task does without leaving the command line). And of course **for future self**: when returning to those commands at a later stage, it would be a nice reminder what they are for - just as annotating code is.

**Comment by ruben-arts** [comment]
I like the idea, design wise I would also print it in `pixi run` where pixi already prints the command itself.

**Comment by roaldarbol** [comment]
Yeah, that would be great too!

**Comment by ruben-arts** [comment]
Closed as implemented in #1479
