### ISSUE TITLE
Global read-only cache dir

### ISSUE THREAD

**Issue by gzm55** [prefix-dev/pixi#1126]
### Problem description

Is it possible to provided a system-level global cache dir. It is read-only and searched before the user level cache dir. This cache may be managed by admin of the machine.

**Comment by ruben-arts** [comment]
There is currently no way to serve multiple cache dirs. 

I've heard a request like this before where the maintainers wanted to remove "bad" packages from all environments and force a reinstall if the user wants to continue their environment. This is however the opposite of the logic we used to design our installations. 

We either hardlink or reflink(depends on filesystem) our packages from the cache to the environments. Thus deleting cache won't break environments as the data will stay alive as long as there is an existing link to it. 

If this counts for you too, I would love a chat to understand the use-case better, and to findout how we can support your case.

**Comment by gzm55** [comment]
> There is currently no way to serve multiple cache dirs.
> 
> I've heard a request like this before where the maintainers wanted to remove "bad" packages from all environments and force a reinstall if the user wants to continue their environment. This is however the opposite of the logic we used to design our installations.
> 
> We either hardlink or reflink(depends on filesystem) our packages from the cache to the environments. Thus deleting cache won't break environments as the data will stay alive as long as there is an existing link to it.
> 
> If this counts for you too, I would love a chat to understand the use-case better, and to findout how we can support your case.

Our dev machines are shared by multi users and each one has almost same caches. So from a os admin view, it is better to put the shared packages in a system cache, and each developer maintians his own case overlay on the system one.

**Comment by gzm55** [comment]
> > There is currently no way to serve multiple cache dirs.
> > I've heard a request like this before where the maintainers wanted to remove "bad" packages from all environments and force a reinstall if the user wants to continue their environment. This is however the opposite of the logic we used to design our installations.
> > We either hardlink or reflink(depends on filesystem) our packages from the cache to the environments. Thus deleting cache won't break environments as the data will stay alive as long as there is an existing link to it.
> > If this counts for you too, I would love a chat to understand the use-case better, and to findout how we can support your case.
> 
> Our dev machines are shared by multi users and each one has almost same caches. So from a os admin view, it is better to put the shared packages in a system cache, and each developer maintians his own case overlay on the system one.

or we can use some features like `pkgs_dirs` in condarc to support a multi-user cache dir.

ref: https://github.com/mamba-org/mamba/issues/488

**Comment by ruben-arts** [comment]
If it's used to lower diskspace this makes sense. For the conda packages this logic could be located in `rattler`.

**Comment by baszalmstra** [comment]
See: https://github.com/mamba-org/rattler/issues/43

**Comment by ruben-arts** [comment]
Closing in favor of https://github.com/mamba-org/rattler/issues/43, thanks @baszalmstra

**Comment by gzm55** [comment]
> Closing in favor of [mamba-org/rattler#43](https://github.com/mamba-org/rattler/issues/43), thanks @baszalmstra

thanks to @baszalmstra and @ruben-arts . mamba-org/rattler#43 resolve the reading and user writing problem. To manage the os level cache dir, we could have some `promte-cache`  method to move unmodified packages from the user cache to the shared cache dir.

**Comment by ruben-arts** [comment]
I don't think I understand the request. Does the maintainer want to copy from user level caches to the os level cache?

**Comment by gzm55** [comment]
> I don't think I understand the request. Does the maintainer want to copy from user level caches to the os level cache?

yes, the os admin does not know what packages will be used, so at very first the shared os cache is empty; after somedays, the disk usage is nearly full, then the os maintainer wants to remove redundant packages, at this moment, he need copy and remove cached pkgs.

**Comment by oliver-batchelor** [comment]
Second, we have multiple uses for this on shared user machines. Our admins currently look at the use of any kind of environment for student use very unfavourably since it just results in a lot of network traffic and wasted storage. 

Another use is for sharing a cache, e.g. running tests in Docker and sharing the cache without polluting it with unreadable files.
