### ISSUE TITLE
Environments folders not deleted when removed from `pixi.toml`

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/pixi#1132]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell

[project]
name = "test"
version = "0.1.0"
description = "Add a short description here"
authors = ["user<user.name@domain.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[dependencies]
python = "3.11.*"
requests = "*"
numpy = "*"

[feature.test.dependencies]
pytest = "*"

[environments]
test = ["test"]

```

### Issue description

Running `pixi install` with the above configuration results in 2 environments, `default` and `test`. Remove the `test` env configuration from `pixi.toml` and rerun `pixi install`. The envs folders are not updated and the deleted env's folder/s remain.

Current: `.pixi/envs/test` folder remains.

### Expected behavior

`.pixi/envs/test` folder is removed.

**Comment by ruben-arts** [comment]
I think I rather have a `pixi clean` command to clean on request. If you switch between branches this might already be a bigger annoyance than having the environment which doesn't break or interfere with other environments. 

I could be convinced otherwise but this is the first idea I have on it.

**Comment by vigneshmanick** [comment]
agree that `pixi clean` makes the most sense here. In a similar vein, `pixi global` also gets a `clean` option that clears the `rattler cache` ?

**Comment by ruben-arts** [comment]
There is now a `pixi clean` and `pixi clean cache`
