### ISSUE TITLE
Environment variables do not work when using cmd in tasks

### ISSUE THREAD

**Issue by nicornk** [prefix-dev/pixi#1154]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Task:

```
just-test = { cmd = [    
    "export STACK_NAME=fargate-batch-job",
    "&&",
    "echo $STACK_NAME"

] }
```

```shell
pixi run just-test
✨ Pixi task (ci): "export STACK_NAME=fargate-batch-job" && "echo $STACK_NAME"
export STACK_NAME=fargate-batch-job: command not found

Available tasks:
        build-wheel
        deploy
        download_database
        just-test
        just-test-2
        postinstall-production
        start
        test
(grayskull) (base) ➜  oligo 
```

Task:

```
just-test-2 = "export STACK_NAME=fargate-batch-job && echo $STACK_NAME"
```

```shell
✨ Pixi task (ci): export STACK_NAME=fargate-batch-job && echo $STACK_NAME
fargate-batch-job
(grayskull) (base) ➜  oligo 
```

### Issue description

It seems that export / referencing environment variables in the "cmd" way to define tasks is not working as expected.

### Expected behavior

Both examples should work the same way.

**Comment by ruben-arts** [comment]
This is actually because of this issue: https://github.com/prefix-dev/pixi/issues/837

So will close it, in favor of that.

For now, either use the multi-line toml notation or separate per word in an array.

```toml
just-test = { cmd = """
    export STACK_NAME=fargate-batch-job
    &&
    echo $STACK_NAME
"""}
just-test2 = { cmd = [    
    "export",  "STACK_NAME=fargate-batch-job",
    "&&",
    "echo", "$STACK_NAME"
] }
```

**Comment by nicornk** [comment]
ty for the quick reply!
