### ISSUE TITLE
Parenthesis fail if used in `pixi run`

### ISSUE THREAD

**Issue by roaldarbol** [prefix-dev/pixi#1161]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi run Rscript -e "data.frame()"
```

### Issue description

It is possible to run inline R commands. The following works:
```shell
pixi run Rscript -e "1"
```

But the above doesn't. It gives the error:
```shell
  × deno task shell failed to parse 'Rscript -e data.frame() ': Unexpected character.
  │   ()
  │   ~
```

### Expected behavior

I would expect the code to run without any issues.

**Comment by ruben-arts** [comment]
This should be fixed by #1582
