### ISSUE TITLE
Support `find-links` for pypi dependencies

### ISSUE THREAD

**Issue by roym899** [prefix-dev/pixi#1163]
### Problem description

Similar  `index-url` and `extra-index-url` (see #1094), some projects (for example, [Rerun's prerelease](https://github.com/rerun-io/rerun/releases/tag/prerelease)) require `find-links` instead.

**Comment by tdejager** [comment]
The flat index that I mentioned in #1094 should cover this. It's the same thing but the UV wording for it :)

**Comment by ruben-arts** [comment]
Closing in favor of #1094 as it would also be implemented in #1225
