### ISSUE TITLE
Docs for `--frozen` differ between website and `pixi install --help`

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#1165]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```
nu ❯ pixi install --help
Install all dependencies

Usage: pixi install [OPTIONS]

Options:
[...]
      --frozen                         Don't check or update the lockfile, continue with previously installed
                                       environment [env: PIXI_FROZEN=]
[..]
```

This differs from https://pixi.sh/latest/reference/cli/#install

### Issue description

Docs for `--frozen` differ between website and `pixi install --help`.
To me, they read quite differently.
@wpbonelli and I wondered which one of them was the correct description.

### Expected behavior

The docs are exactly the same

**Comment by ruben-arts** [comment]
I'll fix this, what is the difference you read from it?

`pixi install --frozen` will install what is in the lockfile. So it will never verify that the lockfile is actually up to date with the manifest.
