### ISSUE TITLE
`pixi self-update` fails on symlink-ed home directory

### ISSUE THREAD

**Issue by apoorvkh** [prefix-dev/pixi#1171]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

—

### Issue description

When I run:

```shell
pixi self-update
```

I get the following output:

```
  × pixi is not installed in the default location:
  │ 
  │ - Default pixi location: /users/apoorvkh/.pixi/bin/pixi
  │ - Pixi location detected: /nfs/home/apoorvkh/.pixi/bin/pixi
```

My `$HOME` is `/users/apoorvkh`. But this is actually a bit of a red herring, since I think `/users/apoorvkh` is a symlink to `/nfs/home/apoorvkh`.

`pixi self-update --force` does work, but I just wanted to flag this edge case. Thanks!

### Expected behavior

—

**Comment by ruben-arts** [comment]
He did pixi install it in the original location or did it move it into that location of the symlink?

**Comment by apoorvkh** [comment]
Hey, I believe pixi was installed to `/users/apoorvkh/.pixi` (which is both `$HOME` and a symlink). So I think the "Pixi location detected" is only considering the `realpath` in this case.

**Comment by ruben-arts** [comment]
Does forcing it put it in the incorrect location or does it work?

**Comment by apoorvkh** [comment]
To try to reproduce this, I would create a symlink from `~/.pixi` to some other location, then install an older version of pixi, then try to run `pixi self-update`.

**Comment by ruben-arts** [comment]
Could you clarify the expected behavior?

**Comment by chebee7i** [comment]
I've hit this too now. 
```console
$ pixi self-update
  × pixi is not installed in the default location:
  │ 
  │ - Default pixi location: /home/user/.pixi/bin/pixi
  │ - Pixi location detected: /physical/something/user/.pixi/bin/pixi
  │ 
  │ It can happen when pixi has been installed via a dedicated package manager (such as Homebrew on macOS).
  │ You can always use `pixi self-update --force` to force the update.
```
These paths are interchangeable because they are the same if you `realpath` the default pixi location.  I can indeed update with `--force`, but the warning will reappear the next time...but this shouldn't actually matter. If I happen to put `/home/user/.pixi/bin` on `PATH` and then later decide to put an equivalent path `/physical/something/user/.pixi/bin/pixi` on `PATH` instead...these are the same paths, so there should be no warning about them being installed in the non-default location.

**Comment by apoorvkh** [comment]
Yeah, it’s as @chebee7i says. Sorry to miss the follow-up.

> Could you clarify the expected behavior?

Instead of checking whether “Default pixi location” and “Pixi location detected” are the same path (like string equality), should check whether they resolve to the same file, e.g. with https://docs.rs/same-file

**Comment by apoorvkh** [comment]
For sure! I am starting a draft PR in #2132 with this fix. Still need to test that it works. For the record, I don't have any Rust experience, but this seems pretty straightforward.
