### ISSUE TITLE
`pixi run` behaves differently on cmd.exe and powershell

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1195]
PowerShell:
![image](https://github.com/prefix-dev/pixi/assets/29506042/6e32de13-7118-4740-8952-0a935dcd9884)

CMD.exe
![image](https://github.com/prefix-dev/pixi/assets/29506042/8c797932-b742-429c-a176-3d0fc34ab06e)

The powershell variant is what I would expect since everything behind `run` is being executed in a deno task shell. No clue what cmd.exe does...

**Comment by wolfv** [comment]
Hmmm, the following works in cmd.exe

```
pixi run "echo $CONDA_PREFIX\\bla\\bla"
```

And this works in powershell (notice different quotes):

```
pixi run 'echo $CONDA_PREFIX\\bla\\bla'
```

This might be one of these issues where it's about the quoting in the shell ...

**Comment by pavelzw** [comment]
Well, I guess nothing that pixi can do here 🤷🏻
