### ISSUE TITLE
BUG: pixi keeps adding global package to `%PATH%` until it's too long

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/pixi#1200]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
echo %PATH%
# do something with git
echo %PATH%
# notice duplication
```

### Issue description

I recently started using pixi-controlled git for my (global) git setup on windows, and ran into a problem pretty soon:
```
E:\upstreams\scipy>git log
The input line is too long.
The syntax of the command is incorrect.

E:\upstreams\scipy>@SET "PATH=C:\Users\[...]\.pixi\envs\git\bin:%PATH%"
```

The last line provides a clue - it seems that pixi will add itself to the path _for every invocation_ of git, leading eventually to a path that breaks windows' max size allowed for variables.

### Expected behavior

Do not add `%HOME%\.pixi\envs\<global>\bin` to path on every invocation of a globally installed package.

**Comment by wolfv** [comment]
Thanks! I think adding `setlocal` and `endlocal` fixes this. Will open a PR shortly.
