### ISSUE TITLE
Add `pixi list --explict`

### ISSUE THREAD

**Issue by bollwyvl** [prefix-dev/pixi#1216]
### Problem description

As always: thanks for pixi!

The creaky old `conda list --explicit --md5` format (broken hash, without PyPI deps, and all) is _still_ the most portable thing for feeding into other tools such as `constructor` and dependency scanners.

While it would be _possible_ to make a third-party contraption that extracted this data from the `pixi.lock` file, if the structure of even that is in flux (#1172), having a `pixi list --explicit` in the near term is likely the easiest thing to offer to folk that are otherwise curious about `pixi`, but need to ship installers.

An extra magic bonus would be _not_ having to re-calculate a matrix with something akin to `conda-lock`'s template mechanism:

```bash
pixi list --explicit --format="path/to/folder/{environment}-{platform}.conda.lock.txt"
```

**Comment by ruben-arts** [comment]
That could make sense! Not sure how hard it would be as pixi can still read conda lock like format using `rattler`

**Comment by bollwyvl** [comment]
Cool. Or, as `pixi list` already has a lot of options, having an `pixi export` (with `explicit` as the first of perhaps several formats) would make sense.

**Comment by abkfenris** [comment]
> Cool. Or, as `pixi list` already has a lot of options, having an `pixi export` (with `explicit` as the first of perhaps several formats) would make sense.

A`pixi export` command was also my first thought from hacking around in `list` recently.

**Comment by baszalmstra** [comment]
Will be implemented in: https://github.com/prefix-dev/pixi/pull/1873

**Comment by bollwyvl** [comment]
Huzzah! Looking forward to the next release!
