### ISSUE TITLE
`pixi install -e ENV_NAME` always installs all environments

### ISSUE THREAD

**Issue by tadejsv** [prefix-dev/pixi#1218]
Whenever I run `pixi install` with environment name specified, all environments listed in `pixi.toml` appear in `.pixi/envs`. Is it possible somehow to only install one environment?

**Comment by ruben-arts** [comment]
This is a reaction from the lock file generation. 

If there is a `pypi-dependency` in an environment you need to have the python interpreter installed to solve the lock file. This forces the conda `dependencies` to also be installed. Currently the only way to avoid this is to only have conda dependencies. Or having a pre-solved lock file when you run `pixi install` e.g. in CI you shouldn't install all environments when you run `pixi install -e test` 

This issue requests for a way around this: https://github.com/prefix-dev/pixi/issues/1130 using wheel only installs

**Comment by baszalmstra** [comment]
Closing for now! See linked issue to track progress.
