### ISSUE TITLE
Create command pixi init --import pyproject.toml

### ISSUE THREAD

**Issue by j-bac** [prefix-dev/pixi#1219]
### Problem description

When installing python projects, it is not possible to run pixi install without modifying the existing pyproject.toml. 
It would be very useful to have pixi init --import pyproject.toml for installation / inplace modification of a pyproject.toml file to pixi-compatible format, like it is currently possible with .yml files.

It would also be useful to have best practices recommendations for how to handle duplicate fields (e.g. dependencies)

**Comment by ruben-arts** [comment]
He do you want a `pixi.toml` file or do you want to keep using the `pyproject.toml` and extend it with pixi's tables?

For the later checkout: https://pixi.sh/latest/advanced/pyproject_toml/

If you have  `pyproject.toml` and you run `pixi init` it will automatically add pixi to that file.
