### ISSUE TITLE
conda-pack doesn't work with pixi

### ISSUE THREAD

**Issue by tokoko** [prefix-dev/pixi#1229]
```shell
[project]
name = "pixi-hello-world"
version = "0.1.0"
description = "Add a short description here"
authors = [""]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
pack = "conda-pack -p $CONDA_PREFIX"
grep-link = 'grep -r \"link\" $CONDA_PREFIX/conda-meta'

[dependencies]
python = ">=3.12.3,<3.13"
conda-pack = {version = ">=0.7.1,<0.8"}
```

Not sure if this is a bug or a feature request :) I'm trying to pack pixi environment with `conda-pack` to pass the packed env to [pyspark](https://spark.apache.org/docs/latest/api/python/user_guide/python_packaging.html#using-conda). I added relevant commands as tasks, `pixi run pack` generates the following error for me:
```
  File "/home/projects/feast/pixi-hello-world/.pixi/envs/default/lib/python3.12/site-packages/conda_pack/core.py", line 814, in load_environment
    pkg = info['link']['source']
          ~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
After a not very long investigation I saw that `conda-pack` is looking for contents of a `link` key in json files in environment conda-meta directory. Seems like `pixi` always sets those to null (`pixi run grep-link`).

**Comment by wolfv** [comment]
Thanks for the report! 

With these changes in rattler, it should look better: https://github.com/mamba-org/rattler/pull/610 

Also still needs some more changes in `pixi` :)

**Comment by tokoko** [comment]
That was fast, thanks a lot. Let met me know if I can help test things out once it's merged.

**Comment by tokoko** [comment]
Just tried packing a bunch of different libraries and it seems to be working fine, no more errors during packing. I'll try to run an actual spark application with pixi env later.

**Comment by tokoko** [comment]
installed from your pr branch actually to test it :) just a couple minutes before it was merged, you guys are fast lol

**Comment by wolfv** [comment]
Alright, I'll close this issue for now :) 🚀 let us know how it goes with spark!
