### ISSUE TITLE
Dependencies doesn't error with wrong right hand side

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#1236]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I accidentally had

```toml
[dependencies]
dependencies = { pillow = "*" }
```

in my pixi.toml

### Issue description

pixi tried to resolve `*` as a name I think and then complained about not finding a matching package.

### Expected behavior

Ideally we'd see that this doesn't make sense and give a helpful error message that says `{pillow = "*"}` is not a valid matchspec.

**Comment by baszalmstra** [comment]
In recent versions you are now presented with:

```
× failed to parse project manifest
    ╭─[pixi.toml:12:16]
 11 │ [dependencies]
 12 │ dependencies = { pillow = "*" }
    ·                ────────┬───────
    ·                        ╰─┤ unknown field `pillow`, expected one of `version`, `url`, `git`, `path`, `branch`, `rev`, `tag`, `build`, `build-number`, `file-name`, `channel`, `subdir`, `md5`, `sha256`
    ·                          │
    ·                          │
    ╰────
```
