### ISSUE TITLE
Task caching only works if the directory is a subdirectory of `cwd`

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#1237]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
git clone https://github.com/Hofer-Julian/pixi-task-cache-cwd
cd pixi-task-cache-cwd
pixi run start # it is not cached
pixi run start # it is cached but shouldn't be since output folder has been modified
```

### Issue description

Another issue popped up with @Jingru923's [work](https://github.com/Deltares/Ribasim/pull/1407).
My [minimal example](https://github.com/Hofer-Julian/pixi-task-cache-cwd) has a task defined like this
```toml
[tasks]
start = { cmd = "echo Hello >> ../folder_a/a.txt", 
          cwd = "folder_b", inputs = ["b.py"],
          outputs = ["../folder_a/a.txt"]}
```

The cache should be invalidated every single time.
However, when running `pixi run --verbose start`, one can read from the logs that `a.txt` isn't tracked.
So we get a cache hit, after the first run.

Related to https://github.com/prefix-dev/pixi/issues/1139

### Expected behavior

It should be possible to track folders that aren't in `cwd`.
@wolfv wondered in https://github.com/prefix-dev/pixi/issues/1139#issuecomment-2058206805 

> Now, I am not sure what we should do ... use the cwd or not? I do think that we may not want to use the cwd for the inputs and outputs path computation.

My first instinct was to *not* take it into account, so I have a slight preference for that.

**Comment by wolfv** [comment]
We have some larger updates to the cache behavior in `main`: https://github.com/prefix-dev/pixi/pull/1204

I am not sure if it will fix this issue, but it does fix some issues around `cwd` + cache (uses the project root instead of the task.cwd).

**Comment by wolfv** [comment]
Could you retry with yesterday's release? I think this is fixed :)

**Comment by Hofer-Julian** [comment]
I can confirm that now that the project root is used for `inputs` and `outputs` this isn't a problem anymore.

**Comment by wolfv** [comment]
Thanks @Hofer-Julian!
