### ISSUE TITLE
Allow flexible channel priority

### ISSUE THREAD

**Issue by dp-alvarez** [prefix-dev/pixi#1254]
### Problem description

I'm trying to get introduce Pixi at the company I work at, when I ran into this issue compared to our old conda setup.
Basically we have our own internal conda channels with custom versions of some conda packages. Some projects depend on the custom version of those libraries, some depend on the upstream ones.

Pixi, according to the docs [here](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html), follows the behavior conda has with "strict channel priority" set.
We can work around it by setting the channel source on a per-package basis, but that won't scale for wider adoption.
Is there a plan to implement flexible channel priority in Pixi? Does the solver have this behavior and it's only a matter of exposing it in Pixi?

**Comment by ruben-arts** [comment]
He @dp-alvarez 

Do you build your custom channel on top of conda-forge?

This is a known request, the latest response is: https://github.com/prefix-dev/pixi/discussions/1029#discussioncomment-8862908. 

With enough people wanting this, we probably need to give in at some point :wink:  Track it by giving a thumbs up! :+1:

**Comment by dp-alvarez** [comment]
Ooh I didn't that thread it as I only searched in issues, thanks for pointing it out.

We don't build it on top of conda-forge, that channel only has our own internal packages plus patched versions of some upstream libraries.

**Comment by wolfv** [comment]
There is also some work ongoing in `rattler`, the underlying library: https://github.com/mamba-org/rattler/pull/598 :)

**Comment by ruben-arts** [comment]
> We don't build it on top of conda-forge, that channel only has our own internal packages plus patched versions of some upstream libraries.

Oh that is interesting. Are you building everything from scratch? Including all compilers etc?

**Comment by dp-alvarez** [comment]
> Oh that is interesting. Are you building everything from scratch? Including all compilers etc?
Sadly it's nowhere that cool. We just build patched versions of libraries (pulling dependencies from conda-forge) and upload them to an internal conda channel.
When I said "we don't build it on top of conda-forge" I meant that the internal channel isn't a mirror of conda-forge + patched packages, it contains just our internal patched packages and nothing else.

@wolfv great to know there is already code underway for it, thanks for the link!

**Comment by roaldarbol** [comment]
Just saw that the `py-rattler` PR is merged (https://github.com/mamba-org/rattler/pull/598). Would it be possible to expose the option in pixi now? :-)
