### ISSUE TITLE
Improve `pixi.toml` schema syntax for human and machine consumption

### ISSUE THREAD

**Issue by bollwyvl** [prefix-dev/pixi#1258]
### Problem description

After using the `pixi.toml` format some, there are some concrete things that would make it more precise in both editors and in programmatic use:

- things like `project` have no description
  - fill out more of the docstrings, etc. to make their way into the generated schema
- publish the schema as e.g. `https://pixi.sh/v0.20.0/schema/manifest/schema.json`
    - this would allow for future schematizing of other things (e.g. `lock`, various CLI outputs, etc)
- declare that URL as the `$id`
  - _technically_ it's just a URI, but...
  - this is generally better than re-inventing something with a `version` field... 
    - ... _unless_ that actually drives some backwards-compatibility mechanism
- declare the (meta) `$schema` of the schema
  - pydantic _claims_ `https://json-schema.org/draft/2019-09/schema`, but last i checked `taplo` doesn't support that
  - as long as it (meta)validates, staying on `http://json-schema.org/draft-07/schema#` is a quite safe choice
- allow `"$schema"` in `pixi.toml` to point to that URL
  - while `taplo` has magic a `# schema: ` directive used in a few of the examples, allowing `"$schema"` (also supported by `taplo`) would make it more portable
- apply a custom [JSONEncoder](https://docs.python.org/3/library/json.html#json.JSONEncoder), so that the document at rest is easier to consume, and changes between versions are easier to inspect
  - for example:
    - `$schema`
    - `$id`
    - `title`
    - `description`
    - `properties`
      - sort these recursively by the same scheme
    - `$defs`
      - sort these recursively by the same scheme

And thanks again for `pixi`!

**Comment by wolfv** [comment]
Just for reference (for people finding this issue), the schema is declared as Python pydantic model here: https://github.com/prefix-dev/pixi/blob/main/schema/model.py

Contributions are, of course, welcome! :)
