### ISSUE TITLE
Any plans for a license checker?

### ISSUE THREAD

**Issue by asmith26** [prefix-dev/pixi#1277]
Hi there,

Just wondering if you had any plans for incorporating a license checker feature into pixi (e.g like https://github.com/dhatim/python-license-check, which checks all dependencies are valid for a given license policy)?

Many thanks for any help, and this amazing lib!

**Comment by ruben-arts** [comment]
Yes there are ideas, but we're not sure if we're going to make it part of `pixi` itself. 

If you're okay with this answer I would like to close this issue for now.

**Comment by asmith26** [comment]
Thanks for the info, this would be a helpful feature.
Thanks again!

**Comment by asmith26** [comment]
In case helpful for others, a possible workaround for now is to using pyproject.toml file as both projects support this:
- https://pixi.sh/latest/advanced/pyproject_toml/
- https://github.com/dhatim/python-license-check?tab=readme-ov-file#how-to-use
