### ISSUE TITLE
Unable to parse version spec: =>96

### ISSUE THREAD

**Issue by MarcoGorelli** [prefix-dev/pixi#1290]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init --import conda/environment-test-3.10.yml
```

### Issue description

I wanted to try contributing something to [bokeh](https://github.com/bokeh/bokeh), so I cloned their repo, and ran the above command in their repo

I get
```
$ pixi init --import conda/environment-test-3.10.yml
0: at line 1, in Tag:
=>96
 ^

1: at line 1, in Alt:
=>96
 ^

2: at line 1, in version:
=>96
 ^


  × Unable to parse version spec: =>96
```

### Expected behavior

I don't really know, I'm new to pixi, first time trying it out

**Comment by baszalmstra** [comment]
It means the environment file contains a requirement with a constraint =>96 which is not a valid version constraint. Most likely >=96 is ment.

You could create a PR to environment.yml because its definitely not correct!

**Comment by MarcoGorelli** [comment]
thanks! indeed, fixing that, it builds. I'll report upstream then!
