### ISSUE TITLE
Support bootstrapping a pixi config from environment.yml

### ISSUE THREAD

**Issue by jonashaag** [prefix-dev/pixi#131]
I'd like to use pixi on some projects that already use Conda and have an `environment.yml` file.

Would be nice to be able to `pixi add -f environment.yml` or some other way to bootstrap a `pixi.toml` from an `environment.yml`.

**Comment by ruben-arts** [comment]
That is a good idea! Will take a look at that!

**Comment by jonashaag** [comment]
My current workaround

```
yq < environment.yml -r '.dependencies' -o tsv | tr '\t' '\0' | xargs -0 pixi add
```

**Comment by xhochy** [comment]
`pixi import` would be a nice alias for this (at least I would have expected it there)
