### ISSUE TITLE
Not possible to `pixi remove` PyPI dependendency with optional dependencies

### ISSUE THREAD

**Issue by JesperDramsch** [prefix-dev/pixi#1312]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi add black[cli] --pypi
pixi remove black[cli] --pypi
```

### Issue description

You can currently add PyPI dependencies with the `--pypi` flag using a `pyproject.toml` but the same package cannot be removed with `pixi remove`.

```shell
$ pixi add black[cli] --pypi
Added black[cli]
Added these as pypi-dependencies.
$ pixi remove black[cli] --pypi
× Can't convert dependency name `black[cli]` to package name
```

### Expected behavior

`pixi remove` should remove anything `pixi add` adds, as I would expect it to be the "inverse" operation.

**Comment by olivier-lacroix** [comment]
This behaviour is not limited to pypi dependencies or `pyproject.toml`

The following will also fail for instance.

```
pixi add flask==2.*
pixi remove flask==2.*
```

It sounds sensible to be able to extract the names out of pypi / conda specs though.
