### ISSUE TITLE
`pixi global upgrade` only takes a single channel into account

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1318]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
default_channels = ["conda-forge", "https://my.quetz/get/private-channel"]
```

### Issue description

```shell
$ pixi global install private-package
<checks all channels>
✔ Installed package private-package 0.13.0 pyh4616a5c_0 from get/private-channel
$ pixi global upgrade private-package
<only checks private-channel, not conda-forge>
  × Cannot solve the request because of: private-package * cannot be installed because there are no viable options:
  │ └─ private-package 0.0.2 | 0.1.0 | 0.1.1 | 0.1.2 | 0.2.0 | 0.3.0 | 0.4.0 | 0.4.2 | 0.4.3 | 0.4.4 | 0.4.5 | 0.4.6 | 0.4.7 | 0.4.8 | 0.5.0 | 0.6.0 | 0.7.0 | 0.8.0 | 0.9.0 | 0.10.0 | 0.11.0 | 0.12.0 |
  │ 0.12.1 | 0.12.2 | 0.13.0 would require
  │    └─ python >=3.8, for which no candidates were found.
```

### Expected behavior

pixi should either check all channels that are defined in `config.toml` or check all channels that were used to check initially.

**Comment by chawyehsu** [comment]
It will only use the channel where you installed the package, otherwise something like https://github.com/prefix-dev/pixi/issues/943#issuecomment-1987156649 would happen.

**Comment by pavelzw** [comment]
I don't plan on hosting dependencies like python on my private channels but only my tools. So IMO it should search _both_ channels.
