### ISSUE TITLE
Add ability to clean pixi cache

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/pixi#1321]
### Problem description

Similar with #749 
I think it would be nice to have something like `pixi clean cache` to remove cached pkgs for testing purposes

**Comment by pavelzw** [comment]
Is there the ability to see the inode count in linux? Then maybe one could try only removing unused packages from the cache.

**Comment by ruben-arts** [comment]
@pavelzw that would be the best :star_struck:

**Comment by ReimarBauer** [comment]
This seems to need a TTY, I can't use it in a docker build.
Is there an option I don't know?
