### ISSUE TITLE
Set project name with CLI

### ISSUE THREAD

**Issue by jjv5** [prefix-dev/pixi#1359]
### Problem description

Project info can be set from CLI like this:

project description set

except for name. It would be useful to include 'name' in this also:

project name set  "myProject"

**Comment by ruben-arts** [comment]
This is an obvious next addition! Contributions are welcome!

**Comment by LiamConnors** [comment]
May I try this one? Is the idea that there would be two commands, one to set the name and one to get it, like:

```
pixi project name get
```

```
pixi project name set <name>
```

**Comment by ruben-arts** [comment]
Hi @LiamConnors, 

Yes, I would have done that! Please give it a go!

**Comment by ruben-arts** [comment]
Closing as done!
