### ISSUE TITLE
`pixi shell-hook -e default` doesn't work

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1370]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
❯ pixi shell-hook -e default
  × unknown environment 'default'
```

### Expected behavior

Same as `pixi shell-hook`

**Comment by borchero** [comment]
I just checked, this has been fixed by #1364 just yesterday :smile:
