### ISSUE TITLE
Expose different uv index resolution strategies

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#1377]
### Problem description

UV currently support different index resolution strategies, see this: [astral-sh/uv@main/PIP_COMPATIBILITY.md#packages-that-exist-on-multiple-indexes](https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md?rgh-link-date=2024-05-13T11%3A20%3A00Z#packages-that-exist-on-multiple-indexes)

Pixi currently supports the default option, which is similar to strict index priority in conda.
For some users, this has proved too limiting: https://github.com/prefix-dev/pixi/issues/1373

I propose having this option exposed through the `[pypi-options]` table, this would be an exclusive option per solve-group/environment.

**Comment by abazabaaa** [comment]
Has this feature been enabled? This is a significant issue for me and a project I am working with.
