### ISSUE TITLE
Install error extra-url

### ISSUE THREAD

**Issue by jomalla123** [prefix-dev/pixi#1389]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Hi guys, I am currently trying out pixi and liking it a lot so far. I just have one issue when I am trying to install a package called torch_scatter via an extra-url:

here is my pixi.toml:
```
[project]
name = "test-torch-cuda"
version = "0.1.0"
channels = ["nvidia", "conda-forge", "pytorch", "pyg"]
platforms = ["win-64"]

[tasks]

[pypi-options]
extra-index-urls = ["https://data.pyg.org/whl/torch-2.3.0+cu121.html"]

[dependencies]
python = ">=3.12.3,<3.13"
pytorch-cuda = "12.1.*"
pytorch = ">=2.0.0"

[pypi-dependencies]
torch-geometric = ">=2.3.1,<3"
torch_sparse = "*"
```

The error, I am getting:
```
C:\git\test\test-scatter>pixi install
  × failed to solve the pypi requirements of 'default' 'win-64'
  ├─▶ failed to resolve pypi dependencies
  ├─▶ Failed to download and build `torch-sparse==0.6.18`
  ├─▶ Failed to build: `torch-sparse==0.6.18`
  ╰─▶ Build backend failed to determine extra requires with `build_wheel()` with exit code: 1
      --- stdout:

      --- stderr:
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "C:\Users\jonathan.cawalla\AppData\Local\rattler\cache\uv-cache\.tmpuRQJjj\.venv\Lib\site-
      packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jonathan.cawalla\AppData\Local\rattler\cache\uv-cache\.tmpuRQJjj\.venv\Lib\site-
      packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\jonathan.cawalla\AppData\Local\rattler\cache\uv-cache\.tmpuRQJjj\.venv\Lib\site-
      packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\jonathan.cawalla\AppData\Local\rattler\cache\uv-cache\.tmpuRQJjj\.venv\Lib\site-
      packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'torch'
```

### Issue description

When I just run `pip install torch_scatter -f https://data.pyg.org/whl/torch-2.3.0+cu121.html ` in the already created environment by pixi it works fine.

### Expected behavior

I would hope that it works in the same as with pip install.

**Comment by olivier-lacroix** [comment]
The extra index is meant for a python package registry. That is something similar to pypi.

You can add URL dependencies (which I think is what you are trying to do?) under the  pypi-dependencies table

**Comment by jomalla123** [comment]
> The extra index is meant for a python package registry. That is something similar to pypi.
> 
> You can add URL dependencies (which I think is what you are trying to do?) under the pypi-dependencies table
> 
> see here: https://pixi.sh/v0.22.0/reference/configuration/#pypi-dependencies


Yes, thanks! If I select the whl url dependencies directly for operating system and version, then it works:

```
[pypi-dependencies]
torch_sparse = {url="https://data.pyg.org/whl/torch-2.3.0%2Bcu121/torch_sparse-0.6.18%2Bpt23cu121-cp310-cp310-win_amd64.whl"}
```

However, I would like to not choose that manually, I also tried the following but it seems like it is not supported:

```
[pypi-dependencies]
torch_sparse = {url="https://data.pyg.org/whl/torch-2.3.0+cu121.html"}
```

I guess when I want a pixi.toml that works for both windows and linux, I have to use the platform functionality of pixi, right?

**Comment by tdejager** [comment]
I think you can use the `find-links` option for this?

```toml
[pypi-options]
find-links = { url = "https://data.pyg.org/whl/torch-2.3.0+cu121.html" }
```

**Comment by jomalla123** [comment]
> I think you can use the `find-links` option for this?
> 
> ```toml
> [pypi-options]
> find-links = { url = "https://data.pyg.org/whl/torch-2.3.0+cu121.html" }
> ```

Oh, thats great I missed that in the documentation. I had to add brackets as a sequence is expected, but it works. Thanks!

```
[pypi-options]
find-links = [{url = "https://data.pyg.org/whl/torch-2.3.0+cu121.html"}]
```
