### ISSUE TITLE
Can't install pypi package by version, but success if by path

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#1390]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

![image](https://github.com/prefix-dev/pixi/assets/38552291/83ecd8a6-a2db-4c4c-9b26-0264e25a2c31)
<img width="1920" alt="image" src="https://github.com/prefix-dev/pixi/assets/38552291/f7b23b69-a785-4eec-ab50-122b3d5353b2">

### Issue description

pixi fail to resolve pypi dependencies by version, but it will succeed when by path

Additionally, I successfully installed this package by `uv@0.1.38`.
<img width="814" alt="image" src="https://github.com/prefix-dev/pixi/assets/38552291/2202ee63-e0f4-432e-9caf-8f950ebca667">

### Expected behavior

Can successfully resolve pypi dependencies through version

**Comment by ruben-arts** [comment]
I think this again has to do with the `system-requirements`. Could you try with:
```toml
[system-requirements]
linux = "2.31"
```

I personally can not recreate this issue as I can't seem to find the package at all.

**Comment by zen-xu** [comment]
Still doesn't work.

**Comment by ruben-arts** [comment]
Is there a way to get alpha-flow2 for me?

**Comment by zen-xu** [comment]
Sorry, this is a private package, but I will continue to investigate. At present, I found that the UV only detects the wheel of py311, and does not detect the wheel of py37, resulting in the inability to install py37.

**Comment by zen-xu** [comment]
I've found the reason. The default value for `default_glibc_version` is 2.17, which causes the largest manylinux not to be less than it. However, the package I installed requires 2.31.

https://github.com/prefix-dev/pixi/blob/66ce6cf69e9b8ff9bc7b427cce00c8b555165171/src/project/virtual_packages.rs#L17-L19

https://github.com/prefix-dev/pixi/blob/66ce6cf69e9b8ff9bc7b427cce00c8b555165171/src/pypi_tags.rs#L19-L53

<img width="1919" alt="image" src="https://github.com/prefix-dev/pixi/assets/38552291/7483d0a6-85da-424b-b2a2-b5ea775ed9f2">

**Comment by zen-xu** [comment]
So I just need to specify system-requirements glibc = "2.31"

**Comment by ruben-arts** [comment]
I'm sorry for my typo, I did indeed mean `libc` with my system-requirements example. Thanks for the full answer!
