### ISSUE TITLE
npm install -g typescript-language-server Not adding executables to path

### ISSUE THREAD

**Issue by BrayanLope5** [prefix-dev/pixi#1398]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
# Use pixi to install nodejs and npm
pixi global install nodejs

# Then use npm to install package globally
npm install -g typescript-language-server

# typescript-language-server is not part of path.
# The actual path to typescript-language-server is ~/.pixi/envs/nodejs/bin but this is not added with node, npm, and npx to path as an executable.
```

### Issue description

Trying to install an executable like typescript-language-server globally with the npm executable that comes with the nodejs package on pixi doesn't add npm packages installed globally to the path. I am also wondering if this is a problem with the package and not with pixi.

### Expected behavior

~/.pixi/envs/nodejs/bin should also be part of path(?).

**Comment by ruben-arts** [comment]
We don't link executables that do not come from the top level package directly. This has to do with things like, most environments will have python but if you want python on your path you should run `pixi global install python`. So dependency binaries are not exposed. The issue related to this #1017.

This then also counts for packages that install tools themselfs. For `npm` you can fix this by resetting the prefix location:
```
npm config set prefix ~/.npm
```
Then make sure that the `~/.npm/bin` path is on the PATH and you should be good to go.

**Comment by BrayanLope5** [comment]
This works great for node. Thanks.
