### ISSUE TITLE
How to add dependencies without changing python?

### ISSUE THREAD

**Issue by yanecc** [prefix-dev/pixi#1400]
### Problem description

How to add dependencies without changing python?
Everytime I add a dependency with pixi, it will automatically fetch a python interpreter. This may cause inconsistent behaviors before and after. In addition, I don't want to have redundant python copies in every project.

Maybe we could have an option in config file that specify the interpreter path. When this is set, the default interpreter will be used if no given python provided in project dependencies. And we can get the local python version and keep it in project config file when `pixi init` a project to keep the migrability.

**Comment by yanecc** [comment]
> He @yanecc,
> 
> The main idea of pixi is to not have global settings to force an interpreter into projects. But what I agree with is that we could look into making pixi less disk hungry by reusing more of the existing cache. I've done a write-up of my idea in this [Discussion](https://github.com/prefix-dev/pixi/discussions/1354)
> 
> For instance this would be really beneficial for the .`pixi global command`
> 
> If this Issue does indeed align with the ideas from the discussion please close this Issue.

It's partly consistent with my idea. 
I'd like to know how will you reuse the existing cache.
If you storage it in a global dir, why not make use of what's already in the Path?

**Comment by olivier-lacroix** [comment]
It is lind of the case already: each .pixi environment is contains links to the global cache. so if you specify exactly the same python (or any other package) version, this will take zero additional space.

**Comment by baszalmstra** [comment]
For the time being we will not implement using an existing python interpreter. This makes a project less reproducible which goes against the whole idea of pixi.

Closing for now, but feel free to reopen if this remains a large issue you would like to see fixed.
