### ISSUE TITLE
prompt in fish shell with tide looks wrong

### ISSUE THREAD

**Issue by tfriedel** [prefix-dev/pixi#1407]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

--

### Issue description

I use fish shell with the [tide prompt](https://github.com/IlanCosman/tide). 
Usually the prompt has two lines, with the second starting with ">". 

After I run pixi shell however, there's some ellipsis (...) that were not there before and the ">" is in the same line as the rest of the prompt. Also the conda environment of the project is not shown. 
![grafik](https://github.com/prefix-dev/pixi/assets/1817286/2c55e559-c9d2-4e73-b920-faebca3b54fc)

### Expected behavior

--

**Comment by ruben-arts** [comment]
With these fancy prompts it's adviced to turn of the prompt injection that pixi does. 

Put this in your `~/.config/pixi/config.toml`
```toml
change-ps1 = false
```

**Comment by ruben-arts** [comment]
Oh it would be great if you improve our prompt so it works for you:
https://github.com/prefix-dev/pixi/blob/f7dd0086be4a27f5530755154f483514aafa24cd/src/prompt.rs#L20

I think it works a little different from the conda one but if you could figure out how to fix it that would be awesome!
