### ISSUE TITLE
`pixi install` raises `thread 'main' has overflowed its stack` when building from source without `-r` flag .

### ISSUE THREAD

**Issue by Glatzel** [prefix-dev/pixi#1414]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

system: windows 10

here is a demo pixi.toml . 
```
[project]
name = "Install-Multi-Envs"
platforms = ["win-64"]
channels = ["conda-forge"]

[dependencies]
python = ">=3.10"
[pypi-dependencies]
numpy = ">=1.23"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[environments]
py312 = ["py312"]
py311 = ["py311"]
```
command
```
pixi install
```

### Issue description

The toml above work fine with stable release or building from source by `cargo build -r` command.

If building from source without `-r` flag, the `pixi install` will raise `thread 'main' has overflowed its stack`.

### Expected behavior
I do not have rust background, and can't figure out why this happens. But, this bug doesn't influence most users. Just add `-r` flag to build from source section in readme.md file could prevent others from getting this issue.

**Comment by Glatzel** [comment]
I did some other trials. `thread 'main' has overflowed its stack`  only occurs when building pixi by `cargo build`.

If using `cargo build -r`, this problem doesn't happen.

**Comment by ruben-arts** [comment]
Thanks for letting us know @Glatzel !
