### ISSUE TITLE
Add Support for External Shared Libraries from Host

### ISSUE THREAD

**Issue by Tabrizian** [prefix-dev/pixi#1415]
### Problem description

I'm working on a C++ project that relies on the libb64 library. While I'm using pixi to manage my project's dependencies and CMake builds, I've encountered a roadblock because libb64 isn't available on conda-forge.

It would be incredibly helpful if pixi could support adding shared libraries from locations outside of conda-forge, such as:

* Directly from the host system
* From custom or user-specified paths
This enhancement would enable seamless integration of external libraries into pixi-managed projects.

Thank you for considering this feature request. Please let me know if you'd like any additional details or clarification.

**Comment by ruben-arts** [comment]
I believe this is not really up to `pixi` but more up to your CMake configuration. We don't isolate the environments like you would with a `docker` image. So you could use absolute paths in your CMake, or make use of the `find_library` functions.

It's not possible for pixi to depend on local packages, as we cannot lock them. So it would be up to the creator of the project to create a task to install it after pixi did its installation. 

It would be even more awesome to contribute the `libb64` conda package to `conda-forge` through the [staged-recipes](https://github.com/conda-forge/staged-recipes) so it would become easier for everyone.

**Comment by baszalmstra** [comment]
We are not planning on implementing this feature request. You can either directly use a tool like CMake to find the shared libraries you need or bundle them with your source.
