### ISSUE TITLE
Add `pixi update --json`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1437]
### Problem description

https://github.com/prefix-dev/pixi/issues/73#issuecomment-1926999625

I would like to create an internal dependabot replacement that calls `pixi update` and generates some markdown diffs. I planned to make the json-to-md renderer open source after that :)
I don't think it would make sense to let pixi create markdown directly since eventual dependabot/renovate config will probably do their own implementation.

**Comment by baszalmstra** [comment]
What would you like to output of this command to look like?

**Comment by pavelzw** [comment]
```json
{
  "py38": {
    "linux-64": {
      "python": {
        "before": {
          "version": "3.9.0",
          "build": "h12debd9_0"
        },
        "after": {
          "version": "3.9.0",
          "build": "h12debd9_0"
        },
        "changed": "no" // one of build, major, minor, patch
      },
      "polars": {
        "before": {
          "version": "0.10.0",
          "build": "py38h1f7f2b9_0"
        },
        "after": {
          "version": "0.10.1",
          "build": "py38h1faeeb9_1"
        },
        "changed": "patch"
      }
...
```

how about something like this?

**Comment by baszalmstra** [comment]
Seems simple enough!

Just the `changed` is a bit more complex. Not all versions are semver based and both the version and the build number can be changed at the same time. Do you really need this field?

**Comment by pavelzw** [comment]
I would also be fine with `no, added, removed, newer, older` or `no, added, removed, changed` and i would do the version magic with a custom tool.

**Comment by baszalmstra** [comment]
But wouldnt this already be present from the fact that "before" and "after" exist or not? 

* `added` - only "after"
* `removed` - only "before"
* `changed` - "after" and "before"
* `no` - package not present? Or neither and "after" or a "before"

**Comment by pavelzw** [comment]
yes, that's a bit smarter than my idea 😅 then let's not include `changed` at all

**Comment by pavelzw** [comment]
we probably also need to add pypi dependencies there:

```json
{
  "py38": {
    "linux-64": {
      "python": {
        "before": {
          "version": "3.9.0",
          "build": "h12debd9_0"
        },
        "after": {
          "version": "3.9.0",
          "build": "h12debd9_0"
        },
        "type": "conda"
      },
      "polars": {
        "before": {
          "version": "0.10.0"
        },
        "after": {
          "version": "0.10.1"
        },
        "type": "pypi"
      }
...
```

how about this?

**Comment by baszalmstra** [comment]
Sure thing!

**Comment by pavelzw** [comment]
Almost done with the markdown generator 🤩 
One other thing I would love to have: an indicator whether the dependency is explicit (i.e. defined in our pixi.toml) or not.

```json

{
  "py38": {
    "linux-64": {
      "python": {
        "before": {
          "version": "3.9.0",
          "build": "h12debd9_0"
        },
        "after": {
          "version": "3.9.0",
          "build": "h12debd9_0"
        },
        "type": "conda",
        "explicit": true
      },
      "polars": {
        "before": {
          "version": "0.10.0"
        },
        "after": {
          "version": "0.10.1"
        },
        "type": "pypi",
        "explicit": false
      }
...

```
