### ISSUE TITLE
ros2-nav2 example is broken

### ISSUE THREAD

**Issue by blooop** [prefix-dev/pixi#1450]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
cd example/ros2-nav2
pixi install
```

### Issue description

When running install on the ros2-nav2 example I get the error:

```
  × failed to parse project manifest
    ╭─[pixi.toml:9:13]
  8 │ 
  9 │ [activation.env]
    ·             ─┬─
    ·              ╰── unknown field `env`, expected `scripts`
 10 │ TURTLEBOT3_MODEL = "waffle"
    ╰────
```

The example installs if remove that line, but when I run no robot shows up.  I tried moving the line into the env command under tasks.start but that doesn't fix it either.

### Expected behavior

pixi installs without error.

**Comment by blooop** [comment]
Sorry, for the churn but I think the example is broken in another way.  I've waited for 3 mins now, but the robot does not load as shown in the screenshot in the readme.

**Comment by ruben-arts** [comment]
Oh this is really my bad, didn't take care of the example while we we're developing. 

The fix is:
```diff
 [tasks.start]
-env = {GAZEBO_MODEL_PATH = "$GAZEBO_MODEL_PATH:$PIXI_PROJECT_ROOT/.pixi/env/share/turtlebot3_gazebo/models"}
+env = {GAZEBO_MODEL_PATH = "$GAZEBO_MODEL_PATH:$PIXI_PROJECT_ROOT/.pixi/envs/default/share/turtlebot3_gazebo/models"}
```

Will push it soon!

**Comment by ruben-arts** [comment]
It's now fixed in `main` after merging #1448.

**Comment by blooop** [comment]
Working now, thanks!  I don't know how easy this would be to implement, but maybe checking the example work as expected could be added to CI.

**Comment by ruben-arts** [comment]
Yes you are completely right, but the issue with this one is that it is extremely slow and hard to test in CI as it's a gui. But there could definitely be one!
