### ISSUE TITLE
--frozen helpstring is missing from 0.23.0

### ISSUE THREAD

**Issue by benmoss** [prefix-dev/pixi#1467]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi run --help
```

```shell
Options:
      --manifest-path <MANIFEST_PATH>                  The path to 'pixi.toml' or 'pyproject.toml'
      --frozen                                         [env: PIXI_FROZEN=]
      --locked                                         Check if lockfile is up-to-date before installing the environment, aborts when lockfile isn't up-to-date with the manifest file
                                                       [env: PIXI_LOCKED=]

```

### Issue description

There's no description of what `--frozen does`

### Expected behavior

I think it uses packages from the lockfile but will never update the lockfile?

**Comment by ruben-arts** [comment]
Easiest bug fix ever, not sure why that ever changed.
