### ISSUE TITLE
thread panic in rattler solve

### ISSUE THREAD

**Issue by kpweiler** [prefix-dev/pixi#1469]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ cat pixi.toml
[project]
name = "test"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "==3.11"
awswrangler = "*"

$ RUST_BACKTRACE=1 RUST_BACKTRACE=full pixi install
⠁ updating lock-file   [00:00:01] [────────────────────────────────────────]    0/2
  ⠠ default:linux-64     [00:00:01] resolving conda                                                                          thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rattler_solve-0.23.0/src/resolvo/mod.rs:489:87:
called `Result::unwrap()` on an `Err` value: InvalidBracket
stack backtrace:
   0:     0x7fef8e3bc2d9 - <unknown>
   1:     0x7fef8d889fc0 - <unknown>
   2:     0x7fef8e37e6c2 - <unknown>
   3:     0x7fef8e3c034e - <unknown>
   4:     0x7fef8e3bfad0 - <unknown>
   5:     0x7fef8e3c0c7b - <unknown>
   6:     0x7fef8e3c06a0 - <unknown>
   7:     0x7fef8e3c05f6 - <unknown>
   8:     0x7fef8e3c05e3 - <unknown>
   9:     0x7fef8d1cb094 - <unknown>
  10:     0x7fef8d1cb602 - <unknown>
  11:     0x7fef8d6f581a - <unknown>
  12:     0x7fef8d6f8658 - <unknown>
  13:     0x7fef8d688234 - <unknown>
  14:     0x7fef8d692d1e - <unknown>
  15:     0x7fef8d614802 - <unknown>
  16:     0x7fef8d5b9247 - <unknown>
  17:     0x7fef8e3ef87b - <unknown>
  18:     0x7fef8e3ef57f - <unknown>
  19:     0x7fef8e3c4585 - <unknown>
```

### Issue description

This only happens with this `awswrangler` package from `conda-forge`. For what it's worth, it will work as a pypi dependency, so I'm guessing it's choking on something in the `conda-forge` package spec.

### Expected behavior

The tool should handle the improper spec or install the package.

**Comment by baszalmstra** [comment]
Thanks for reporting! I will take a look.

**Comment by baszalmstra** [comment]
Ah looks like its because awswrangler depends on ray[default,data] >=2.9.0,<3.0.0 which is not a valid package name. This should be fixed in the awswrangeler feedstock.

Regardless, pixi should not crash. Ill see if I can implement a fix.

**Comment by baszalmstra** [comment]
See: https://github.com/conda-forge/awswrangler-feedstock/issues/125

**Comment by kpweiler** [comment]
thanks @baszalmstra - really appreciate the quick response - very excited about what you guys are doing with this project!

**Comment by baszalmstra** [comment]
Thanks for the kind words! 

I also drafted a repodata patch https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/753 this will fix the issue before we can fix it internally.

**Comment by baszalmstra** [comment]
I also fixed this issue in rattler: https://github.com/mamba-org/rattler/pull/732

**Comment by baszalmstra** [comment]
Note that the main feedstock has also been updated and the repodata patch landed as well so this issue can be considered fixed in the next few hours. 👍 With the fix in rattler this issue should never occur ever again!
