### ISSUE TITLE
Pixi does not freeze version number for PyPI package installs

### ISSUE THREAD

**Issue by SeanPedersen** [prefix-dev/pixi#1476]
### Problem description

When installing a package via PyPI, pixi does not freeze the installed version number (as it does for conda).
`pixi add --pypi polars`
results in
`polars = "*"`

whereas
`pixi add polars`
results in
`polars = ">=0.20.31,<0.21"`

**Comment by olivier-lacroix** [comment]
You are correct. I believe this is a duplicate of https://github.com/prefix-dev/pixi/issues/1409

**Comment by ruben-arts** [comment]
Closing in favor of #1409
