### ISSUE TITLE
`pixi run` warning about project manifest should only show up if `PIXI_PROJECT_MANIFEST` and local `pixi.toml` are different

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1480]
![image](https://github.com/prefix-dev/pixi/assets/29506042/47fbbfc6-7069-44ff-8832-a6ac698f0b0e)

we should compare the resolved paths, not only the string

**Comment by ruben-arts** [comment]
You are right.

**Comment by tdejager** [comment]
Hey @pavelzw, how are you the env variable set to this?

Unable to reproduce with:
```
cd /tmp
pixi init test-path
cd test-path
pixi s
echo $PIXI_PROJECT_MANIFEST
> /tm/test-path/pixi.toml
```

**Comment by pavelzw** [comment]
I think it happens when running `--manifest-file pixi.toml` (which is what setup-pixi does by default as of now)
Can you reproduce with that?

**Comment by tdejager** [comment]
Ah nice, will give that a go :)
