### ISSUE TITLE
tasks not found when running from osx-64 environment on osx-arm64 machine

### ISSUE THREAD

**Issue by croth1** [prefix-dev/pixi#1489]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```
[project]
name = "greetings"
requires-python = ">=3.10"
version = "0.1.0"
description = "Just greeting here"

[tool.pixi.project]
channels = ["conda-forge"]
# platforms = ["osx-arm64", "osx-64", "linux-64"]       # greet task found
platforms = ["osx-64", "linux-64"]                                  # greet task not found

[tool.pixi.dependencies]
python = "3.10.*"

[tool.pixi.tasks]
greet = "python -c \"print('hello world')\""
```

Run: `pixi task list`

### Issue description

Just played around with the `best_platform` implementation and ran into following curiosity:

When I set `platforms = ["osx-64", "linux-64"]`, `pixi task list` claims `No tasks found` , but adding back  `osx-arm64`, magically collects the tasks correctly.

### Expected behavior

Tasks correctly collected when osx-64 is inferred as the best platform on osx-arm64 hardware.

**Comment by ruben-arts** [comment]
This is related to: https://github.com/prefix-dev/pixi/issues/1404 and will be fixed in the coming release :+1:
