### ISSUE TITLE
Cannot resolve `__osx >=11.0` requirement on `osx-64`

### ISSUE THREAD

**Issue by petermcevoy** [prefix-dev/pixi#1490]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

To reproduce (on `osx-64`):
```shell
$ mkdir test && cd test
$ pixi init
$ pixi project channel add rttools
$ pixi add pyarts
× could not determine any available versions for pyarts on osx-64. Either the package could not be found or version constraints on other dependencies result in a conflict.
  ╰─▶ Cannot solve the request because of: pyarts * cannot be installed because there are no viable options:
      └─ pyarts 2.5.4 | 2.5.4 | 2.5.6 | 2.5.6 | 2.5.6 | 2.5.8 | 2.5.8 | 2.5.8 | 2.5.10 | 2.5.10 | 2.5.10 | 2.5.12 | 2.5.12 | 2.5.12 | 2.5.12 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.2
      | 2.6.2 | 2.6.2 | 2.6.2 would require
         └─ __osx >=11.0, for which no candidates were found.
```
Above can also be recreated on another platform by replacing `pixi add pyarts` with `pixi add pyarts -p osx-64`.

This is unexpected since virtual package according to `pixi info` is ` __osx=14.5=0`:
```
$ pixi info
      Pixi version: 0.23.0
          Platform: osx-64
  Virtual packages: __unix=0=0
                  : __osx=14.5=0
                  : __archspec=1=skylake
         Cache dir: /Users/peter/Library/Caches/rattler/cache
      Auth storage: /Users/peter/.rattler/credentials.json

Project
------------
              Name: test
           Version: 0.1.0
     Manifest file: /Users/peter/Projects/pixi_test/test/pixi.toml
  Config locations: 

Environments
------------
       Environment: default
          Features: default
          Channels: conda-forge
  Dependency count: 0
  Target platforms: osx-64
```

Also, installing with rattler works:
```shell
$ cd rattler
$ git checkout rattler-v0.26.0
$ cargo run --release --bin rattler create -c rttools -c conda-forge pyarts
works
```

### Issue description

Hello, first of all thanks for a great project! Pixi is very nice!

The issue is that there is a conda package `pyarts` in conda channel `rttools` that has the requirement `__osx >=11.0`, and on my `osx-64` system `pixi info` reports  `__osx=14.5=0`.
But when installing I get an error `__osx >=11.0, for which no candidates were found`.

This is not an issue on arm-based macs: `osx-arm64`.
When doing the same with `rattler` directly, it installs.

A potential lead that might be useful?:
```
$ SYSTEM_VERSION_COMPAT=0 cat /System/Library/CoreServices/SystemVersion.plist
14.4.1

$ SYSTEM_VERSION_COMPAT=1 cat /System/Library/CoreServices/SystemVersion.plist
10.16

$ git checkout rattler-v0.26.0
$ cargo run --release --bin rattler create -c rttools -c conda-forge pyarts
works

$ SYSTEM_VERSION_COMPAT=1 cargo run --release --bin rattler create -c rttools -c conda-forge pyarts
Doesn't work
```

### Expected behavior

Since `pixi info` states I have virtual package `__osx=14.5=0` I do not expect the error:
```
$ pixi add pyarts
× could not determine any available versions for pyarts on osx-64. Either the package could not be found or version constraints on other dependencies result in a conflict.
  ╰─▶ Cannot solve the request because of: pyarts * cannot be installed because there are no viable options:
      └─ pyarts 2.5.4 | 2.5.4 | 2.5.6 | 2.5.6 | 2.5.6 | 2.5.8 | 2.5.8 | 2.5.8 | 2.5.10 | 2.5.10 | 2.5.10 | 2.5.12 | 2.5.12 | 2.5.12 | 2.5.12 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.0 | 2.6.2
      | 2.6.2 | 2.6.2 | 2.6.2 would require
         └─ __osx >=11.0, for which no candidates were found.
```

**Comment by wolfv** [comment]
Can you add the `macos` entry to the `system-requirements` table?

E.g.

```toml
[system-requirements]
macos = "12.0"  # or 13.0
```

It should then resolve fine! :)

**Comment by petermcevoy** [comment]
Thank you @wolfv, that worked great!

For myself and others:
I see my reasoning was a bit flawed also. The virtual packages used for resolving is not the same as my system's current virtual packages from `pixi-info`. Instead it's controlled by the [system-requirements table](https://pixi.sh/latest/reference/project_configuration/#the-system-requirements-table), with defaults if not specified. That makes sense.

Thanks again!
