### ISSUE TITLE
pixi shell broken on Windows if Env vars contains quotes

### ISSUE THREAD

**Issue by melund** [prefix-dev/pixi#1505]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

On windows poweshell create an environment variable with quotes then activate the shell

```shell
❯ $env:MYVAR = '"hello"'
❯ pixi shell
ParserError: D:\TEMP\.tmpDLRbMf.ps1:56
Line |
  56 |  ${Env:MYVAR} = ""hello""
     |                   ~~~~~~~
     | Unexpected token 'hello""' in expression or statement.
```

### Issue description

Quotes are not correctly escaped when creating the tempoarary script used by `pixi shell` in windows powershell. 

### Expected behavior

The command would succeed.

**Comment by ruben-arts** [comment]
Same issue as #1503 

We shouldn't copy the environment variables as the shell will do that itself. #1507 fixes the issue.
