### ISSUE TITLE
After pixi update, cannot launch pixi shell anymore

### ISSUE THREAD

**Issue by ernimd** [prefix-dev/pixi#1512]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```bash
$ pixi shell
$  . "/tmp/pixi_env_1uS.sh"
bash: /tmp/pixi_env_1uS.sh: line 26: syntax error near unexpected token `('
bash: /tmp/pixi_env_1uS.sh: line 26: `export BASH_FUNC_ml()="() {  eval $($LMOD_DIR/ml_cmd "$@")' 
```

### Issue description

After an update, the shell command stops working. The line (or rather two) in the environment causing trouble is:
```bash
export BASH_FUNC_ml()="() {  eval $($LMOD_DIR/ml_cmd "$@")
}"
```

### Expected behavior

Shell initialized properly

**Comment by ruben-arts** [comment]
This issue is fixed by https://github.com/prefix-dev/pixi/pull/1507
