### ISSUE TITLE
Can't hide the stdout

### ISSUE THREAD

**Issue by yanecc** [prefix-dev/pixi#1517]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

``` shell
pixi global install -q clang=18.1.7
pixi global install -q clang=18.1.7 > nul       # Windows
pixi global install -q clang=18.1.7 > /dev/null # Unix
```

### Issue description

Can't hide the stdout of pixi.

### Expected behavior

To hide the stdout completely, but keep the stderr.

**Comment by baszalmstra** [comment]
We ouput logging to stderr instead of stdout. You can pipe that using

```
pixi global install -q clang=18.1.7 2> nul       # Windows
pixi global install -q clang=18.1.7 2> /dev/null # Unix
```

**Comment by yanecc** [comment]
> We ouput logging to stderr instead of stdout. You can pipe that using
> 
> ```
> pixi global install -q clang=18.1.7 2> nul       # Windows
> pixi global install -q clang=18.1.7 2> /dev/null # Unix
> ```

What if I want to keep the stderr?

**Comment by baszalmstra** [comment]
In that case you dont pipe the output? Im not sure I understand what you intend?

**Comment by yanecc** [comment]
> In that case you dont pipe the output? Im not sure I understand what you intend?

I want to process stdout and stderr separately, usually hiding the output when there is no error, and when some error occurs, it should be reported.

**Comment by yanecc** [comment]
@baszalmstra

**Comment by Flova** [comment]
I also encounter this issue. What is the reason for always using stderr. See the following example:

```
pixi install --quiet --no-progress  > /dev/null
✔ The default environment has been installed.
```

For the lowest log level, I would expect to only get terminal output if something went wrong and no output if everything goes well. Instead, I get these status messages or I need to hide all errors.
