### ISSUE TITLE
Unable to install mamba-ssm as a pypi dependency

### ISSUE THREAD

**Issue by kszlim** [prefix-dev/pixi#1518]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
# setup base environment
pixi init --pyproject
pixi add mamba-ssm
```

### Issue description

I'm unable to install mamba-ssm as a pypi dependency, it breaks even if i add pip as a conda dep and if i add packaging as a pypi dep.

```
pixi add --pypi mamba-ssm
  ⠂ default:linux-64     [00:00:00] resolving mamba-ssm==2.0.4                                                                                                                                                                                                  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ├─▶ Failed to download and build `mamba-ssm==2.0.4`
  ├─▶ Failed to build: `mamba-ssm==2.0.4`
  ╰─▶ Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
      --- stdout:
      
      --- stderr:
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "/path/to/home/.cache/rattler/cache/uv-cache/.tmpuEioZ7/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/path/to/home/.cache/rattler/cache/uv-cache/.tmpuEioZ7/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/path/to/home/.cache/rattler/cache/uv-cache/.tmpuEioZ7/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/path/to/home/.cache/rattler/cache/uv-cache/.tmpuEioZ7/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'packaging'
      ---
```

I'm able to get it to install using `pip` on top of my pixi setup (but it required that i had a properly setup cuda/torch env + installed `packaging`), and also am able to get it installing with `uv` if I follow the workaround described [here](https://github.com/astral-sh/uv/issues/4354#issuecomment-2172743481). I'm not sure what work would be required for it to work in pixi?

### Expected behavior

Should by added with minimal fuss (and maybe an extra flag in the pyproject.toml if required)

**Comment by tdejager** [comment]
Indeed, if we support that flag we should be able to create a conda workspace with packaging and build without isolation using that dependency.

**Comment by tdejager** [comment]
Should now be possible with #1909 merged, and will soon be released, documentation is here: https://pixi.sh/dev/reference/project_configuration/#no-build-isolation
