### ISSUE TITLE
Pixi run without updating or checking dependencies

### ISSUE THREAD

**Issue by brian316** [prefix-dev/pixi#1528]
### Problem description

want to run command `pixi run` without it trying to update packages every time.

**Comment by wolfv** [comment]
Hi @brian316 - are you using pyproject.toml with editable dependencies?

I think if you pass `--locked` or `--frozen` this should help.

**Comment by tdejager** [comment]
Could you share the `pyproject.toml` so that we can reproduce? :)

**Comment by baszalmstra** [comment]
We need more information to act on this. Closing for now. Feel free to reopen if the issue persists.
