### ISSUE TITLE
In `pixi shell`, add an option to turn off the prompt

### ISSUE THREAD

**Issue by Yura52** [prefix-dev/pixi#1533]
### Problem description

I use starship as the prompt provider for my zsh. Currently, in `pixi shell`, the prompt by Pixi is concatenated with the prompt generated by starship, and the result does not look good. Is it possible to add an option to turn off the prompt modifier provided by Pixi?

**Comment by wolfv** [comment]
Yes, there is an option in the config file: https://pixi.sh/latest/reference/pixi_configuration/#change-ps1

**Comment by corneliusroemer** [comment]
As a +1 here, I would suggest maybe making the prompt opt _in_ rather than opt _out_.

It's quite intrusive right now (at least to a starship user, which I am)

This came up before here: https://github.com/prefix-dev/pixi/issues/1275
