### ISSUE TITLE
Return value of pixi run is not the one of the wrapped command

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#157]
I am experimenting a bit of integrating pixi with a CI of a C++-based CLI tool in https://github.com/ami-iit/onnx-cpp-benchmark/pull/3. The idea is to run the cli tool in the CI with the --help option as a smoke testing, to see if it start normally without loading errors or similar problems.

However, while I ran:
~~~
pixi run onnx-cpp-benchmark --help
~~~

I was expecting `pixi run` to propagate the return value of `onnx-cpp-benchmark --help` . Instead, it seems that the two return values are different, and `pixi run` returns a non-zero value even if the launched command returned with zero value:
~~~
traversaro@IITICUBLAP257:~/onnx-cpp-benchmark$ pixi run onnx-cpp-benchmark --help
onnxfilepath is required
Run with --help for more information.
traversaro@IITICUBLAP257:~/onnx-cpp-benchmark$ echo $?
106
traversaro@IITICUBLAP257:~/onnx-cpp-benchmark$ mamba activate .pixi/env
(/home/traversaro/onnx-cpp-benchmark/.pixi/env) traversaro@IITICUBLAP257:~/onnx-cpp-benchmark$ .build/onnx-cpp-benchmark --help
onnx-cpp-benchmark: Simple tool to profile onnx inference with C++ APis.
Usage: .build/onnx-cpp-benchmark [OPTIONS] onnxfilepath

Positionals:
  onnxfilepath TEXT:FILE REQUIRED
                              The name of the onnx file to benchmark

Options:
  -h,--help                   Print this help message and exit
  --batch_size INT            Number of parallel inputs in one iteration/inference run
  --iterations INT            Number of iterations (inference runs) to use for benchmark
  --backend TEXT              Backend to use, one of : onnxruntimecpu, onnxruntimecuda
(/home/traversaro/onnx-cpp-benchmark/.pixi/env) traversaro@IITICUBLAP257:~/onnx-cpp-benchmark$ echo $?
0
~~~

**Comment by wolfv** [comment]
Thanks! I'll give this a shot - should be straight forward to fix :)

**Comment by wolfv** [comment]
Well, I think @tdejager already fixed it in this PR! https://github.com/prefix-dev/pixi/pull/138/files#diff-71509a72ac18869fce4fffe3bb56afd0e916ac02565049a4c621b2a3d0a118e2R149 :)

We'll do another release today with the fix (hopefully).

**Comment by traversaro** [comment]
> Well, I think @tdejager already fixed it in this PR! https://github.com/prefix-dev/pixi/pull/138/files#diff-71509a72ac18869fce4fffe3bb56afd0e916ac02565049a4c621b2a3d0a118e2R149 :)

Thanks! I should have fixed with the latest version indeed.

**Comment by traversaro** [comment]
I just tested and indeed this is working fine in pixi 0.0.6 release, thanks a lot!
