### ISSUE TITLE
`exec` broken after aborted environment creation

### ISSUE THREAD

**Issue by jonashaag** [prefix-dev/pixi#1577]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Run any `pixi exec` and abort during environment creation, then re-run, e.g.:

```
❯ pixi exec -s 'tesseract<5' tesseract ...
  × failed to execute 'tesseract'
  ╰─▶ No such file or directory (os error 2)
```

### Issue description

When environment creation is aborted during `exec`, it can't be resumed

### Expected behavior

Should resume/recreate environment needed to run `exec`

**Comment by tdejager** [comment]
Thanks, was able to re-create!
