### ISSUE TITLE
pixi run does not support --manifest-path, even though the help says it does

### ISSUE THREAD

**Issue by sg-s** [prefix-dev/pixi#1603]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell

cd ~/
mkdir pixi-bug
cd pixi-bug
pixi init
cd /


pixi add jupyterlab --manifest-path ~/pixi-bug/pixi.toml
pixi list --manifest-path ~/pixi-bug/pixi.toml | grep "jupyter"

pixi run jupyter lab --manifest-path ~/pixi-bug/pixi.toml

```

i get this errror:

```
  × could not find pixi.toml or pyproject.toml which is configured to use pixi
```

despite me massing in `--manifest-path`. 

### Issue description

looks like --manifest-path isn't being read for the run command

### Expected behavior

i expect it to run as though i were in the directory containing the manifest-path

**Comment by baszalmstra** [comment]
Try adding the argument right after run. Otherwise the argument is passed to jupyter instead.

**Comment by sg-s** [comment]
oof basic fail. thanks for that, that works!
