### ISSUE TITLE
All commands fail for private registry

### ISSUE THREAD

**Issue by jamesfricker** [prefix-dev/pixi#1606]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell

```

Not able to reproduce on a public registry.

### Issue description

I add a private registry to my pixi.toml, and get the following error when attempting any operation involving the newly added registry. 

```shell
pixi search $pkg

invalid type: floating point “1719972900.0”, expected i64 at line 12 column 31.
```

### Expected behavior

I expect that I am able to search/download packages from this private registry. This registry works with conda.

**Comment by wolfv** [comment]
It seems that your repodata.json is broken in some ways and contains `float` timestamps (while it should be an integer). We seem to be more strict about that then conda ... 

Can you identify the package that has this metadata and remove it?

**Comment by jamesfricker** [comment]
Thanks for the tip! Looks like the timestamp field in the repodata is a float, when the conda sceham clearly states that it should be an integer. 

Fixing that should solve my problem.

Thanks for your help!
