### ISSUE TITLE
pixi add ollama not working correctly but pixi add --pypi "ollama" works

### ISSUE THREAD

**Issue by amiune** [prefix-dev/pixi#1613]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi add ollama
# Added ollama seems to work but...
pixi run python -c "import ollama"
# ModuleNotFoundError: No module named 'ollama'
pixi add --pypi "ollama"
# this works ok
pixi run python -c "import ollama"
```

### Issue description

Cannot import ollama when adding through pixi add ollama

### Expected behavior

```shell
pixi add ollama
# Added ollama seems to work but...
pixi run python -c "import ollama"
# ModuleNotFoundError: No module named 'ollama'
```

**Comment by ruben-arts** [comment]
I get the same error with `micromamba` so I'm assuming it's not `pixi` here but rather the package of ollama itself. Could you contact the feedstock maintainers? https://github.com/conda-forge/ollama-feedstock/issues

**Comment by amiune** [comment]
Yes you are right I also tested the same thing a few moments ago. Thank you.
