### ISSUE TITLE
pixi shell does not print something before the terminal prompt to signal that a conda environment is active

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#163]
`conda`, `mamba` and `micromamba` all print something before the terminal prompt to signal that a conda environment is activated. I found it would be convenient if also `pixi shell` did something like that.

**Comment by ruben-arts** [comment]
Good one! going to add that as I was also missing that myself!

**Comment by ruben-arts** [comment]
It is merged in #201 but it is not working perfectly yet see #219 so closing this as it is redundant. Reopen if I missed something!

**Comment by traversaro** [comment]
Thanks a lot!
