### ISSUE TITLE
Standardize whether we use `stdout` or `stderr` for machine-readable output

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#1638]
`pixi run --machine-readable` uses `stderr`: https://github.com/prefix-dev/pixi/blob/b819cffd59ea5bd723b26b7ce27bfa7497c8e3bf/src/cli/task.rs#L426

While we print the `--json` flag at `stdout`: https://github.com/prefix-dev/pixi/blob/b819cffd59ea5bd723b26b7ce27bfa7497c8e3bf/src/cli/list.rs#L297-L298

My feeling is it should all be `stdout`.

**Comment by ruben-arts** [comment]
Yes, I think you are correct. Machine readable should always go to stdout. Only user messages should go to stderr.
