### ISSUE TITLE
Fails to install package

### ISSUE THREAD

**Issue by EdvardsZ** [prefix-dev/pixi#1666]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
[project]
channels = ["nvidia/label/cuda-11.8.0", "conda-forge", "pytorch"] # conda channels
name = "fail"
platforms = ["linux-64"]

[dependencies] # conda system dependencies
python = "3.10.*"
cuda = { version = "*", channel = "nvidia/label/cuda-11.8.0" }
pytorch-cuda = { version = "11.8", channel = "pytorch" }
pytorch = { version = "*", channel = "pytorch" }

[pypi-dependencies] # pipy dependencies
gsplat = {git="https://github.com/nerfstudio-project/gsplat", extras = ["no-build-isolation"]}
```

### Issue description

I know that pixi under the hood uses uv package so I thought that this is problem with uv so I opened an issue there:
[uv issue](https://github.com/astral-sh/uv/issues/5399)

However, the problem with `uv` is fixed when I install first` torch` and then installl it using `--no-build-isolation`.

When I try my provided pixi.toml and run `pixi install` it fails.
I have the latest pixi version 0.26.1

### Expected behavior

it installs the package and succeeds

**Comment by ruben-arts** [comment]
Hi @EdvardsZ,

We currently don't support `--no-build-isolation`, this is the tracked issue for that: https://github.com/prefix-dev/pixi/issues/1124.

A workaround for your current workflow would be to use `pip` in a pixi task to install it into the environment. 

I'm going to close this issue in favor of the other one. Feel free to comment further there. And please give it a :+1: to bump the importance of it!
