### ISSUE TITLE
Cannot run remove --no-install

### ISSUE THREAD

**Issue by clement-chaneching** [prefix-dev/pixi#1669]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
[project]
dependencies = [
    "package-1",
]
```
Run `pixi remove --no-install --pypi package-1`

### Issue description

I cannot run pixi remove --no-install because i m getting:
```
  × Cannot update pypi dependencies without first installing a conda prefix that includes python.
```

I want the --no-install because the idea is to be able to run something that removes private packages and then add them as editable package instead.

```
   pixi remove --no-install --pypi private-package-1 \
    && pixi remove --no-install --pypi --feature env1 private-package 2 \
    && pixi add --pypi --pypi-keyring-provider subprocess \
    "private-package1 @ file:///app/private-package1" \
    --editable \
```

Shouldnt --no-install just clean the pyproject.toml and the pixi.lock?
Not sure where that error is coming from

### Expected behavior

I have a current workaround using sed to comment out the private packages that I do not want, and then run pixi add, but its not really clean.

**Comment by ruben-arts** [comment]
He @clement-chaneching, we can't update the lockfile without installing when using `pypi-dependencies`. But what you are looking for is `--no-lockfile-update` this avoids all lockfile and installation logic. It only edits the manifest.

**Comment by clement-chaneching** [comment]
Oh yes thanks it works.
It should probably be added in the doc : https://pixi.sh/latest/reference/cli/#remove

**Comment by clement-chaneching** [comment]
Sorry @ruben-arts, it looks like it works on my local, but not on my Dockerfile:
![image](https://github.com/user-attachments/assets/b0a79b7e-faf6-4b4b-b788-b0557d1f61e5)

As mentioned, i m just trying to remove a dependency from my manifest, not sure what it takes 300s and then tries to update my pypi prefix.

**Comment by clement-chaneching** [comment]
Sure.
With this dockerfile:

```
FROM ghcr.io/prefix-dev/pixi:0.26.1 AS build

COPY pyproject.toml pixi.lock ./

RUN pixi remove --no-lockfile-update --pypi retrying
```

And a pyproject.toml like this:
```
[project]
name = "..."

dependencies = [
    "retrying",
    "private-package"
]

[tool.pixi.pypi-options]
extra-index-urls = ["https://oauth2accesstoken@<google artifact registry URL>simple"]

```

Install pixi lock with pixi install --pypi-keyring-provider subprocess
Then run docker build .

![image](https://github.com/user-attachments/assets/4548f494-93b6-4829-a999-ec26111bb478)

**Comment by olivier-lacroix** [comment]
@ruben-arts , the mental model I have currently of how pixi  works is the below:

1. Update manifest
2. Update lockfile based on manifest
3. Install prefix based on lockfile

My understanding of the CLI options are as follow

- `—no-install` does 1 and 2 but not 3
-  `—no-lockfile-update` does 1 but not 2 nor 3
-  `—frozen` does 3 but not 1 nor 2

This means that `—frozen —no-install` would be a no-op / conflict , and is not equivalent to `—no-lockfile-update` I think.

This being said, I agree that with `—no-lockfile-update`, for a remove operation, there should be no need to authenticate to anything. This wouldn’t always be true for an add operation, as we sometimes add version range to packages.

Does this help?

**Comment by ruben-arts** [comment]
I can see what you mean, my idea of these flags is not a "does" but only a subtraction. So my mental model currently is:
- `--no-install`: No install of at all prefix, not for solving not for running.
- `--locked`: No solving but checking if the lockfile is up to date.
- `--frozen`: No solving and not checking, thus no lock file update.

So for me the `--no-lockfile-update` is just a concatenation of `--frozen --no-install` this is also how it is implemented in code at the moment. (if we ignore the problem of this Issue)

Could that make sense for you to?

**Comment by olivier-lacroix** [comment]
@ruben-arts , I see.

But `—frozen` and `—no-install` would never be used together, right?

- For `pixi install`, specifying both would mean doing nothing at all, 
- For `pixi add` or `pixi remove`, you cannot really install without touching the lockfile, so that means `—frozen` implies `—no-install`

This to say that I don’t really feel they are additive options?

**Comment by ruben-arts** [comment]
I think we have opposite understandings of the result of these flags. Which kind of worries me, as we've both spend a significant amount of time in the `pixi` code-base. This tells me we're not making the right decision doing either of the options. 

Lets pull this into a different form of discussion and leave this Issue for the fix of the current bug.
