### ISSUE TITLE
recipe-less conda build / index alike functionality for pyproject.toml-based projects

### ISSUE THREAD

**Issue by kfot** [prefix-dev/pixi#1682]
### Problem description
Is it currently possible to replace conda build / conda index with pixi? I learned from https://github.com/prefix-dev/pixi/issues/248 that I can use rattler-build for that, but it looks like it relies on conda recipe, while my main goal is to fully switch to `pyproject.toml` based configuration, including the package publishing phase and making the recipe redundant.

If I get the current setup right, the recipe is still required and it prevents the users from having the requirements defined only in `pyproject.toml`.

I would also like to mention https://github.com/prefix-dev/pixi/issues/593 as the docs are silent on the detailed purpose, behavior and configurability of the `upload` subcommand.

**Comment by olivier-lacroix** [comment]
This is in the works 😀. See https://github.com/prefix-dev/pixi/issues/1654

**Comment by ruben-arts** [comment]
Closing in favor or the on going work in #1654
