### ISSUE TITLE
`pixi global install` does not allow version specifications in 0.26.x

### ISSUE THREAD

**Issue by davised** [prefix-dev/pixi#1685]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
❯ pixi --version
pixi 0.26.1
❯ pixi global install numpy=2.0.1
  × 'numpy=2.0.1' is not a valid package name. Package names can only contain 0-9, a-z, A-Z, -, _, or .
```
Ignore that numpy isn't a good example for global install. It happens with other packages too : 

```shell
❯ pixi global install bat=0.24.0
  × 'bat=0.24.0' is not a valid package name. Package names can only contain 0-9, a-z, A-Z, -, _, or .
```

### Issue description

`pixi global install` fails when the package has a version specified. This does not happen on versions <= 0.25.0.

### Expected behavior

Previous versions allowed a version specification during global install. I see no reason to continue allowing version specifications for global installs.

**Comment by davised** [comment]
My current work-around is to install pixi v0.25.0 binary as `pixi-0.25.0` and use that for global installs that need a version specified.

```shell
❯ ./pixi-0.25.0 global install kneaddata=0.12.0
✔ Installed package kneaddata 0.12.0 pyhdfd78af_1 from bioconda
  These executables are now globally available:
   -  kneaddata_trf_parallel
   -  kneaddata
   -  kneaddata_bowtie2_discordant_pairs
   -  kneaddata_database
   -  kneaddata_build_database
   -  kneaddata_read_count_table
   -  kneaddata_test
```

**Comment by baszalmstra** [comment]
Thanks for reporting! We will fix this. As a workaround try adding spaces: "numpy 2.0.1"

**Comment by davised** [comment]
> Thanks for reporting! We will fix this. As a workaround try adding spaces: "numpy 2.0.1"

Looks like that uncovers another bug:

```shell
❯ pixi global install bat 0.24.0
✔ Installed package bat 0.24.0 he8a937b_0 from conda-forge
  × Cannot solve the request because of: No candidates were found for 0.24.0 *.
  │
```

**Comment by baszalmstra** [comment]
Youll need to add quotes!

**Comment by davised** [comment]
> Youll need to add quotes!
> 
> pixi global install "bat 0.24.0"

```shell
❯ pixi global install "bat 0.24.0"
  × 'bat 0.24.0' is not a valid package name. Package names can only contain 0-9, a-z, A-Z, -, _, or .
```
Quotes works on previous versions though:

```shell
❯ ./pixi-0.25.0 global install "bat 0.24.0"
✔ Installed package bat 0.24.0 he8a937b_0 from conda-forge
  These executables are now globally available:
   -  bat
```

**Comment by baszalmstra** [comment]
Haha Im sorry, its currently missing an operator, try:

pixi global install "bat =0.24.0"

Ill take a better look next week. Parsing and the error messages can definitely be improved.

**Comment by davised** [comment]
> Haha Im sorry, its currently missing an operator, try:
> 
> pixi global install "bat =0.24.0"
> 
> Ill take a better look next week. Parsing and the error messages can definitely be improved.

Still broken on the latest version, but works on the previous:

```shell
❯ pixi global install "bat =0.24.0"
  × 'bat =0.24.0' is not a valid package name. Package names can only contain 0-9, a-z, A-Z, -, _, or .

❯ ./pixi-0.25.0 global install "bat =0.24.0"
✔ Installed package bat 0.24.0 he8a937b_0 from conda-forge
  These executables are now globally available:
   -  bat
```
