### ISSUE TITLE
Sudden "failed to resolve pypi dependencies" on WSL2

### ISSUE THREAD

**Issue by SharkWipf** [prefix-dev/pixi#1686]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

https://github.com/nerfstudio-project/nerfstudio/blob/main/pixi.toml

The specific WSL2 instructions: https://gist.github.com/SharkWipf/0a3fc1be3ea88b0c9640db6ce15b44b9

### Issue description

As of presumably the latest version(s), and specifically (so far) only under WSL2, Pixi fails to resolve pypi dependencies.
This issue has been noted by several people trying to install Nerfstudio under WSL2 via Pixi the past ~day, while it was fine previously.

```
~/src/nerfstudio$ pixi run -v --color never post-install | cat -
 INFO pixi::environment: verifying prefix location is unchanged, with prefix file: /home/user/src/nerfstudio/.pixi/envs/default/conda-meta/pixi_env_prefix
 INFO pixi::lock_file::outdated: the pypi dependencies of environment 'default' for platform linux-64 are out of date because source tree hash for nerfstudio does not match the hash in the lock-file
 INFO pixi::lock_file::resolve::uv_resolution_context: uv keyring provider is disabled
 INFO pixi::environment: Creating prefix file at: /home/user/src/nerfstudio/.pixi/envs/default/conda-meta/pixi_env_prefix
 INFO pixi::environment: No update needed for the prefix file.
 INFO pixi::environment: Checking if history file exists: /home/user/src/nerfstudio/.pixi/envs/default/conda-meta/history
 INFO pixi::lock_file::update: updated conda packages in the 'default' prefix in 89ms 803us 2ns
 INFO resolve_pypi{group=default platform=linux-64}: pixi::lock_file::resolve::pypi: the following python packages are assumed to be installed by conda: wheel 0.43.0, networkx 3.3, brotli 1.1.0, pysocks 1.7.1, torch 2.2.2, certifi 2024.2.2, pip 24.0, setuptools 69.5.1, mpmath 1.3.0, sympy 1.12, idna 3.7, pyarrow 15.0.2, urllib3 2.2.1, charset-normalizer 3.3.2, jinja2 3.1.4, gmpy2 2.1.5, pillow 10.3.0, numpy 1.26.4, pyyaml 6.0.1, requests 2.31.0, markupsafe 2.1.5, torchvision 0.17.2, filelock 3.14.0, typing-extensions 4.11.0
  ⠙ default:linux-64     [00:00:00] resolving fire==0.6.0                                       × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ├─▶ Failed to download and build fire==0.6.0
  ├─▶ Failed to build: fire==0.6.0
  ├─▶ Failed to install requirements from build-system.requires (install)
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: setuptools==69.5.1
  ├─▶ Failed to extract archive
  ╰─▶ Unsupported archive type: setuptools
```
Both the ~/.pixi folder and the git repo with the pixi.toml file exist on the native Linux filesystem, not on the mapped Windows filesystem, so that shouldn't be the issue.
Removing the ~/.pixi and ~/src/nerfstudio/.pixi folders and starting fresh did not help.

(Edit: Installing via pip or conda directly does not have this issue, it's seems to be specific to Pixi specifically)

Note: I have not yet reproduced this myself yet as I am not near my WSL2 machine, but since multiple users have reported it I figured it was worth opening an issue over now.
I will hopefully be reproducing and debugging the issue myself somewhere in the coming week. I should also be able to test any suggestions then.

### Expected behavior

(Same freshly installed Pixi and Nerfstudio version, on native Alma 9 instead of WSL2)

```
(0) sebastiaan@almavm:~/src/nerfstudio $ pixi run post-install
✨ Pixi task (make-third_party-dir): ls third_party || mkdir third_party
Hierarchical-Localization

✨ Pixi task (clone-hloc): ls Hierarchical-Localization || git clone --recursive https://github.com/cvg/Hierarchical-Localization/
Dockerfile  LICENSE  README.md  datasets  demo.ipynb  doc  hloc  hloc.egg-info  pairs  pipeline_Aachen.ipynb  pipeline_InLoc.ipynb  pipeline_SfM.ipynb  requirements.txt  setup.py  third_party

✨ Pixi task (hloc-install): python -m pip install -e .
Obtaining file:///home/sebastiaan/src/nerfstudio/third_party/Hierarchical-Localization
  Preparing metadata (setup.py) ... done
Collecting lightglue@ git+https://github.com/cvg/LightGlue (from hloc==1.5)
```

**Comment by DrJessop** [comment]
Just wanted to mention I noticed this same error signature with an imageio-ffmpeg pypi dependency in our CI pipeline. For us, however, this is a sporadic failure.

Here is the signature
```bash
   INFO resolve_pypi{group=default platform=osx-arm64}:get_or_build_wheel_metadata{dist=imageio-ffmpeg==0.5.1}:build_metadata{dist=imageio-ffmpeg==0.5.1}:setup_build{version_id="imageio-ffmpeg==0.5.1" subdirectory=None}: uv_virtualenv::bare: Ignoring empty directory
   INFO solve:solve_tracked: pubgrub::internal::partial_solution: add_decision: root @ 0a0.dev0    
   INFO solve:solve_tracked: pubgrub::internal::partial_solution: add_decision: setuptools @ 71.0.4    
    × failed to solve the pypi requirements of 'default' 'osx-arm64'
    ├─▶ Failed to build: `imageio-ffmpeg==0.5.1`
    ├─▶ Failed to install requirements from build-system.requires (install)
    ├─▶ Failed to prepare distributions
    ├─▶ Failed to fetch wheel: setuptools==71.0.4
    ├─▶ Failed to extract archive
    ╰─▶ Unsupported archive type: setuptools
```

As mentioned, it's non-deterministic. When it does pass, it seems to be using the 'cuda' group rather than the 'default' group. Here is an example of the logs from when it passes 

```bash
   INFO resolve_pypi{group=cuda platform=osx-arm64}:get_or_build_wheel_metadata{dist=imageio-ffmpeg==0.5.1}:build_metadata{dist=imageio-ffmpeg==0.5.1}:setup_build{version_id="imageio-ffmpeg==0.5.1" subdirectory=None}: uv_virtualenv::bare: Ignoring empty directory
```

Not sure what's going on here.

What seemed to fix this problem for us was to just add imageio-ffmpeg as a dependency rather than using a transitive pypi dependency, but it would still be nice to know what the problem is.

I was not able to reproduce locally on my mac, I just have the github runner logs, but I can share the toml that sporadically fails as well as the toml that seems to be robust:

FAILURE TOML
```toml
#:schema https://raw.githubusercontent.com/prefix-dev/pixi/main/schema/schema.json
[project]
name = "research"
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
ax-platform = "=0.3.6"                                        # https://github.com/ray-project/ray/issues/45720
equinox = ">=0.11.4,<0.12"
gymnasium = ">=0.28,<0.29"
jax = ">=0.4.26,<0.5.0"
loguru = ">=0.7.0,<0.8.0"
mlflow-skinny = ">=2.12.1,<2.13"
optax = ">=0.2.2,<0.3"
plum-dispatch = ">=2.4.1,<2.5"
py-spy = ">=0.3.14,<0.4.0"
pygame = ">=2.5,<2.6"
pyright = ">=1.1.358,<1.2"
pytest = ">=8.0,<9.0"
pytest-cov = ">=5.0.0,<5.1"
pytest-skip-slow = ">=0.0.5,<0.1"
pytorch = { version = ">=2.3.0,<2.4.0", channel = "pytorch" }
ray-client = ">=2.31,<2.32"
ray-default = ">=2.31,<2.32"                                  # Needed to run ray server on cluster
ray-tune = ">=2.31,<2.32"
tqdm = ">=4.66.2,<4.67"
jax-dataclasses = ">=1.6.1,<1.7"

[feature.cuda]
# CUDA not really supported on osx-arm64 but we have to pretend
# so that Pixi can install things correctly.
platforms = ["linux-64", "osx-arm64"]
channels = ["nvidia"]
system-requirements = { cuda = "12" }

[feature.cuda.target.linux-64.dependencies]
# jaxlib requires a newer version than what is available in nvidia channel
cudnn = { version = "*", channel = "conda-forge" }
jaxlib = { version = ">=0.4.23,<0.5.0", build = "*cuda12*" }
pytorch-cuda = { version = "=12.1", channel = "pytorch" }

[feature.cuda.target.osx-arm64.dependencies]
jaxlib = ">=0.4.23,<0.5.0"

[host-dependencies]
python = ">=3.11,<3.12"

[pypi-dependencies]
craftax = "==1.4.1"
crafter = "~=1.8.3"
research = { path = "./", editable = true }
gymnax = "==0.0.8"
minigrid = "~=2.3.1"
xminigrid = ">=0.7,<0.8"
rlax = ">=0.1.6,<0.1.7"
flashbax = ">=0.1.2,<0.1.3"

[environments]
cuda = ["cuda"]
```

PASSING TOML
```toml
#:schema https://raw.githubusercontent.com/prefix-dev/pixi/main/schema/schema.json
[project]
name = "research"
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
ax-platform = "=0.3.6"                                        # https://github.com/ray-project/ray/issues/45720
equinox = ">=0.11.4,<0.12"
gymnasium = ">=0.28,<0.29"
imageio-ffmpeg = ">=0.5.1,<0.6"
jax = ">=0.4.26,<0.5.0"
jax-dataclasses = ">=1.6.1,<1.7"
loguru = ">=0.7.0,<0.8.0"
mlflow-skinny = ">=2.12.1,<2.13"
optax = ">=0.2.2,<0.3"
plum-dispatch = ">=2.4.1,<2.5"
py-spy = ">=0.3.14,<0.4.0"
pygame = ">=2.5,<2.6"
pyright = ">=1.1.358,<1.2"
pytest = ">=8.0,<9.0"
pytest-cov = ">=5.0.0,<5.1"
pytest-skip-slow = ">=0.0.5,<0.1"
pytorch = { version = ">=2.3.0,<2.4.0", channel = "pytorch" }
ray-client = ">=2.31,<2.32"
ray-default = ">=2.31,<2.32"                                  # Needed to run ray server on cluster
ray-tune = ">=2.31,<2.32"
tqdm = ">=4.66.2,<4.67"

[feature.cuda]
# CUDA not really supported on osx-arm64 but we have to pretend
# so that Pixi can install things correctly.
platforms = ["linux-64", "osx-arm64"]
channels = ["nvidia"]
system-requirements = { cuda = "12" }

[feature.cuda.target.linux-64.dependencies]
# jaxlib requires a newer version than what is available in nvidia channel
cudnn = { version = "*", channel = "conda-forge" }
jaxlib = { version = ">=0.4.23,<0.5.0", build = "*cuda12*" }
pytorch-cuda = { version = "=12.1", channel = "pytorch" }

[feature.cuda.target.osx-arm64.dependencies]
jaxlib = ">=0.4.23,<0.5.0"

[host-dependencies]
python = ">=3.11,<3.12"

[pypi-dependencies]
craftax = "==1.4.1"
crafter = "~=1.8.3"
research = { path = "./", editable = true }
gymnax = "==0.0.8"
minigrid = "~=2.3.1"
xminigrid = ">=0.7,<0.8"
rlax = ">=0.1.6,<0.1.7"
flashbax = ">=0.1.2,<0.1.3"

[environments]
cuda = ["cuda"]
```

**Comment by ruben-arts** [comment]
Pinging @tdejager for pypi expertise.

**Comment by geoHeil** [comment]
same here - on osx apple silicon https://github.com/prefix-dev/pixi/issues/1686 reproducible for a list of packages

**Comment by tdejager** [comment]
Sorry I briefly looked into this, I think this is happening somewhere in the uv code. I suspect it's getting an archive without extension when building a source dist, but couldn't figure out why.

I'll have a closer look tomorrow, @SharkWipf do you know if the failure are sporadic for you and your users as well?

**Comment by SharkWipf** [comment]
Due to several unlucky circumstances I haven't gotten around to testing it myself yet, I'll try to get to it soon.
I haven't seen any new reports of the issue, but I also modified the guide to warn of this issue and push for the non-Pixi install method until it's figured out. On top of that, the native Windows Nerfstudio docs got updated to handle more edge cases, so I imagine less people are trying and thus running into the issue atm.

**Comment by tdejager** [comment]
Oh thats too bad, because its a great use-case for pixi I think :) Lets see if we can fix it!

**Comment by tdejager** [comment]
> same here - on osx apple silicon #1810 reproducible for a list of packages
> 
> even for rather simple dependency graphs:
> 
> ```toml
> [dependencies]
> 
> python = "3.11"
> pip = ">=24.2"
> 
> [pypi-dependencies]
> dbt-core = "~=1.8.5"
> ```

I can't reproduce on apple silicon :(, could you maybe attach the lock file as well?

**Comment by tdejager** [comment]
My current hunch is that both of your enviroments lock `setuptools` as a conda package, this overrides the uv solve even for the sdist build (it seems, even though it's using a python venv for this). And that this somehow causes issues.

**Comment by geoHeil** [comment]
> > same here - on osx apple silicon #1810 reproducible for a list of packages
> > even for rather simple dependency graphs:
> > ```toml
> > [dependencies]
> > 
> > python = "3.11"
> > pip = ">=24.2"
> > 
> > [pypi-dependencies]
> > dbt-core = "~=1.8.5"
> > ```
> 
> I can't reproduce on apple silicon :(, could you maybe attach the lock file as well?

Very strange - I tried it again today morning - and I can no longer reproduce these problems

**Comment by tdejager** [comment]
Could be a spurious issue with the registry

**Comment by SharkWipf** [comment]
> My current hunch is that both of your enviroments lock `setuptools` as a conda package, this overrides the uv solve even for the sdist build (it seems, even though it's using a python venv for this). And that this somehow causes issues.

Sounds plausible, we did have to pin setuptools to <70 for a while (maybe still).

**Comment by ruben-arts** [comment]
The nerfstudio example reproduces on my PopOS linux-64:
```
nerfstudio on  main is 📦 v1.1.3
❯ pixi i
  ⠴ default:linux-64     [00:00:00] resolving fire==0.6.0                         × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ├─▶ Failed to download and build `fire==0.6.0`
  ├─▶ Failed to build: `fire==0.6.0`
  ├─▶ Failed to install requirements from build-system.requires (install)
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: setuptools==69.5.1
  ├─▶ Failed to extract archive
  ╰─▶ Unsupported archive type: setuptools
```

**Comment by tdejager** [comment]
Yeah we verified this on wsl2 as well, the strange thing being if you add `fire` directly as a dependency it does seem to work. So the fact that is being installed from an editable, seems to have something to do with it.

Also, I've looked in the uv codebase and can find the error, but not any usage of it.

**Comment by ruben-arts** [comment]
The issue is coming from this line: https://github.com/astral-sh/uv/blob/0.2.18/crates/uv-extract/src/stream.rs#L261

The archive function is used in multiple places but it's gone in the latest version of `uv` so I propose to update the `uv` version and see if that fixes it.

**Comment by violetamenendez** [comment]
Hi,

I just wanted to confirm that this is not a WSL2 issue, I am getting the same on native Linux Ubuntu 22.04 very consistently. Not intermitently at all, but it is true that the first time I attempted it it failed blaming `pycollada==0.8`, and the rest (more than ten attempts across several hours) has been `fire==0.6.0`. Let me know if there's anything specific I can test or help with.

```
$ PIXI_CACHE_DIR=/<path>/.cache/rattler pixi run post-install
  ⠉ default:linux-64     [00:00:02] resolving fire==0.6.0
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ├─▶ Failed to download and build `fire==0.6.0`
  ├─▶ Failed to build: `fire==0.6.0`
  ├─▶ Failed to install requirements from build-system.requires (install)
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: setuptools==69.5.1
  ├─▶ Failed to extract archive
  ╰─▶ Unsupported archive type: setuptools
```

**Comment by geoHeil** [comment]
https://github.com/prefix-dev/pixi/issues/1917 is probably related

**Comment by tdejager** [comment]
I've made a PR that I think will resolve this issue: https://github.com/prefix-dev/pixi/pull/1969 we should test this after it lands in main. Also #1909 was added giving us a bit more control on the wheel building side of things.

**Comment by tdejager** [comment]
Okay so I think that previous referenced PR solved it and I'm adding a linux only test to keep verifying this: https://github.com/prefix-dev/pixi/pull/1996, it was failing on linux consistently for a lot of users so I hope this test avoids this from happening

**Comment by tdejager** [comment]
Downstream test has been added to our CI for linux.
