### ISSUE TITLE
Can no longer specify package version

### ISSUE THREAD

**Issue by slobodaapl** [prefix-dev/pixi#1715]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi global install python=3.11
```

### Issue description

Previous, we were able to use `pixi global install python=3.11` to install python 3.11, this worked on older pixi versions, but now it gives us:

```
'python=3.11' is not a valid package name. Package names can only contain
 0-9, a-z, A-Z, -, _, or .
 ```

### Expected behavior

Pixi correctly installs specified package version

**Comment by ruben-arts** [comment]
Yep indeed
