### ISSUE TITLE
Use the new repodata gateway in `pixi search`

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#1720]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
# Clone pixi, and go into its folder 
❯ pixi search -c https://fast.prefix.dev/conda-forge rattler-build
Using channels from arguments: https://fast.prefix.dev/conda-forge
ERROR error=repodata not found
ERROR error=repodata not found
  × failed to fetch repodata from channels
  ├─▶ repodata not found
  ╰─▶ HTTP status client error (404 Not Found) for url (https://
      fast.prefix.dev/conda-forge/noarch/repodata.json)
```

### Issue description

We're using a new repodata fetching function from rattler in the environment generation of the projects. But we've yet to do it in all of pixi. 

### Expected behavior

We should always be able to use the fast index :rocket:

**Comment by olivier-lacroix** [comment]
I think this issue should be reopened, as search is not using the new gateway (yet)

**Comment by olivier-lacroix** [comment]
@baszalmstra do you have any pointer for converting the search function? It was not obvious to me how to make the switch for this one

**Comment by baszalmstra** [comment]
@olivier-lacroix @nichmor is working on implementing the ability in the `Gateway` to query package names.

**Comment by olivier-lacroix** [comment]
Cool, I did think that may be needed there :-)

**Comment by baszalmstra** [comment]
Merged with https://github.com/prefix-dev/pixi/pull/1819
