### ISSUE TITLE
`pixi install --locked` does not abort as expected

### ISSUE THREAD

**Issue by mfisher87** [prefix-dev/pixi#1721]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
(myenv) (rc: 0) $ pixi install --locked
  × lock-file not up-to-date with the project

(myenv) (rc: 0) $ pixi install --locked
✔ The default environment has been installed.
(myenv) (rc: 0) $
```

```toml
[project]
name = "test"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
quarto = ">=1.4.550,<2,!=1.4.557"
```

I don't think the specific TOML matters here, just trying to comply with the form :) It just matters that the TOML changes in a way that breaks compatibility with a lock file, for example increasing the minimum version or excluding a version as I've done above, after locking.

### Issue description

The help text for `pixi install` shows the `--locked` option as a check that aborts early when a lock-file is found to not comply with the manifest. This doesn't require an environment solve, so could be used in CI or pre-commit hook to quickly identify when a contributor forgot to commit the lockfile. However, when the lock file is found to be out of date, the command _does not_ abort as described, and continues on to update the lockfile.

```
      --locked                                         Check if lockfile is up-to-date before installing the environment, aborts when lockfile isn't up-to-date with the manifest file [env:
                                                       PIXI_LOCKED=]
```

### Expected behavior

I expect the command to abort (personally, I intuited a non-zero return code would be returned) immediately after detecting 

## Thank you :tada: :heart: 

I'm a new `pixi` user, and as I've been telling my colleagues since yesterday, I think the design you're bringing to the conda userbase is revolutionary. I hope you don't mind an inline experience report. I didn't see an issue type for this. I work with researchers a lot, and I've dreamed of these things. Thank you! I am super impressed with these changes, as they resolve ways that I feel the traditional conda user experience would get in the way of the work researchers want to do:

* Automatically handles building a sensible manifest and lock file from `install` commands. This is _huge_ - for many, the importance of repeatability is understood, but the number of little things you need to remember to properly define a repeatable `environment.yml` is a lot. :bow:
* Treats projects as the top-level "thing" instead of environments. It's so easy for researchers to install Anaconda and then start `conda install`ing things into the base environment and get in to trouble later. Because projects are the entrypoint to using `pixi`, and there is no base environment, isolated environments are the default. Because environments are stored in a local directory, and activated based on current working directory, remembering environment names isn't a struggle and cleaning environments up can be done with regular OS-level tools. "I broke my conda install, can I re-install miniconda and keep my environments?" is a super common user experience in traditional conda. Yuck! :bow:

**Comment by ruben-arts** [comment]
Hi @mfisher87, thanks for the kind words and good to see we're working on the right things!

The issue you describe is indeed a bug, but I can't seem to reproduce it. For my it only aborts and does that repeatably.

Could you specify exactly a reproducible state between two pixi tomls
- One state that is installed and compatible with the lock file
- One state that would be the second step and is not compatible with the lockfile.

Note that a lockfile can be in sync when adding dependencies or changing the version as long as the version specification is compatible and the package is already in the lockfile.

**Comment by mfisher87** [comment]
I can't reproduce this anymore! :scream: 

I can tell you that the file pasted above is the "after" version, and the "before" version I tested yesterday had the `!=1.4.557` specification omitted. But given that I can't reproduce today, there must have been some other variable involved. I'll post back if I ever find another reproduction :)

Thanks so much for your time, and apologies for the incorrect report!
