### ISSUE TITLE
Allow environment variables definition on activation without setting them in pixi.toml

### ISSUE THREAD

**Issue by yonil7** [prefix-dev/pixi#1726]
### Problem description

1. `[activation.env]` section does not support some kind of composite env var syntax that will allow defining env variables such as: `PGDATA="${PIXI_PROJECT_ROOT}/my_pg_data_folder"`
2. `[activation.script]` section only allows running scripts files. (so I cant do: `export PGDATA="${PIXI_PROJECT_ROOT}/my_pg_data_folder` or `source my_env_vars_definition_script.sh` there)
This means there is no way to define "composite" env vars on pixi activation. (not in pixi.toml syntax and not by running something else on activation)

**Comment by ruben-arts** [comment]
That would indeed be nicer. Currently the activation env is thrown on the pile of env vars that pixi adds to the activation. 

What does work in this case is:
`pixi.toml`:
```toml
[activation]
scripts = ["activation.sh"]
```
`activation.sh`:
```bash
export PGDATA="$PIXI_PROJECT_ROOT/my_pg_data_folder"
```

```shell
# Make sure you escape the `$` on your shell
pixi run "echo \$PGDATA"
```
