### ISSUE TITLE
Test failure on x86 macos

### ISSUE THREAD

**Issue by pbsds** [prefix-dev/pixi#1738]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

`nix build github:nixos/nixpkgs/refs/pull/325720/head#pixi` on a x86 mac

### Issue description

It seems the test suite fails on x86 darwin, which is an issue for distribution in nixpkgs.

log excerpt from https://logs.ofborg.org/?key=nixos/nixpkgs.325720&attempt_id=11d80947-ab21-45f0-9d00-f31634683025 :

```
failures:
---- task::task_environment::tests::test_find_ambiguous_task stdout ----
thread 'task::task_environment::tests::test_find_ambiguous_task' panicked at src/task/task_environment.rs:337:9:
assertion failed: matches!(result, Err(FindTaskError::AmbiguousTask(_)))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- task::task_environment::tests::test_find_task_dual_defined stdout ----
thread 'task::task_environment::tests::test_find_task_dual_defined' panicked at src/task/task_environment.rs:246:9:
assertion failed: matches!(result, Err(FindTaskError::AmbiguousTask(_)))
---- task::task_environment::tests::test_find_task_explicit_defined stdout ----
thread 'task::task_environment::tests::test_find_task_explicit_defined' panicked at src/task/task_environment.rs:272:9:
assertion failed: matches!(result, Err(FindTaskError::AmbiguousTask(_)))
---- task::task_graph::test::test_custom_command stdout ----
thread 'task::task_graph::test::test_custom_command' panicked at src/task/task_graph.rs:368:10:
called `Result::unwrap()` on an `Err` value: UnsupportedPlatform(MismatchingVersion { required: "__osx", required_version: Version { version: [[0], [13], [0]], local: [] }, local_version: Version { version: [[0], [10], [16]], local: [] } })
---- task::task_graph::test::test_multi_env_defaults_ambigu stdout ----
note: test did not panic as expected
failures:
    task::task_environment::tests::test_find_ambiguous_task
    task::task_environment::tests::test_find_task_dual_defined
    task::task_environment::tests::test_find_task_explicit_defined
    task::task_graph::test::test_custom_command
    task::task_graph::test::test_multi_env_defaults_ambigu
test result: FAILED(B. 192 passed; 5 failed; 0 ignored; 0 measured; 2 filtered out; finished in 1.05s
```

discovered in: https://github.com/NixOS/nixpkgs/pull/325720
related: https://github.com/prefix-dev/pixi/pull/1045

### Expected behavior

success

**Comment by pbsds** [comment]
I don't have a mac myself, so i cannot help test this, CC @happysalada

**Comment by ruben-arts** [comment]
The error makes sense but we also test on all platforms so I would expect us to catch it before nix pkgs. Going to have a look.

**Comment by ruben-arts** [comment]
That said, it won't fix these specific issues. As you're apparently running on a macos 10 as build machine. :fearful:

**Comment by ruben-arts** [comment]
Question for the team, are we going to support MacOS 10.16 as a supported platform to run the tests on? 

This would require to test on it and add the system-requirements to the test manifests where that is important.
