### ISSUE TITLE
`pixi self-update` on v0.27.0 thinks it is updating from v0.1.0

### ISSUE THREAD

**Issue by matthewfeickert** [prefix-dev/pixi#1768]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

To show this is from a fresh `pixi` install I'll demonstrate from inside a Docker container

```shell
$ docker run --rm -ti debian:bookworm
root@09944251b956:/# apt update && apt install -y curl
root@09944251b956:/# curl -fsSL https://pixi.sh/install.sh | bash
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz
######################################################################## 100.0%
The 'pixi' binary is installed into '/root/.pixi/bin'
Updating '/root/.bashrc'
Please restart or source your shell.
root@09944251b956:/# . ~/.bashrc 
root@09944251b956:/# pixi --version
pixi 0.27.0
root@09944251b956:/# pixi self-update
Pixi will be updated from 0.1.0 to 0.27.0
Pixi archive downloaded.
Pixi archive uncompressed.
Pixi has been updated to version 0.27.0.
root@09944251b956:/# pixi self-update
Pixi will be updated from 0.1.0 to 0.27.0
Pixi archive downloaded.
Pixi archive uncompressed.
Pixi has been updated to version 0.27.0.
root@09944251b956:/#
```

### Issue description

For `pixi` release [`v0.27.0`](https://github.com/prefix-dev/pixi/releases/tag/v0.27.0) if the `self-update` command is run it will always think it is updating from `pixi` `v0.1.0` and not realize that it is already at `pixi` `v0.27.0`

```console
$ pixi --version
pixi 0.27.0
$ pixi self-update
Pixi will be updated from 0.1.0 to 0.27.0
Pixi archive downloaded.
Pixi archive uncompressed.
Pixi has been updated to version 0.27.0.
```

### Expected behavior

For `pixi` to detect that it is at the latest release and not attempt to update, also for `pixi` to know it is not `v0.1.0`, as was the previous behavior.

Example using [`v0.26.1`](https://github.com/prefix-dev/pixi/releases/tag/v0.26.1):

```console
$ pixi self-update --version 0.26.1  # roll back from v0.27.0 to v0.26.1
Pixi will be updated from 0.1.0 to 0.26.1
Pixi archive downloaded.
Pixi archive uncompressed.
Pixi has been updated to version 0.26.1.
$ pixi self-update --version 0.26.1
pixi is already up-to-date (version 0.26.1)
```

**Comment by ruben-arts** [comment]
Hey @matthewfeickert, thanks for the ping, we've already fixed this in main: https://github.com/prefix-dev/pixi/pull/1759

Closing this as fixed :smiley:

**Comment by matthewfeickert** [comment]
Ah great! Thanks for being super fast. I missed PR #1759 while checking as it "self-updated" didn't bring it up, but I see why now. :+1:
