### ISSUE TITLE
Unable to `pixi add --pypi` from codeartifacts

### ISSUE THREAD

**Issue by ericmjl** [prefix-dev/pixi#1783]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init
pixi add python
pixi add --pypi <company-proprietary package from AWS CodeArtifacts>
```

This gives the following output:

```bash
failed to resolve the pypi requirements of 'default' 'linux-64'
  failed to resolve pypi dependencies
  Because <package name> was not found in the package registry and you require <package name>, we can conclude that the requirements are unsatisfiable.
```

That said, when I try to `pixi run pip install <package name>`, no issues -- we pull from CodeArtifacts nonetheless.

### Issue description

As described above, I'm unable to use `pixi add` to add a dependency from a non-PyPI but nonetheless pip-accessible CodeArtifacts package repository. This can cause issues for reproducibility.

### Expected behavior

I would like to suggest that alternative pip indexes (such as CodeArtifacts) be part of the indexes that are searched when using `pixi add --pypi`, if that's not already enabled.

**Comment by olivier-lacroix** [comment]
@ericmjl what does your `pixi.toml` / `pyproject.tml` look like? You have to indicate the extra index url as indicated [here](https://pixi.sh/latest/reference/project_configuration/#the-pypi-options-table)?

You will also need to make sure [keyring is properly setup](https://pixi.sh/latest/advanced/authentication/#keyring-authentication) and use `--pypi-keyring-provider subprocess` argument to pixi commands (or add this to the local pixi config)

**Comment by ericmjl** [comment]
@olivier-lacroix thank you for responding!

I tried out the following after reading through the link you provided.

Firstly, I edited my `pixi.toml` to include the following:

```toml
[pypi-options]
index-url = "https://aws:<a signed url which changes on each log in>@<acct>.d.codeartifact.<region>.amazonaws.com/pypi/<repo name>/simple"
```

(Reminder to self: quotation marks needed!)

The URL came directly from `~/.config/pip/pip.conf`.

Then, I did the following at the terminal:

```bash
loginca # my shell alias for logging into codeartifacts
pixi add --pypi <internal package name>
```

`pixi` started to solve for a while, following which it succeeded:

```bash
❯ pixi add --pypi-keyring-provider subprocess --pypi <internal package name>
✔ Added <internal package name>
Added these as pypi-dependencies.
```

Here is the main issue I see with this approach: Because the long signed URL is always changing from login to login, it's non-ergonomic to always need to copy the URL over from `~/.config/pip/pip.conf`. Ideally, the file `~/.config/pip/pip.conf` remains the source of truth for `pip` index-urls for `pixi` as well as `pip`. Is there a way to reference `~/.config/pip/pip.conf` in `pixi.toml` or `pyproject.toml`, or even have `pixi` directly recognize `~/.config/pip/pip.conf` on a prioritized collection of configuration paths for `pip` installed-packages?

**Comment by olivier-lacroix** [comment]
@ericmjl I see. Not sure what your setup is, but ideally, you would use keyring rather than a signed URL. [this package](https://github.com/jmkeyes/keyrings.codeartifact) may help (or not) depending on your login flow.

Currently, I don't think there is a way for pixi to reference `pip.conf` in any way.

@tdejager , could the index url contain an env var maybe, which would be resolved before handing over to uv?

**Comment by ericmjl** [comment]
@olivier-lacroix thanks for responding again! I just tried to add `keyrings.codeartifact` via pixi, but found the following issue: 

```bash
❯ pixi add --pypi "keyrings.codeartifact"
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because keyrings-codeartifact was not found in the package registry and you require keyrings-codeartifact, we can conclude that the requirements are unsatisfiable.
```

It seems like `pixi` is automatically converting `.` in PyPI package names to be hyphen, which would lead to `keyrings.codeartifact` not being found. This does sound like a separate bug, if you'd like me to create a new issue for this one, I'm happy to do so!

**Comment by olivier-lacroix** [comment]
@ericmjl , keyring needs to be setup globally rather than as a dependency of your project. have a look [here](https://pixi.sh/latest/advanced/authentication/#keyring-authentication) You will need to adapt it a bit, but that should get you started :-)

**Comment by tdejager** [comment]
> Hello everyone. I'm also trying to make this setup work and it seems that at least I have not found a way to [login to AWS Codeartifact other than with `pip`](https://docs.aws.amazon.com/codeartifact/latest/ug/python-configure-pip.html)
> 
> AFAIK Keyring Authentication is not supported and pretty much what amazon does is a hack, which means, overriding the `index-url` setting in the `pip` config file: ` ~/.config/pip/pip.conf`
> 
> I tried to setup [keyrings.codeartifact](https://github.com/jmkeyes/keyrings.codeartifact) as @olivier-lacroix suggested without any success.
> 
> @ericmjl could you make it work? If so, could you share your approach? Thank you very much.
> 
> I believe that this is something ([AWS Codeartifact](https://docs.aws.amazon.com/codeartifact/latest/ug/using-python.html)) that we should take into account for this project and I'm more than happy to contribute in any way I can if someone could provide some hints on where I should start from.
> 
> Keep rocking here. `pixi` has a great future. 🎉 🚀

Hmmm, from what I'm reading https://github.com/jmkeyes/keyrings.codeartifact does look pretty promising. Note that the keyring setup can be especially finicky. It really depends on getting everything right and there is little feedback current, partially how uv integrates this but we could also check some common caveats I think.

You could try running with a higher verbosity level e.g `-vv` or `-vvv` there should be some more keyring info in the logs. 

Reading from the docs, it mentions:

> https://aws:$CODEARTIFACT_AUTH_TOKEN@my_domain-111122223333.d.codeartifact.region.amazonaws.com/pypi/my_repo/simple/

Does setting that with the correct `$CODEARTIFACT_AUTH_TOKEN`, whatever that is(?), work if you set it as in `index-url` in the `[pypi-options]`? Then the environment variable replacement would be an option still.

**Comment by android10** [comment]
@tdejager thanks for such great insights! I will give it another try, see what I can come up with and share the results. I'm more than happy to help. ❤️ 

I'm actually writing an internal RFC in my company to migrate to `pixi` and that is the reason behind this discussion :). 

I will also migrate some of my personal projects and hopefully find some time to dive into the `pixi` codebase to understand and contribute. 💪🏻

**Comment by ericmjl** [comment]
Hey guys, looping back with a bit of documentation on what I've done to date to try to make this happen.

To start, I have keyring available globally:

```bash
❯ which keyring
/home/ema/.pixi/bin/keyring
```

I then installed `keyrings.codeartifacts` in my project environment, as evidenced by my `pyproject.toml` configuration:

```bash
❯ cat pyproject.toml 
[project]
authors = [{name = "Eric Ma", email = "<...email redacted...>"}]
dependencies = ["keyrings-codeartifact>=1.3.3,<2", "pip>=24.2,<25", "seaborn>=0.13.2,<0.14"]
description = "Add a short description here"
name = "pixi-test-repo"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pixi-test-repo = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.pypi-options]
extra-index-urls = ["https://<...domain redacted...>-<...account redacted...>.d.codeartifact.us-east-1.amazonaws.com/pypi/<...repo name redacted...>/simple/"]
```

Won't bore everyone with the `pixi.lock` file :smile:.

Next, I configured my `pip.conf` file, just to be doubly-sure:

```bash
❯ cat ~/.config/pip/pip.conf
[global]
extra-index-url = https://<...domain redacted...>-<...account redacted...>.d.codeartifact.us-east-1.amazonaws.com/pypi/<...repo name redacted...>/simple/
```

I also double-checked my keyring configuration:

```bash
❯ keyring diagnose
config path: ~/.config/python_keyring/keyringrc.cfg
data root: ~/.local/share/python_keyring

❯ cat ~/.config/python_keyring/keyringrc.cfg
[codeartifact]
profile_name = default
token_duration = 1800
aws_access_key_id=<...redacted...>
aws_secret_access_key=<...redacted...>
```

I then tried to install a custom package that only exists on our internal CA repo:

```bash
❯ pixi add --pypi --pypi-keyring-provider subprocess my-own-package
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because my-own-package was not found in the package registry and you require my-own-package, we can conclude that the requirements are unsatisfiable.
```

I think I've run out of ideas here. Part of it is my mental model of AWS authentication and the likes -- it's complex! But I'm also not sure how tools are being called behind-the-scenes. Am I missing anything here? Is the configuration mis-specified? I'd love to get some feedback if possible please!

**Comment by olivier-lacroix** [comment]
@ericmjl you should install both keyring and keyrings.codeartifacts via pipx & pipx inject, as documented [here](https://pixi.sh/latest/advanced/authentication/#keyring-authentication)

**Comment by tdejager** [comment]
@olivier-lacroix thanks, and indeed @ericmjl :) If there would be a conda package for it similar to: https://github.com/jslorrma/keyrings.artifacts (Azure). Then we could actually global install that I think. I think it might also be time to add some diagnostic options to pixi, so that you can test something along the lines of `pixi diagnose pypi-aut` or something that tells you something about the setup.

**Comment by ericmjl** [comment]
Ok, I had another small chunk of time to try this out:

```bash
# This shows that I'm using a pipx-installed keyring
(base) USERNAME@HOSTNAME:~/projects/pixi-test-repo$ which keyring
/home/USERNAME/.local/pipx/venvs/keyring/bin/keyring

# This shows that keyrings.codeartifact is injected correctly
(base) USERNAME@HOSTNAME:~/projects/pixi-test-repo$ pipx inject keyring keyrings.codeartifact
⚠️ keyrings-codeartifact already seems to be injected in 'keyring'. Not modifying existing installation in '/home/USERNAME/.local/pipx/venvs/keyring'. Pass '--force' to force installation.

# This still does not work:
(base) USERNAME@HOSTNAME:~/projects/pixi-test-repo$ pixi add --pypi --pypi-keyring-provider subprocess CUSTOM_PAKAGENAME
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because CUSTOM_PAKAGENAME was not found in the package registry and you require CUSTOM_PAKAGENAME, we can conclude that the requirements are unsatisfiable.
```

@olivier-lacroix I'm a bit lost here, is there something else that I might be missing?

**Comment by tdejager** [comment]
1. Does the `pixi.toml` still have the correct extra-index-url? Note that this **requires** a `username@` in the URL.
2. Did you add the `[codeartifact]` sections to the potential new `keyring.cfg` location, you can see this with `keyring diagnose`. 
3. Also does `keyring get <url> <username>` do anything?
4. If you run a `pixi add --pypi --pypi-keyring-provider subprocess CUSTOM_PAKAGENAME -vvv` do you see anything regarding keyring authentication being found?
5. Can you try adding the package to the `pypi-dependencies` array manually. And running a `pixi install -vvv`?

**Comment by ericmjl** [comment]
@tdejager woohoo! It turns out I mis-spelled my AWS domain, and that was the root cause of the issue! At the same time, your point 1 was super helpful as well, as I didn't specify the correct username (we don't use usernames at work, instead we use IAM roles, so I was suuuuuper confused at first, but later my colleagues helped clear that up for me).

I am going to be putting together notes on how to make this work in a reproducible fashion, as well as gotchas to be aware of. (One of them is that we now need to have `--pypi-keyring-provider subprocess` with every `pixi add` call, and that feels like it should be in the configuration rather than in the shell command.) But I'll loop back with notes shortly!

**Comment by tdejager** [comment]
Great @ericmjl!! Note that you can set it in the global config.toml, this is explained in the pixi.sh docs under global configuration. That removes the need to use it in each call. However, I would like it in the manifest actually because we can then do some extra checks 😀

**Comment by tdejager** [comment]
Let's close this and re-open when encountering issues.

**Comment by ericmjl** [comment]
Following up with my notes (no need to re-open!): https://ericmjl.github.io/blog/2024/9/19/how-to-set-up-pixi-with-codeartifacts/
