### ISSUE TITLE
Blas implementation switch syntax unrecognised

### ISSUE THREAD

**Issue by lucascolley** [prefix-dev/pixi#1785]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi shell
```

with `libblas = "*=*openblas"` as a dependency in `pixi.toml`.

### Issue description

Following the syntax specified at https://conda-forge.org/docs/maintainer/knowledge_base/#switching-blas-implementation, pixi reports `WARN Parsed '*=*openblas' as '* *openblas', in a future version this will become an error.`.

### Expected behavior

Recognise the syntax such that the user can "change the BLAS implementation without changing the conda packages depending on BLAS" as per the conda-forge docs.

x-ref https://github.com/rgommers/pixi-dev-scipystack/issues/3

**Comment by baszalmstra** [comment]
We can definitely improve the error message!

We only accept a version when you use a string. This should work:


```
libblas = { build = "*openblas" }
```

**Comment by baszalmstra** [comment]
I made an attempt at improving the error message: https://github.com/prefix-dev/pixi/pull/1786

**Comment by baszalmstra** [comment]
Closing this now that #1786 has been merged.

**Comment by lucascolley** [comment]
thanks!!
