### ISSUE TITLE
`pixi add '<package>=*'` no longer works

### ISSUE THREAD

**Issue by matrss** [prefix-dev/pixi#1792]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ cat pixi.toml
[project]
authors = ["Matthias Riße <m.risse@fz-juelich.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "clams-git"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
$ pixi add 'python=*'
  × invalid version constraint: '*' is incompatible with '=' operator'
  ╰─▶ '*' is incompatible with '=' operator'

[ble: exit 1]
```

### Issue description

I want to add a dependency without any specific version. I always want it to get the latest version as of creating the lock file. In the past I've used `pixi add '<package>=*'` for this purpose, but that no longer works. Manually adding `<package> = "*"` to the dependencies section in pixi.toml does work though, so I am not sure why `pixi add` refuses to do it.

### Expected behavior

I expected `*` to continue to be a valid version for `pixi add`, or alternatively some other way to specify "always the latest version".

**Comment by matrss** [comment]
As an alternative or complementary feature, it would be nice to be able to specify `[package]>=[latest-version]` as the dependency to add, without having to figure out the latest version beforehand.

This is similar to what `pixi add` does already, but without the upper bound on the next major version. In many cases a major version upgrade won't lead to any issues, and if it does I expect the review process in place for updating the lock file to catch those (e.g. through automated testing). The situations where one would want the upper bound are the exception, not the norm, IMO, and those would be determined by the issues found in the lock file update process.

**Comment by baszalmstra** [comment]
I add #1852 to allow for old style parsing on the command line!
