### ISSUE TITLE
pixi panics on parsing a git+ssh url in pyproject.toml dependencies

### ISSUE THREAD

**Issue by brettc** [prefix-dev/pixi#1797]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

[Install pdm](https://pdm-project.org/en/latest/#installation)

```shell
mkdir pixi-bug
cd pixi-bug

# initialize pyproject.toml. Use defaults, creating a venv.
pdm init

# Now add an ssh dependency (any will do). 
# This will successfully install the package into the venv
pdm add "attrs @ git+ssh://git@github.com/python-attrs/attrs.git@main"

# Now convert to pixi (adding sections)
pixi int

# This panics
pixi install
```

The error produced is 
```
thread 'main' panicked at crates/pixi_manifest/src/target.rs:226:14:
could not convert pep508 requirement: ParseGitRev(InvalidCharacters("github.com/python-attrs/attrs.git@main"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

pixi fails to parse pyproject.toml dependencies when they are git+ssh.

see [discord thread](https://discord.com/channels/1082332781146800168/1272007654201491457/1272007654201491457)

### Expected behavior

It should work.

**Comment by ruben-arts** [comment]
I found the underlying issue. We're splitting the url on `@` to split the url from the version. 

But this fails with `ssh://git@` urls. We'll have to find a smarter way to parse this. 
Here is the related function: https://github.com/prefix-dev/pixi/blob/c963a41615179abd3e5853b492fc26bf544a3fa4/crates/pixi_manifest/src/pypi/pypi_requirement.rs#L193

**Comment by pperanich** [comment]
This also fails when you specify a particular rev in the url as well. E.g.

```
"some-package @ git+https://github.com/user-abc/some-package.git@someBranchOrHash",
```

**Comment by niemiaszek** [comment]
> This also fails when you specify a particular rev in the url as well. E.g.
> 
> ```
> "some-package @ git+https://github.com/user-abc/some-package.git@someBranchOrHash",
> ```

Maybe somehow related to #1206
Using branches is not supported at all as far as I know. There is draft PR for branches #1245
