### ISSUE TITLE
Make pixi envs relocatable

### ISSUE THREAD

**Issue by savente93** [prefix-dev/pixi#180]
This may or may not already be the case, but I know that conda environments are in general not relocatable, i.e. if you package them up, and move them for example to another machine/environment it is not guaranteed to work. This causes significant headaches when trying to cache and reuse environments in CIs/distributing examples etc. It would be really nice if pixi environments could be in some way packaged and relocated. This is more of a means to an end, so if another way of solving these problems arise I'm also happy with that, but the ultimate goal for me is to be able to have a CI workflow start from a cached environment to speed them up.

**Comment by savente93** [comment]
This only occurred to me after the fact, but making them cross platform relocatable is not necessarily a requirement for me here.

**Comment by ruben-arts** [comment]
He @savente93, do you mean that you can output an environment as cache in the CI? 

There is a tool called [`conda-pack`](https://github.com/conda/conda-pack) which does what you want. But our solution for the relocating is using a lockfile that describes the environments precisely. The only thing you need to take care of is that your CI runner cache (`~/.cache/rattler/cache`) is being shared between runners. This can speedup the installation. With pixi the solve is usually so quick that its not a problem to rerun it in CI.

Is it possible for you to share an example project where you would like this feature for?

**Comment by savente93** [comment]
I'm about to head into a string of meetings, and I want to write up a proper answer for you. I'll get back to this asap.

**Comment by savente93** [comment]
Sorry it took me this long to get back to you. 

I'm just trying to reconstruct what I was thinking at the time (again, sorry for not coming back sooner) I looked at the conda pack link you shared and I think this is more or less exactly what I had in mind. so if `pixi` already can do those things then I think we can close this issue.

**Comment by tokoko** [comment]
@ruben-arts sorry for digging up an old issue, do you know of anyone having successfully used `conda-pack` with pixi envs? I tried running it but failed pretty early on, something about json files in `conda-meta` folder always having `link` key set to null. I was trying to use pixi instead of conda for pyspark [environment management](https://spark.apache.org/docs/latest/api/python/user_guide/python_packaging.html#using-conda). pyspark doesn't really make it easy to rerun from a lockfile (at least when you're running in hadoop yarn and not using containers).

**Comment by wolfv** [comment]
Hey @tokoko awesome. Feel free to open a new issue with your findings. Maybe we can fix it easily :)

**Comment by tokoko** [comment]
@wolfv sure, I'll cook up an example and open an issue then, thanks
