### ISSUE TITLE
pixi shell does not use project Python

### ISSUE THREAD

**Issue by fonnesbeck** [prefix-dev/pixi#1816]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init test
cd test
pixi add python
pixi shell
which python
```

### Issue description

Creating a new project and adding python does not make the installed python available to the pixi shell. The result of `which python` above returns `/usr/bin/python`.

### Expected behavior

Should have returned the installed Python in `.pixi/`

**Comment by truatpasteurdotfr** [comment]
works for me:
```
tru@bisadms-MacBook-Air pixi.d % pixi --version; pixi init test && cd test && pixi add python && pixi shell
pixi 0.27.1
✔ Created /Users/tru/pixi.d/test/pixi.toml
✔ Added python >=3.12.5,<4
 . "/var/folders/cc/kzhhjdv119d6yzkz2qjfg15r0000gp/T/pixi_env_evv.sh"
tru@bisadms-MacBook-Air test %  . "/var/folders/cc/kzhhjdv119d6yzkz2qjfg15r0000gp/T/pixi_env_evv.sh"
(test) tru@bisadms-MacBook-Air test % command -v python python3
/Users/tru/pixi.d/test/.pixi/envs/default/bin/python
/Users/tru/pixi.d/test/.pixi/envs/default/bin/python3
(test) tru@bisadms-MacBook-Air test % exit
tru@bisadms-MacBook-Air test % command -v python python3
/opt/homebrew/bin/python3
tru@bisadms-MacBook-Air test %
tru@bisadms-MacBook-Air test % pixi run which python
/Users/tru/pixi.d/test/.pixi/envs/default/bin/python
tru@bisadms-MacBook-Air test % which python
python not found
```

**Comment by ruben-arts** [comment]
I cannot reproduce this issue. 

What you could try is `eval "$(pixi shell-hook)"` instead of `pixi shell`.

If that works it could be that you have some function that forces the python from your system into your shell. 

You could test this by checking if the `bin` dir or your environment is the first in the list of the `PATH` variable. e.g.:
```
> pixi shell
(test) > echo $PATH
/home/user/test/.pixi/envs/default/bin:/...
```

**Comment by fonnesbeck** [comment]
@ruben-arts yeah, that works. Should I be aliasing that command to something convenient?

**Comment by ruben-arts** [comment]
@fonnesbeck the best would be to remove the command in your rc file that adds the bin path.

If you could share that file I could take a look.

**Comment by fonnesbeck** [comment]
There actually is not much in my bashrc:

```
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

### bling.sh source start
test -f /usr/share/ublue-os/bluefin-cli/bling.sh && source /usr/share/ublue-os/bluefin-cli/bling.sh
### bling.sh source end
export PATH=/var/home/fonnesbeck/.pixi/bin:$PATH
eval "$(pixi completion --shell bash)"
```

**Comment by ruben-arts** [comment]
This is really strange :octopus: 

Could you show the `echo $PATH` you get in `pixi shell`. And what does it do if you do a `pixi run "echo \$PATH"`.

**Comment by fonnesbeck** [comment]
```
>  echo $PATH
/var/home/fonnesbeck/.pixi/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/var/home/fonnesbeck/.pixi/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/var/home/fonnesbeck/.pixi/bin:/var/home/fonnesbeck/miniforge3/bin:/var/home/fonnesbeck/miniforge3/condabin:/var/home/fonnesbeck/.local/bin:/var/home/fonnesbeck/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

```
>  pixi run "echo \$PATH"
/var/home/fonnesbeck/test/.pixi/envs/default/bin:/var/home/fonnesbeck/.pixi/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/var/home/fonnesbeck/.pixi/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/var/home/fonnesbeck/.pixi/bin:/var/home/fonnesbeck/miniforge3/bin:/var/home/fonnesbeck/miniforge3/condabin:/var/home/fonnesbeck/.local/bin:/var/home/fonnesbeck/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

so it does prepend the project bin directory.

**Comment by ruben-arts** [comment]
Does it spawn the source of the tmp file for you when you run `pixi shell`?
```
❯ pixi shell
 . "/tmp/pixi_env_shb.sh"
```

If yes, could you share the contents with us. (You can only access it when the shell is active)

**Comment by fonnesbeck** [comment]
```
> more /tmp/pixi_env_NCg.sh
export CONDA_DEFAULT_ENV="test"
export PIXI_ENVIRONMENT_NAME="default"
export PATH="/var/home/fonnesbeck/test/.pixi/envs/default/bin:/var/home/fonnesbeck/.pixi/bin:/home/linuxbrew/.linuxbrew/b
in:/home/linuxbrew/.linuxbrew/sbin:/var/home/fonnesbeck/.pixi/bin:/var/home/fonnesbeck/miniforge3/bin:/var/home/fonnesbec
k/miniforge3/condabin:/var/home/fonnesbeck/.local/bin:/var/home/fonnesbeck/bin:/usr/lib64/ccache:/usr/local/bin:/usr/loca
l/sbin:/usr/bin:/usr/sbin"
export PIXI_IN_SHELL="1"
export PIXI_EXE="/var/home/linuxbrew/.linuxbrew/Cellar/pixi/0.27.1/bin/pixi"
export PIXI_ENVIRONMENT_PLATFORMS="linux-64"
export PIXI_PROJECT_MANIFEST="/var/home/fonnesbeck/test/pixi.toml"
export PIXI_PROJECT_NAME="test"
export PIXI_PROJECT_VERSION="0.1.0"
export CONDA_PREFIX="/var/home/fonnesbeck/test/.pixi/envs/default"
export PIXI_PROJECT_ROOT="/var/home/fonnesbeck/test"
export PIXI_PROMPT="(test) "
export PS1="(test) $PS1"
pixi() {
    local first_arg="$1"
    local cmd="$PIXI_EXE $*"

    eval "$cmd"

    case "$first_arg" in
        add|remove|install)
            eval "$($PIXI_EXE shell-hook)"
            hash -r
            ;;
    esac
}
```

**Comment by ruben-arts** [comment]
That all looks perfect. I'm at the point where I have to ask if you tried to restart your machine :sweat_smile:

**Comment by fonnesbeck** [comment]
Unfortunately, I restart my computer several times a week (since I'm on an immutable Linux distro, that's how it does its updates). Here's a visual of what happens for a simple test case:

![image](https://github.com/user-attachments/assets/38700f8c-25d5-4e4d-aa2e-0c0a117430ec)

Not sure if that splash screen that pops up when I call `pixi shell` is part of the cause -- it pops up any time I open a new terminal.

**Comment by baszalmstra** [comment]
You are using `zsh` I think, can you paste the contents of the `.zshrc`? I assume the `bluefin` thing is part of your zsh initialization script somehow.

**Comment by baszalmstra** [comment]
Clearly your shell is initializing something because the bluefin part is not part of pixi. Can you figure out what is causes that? I assume there you will also find the cause of the initialization of miniforge.

**Comment by fonnesbeck** [comment]
Maybe so. Bluefin is the Linux distro I'm using: https://projectbluefin.io/

**Comment by fonnesbeck** [comment]
Yup, it was the motd banner (somehow!). After disabling it:

```bash
> which python
~/test/.pixi/envs/default/bin/python
```

Closing this, thanks for your help and sorry for the trouble.
