### ISSUE TITLE
Please add pixi to the scoop.sh registry

### ISSUE THREAD

**Issue by W1M0R** [prefix-dev/pixi#1838]
### Problem description

[Scoop](https://scoop.sh/#/) is a command line installer for Windows.

Please consider adding `pixi` to the [Scoop registry](https://github.com/ScoopInstaller/Main).

A few attempts have been made by the community, but this requires installing those Scoop "buckets".

1. https://github.com/okibcn/ScoopMaster/blob/master/bucket/pixi.json
2. https://github.com/anderlli0053/DEV-tools/blob/master/bucket/pixi.json

It would be nice to have pixi in the [main](https://github.com/ScoopInstaller/Main) Scoop bucket.

Here is a basic Scoop Application manifest that seems to work for me:

```json
{
  "homepage": "https://prefix.dev/",
  "description": "Package management made easy",
  "version": "0.27.1",
  "license": "BSD-3-Clause",
  "architecture": {
    "64bit": {
      "url": "https://github.com/prefix-dev/pixi/releases/download/v0.27.1/pixi-x86_64-pc-windows-msvc.zip",
      "hash": "459d559f0424aab1bdb44122bed8df2d4365c297d6ec8da4af5d980929282575"
    }
  },
  "bin": [ "pixi.exe" ],
  "env_set": {
    "PIXI_HOME": "$dir"
  },
  "checkver": {
    "github": "https://github.com/prefix-dev/pixi"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/prefix-dev/pixi/releases/download/v$version/pixi-x86_64-pc-windows-msvc.zip"
      }
    }
  }
}
```

**Comment by ruben-arts** [comment]
Feel free to create a PR!

**Comment by W1M0R** [comment]
@ruben-arts Thanks. Will keep this around as a reference implementation.

**Comment by aliesbelik** [comment]
ScoopInstaller/Main#5773
