### ISSUE TITLE
Crash with `tree -i`

### ISSUE THREAD

**Issue by jonashaag** [prefix-dev/pixi#1839]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi tree -i python
```

### Issue description

If you have very large reverse dependencies, pixi does a bad job at rendering it.

### Expected behavior

Could be improved :)

**Comment by ruben-arts** [comment]
Hi @jonashaag, do you have an example and an idea on how to improve?

**Comment by jonashaag** [comment]
Turns out this isn't a visualization problem but a infinite loop!

```
[project]
channels = ["conda-forge"]
name = "tmp"
platforms = ["osx-arm64"]

[dependencies]
fastapi = "*"
```
