### ISSUE TITLE
Sharing environment between multiple users

### ISSUE THREAD

**Issue by amirhosseindavoody** [prefix-dev/pixi#1875]
### Problem description

Use case scenario: I use pixi to setup my python environment for running a script. For each new release, the code along with the pixi related files are published to a central location on a shared linux disk where multiple users can activate the environment and run the script. 

The issue is that since the `.pixi` folder is shared between all users this can cause permission issues. Even in cases that the environment is already installed and the user does not need to download any new packages.

I don't have an idea of how this can be fixed, one proposal would be to use a custom location for each user but that may require a fundamental change in the pixi architecture.

**Comment by davised** [comment]
I don't know if you've tried using the `pixi shell-hook` to get around this issue. I generally do this:

```
mkdir project
cd project
pixi init .
pixi add ...
pixi shell-hook > activate.sh
```

Then you can source ./activate.sh regardless of file/dir ownership.

You do have to exit your shell to get out of the settings. But for example, if you need to run a specific program:

```
mkdir bin
cd bin
echo '#!/usr/bin/env bash' > program
echo 'source /full/path/to/project/activate.sh' >> program
echo 'program "$@"' >> program
chmod +x program
```

Then you can run that program as if you're in the environment, regardless of which user you are.

Good luck.

**Comment by amirhosseindavoody** [comment]
This is actually a pretty good idea. I will keep using this and reopen the issue if I see any problemn.
