### ISSUE TITLE
Make 4.18 the default `linux` system-requirement

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1884]
centos 8 is using 4.18 by default. I would prefer to have this as the default lower bound as there are still a lot of systems that are based on centos 8 where we need to manually change this for every project.
(also i don't think there are many packages that require a higher linux kernel version)

xref https://discord.com/channels/1082332781146800168/1272823440461529140/1272841941515636767

**Comment by traversaro** [comment]
Today I tried a bunch of pixi projects of the lab on my institute HPC system, and indeed it was quite cumbersome to deal with this. This may be mitigated by https://github.com/prefix-dev/pixi/issues/815 or https://github.com/prefix-dev/pixi/issues/346, but if there is no advantage in having such a recent linux version (I may be simply ignorant, but I am not aware of any conda-forge package constraining `linux` version, to be honest :) ) it would be convenient to just change the default.

**Comment by baszalmstra** [comment]
I also see no reason not to lower this. The default version came from conda-lock. 

Would you be ok with that @ruben-arts ?

**Comment by ruben-arts** [comment]
The only reason I could see is that if people run `pixi update` on a project that would silently depend on it (apparently not on conda-forge) They might get older versions than they had before. 

But I would agree with you that the benefits outweigh the problems it causes. I'll update it.
