### ISSUE TITLE
Error when executing `pixi shell` ("The current system has a mismatching virtual package...")

### ISSUE THREAD

**Issue by apcamargo** [prefix-dev/pixi#1905]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ pixi --version
```
	pixi 0.28.0

```shell
$ pixi init test-project
$ cd test-project
$ pixi shell
```
	  × The current system has a mismatching virtual package. The project requires '__glibc' to be at
	  │ least version '2.28' but the system has version '2.26'

### Issue description

I face the error mentioned above every time I create a new project and try to execute `pixi shell` within it. To solve this, I need to add the following to my `pixi.toml` file (based on the solution provided [here](https://github.com/prefix-dev/pixi/issues/346)):

```toml
[system-requirements]
libc = { family="glibc", version="2.26" }
```

My setup is straightforward, with my `$HOME/.config/pixi/config.toml` only containing the following:

```toml
default-channels = ["conda-forge", "bioconda"]
```

I am running Amazon Linux release 2 (Karoo).

### Expected behavior

`pixi shell` should start a new shell in the project's environment.

**Comment by ruben-arts** [comment]
We have a solution in mind that is high on the list of things we need to solve. I acknowledge that this is not a comfortable way to use pixi. The solution is explained here: https://github.com/prefix-dev/pixi/issues/346#issuecomment-2094906047.

Closing this as a duplicate. Thanks for writing down your current work around for future issue searchers.
