### ISSUE TITLE
Additional interesting information

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#193]
From #40:

Ideas for additional info elements:

- global
  - authentication store location (if fallback used)
  - global cache size?
  - last time repodata downloaded?
  - proxy settings (`HTTP_PROXY` / `HTTPS_PROXY`)
  - `netrc` files (if they are used by `reqwest`)
- project
  - number of packages installed
  - disk space used / size of .pixi folder
  - last time updated / locked
  - platforms that were locked

**Comment by Wackyator** [comment]
I would like to work on this issue.

**Comment by wolfv** [comment]
Awesome! Let us know if you have questions :)

**Comment by Wackyator** [comment]
Could you please tell me more about these proxy settings, netrc files and platform that were locked. Where can I look for these?
