### ISSUE TITLE
Docs: updating and improving the Docker Python example

### ISSUE THREAD

**Issue by jennydaman** [prefix-dev/pixi#1938]
### Problem description

Today I've stumbled across the example https://github.com/prefix-dev/pixi/tree/220de8bb22c5113f86d1979cd82daf8330078c65/examples/docker

The example was helpful though there are some things which I think scan be improved about it.

- update base image from `ghcr.io/prefix-dev/pixi:0.18.0` to `ghcr.io/prefix-dev/pixi:0.28.2`
- It seems like `pixi run postinstall-production` _must_ come after `pixi shell-hook -e prod > /shell-hook` here...

https://github.com/prefix-dev/pixi/blob/220de8bb22c5113f86d1979cd82daf8330078c65/examples/docker/Dockerfile#L6-L7

... because `pixi shell-hook ...` will synchronize the project, uninstalling the wheel and reinstalling `docker-project` in editable mode.

- The example uses the flit build system, however by [default `pixi init` produces a configuration for using hatch](https://pixi.sh/latest/tutorials/python/). Should the `build-wheel` task be replaced with `hatch build`?
- We can cache packages if we do an explicit `pixi install` step:

```dockerfile
RUN --mount=type=cache,target=/root/.cache/rattler/cache,sharing=private pixi install
```

- The current solution, hard-codes the command to run in a file called  `/shell-hook`

https://github.com/prefix-dev/pixi/blob/220de8bb22c5113f86d1979cd82daf8330078c65/examples/docker/Dockerfile#L8C1-L17

It is not convenient for a downstream user to change the command run, e.g. `docker run pixi-docker python --help` would give "command not found."

A common practice is for images to have an "entrypoint.sh" script where the last line is `exec "$@"`. I recommend this approach because it is more versatile.

```dockerfile
RUN printf '#!/bin/sh\n%s\nexec "$@"' "$(pixi shell-hook -e prod)" > /entrypoint.sh
RUN chmod +x /entrypoint.sh
# -- snip --
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["gunicorn", "-w", "4", "docker_project:app", "--bind", ":8000"]
```

Now, downstream users can specify whatever command they want, and the pixi environment will be sourced correctly by `/entrypoint.sh`

LMK if you want a PR for any or all of these points.

**Comment by baszalmstra** [comment]
Thanks for the feedback! A PR would be much appreciated!

**Comment by tdejager** [comment]
I also think we should not use the conda `build` as it seems kind of gone from conda-forge: https://prefix.dev/channels/conda-forge/packages/build?
