### ISSUE TITLE
Regression from 0.25.0 -> 0.28.2

### ISSUE THREAD

**Issue by pablovela5620** [prefix-dev/pixi#1950]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

pixi toml file is here https://github.com/nerfstudio-project/nerfstudio/blob/d395aa2e537244b6f54fab2082b01b0edb589e62/pixi.toml

project is here https://github.com/nerfstudio-project/nerfstudio

fails when doing `pixi install`

### Issue description

pixi install fails when using 0.28.2, I had originally merged this in with 0.25.0 and it works fine there

error I get with 0.28.2
```
pixi install
  ⠠ default:linux-64     [00:00:01] resolving tomli==2.0.1                                                                                                                                                          × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ├─▶ Failed to download and build `fire==0.6.0`
  ├─▶ Failed to install requirements from build-system.requires (install)
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: setuptools==69.5.1
  ├─▶ Failed to extract archive
  ╰─▶ Invalid gzip header
  ```

### Expected behavior

Should resolve and install deps as it does in version 0.25.0

**Comment by tdejager** [comment]
I believe we should be able to work around this with build isolation options merged into main.

**Comment by tdejager** [comment]
I think there have been changes in UV where it is triggering our depends override even for isolated installs. However, we cannot work around that with the current uv API other than non isolated builds.

**Comment by pablovela5620** [comment]
I'm not totally sure what you mean by isolated builds, is this whats meant by it?
https://pixi.sh/latest/features/advanced_tasks/#clean-environment

**Comment by tdejager** [comment]
No, it's not that :), again its only available in main: https://pixi.sh/dev/reference/project_configuration/#no-build-isolation so in the nerfstudio example you could add `fire` and other packages for which this error pops up to that list.

Also, I'm closing this issue in favor of this one: https://github.com/prefix-dev/pixi/issues/1686 which is the same problem with nerf-studio. I will check someone with a linux box to verify if we can get this fixed with the `no-build-isolation` I've mentioned above.
