### ISSUE TITLE
`conda-pypi-map = { }` doesn't work in offline

### ISSUE THREAD

**Issue by toiletsandpaper** [prefix-dev/pixi#1962]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I can't reopen https://github.com/prefix-dev/pixi/issues/1764#issuecomment-2312541733 so I've created a new issue

You can see the full story there

### Issue description

When I set `conda-pypi-map = {}` on a machine with configured Sonatype Nexus mirror - I can only download conda packages (from the same mirror), but `--pypi` flag outputs error pinned as file here: https://github.com/prefix-dev/pixi/issues/1764#issuecomment-2291460927

### Expected behavior

I've expected that pixi will download packages from pypi index (from mirror) directly, without trying to fetch prefix.dev

**Comment by nichmor** [comment]
hey @toiletsandpaper ! let me look into this

**Comment by toiletsandpaper** [comment]
Thank you! I'll wait for a next release and let you know if this fixes my issue or not.
