### ISSUE TITLE
Regression with pixi 0.28.x

### ISSUE THREAD

**Issue by rjanvier** [prefix-dev/pixi#1967]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

On arm based macOS:

```shell
git clone --recursive https://github.com/cloudcompare/CloudCompare.git
cd CloudCompare
pixi install # pixi 0.28.2, get stuck in pyqt resolution
pixi self-update --version 0.26.1 # (works also with 0.27)
pixi install # works fine
```

### Issue description

Hi pixi team.
I have this [pixi](https://github.com/CloudCompare/CloudCompare/blob/master/pixi.toml) file that works with 0.26.x. But it does not with newer version of pixi and get stuck when trying to resolve pyqt (Please note that _in fine_, I would like to have in this `pixi` env the `pyqt` from conda for ABI compatibility with the QT app, not the `PyQT5` package from PyPI). I do not now if it's related with any current issue in the tracker but it reminds me the issue I have reported in this [question](https://github.com/prefix-dev/pixi/discussions/1343#discussioncomment-9342461). 

### Expected behavior

`pyqt` from conda repo is resolved.

**Comment by tdejager** [comment]
@nichmor just glance quickly but the question was pertaining to the mapping.

**Comment by nichmor** [comment]
Yes, looking into this rn

**Comment by nichmor** [comment]
hey @rjanvier ! Thanks for reporting this.

A small overview of this issue - 
right now pyqt packages from conda for osx-arm64 does not contain .dist-info or .egg-info folders which our mapping need to check if it's a pypi one - this means that we mare them as not-pypi and proceed installing pyqt5 from pypi.

A small overview for fix(es):
* we will report if for pyqt feedstock so it will fixed upstream.
* we will yank some of the mapping for pyqt osx-arm64 so it will fallback to the compressed mapping ( in this case, you will not need to update pixi ).

I will let you know about the progress for this work.

**Comment by nichmor** [comment]
> Thanks again @nichmor. So, if I understand correctly, the issue remains the same as it was in the [original question](https://github.com/prefix-dev/pixi/discussions/1343#discussioncomment-9342461). it's "miracle" it worked with 0.26 and 0.27.

yes! the issue remain the same.

we just accidentally bypass it : inconsistency was from our side, which led to a "miracle" working in terms that we ignored the fact that some names are empty and fallback for compressed mapping -> this is why it worked.

So current not-working solving problem is the right way of things, which we are working to fix

**Comment by nichmor** [comment]
hello @rjanvier !

I'm happy to report that this issue was fixed. 
The only thing that you need to do, is to run `pixi clean cache --mapping`. 
This will clean yanked hashes and the project will be installed.

Let me know if it helps you 🚀

**Comment by rjanvier** [comment]
Hi @nichmor, my use case seems to work perfectly now. Thank you!
