### ISSUE TITLE
Invalid peer certificate with `--tls-no-verify`

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#1982]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/a15ffde4-5639-474b-8cd8-42416a7ab913">

### Issue description

I installed a pypi package published on nexus using the latest pixi on the company's intranet server, but encountered `invalid peer certificate: UnknownIssuer`
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/da0c856e-e468-448e-9e94-c90684aae931">

### Expected behavior

`--tls-no-verify` should work

**Comment by zen-xu** [comment]
Additionally, version 0.28.2 does not have this issue.

**Comment by baszalmstra** [comment]
That is strange! How did you install pixi?

**Comment by zen-xu** [comment]
download it from github

**Comment by zen-xu** [comment]
Or is it possible to provide an option for specifying a self-signed certificate?

**Comment by baszalmstra** [comment]
You should be able to add the certificate to your oses certificate store and it should be picked up.

Ill investigate the regression.

**Comment by zen-xu** [comment]
I have added the certificate to /etc/ssl/certs/, version 0.28.2 can recognize it well, but version 0.29.0 cannot.

**Comment by baszalmstra** [comment]
Ah this seems to be due to an update in uv: https://github.com/astral-sh/uv/pull/6591 .

This is handled differently now between uv and pixi.. Looping in @tdejager . I think this kind of setup would also be much better for pixi but it would require a little refactoring. WDYT?

**Comment by baszalmstra** [comment]
@zen-xu As a workaround you could try setting the `SSL_CERT_FILE` and/or `SSL_CLIENT_CERT` environment variables as described here: https://docs.astral.sh/uv/configuration/authentication/#authentication-with-alternative-package-indexes

**Comment by tdejager** [comment]
> @zen-xu As a workaround you could try setting the `SSL_CERT_FILE` and/or `SSL_CLIENT_CERT` environment variables as described here: https://docs.astral.sh/uv/configuration/authentication/#authentication-with-alternative-package-indexes

Are you sure that these are read from our library calls as well, some env variables uv reads from the command line modules only

**Comment by zen-xu** [comment]
As a workaround you could try setting the `SSL_CERT_FILE` and/or `SSL_CLIENT_CERT` environment variables as described here: [docs.astral.sh/uv/configuration/authentication#authentication-with-alternative-package-indexes](https://docs.astral.sh/uv/configuration/authentication/#authentication-with-alternative-package-indexes)

This works very well> @zen-xu As a workaround you could try setting the `SSL_CERT_FILE` and/or `SSL_CLIENT_CERT` environment variables as described here: [docs.astral.sh/uv/configuration/authentication#authentication-with-alternative-package-indexes](https://docs.astral.sh/uv/configuration/authentication/#authentication-with-alternative-package-indexes)

This works

**Comment by benmoss** [comment]
Also running into the same thing, corporate MITM cert not getting respected by pixi when I use a pyproject file.

```
$ pixi init --pyproject
$ pixi add crane
  × default: error installing/updating PyPI dependencies
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: wow @ file:///private/tmp/wow
  ├─▶ Failed to install requirements from build-system.requires (resolve)
  ├─▶ No solution found when resolving: hatchling
  ├─▶ Request failed after 3 retries
  ├─▶ error sending request for url (https://pypi.org/simple/hatchling/)
  ├─▶ client error (Connect)
  ╰─▶ invalid peer certificate: UnknownIssuer
```

**Comment by tdejager** [comment]
Yes, I need to map the `trusted-hosts` feature from uv to our codebase, just need to think of a good spot in the `pixi.toml` for it.

**Comment by tdejager** [comment]
> Also running into the same thing, corporate MITM cert not getting respected by pixi when I use a pyproject file.
> 
> ```
> $ pixi init --pyproject
> $ pixi add crane
>   × default: error installing/updating PyPI dependencies
>   ├─▶ Failed to prepare distributions
>   ├─▶ Failed to fetch wheel: wow @ file:///private/tmp/wow
>   ├─▶ Failed to install requirements from build-system.requires (resolve)
>   ├─▶ No solution found when resolving: hatchling
>   ├─▶ Request failed after 3 retries
>   ├─▶ error sending request for url (https://pypi.org/simple/hatchling/)
>   ├─▶ client error (Connect)
>   ╰─▶ invalid peer certificate: UnknownIssuer
> ```
> 
> If I use a regular pixi.toml file this bug doesn't occur, so I agree it's due to uv changes rather than the switch to rustls-tls

@benmoss in this case you get the MITM cert instead of the one from `https://pypi.org` right :)?

**Comment by zen-xu** [comment]
@markusschlenker I guess you probably forgot to add `export`

```bash
export SSL_CERT_FILE=/etc/ssl/certs/ca-certification.crt
pixi install
```

**Comment by markusschlenker** [comment]
@zen-xu Thank you for the reply. I work on Windows and tried the following:

```cmd
> set SSL_CERT_FILE="C:\Users\myname\.cert\ca_bundle.pem"
> pixi install
 WARN TLS verification is disabled. This is insecure and should only be used for testing or internal networks.
  ⠂ default:win-64       [00:00:03] resolving pypi dependencies
  x failed to solve the pypi requirements of 'default' 'win-64'
  |-> failed to resolve pypi dependencies
  |-> Failed to fetch: `https://nexus/repository/py-pypi/simple/imohash/`
  |-> Request failed after 3 retries
  |-> error sending request for url (https://nexus/repository/py-pypi/simple/imohash/)
  |-> client error (Connect)
  `-> invalid peer certificate: UnknownIssuer
```

**Comment by zen-xu** [comment]
@markusschlenker I'm sorry, I'm not very familiar with Windows; perhaps you can wait for #2521 to be merged to solve this issue

**Comment by markusschlenker** [comment]
still an issue for me with pixi 0.39

```cmd
C:\Users\myname\pixi\test-dump>pixi -V
pixi 0.39.0

C:\Users\myname\pixi\test-dump>pixi install --tls-no-verify
 WARN TLS verification is disabled. This is insecure and should only be used for testing or internal networks.
  ⠄ default:win-64       [00:00:01] resolving pypi dependencies                                                                               x failed to solve the pypi requirements of 'default' 'win-64'
  |-> failed to resolve pypi dependencies
  |-> Failed to fetch: `https://nexus/repository/py-pypi/simple/imohash/`
  |-> Request failed after 3 retries
  |-> error sending request for url (https://nexus/repository/py-pypi/simple/imohash/)
  |-> client error (Connect)
  `-> invalid peer certificate: UnknownIssuer
```

```pixi.toml
[project]
authors = [""]
channels = [
	"https://nexus/repository/py-conda-forge",
	"https://nexus/repository/bioconda",
]
description = "Add a short description here"
name = "main-py3.12"
platforms = ["win-64"]
version = "0.1.0"
conda-pypi-map = { "https://nexus/repository/py-conda-forge" = "file:///C:/Users/myname/.pixi/conda-pypi-map_prefix-dev_parselmouth_compressed_mapping.json" }

[pypi-options]
index-url = "https://nexus/repository/py-pypi/simple"


[tasks]

[dependencies]
python = ">=3.12.0,<3.13"

[pypi-dependencies]
imohash = "*"

```

**Comment by zen-xu** [comment]
@markusschlenker This will be fixed in the next version

**Comment by markusschlenker** [comment]
@zen-xu still seems to not be working with pixi 0.40.2 

Do I need to configure it separately in pixi.toml ?

**Comment by zen-xu** [comment]
@markusschlenker You should configure it in `~/.pixi/config.toml`

**Comment by markusschlenker** [comment]
@zen-xu thanks, I got it to work now. Turns out I stored config.toml in a directory not valid on Windows but only on Linux (%USERPROFILE%\.config\pixi\config.toml). After moving it to %USERPROFILE%\.pixi\config.toml it works.

**Comment by Sam-Bate-ITV** [comment]
I've just run pixi build with `--tls-no-verify` on version 0.70.2 and it still results in `invalid peer certificate: UnknownIssuer` on a corporate vpn network connection (using Mac os). 

The error was on the request to `https://conda.anaconda.org/conda-forge/osx-arm64/repodata_shards.msgpack.zst`

so I created a `~/.pixi/config.toml` with the following:

```
[pypi-config]
allow-insecure-host = [
    "https://conda.anaconda.org"
]
```

still get the same issue though:

```
$ pixi run build                
Error:   × failed to solve requirements of environment 'default' for platform 'osx-arm64'
  ├─▶   × could not initialize the build-backend
  │   
  ├─▶   × failed to query the conda gateway
  │   
  ├─▶ Request failed after 3 retries
  ├─▶ error sending request for url (https://conda.anaconda.org/conda-forge/osx-arm64/repodata_shards.msgpack.zst)
  ├─▶ client error (Connect)
  ╰─▶ invalid peer certificate: UnknownIssuer
```

perhaps this issue should still be open

**Comment by benmoss** [comment]
@Sam-Bate-ITV can you try `--tls-root-certs=system`? it is strange that `tls-no-verify` doesn't work though.

**Comment by Sam-Bate-ITV** [comment]
```
$ pixi run build --tls-root-certs=system                     
Error:   × failed to solve requirements of environment 'default' for platform 'osx-arm64'
  ├─▶   × could not initialize the build-backend
  │   
  ├─▶   × failed to query the conda gateway
  │   
  ├─▶ Request failed after 3 retries
  ├─▶ error sending request for url (https://conda.modular.com/max/osx-arm64/repodata_shards.msgpack.zst)
  ├─▶ client error (Connect)
  ╰─▶ invalid peer certificate: UnknownIssuer
```

**Comment by baszalmstra** [comment]
@Sam-Bate-ITV I didnt see this at first but you are running a "task" called "build". Is the output you shared part of the task execution or of pixi before the task execution has even started?

**Comment by baszalmstra** [comment]
I think you also need to run it as:

```
pixi run --tls-root-certs=system build
```

Otherwise the `--tls-root-certs` argument is passed along to the task itself!

**Comment by Sam-Bate-ITV** [comment]
> I think you also need to run it as:
> 
> ```
> pixi run --tls-root-certs=system build
> ```
> 
> Otherwise the `--tls-root-certs` argument is passed along to the task itself!

that was it, thanks. Running `pixi run --tls-root-certs=system build` works fine
