### ISSUE TITLE
Search does not return existing conda-forge packages and pixi add complains about "no candidates found"

### ISSUE THREAD

**Issue by mgiugliano** [prefix-dev/pixi#1991]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi search neuron*
```
pixi.toml is
```
[project]
authors = ["XXXXXXXXXXXXXXXXX"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "testme2"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.5,<4"
numpy = ">=2.1.1,<3"
matplotlib = ">=3.9.2,<4"
jupyterlab = ">=4.2.5,<5"
```

### Issue description

Both "neuron" and "neunorm" are valid conda-forge packages, see [here](https://anaconda.org/conda-forge/neuron) and [here](https://anaconda.org/conda-forge/neunorm).

When the `search` command is invoked, pixi returns

```
Using channels: conda-forge
Package                                  Version             Channel            
neunorm                                  1.4.3               conda-forge/noarch 
```

Similarly, `pixi add neuron` returns "missing candidate".

### Expected behavior

pixi should return another hit, showing two results and should allow to install neuron.

Where am I wrong? Thank you for your patience with me.

**Comment by mgiugliano** [comment]
I confirm it must be a bug. I just found [here](https://prefix.dev/channels/conda-forge/packages/neuron) that the suggested pixi command to install that specific package is:

```
pixi add neuron
```

which unfortunately does not work and returns

```
➙ pixi add neuron
  × failed to solve the conda requirements of 'default' 'osx-arm64'
  ╰─▶ Cannot solve the request because of: No candidates were found for neuron *.
```

**Comment by baszalmstra** [comment]
The package is only available for osx-64 try using that in your platforms.

**Comment by mgiugliano** [comment]
> The package is only available for osx-64 try using that in your platforms.

Thank you. 

If I manually add to pixi.toml
```
[pypi-dependencies]
neuron = ">=8.0.0,<9"
```

the package gets installed and works perfectly.

**Comment by baszalmstra** [comment]
I [added `neuron` and `neunorm` to the osx-arm64 migration](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6389), if everything goes right these packages will then also be available for osx-arm64 from conda-forge.

**Comment by tdejager** [comment]
@baszalmstra seems to be looking good on that feedstock!

**Comment by mgiugliano** [comment]
I am in debt with you, @baszalmstra and @tdejager  !!!

**Comment by tdejager** [comment]
Haha thank you @mgiugliano, is it okay to close this?
