### ISSUE TITLE
Relative local paths for dependencies

### ISSUE THREAD

**Issue by lminer** [prefix-dev/pixi#2004]
### Problem description

I have a large monorepo with multiple sub-projects, each with their own pyproject.toml. Some of the subprojects depend on each other.

```
monorepo/
│
├── pyproject.toml         # Base pyproject.toml (for linting only)
├── libs/
│   ├── package_a/
│   │   ├── pyproject.toml  # pyproject.toml for package_a
│   │   ├── src/
│   │   │   └── package_a/
│   │   │       └── __init__.py
│   │   └── tests/
│   │       └── test_package_a.py
│   ├── package_b/
│   │   ├── pyproject.toml  # pyproject.toml for package_b
│   │   ├── src/
│   │   │   └── package_b/
│   │   │       └── __init__.py
│   │   └── tests/
│   │       └── test_package_b.py
│   └── package_c/
│       ├── pyproject.toml  # pyproject.toml for package_c
│       ├── src/
│       │   └── package_c/
│       │       └── __init__.py
│       └── tests/
│           └── test_package_c.py
│
└── other_dirs/            # Other directories in the monorepo
```

It would be nice to be able to have package A refer to a relative path to package B in its pyproject.toml. This is possible using hatch/uv, but I can't find any documentation to see if it can be done in pixi.

**Comment by tdejager** [comment]
This can currently only be done for python projects using pypi-dependencies. See the following example: https://github.com/prefix-dev/pixi/tree/main/examples/pypi-source-deps this also works for pyproject.toml. Also see: https://github.com/Deltares/Ribasim

**Comment by lminer** [comment]
What happens if the local project being linked to is itself a pixi project
with conda dependencies? Will it properly install everything?

**Comment by tdejager** [comment]
Ah no it does not indeed, that is feature that we are working on now called 'pixi build'.

**Comment by lminer** [comment]
Exciting! Is there an issue I can track?

**Comment by tdejager** [comment]
Yes here: https://github.com/prefix-dev/pixi/issues/1654

**Comment by ruben-arts** [comment]
Closing this in favor of `pixi build`
