### ISSUE TITLE
Endless print when entering shell from byobu

### ISSUE THREAD

**Issue by liux2** [prefix-dev/pixi#2026]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
# Enter byobu
byobu
# Enter pixi shell
pixi shell
```

### Issue description

<img width="1289" alt="Screenshot 2024-09-10 at 5 18 15 PM" src="https://github.com/user-attachments/assets/a83107df-afe1-45af-ac71-938a4dc0c2e9">
As the screenshot shows, entering pixi shell from byobu will cause the terminal to be flushed by prints...

### Expected behavior

Running inside byobu should end up with in normal situations
```
(env) user > 
```

**Comment by ruben-arts** [comment]
I can't reproduce the situation. Please create a good reproduction example. 
I've tried with `bash` and `zsh` and on my base ubuntu image with the latest version of `pixi`.
