### ISSUE TITLE
allow specifying priority in `pixi project channel add`

### ISSUE THREAD

**Issue by minrk** [prefix-dev/pixi#2035]
### Problem description

Since channel order/priority matters, it would be nice if `pixi project channel add CHANNEL` could specify the priority of the channel being added.

The following would work:

```
pixi project channel add [--priority N] CHANNEL
```

to generate the toml:

```
channels = ["conda-forge", {channel = "CHANNEL", priority = N}]
```

To compare, `conda config --add channels CHANNEL` adds the channel as _top_ priority by default, and `conda config --append channels CHANNEL` adds at lowest priority. `pixi project channel add` only does the latter, not matching my expectations coming from conda. Conda's default is also more often what I _want_, since one of the main reasons I use channels other than conda-forge is to test out builds of packages not _yet_ on conda-forge in a custom label. This can't be set up easily without manual edits of the toml file.

**Comment by ruben-arts** [comment]
Good idea, PR's are welcome!
