### ISSUE TITLE
Cannot run pixi shell in a Gitlab CI

### ISSUE THREAD

**Issue by jacobwilliams** [prefix-dev/pixi#2037]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi shell
```
or

```shell
pixi shell --color never --no-progress
```

### Issue description

Trying to run `pixi shell` in a shell runner of a GitLab CI instance I get this error:

```
Error starting shell: Not a tty (os error 25)
```

I"m trying to replace `conda activate ...` which always worked fine here.

What is the proper way to run pixi in a CI type environment? 

### Expected behavior

Would like to be able to activate a pixi environment in a CI environment (i.e., what is the replacement for `conda activate` that works here).

**Comment by jacobwilliams** [comment]
I though maybe:

```shell
pixi run --environment ./my_env ./script_i_want_to_run.sh
```

might do it. But I get:

```shell
could not find pixi.toml or pyproject.toml which is configured to use pixi
```

So I guess that only works after calling `pixi shell`? That's not clear from the documentation.

**Comment by jacobwilliams** [comment]
So I would need:

```shell
pixi run --environment ./my_env --manifest-path ./my_env/pixi.toml ./script_i_want_to_run.sh
```

Does `--environment` not imply that's the environment I want to use?

**Comment by baszalmstra** [comment]
I dont think you need to specify --environment unless you have alternative environments setup in you pixi.toml

**Comment by jacobwilliams** [comment]
Thanks! This works:

```
pixi run --manifest-path ./my_env/pixi.toml ./script_i_want_to_run.sh
```

I was confused by the environment flag. Although, honestly, I think a user coming from conda would expect that `--environment ./my_env` would do what I was expecting...

**Comment by mragsac** [comment]
I also encountered the `Error starting shell: Not a tty (os error 25)` issue when starting `pixi shell` in an HPC job to start a `jupyterlab` instance! I was also confused by the `--environment` flag and didn't know what to do until I found this issue... 

Luckily, using the `--manifest-path` flag resolved things on my end to run `jupyter` in my project! Thanks @jacobwilliams!

However, I'm still confused as to why the `pixi.toml` or `pyproject.toml` files can't be recognized after running `pixi shell` within my job? Things do work properly in interactive jobs versus `sbatch` scripts.

**Comment by wolfv** [comment]
In a non interactive way you should be able to run something like `eval $(pixi shell-hook)` to make the environment activated in your current shell. Does that work @mragsac?

**Comment by mragsac** [comment]
> In a non interactive way you should be able to run something like `eval $(pixi shell-hook)` to make the environment activated in your current shell. Does that work [@mragsac](https://github.com/mragsac)?

Whoops! Yes, using `eval $(pixi shell-hook)` works for me! Thanks so much!
