### ISSUE TITLE
Add support for global configuration manipulation in `pixi config`

### ISSUE THREAD

**Issue by apcamargo** [prefix-dev/pixi#2042]
### Problem description

Currently, as far as I can tell, `pixi config` only operates on the project-specific configuration. It would be useful to allow manipulation of the global configuration as well.

For example, the following command would open `$HOME/.config/pixi/config.toml` (or `$HOME/.pixi/config.toml`) in the text editor:

```bash
pixi config edit --global
```

**Comment by olivier-lacroix** [comment]
I believe this is already possible? [See here](https://pixi.sh/latest/reference/cli/#config)

**Comment by apcamargo** [comment]
You're right, my bad. When I tried to run the command above I got an error, but now it's all good. Not sure what happened...

I'll just close this. Thanks for the answer.
