### ISSUE TITLE
Add channel and package in one `pixi add` command.

### ISSUE THREAD

**Issue by ianzone** [prefix-dev/pixi#2051]
### Discussed in https://github.com/prefix-dev/pixi/discussions/2010

<div type='discussions-op-text'>

<sup>Originally posted by **ianzone** September  9, 2024</sup>
I understand that I could specify the channel in `pixi.toml`, but can I execute like 
`pixi add pytorch -c 'pytorch' cuda -c 'nvidia'`? Since my dependency list was empty at the beginning.</div>

**Comment by ruben-arts** [comment]
What we should do is let `pixi add pytorch::pytorch` to add `pytorch` as a channel.
