### ISSUE TITLE
Cannot install Spyder with pixi (but with miniforge). Constrained to old (1.4) version of python.app?

### ISSUE THREAD

**Issue by fangohr** [prefix-dev/pixi#2053]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Please check out https://github.com/spyder-ide/spyder/issues/22386 for a detailed description.

I wasn't sure if this is a pixi, spyder or conda-forge bug, so I filed it with [spyder-ide](https://github.com/spyder-ide/spyder/issues/22386) first.

However, it turns out I can install spyder fine using miniforge. As pixi and miniforge should use the same conda-forge packages as far as I understand, I thought it might be a pixi problem and thus should be reported here. Or if not, perhaps somebody from the pixi team has the experience to quickly point out what is going on.

### Issue description

Executive summary:

- install spyder via pixi results in [spyder not being executable](https://github.com/spyder-ide/spyder/issues/22386#issue-2487937334) . The error reads:
```
❯ pixi run spyder
/Users/fangohr/spyder-pixi-issue/.pixi/envs/default/bin/pythonw: line 3: /Users/fangohr/spyder-pixi-issue/.pixi/envs/default/python.app/Contents/MacOS/python: No such file or directory
```
- A possible cause of the problem is the version of the `python.app` package that is installed: pixi uses version 1.4 (which probably has a bug) and miniforge uses version 3. Please see https://github.com/spyder-ide/spyder/issues/22386#issuecomment-2352215111
- pixi refuses to allow version 3: see https://github.com/spyder-ide/spyder/issues/22386#issuecomment-2352220129

### Expected behavior

Spyder should start.

**Comment by wolfv** [comment]
Is there a conflict if you try to force the newer `python.app` version using constraints? E.g. `pixi add "python.app>=3"`? It would be interesting to find out if there is another package in your environment that depends on an older version of `python.app` (and hence is the reason why it's being held back).
Maybe you could also study the lock file to find all packages that depend on `python.app`.

**Comment by fangohr** [comment]
Thanks for getting back to this. While I didn't say it, the above command is nearly all to reproduce. (It seems I am not getting to the pixi.lock file.) Full example:
```
/tmp via 🐍 v3.12.4 
❯ mkdir issue2053

/tmp via 🐍 v3.12.4 
❯ cd issue2053 

/tmp/issue2053 
❯ pixi init
✔ Created /private/tmp/issue2053/pixi.toml

/tmp/issue2053 
❯ pixi add "python.app>=3"
  × failed to solve the conda requirements of 'default' 'osx-arm64'
  ╰─▶ Cannot solve the request because of: No candidates were found for
      python.app >=3.
      


/tmp/issue2053 
❯ ls -l
total 8
-rw-r--r--  1 fangohr  wheel  232 Sep 16 10:13 pixi.toml

/tmp/issue2053 
❯ cat pixi.toml 
[project]
authors = ["Hans Fangohr <fangohr@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "issue2053"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
```

**Comment by wolfv** [comment]
Actually the version 3 is _only_ available from defaults. So if that is really the culprit, then it cannot work.


<img width="1101" alt="Screenshot 2024-09-16 at 12 39 14" src="https://github.com/user-attachments/assets/81f9236b-12e0-44db-854b-2c7b7bfb6bea">

**Comment by ruben-arts** [comment]
Closing as this issue is not part of pixi itself.

**Comment by fangohr** [comment]
Thank you @wolfv - that was really helpful input. (miniforge tricked me into using the default channel somehow ..)
