### ISSUE TITLE
thread 'main' panicked at crates/pixi_utils/src/reqwest.rs:99:10:

### ISSUE THREAD

**Issue by josephwinston** [prefix-dev/pixi#2056]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

pixi 0.29.0
```shell
pixi init .
pixi shell
thread 'main' panicked at crates/pixi_utils/src/reqwest.rs:99:10:
failed to create reqwest Client: reqwest::Error { kind: Builder, source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

This pattern works elsewhere but is failing on Ubuntu 22.04.4 LTS

### Expected behavior

Downloads requirements and run a new shell

**Comment by ruben-arts** [comment]
Could you provide some more information about your system. Is there some non default read only filesystem setup or something like that? 

This issue is so unexpected that we don't handle the error very nicely. I think we could improve that.

**Comment by ruben-arts** [comment]
I can't recreate it in a `ubuntu:22.04` docker.

**Comment by josephwinston** [comment]
It looks like a misconfiguration system, but I have no idea how this happened. 

```
```
[log.txt](https://github.com/user-attachments/files/17031517/log.txt)

**Comment by ruben-arts** [comment]
Doesn't this break other tools too? Maybe we're touching to many certs. Could you try with other tools like e.g. `conda`

**Comment by josephwinston** [comment]
Everything else to my knowledge is working correctly on the system as it is being used 24x7 in production On Sep 18, 2024, at 3:16 AM, Ruben Arts ***@***.***> wrote:﻿
Doesn't this break other tools too? Maybe we're touching to many certs. Could you try with other tools like e.g. conda

**Comment by josephwinston** [comment]
The system was up to date when it was put into production.  When it is decommissioned, I'll update and work on why the certs are the way they are.

Please close.  I can open a new ticket if needed.

**Comment by ruben-arts** [comment]
Thanks for the update!

**Comment by daylinmorgan** [comment]
I've been getting the same issue starting from v0.29.0.
Similarly, it seems to be a permission issue with specific certs.

This is on a university-managed server, is the solution on my end to modify the permissions of these files so they are world-readable?

I've not had any problems except with `pixi` and `uv` which both originate from the reqwest builder.

These permission issues didn't seem to impede `micromamba`, as it had no issues creating an environment and installing packages.

```
❯ \ls -l /usr/lib/ssl/certs/{afe065ec.0,katello-default-ca.pem} /usr/local/share/ca-certificates/*
lrwxrwxrwx 1 root root   22 Sep 11  2023 /usr/lib/ssl/certs/afe065ec.0 -> katello-default-ca.pem
lrwxrwxrwx 1 root root   55 Sep 11  2023 /usr/lib/ssl/certs/katello-default-ca.pem -> /usr/local/share/ca-certificates/katello-default-ca.crt
-rw-rw---- 1 root root 2492 Sep 11  2023 /usr/local/share/ca-certificates/katello-default-ca.crt
-rw-rw---- 1 root root 1968 Sep 11  2023 /usr/local/share/ca-certificates/katello-server-ca-1.crt
-rw-rw---- 1 root root 2130 Sep 11  2023 /usr/local/share/ca-certificates/katello-server-ca-2.crt
-rw-rw---- 1 root root 1517 Sep 11  2023 /usr/local/share/ca-certificates/katello-server-ca.crt
```

[backtrace-log.txt](https://github.com/user-attachments/files/17101293/backtrace-log.txt)
[strace-log.txt](https://github.com/user-attachments/files/17101298/strace-log.txt)

**Comment by daylinmorgan** [comment]
I don't see this issue when building `pixi` v0.31.0 after swapping `reqwest` to v0.12.8.

**Comment by liquidcarbon** [comment]
Oddly, this is popped up on Windows, with pixi 0.32.1

But fresh pixi init in a an empty folder followed by pixi add works
