### ISSUE TITLE
Openmim support

### ISSUE THREAD

**Issue by ControlNet** [prefix-dev/pixi#2058]
### Problem description

Besides the `conda` and `pip`, sometimes the developers are required to use the libraries from [open-mmlab](https://github.com/open-mmlab), which uses `openmim` library to install the libraries for easier CUDA extension build process.

For instance, the following commands are used to install [mmcv](https://github.com/open-mmlab/mmcv) and [mmdet](https://github.com/open-mmlab/mmdetection):
```
pip install -U openmim
mim install mmcv==2.1.0
mim install mmdet
```

Currently, `conda` support in pixi provides a valuable toolkit for the AI/deep learning community, simplifying GPU-related environment setup. However, there seems to be no support for `openmim` in pixi currently. 

Are there any plans to support `openmim` for those who use OpenMMLab libraries? If not, could you offer any guidance or suggestions on how to address this scenario for users relying on the openmim workflow?

**Comment by ruben-arts** [comment]
This is the first time I hear about `mim` but it seems like you can install it into your environment or globally with:
```
pixi init project && cd project
pixi add openmim
pixi run mim

# Or globally
pixi global install openmim
mim
```

Are you looking for more or would that be enough? If not so, could you write out what the *openmim workflow* means/looks like?

**Comment by ControlNet** [comment]
@ruben-arts Thank you for your suggestion. Yeah, I think that's one way to achieve it. Of course the best solution is to write it in the `pixi.toml` then just one command install it.

Currently I'm deploying the method relies on [mmdetection3d](https://github.com/open-mmlab/mmdetection3d/tree/main), which requires the `openmim`.

Here is my current environment preparation script after git clone mmdetection3d, 
```
conda create -n det3d python=3.10 -y
conda install pytorch==2.4.0 torchvision==0.19 torchaudio==2.4.0 nvidia/label/cuda-12.4.0::cuda pytorch-cuda=12.4 -c pytorch
conda install ninja -y
pip install openmim fsspec
mim install mmengine
CUDA_HOME=$CONDA_PREFIX && mim install "mmcv<2.2.0,>=2.0.0rc4"
CUDA_HOME=$CONDA_PREFIX && mim install 'mmdet>=3.0.0'
CUDA_HOME=$CONDA_PREFIX python projects/BEVFusion/setup.py develop
pip install numba pyquaternion trimesh open3d
```

As you see, it includes the installation with `openmim`, and local cuda extension compilation, which is quite complex.

**Comment by ruben-arts** [comment]
I tried to create your environment in a `pixi` project. Here is the gist: https://gist.github.com/ruben-arts/9e95e7d6b4e85d0010e8ec99b1999a49#file-pixi-toml

I couldn't limit the `mmcv` to only these versions but the rest should be similar. 

You can still use `mim` for all the model logic. But at least you don't have to mix 3 different package managers anymore. 

The `channel-priority = "disabled"` was added to avoid our priority logic. This is not really nice but with these channels it's a pain to mix them with the priority set. 

I hope this could help. 

Ps. We've had lots of conversations with Nvidia and they're working on making the conda experience much better on `conda-forge`

**Comment by ControlNet** [comment]
Thank you for your help. From your gist, seems the solution is to find the conda alternative of these mm packages, which might work for some libraries such as `mmcv` and `mmdet` with older versions, but not for less-popular one, such as `mmdet3d`. But worst case, I can use pypi build from source (which seems is what `mim` is doing).

**Comment by wolfv** [comment]
@ControlNet if you are interested we can help to get them on conda-forge! :)

**Comment by ControlNet** [comment]
@wolfv Thank you, but I think the maintainer from open-mmlab should do that rather than us :)
