### ISSUE TITLE
Failed to read 'paths.json' and 'index.json'

### ISSUE THREAD

**Issue by giswqs** [prefix-dev/pixi#2146]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init
pixi add geospatial
```

### Issue description

I am trying to install the [geospatial](https://github.com/opengeos/geospatial) package. It throws different errors. I had to run `pixi add geospatial` a few times to install it.

![image](https://github.com/user-attachments/assets/0e15474c-96c7-4fc3-9441-b248a1b91b54)

### Expected behavior

It should install the package smoothly without throwing error.s

**Comment by ruben-arts** [comment]
I believe this has to do with a corrupted cache. Could you clear it and try again: `pixi clean cache --conda`

**Comment by giswqs** [comment]
It seems working now. Thanks.
