### ISSUE TITLE
`pixi add --pypi -p <platform>` inconsistent between pixi.toml and pyproject.toml

### ISSUE THREAD

**Issue by escalonn** [prefix-dev/pixi#2149]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Tested on 0.28 since it's the latest on winget
```shell
pixi add --pypi -p win-64 AssertWT
```

### Issue description

With `pixi.toml`, that command adds the package to `target.win-64.pypi-dependencies` as expected.
```toml
[target.win-64.pypi-dependencies]
assertwt = ">=2.3.1, <3"
```
But with `pyproject.toml`, it adds the package to `project.dependencies`, without any environment marker.
```toml
[project]
dependencies = ["assertwt>=2.3.1,<3"]
```
In both scenarios, the same shell output was shown:
```
✔ Added AssertWT
Added these as pypi-dependencies.
Added these only for platform(s): win-64
```

### Expected behavior

The behavior should be consistent between `pixi.toml` and `pyproject.toml` scenarios or else raise an error. The shell output shouldn't claim that the dependencies were added as platform-specific when they were not.

Possibilities:
1. Pixi should have a documented translation from Pixi/Conda platform identifiers to PEP 508 environment markers, and use that translation to write to `project.dependencies` (#1259)
2. Pixi should make the `--platform` and `--pypi` options mutually exclusive for `pyproject.toml` projects, and direct users to write the environment markers themselves (e.g. `pixi add --pypi 'AssertWT;platform_system=="Windows"'` seems to work correctly, though I don't think pixi actually uses that marker yet)
3. Pixi should write to `tool.pixi.target.win-64.pypi-dependencies` in this scenario

**Comment by escalonn** [comment]
(thanks, pixi devs, for finally fixing python after 30 years)

**Comment by ruben-arts** [comment]
Thank you @escalonn, great write up! 

You correctly identified this as a bug. For now I would fix this with option 3, using the `[tool.pixi.target.` table prefix. But we should get the environment markers working to in the near future!

> [!NOTE]
> If anyone is up to the job before we get to it feel free to make a PR. It should be a good first timer issue!

**Comment by olivier-lacroix** [comment]
@escalonn good catch... adding the markers automatically would be pretty cool !

**Comment by thomas-maschler** [comment]
I also ran into that issue and noticed that pypi dependencies for target platforms are not included in the wheel when trying to create a distribution. (I built the wheel with `hatch build`)

**Comment by olivier-lacroix** [comment]
I believe this issue can be closed, thanks to https://github.com/prefix-dev/pixi/pull/2448
