### ISSUE TITLE
winget-releaser github action stopped automated PRs after 0.28.1

### ISSUE THREAD

**Issue by jo-chemla** [prefix-dev/pixi#2165]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

A github workflow was [setup](https://github.com/prefix-dev/pixi/pull/547) ~10 months ago to automate winget-pkgs PRs of newly released msi versions of Pixi, with package identifier `prefix-dev.pixi` - thanks for that! 
However, latest package version on winget available is `Found pixi [prefix-dev.pixi] Version 0.28.1` while latest github release is `0.30.0`.
Reproduction: run `winget install prefix-dev.pixi` which returns version 0.28.1. 

### Issue description

This is probably because the releases after 0.28.1 do not include `msi` builds anymore and that the winget-releaser action has flag `installers-regex: '\.msi' # Only .msi files`. Could either fix the action to build msi release or use exe for the regex. 

Otherwise, it could also be that either the `WINGET_TOKEN` associated which has read permissions was revoked, or that the winget-releaser github action is not run automatically on every github release. 

### Expected behavior

Every github release of pixi should automatically create a PR to winget-pkgs with the new version. 

See [latest PRs](https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs+prefix-dev.pixi+&type=pullrequests&s=created&o=desc) on winget-pkgs mentioning pixi.

**Comment by ruben-arts** [comment]
Thanks for the ping! I actually fixed the MSI installer issue in this pr: https://github.com/prefix-dev/pixi/pull/2087. Hopefully next release this will be fixed.

**Comment by jo-chemla** [comment]
Great to here, and thanks for the awesome work!

**Comment by ruben-arts** [comment]
https://github.com/microsoft/winget-pkgs/pull/177372 Lets see if that works

**Comment by jo-chemla** [comment]
Your PR to winget-pkgs for 0.31.0 was merged, thanks!
And looks like some (but not all) releases of pixi have the corresponding winget-releaser action workflow succeed. 
Not exactly sure why some still fail, after looking through some failed action runs. 

![Image](https://github.com/user-attachments/assets/bdd63b62-4bac-4ccd-9d50-9130cdd1636b)

**Comment by ruben-arts** [comment]
The annoying thing is that it most often fails on our CI but does work. Here are the versions merged into winget-pkgs as a result of the PR's build by those "failing" CI jobs: https://github.com/microsoft/winget-pkgs/pulls?q=sort%3Aupdated-desc+is%3Apr+pixi+is%3Amerged

**Comment by jo-chemla** [comment]
Thanks, looks like most of these action errors occurred because of `ECONNRESET` on get https://api.github.com/repos/microsoft/winget-pkgs/contents/manifests%2Fp%2Fprefix-dev%2Fpixi
This might be because of a github api being hit by too many requests. Closing this issue, thanks a lot for your help!
