### ISSUE TITLE
Pixi ignoring global configuration

### ISSUE THREAD

**Issue by noamgot** [prefix-dev/pixi#2168]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Open `~/.pixi/config.toml`\* and add:

```toml
[system-requirements]
libc = "2.27"
```

Inside some pixi project (I used https://github.com/prefix-dev/pixi ==> pixi/examples/jupyterlab) run:
```shell
pixi shell
```
And get:
```shell
WARN Ignoring 'system-requirements' in at $HOME/.pixi/config.toml
  × The current system has a mismatching virtual package. The project requires '__glibc' to be at least version '2.28' but the system has version '2.27'
```

\* For some reason I don't have `$HOME/.config/pixi/config.toml` (I do have `$HOME/.config/pixi/config.ini`)

### Issue description

I played with the pixi examples from https://github.com/prefix-dev/pixi and in all of the examples I got this error:
```
 × The current system has a mismatching virtual package. The project requires '__glibc' to be at least version '2.28' but the system has version '2.27'
```

I found out that there [global configuration](https://pixi.sh/v0.22.0/advanced/global_configuration/) is available, yet I found out the when I run pixi commands, the global configuration is ignored for some reason

### Expected behavior

Obviously, I'd expect a local pixi project to try and use the global configurations

**Comment by ruben-arts** [comment]
System requirements is a project manifest configuration only.

Put it in your `pixi.toml`:
```toml
[system-requirements]
libc = "2.27"
```

Or `pyproject.toml`:
```toml
[tool.pixi.system-requirements]
libc = "2.27"
```

**Comment by noamgot** [comment]
Interesting. My motivation was that I had to make this change in each project that I initialized. Wouldn't it make sense to allow it as a global configuration?

**Comment by ruben-arts** [comment]
We've got another idea to resolve having to set system-requirements at all. Which is described in https://github.com/prefix-dev/pixi/issues/346.

**Comment by ruben-arts** [comment]
Going to close this as I see not direct action needed to be taken.
