### ISSUE TITLE
Major flaw in `PATH` handling of `install.sh`

### ISSUE THREAD

**Issue by Arcitec** [prefix-dev/pixi#2188]
The latest version of `install.sh` creates the PATH as follows, which breaks every user's system if they have any paths with spaces:

```sh
export PATH=~/.pixi:$PATH
```

The correct method is to always, always, **always** double-quote:

```sh
export PATH="~/.pixi:$PATH"
```

Furthermore, you should either be resolving the `~` or replacing it with `$HOME`, because `~` is not valid inside `PATH`. So the final code would be:

```sh
export PATH="$HOME/.pixi:$PATH"
```

**Comment by wolfv** [comment]
Thanks @Arcitec - the code for `install.sh` is right here: https://github.com/prefix-dev/pixi/blob/main/install/install.sh

Do you want to send a PR?

**Comment by Arcitec** [comment]
Here's an example of every other software's `PATH` handling from my own `.zshrc`:

![Image](https://github.com/user-attachments/assets/310c8a1d-b0d1-471c-9114-6c2b914445ef)

@wolfv I was considering making a PR but I see that you support many shells, so I am not 100% comfortable doing it since I could only test Bash and ZSH.

**Comment by Arcitec** [comment]
@wolfv I suppose I could do the Bash and ZSH parts now.

**Comment by wolfv** [comment]
Yes, that would already cover many users! Thank you 🙏
