### ISSUE TITLE
Place CACHEDIR.TAG in .pixi/envs (and similar directories)

### ISSUE THREAD

**Issue by mdekstrand** [prefix-dev/pixi#2207]
### Problem description

Many backup programs (including the one I use, Kopia) respect a [`CACHEDIR.TAG`](https://bford.info/cachedir/) file to indicate directories that contain caches, build outputs, etc. and exclude them from backups.

It would be useful for Pixi to mark at least `.pixi/envs` and the directory containing solver environments (I am not remembering its name right at the moment) with this file, so that it is easy to exclude them from backups.

**Comment by ruben-arts** [comment]
I would agree, and so does @pavelzw in #1904, so I'll close this issue as duplicate for now, thanks for the input! Please like the other issue to get it more attention.
