### ISSUE TITLE
Docs: Solving environments still mentions rip instead of uv

### ISSUE THREAD

**Issue by saschahofmann** [prefix-dev/pixi#2218]
On [the solving environments section](https://pixi.sh/latest/features/environment/#solving-environments) it still mentions that rip is resolving the PyPI dependencies but I understand that this is done by uv now? I have no clue about the inner workings of pixi but I can go over that part of the docs and replace the references with uv.

**Comment by tdejager** [comment]
Indeed, you are correct this can be removed, feel free to change any documentation in  a PR as you see fit!
