### ISSUE TITLE
`pixi clean cache --yes` raises unexpected argument '--yes' found.

### ISSUE THREAD

**Issue by Glatzel** [prefix-dev/pixi#2237]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi clean cache --yes
error: unexpected argument '--yes' found
```

### Issue description

Test in pixi 0.32.0. windows
`--yes` is not found, while `pixi clean cache -y` works correctly.

### Expected behavior

`pixi clean cache` could take `--yes` argument or replace `pixi clean cache --yes` with `pixi clean cache -y` in document.

**Comment by ruben-arts** [comment]
That is really strange, apparently they broke that function in `clap` as we do have it as an option. I see that it worked in `v0.27.0` of pixi. 

This worked before and now it doesn't 🤔 
```rust
#[clap(short = 'y', long = "yes", long = "assume-yes")]
assume_yes: bool,
```

**Comment by Glatzel** [comment]
I think it started from 0.30.0.
0.29.0: `--yes` ok, `-y` not found.
0.30.0: `--yes` not fount, `-y` ok.

**Comment by ruben-arts** [comment]
Thank you @Glatzel , will be fixed in the next release!
