### ISSUE TITLE
Create a command to check if lockfile is up to date.

### ISSUE THREAD

**Issue by clement-chaneching** [prefix-dev/pixi#2253]
### Problem description

We are using pixi install --locked in the CICD.
It would be nice to have a simple command `pixi check-lock` or similar that just checks if the lockfile is up to date without trying to install anything, so that I can add it to a pre-commit hook.

Right now I am running a pixi install --locked and catching the error message in my pre-commit hook, but it can take a little while as it tries to install the environment.

**Comment by ruben-arts** [comment]
Currently you would be able to get that behavior with: `pixi list --locked`

**Comment by clement-chaneching** [comment]
Ah cool I had to update to latest pixi version and it worked! Thanks
