### ISSUE TITLE
Add support for anaconda.org to `pixi upload`

### ISSUE THREAD

**Issue by travishathaway** [prefix-dev/pixi#226]
### What's the idea?

Currently, the `pixi upload` command only supports uploads to [prefix.dev](https://prefix.dev). We would like to expand that to also support uploads to [anaconda.org](https://anaconda.org).

### What should be done?

- Figure out how this is currently done (this repository should provide plenty of information: https://github.com/Anaconda-Platform/anaconda-client)
- Create an implementation in pixi
- Don't forget to write tests!

### Additional notes

We probably won't want to do actual end-to-end testing for this (let's keep the tests fast 🐇). So, let's just mock the end points for now in the tests.

**Comment by wolfv** [comment]
I'd be fine with having the initial work in pixi and move it to rattler later, but either way works. Ideally this works with the `AuthenticatedClient` in rattler (that does work with the conda token as well :)

**Comment by wolfv** [comment]
Yeah I think we can remove the upload sub command in the meantime from pixi, actually
