### ISSUE TITLE
Global Ruby  — expose executables for installed gems

### ISSUE THREAD

**Issue by iandol** [prefix-dev/pixi#2281]
### Problem description

Ruby uses `gem` to install packages. Packages can add executables. At present `pixi` only exposes the main ruby globally. These executables are available in `.pixi/envs/ruby/share/rubygems/bin/`:

```bash
pixi global install ruby
gem install pandocomatic
```

It is present in `.pixi` folder:

```
ε ➪ ls .pixi/envs/ruby/share/rubygems/bin/
 bundle        bundler.lock        erb        irb.lock              pandocomatic        racc.lock   rbs        rdbg.lock   ri         typeprof.lock
 bundle.lock   do-pandoc.rb        erb.lock   pandoc2yaml.rb        pandocomatic.lock   rake        rbs.lock   rdoc        ri.lock    update_rubygems
 bundler       do-pandoc.rb.lock   irb        pandoc2yaml.rb.lock   racc                rake.lock   rdbg       rdoc.lock   typeprof   update_rubygems.lock
```

```
ε ➪ pixi global expose add pandocomatic -e ruby
  × Failed to add executables for environment: ruby
  ╰─▶ Couldn't find executable pandocomatic in /Users/ian/.pixi/envs/ruby, found these executables: []
```

But it fails. I also tried specifying the absolute path:

```
pixi global expose add ~/.pixi/envs/ruby/share/rubygems/bin/pandocomatic -e ruby
  × Failed to add executables for environment: ruby
  ╰─▶ Couldn't find executable /Users/ian/.pixi/envs/ruby/share/rubygems/bin/pandocomatic in /Users/ian/.pixi/envs/ruby, found these executables: []
```

At present i have do this manually, but this should be offered as there are many ruby packakges with useful executables.

**Comment by ruben-arts** [comment]
Thanks for the write-up. 
This is going to be a hard problem as it conflicts with the "isolated" environments. We don't want to auto expose everything from these environments. 

I guess you could do something like `GEM_HOME=/where/ever/you/want/` and then add `GEM_HOME` to the `PATH`. 

Pixi global (new and old) are not prepared to properly support other package managers to also start exposing binaries automatically.

**Comment by iandol** [comment]
One might not expect pixi to automatically expose all binaries that might be available from a package manager like Ruby's gem. But I thought that if a user manually tries to `expose add mytool -e myenv` that it could at least search the folder where the exes may reside rather than just failing. In this case as the user is responsible for `expose add` and `expose remove` explicitly, then pixi is absolved responsibility of managing these [sub]tools?

**Comment by ruben-arts** [comment]
The problem is that it pixi doesn't understand the `bin` folders in the environments it understands the `conda` packages. So in the current implementation that wouldn't be the same code path. We could make it as such but it's a bit far from the current goal, as it wouldn't give you a manifest you can reproduce, as the gems are not installed by pixi. 

For now I would recommend you to try the `GEM_HOME` path. And see if that fits your needs.

**Comment by iandol** [comment]
For anyone who comes along, note that just adding the existing `.pixi/envs/ruby/share/rubygems/bin` folder to path will not work; symlinking into `.pixi/bin` does work... You can do this when installing using:

```
gem install mypackage -n ~/.pixi/bin
```

Rubygems needs the exes in the same folder as ruby, hence `~/.pixi/bin`
