### ISSUE TITLE
`pixi global upgrade-all` regression in 0.33?

### ISSUE THREAD

**Issue by dhirschfeld** [prefix-dev/pixi#2293]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
❯ pixi global upgrade-all
Upgrade specific package which is installed globally

Usage: pixi global upgrade-all [OPTIONS] [SPECS]...

Arguments:
  [SPECS]...  Specifies the packages to upgrade

Options:
  -c, --channel <CHANNEL>    The channels to consider as a name or a url. Multiple channels can be specified by using this field multiple times
      --platform <PLATFORM>  The platform to install the package for [default: linux-64]
  -v, --verbose...           Increase logging verbosity
  -q, --quiet...             Decrease logging verbosity
      --color <COLOR>        Whether the log needs to be colored [env: PIXI_COLOR=] [default: auto] [possible values: always, never, auto]
      --no-progress          Hide all progress bars [env: PIXI_NO_PROGRESS=]
  -h, --help                 Print help (see more with '--help')
```

### Issue description

Previously `upgrade-all` would do as the name suggests - it would update all of globally installed tools.

Now it seems to want to provide a list of packages to update. Since I have a lot of packages and I want to keep them all update to date that's not very ergonomic.

### Expected behavior

`upgrade-all` updates all global environments (as was done previously)

**Comment by dhirschfeld** [comment]
It seems perhaps this functionality has moved to `pixi global update` - is that correct?
```
❯ pixi global update
✔ Updated environment fzf.
✔ Updated environment git-delta.
✔ Updated environment podman.
✔ Updated environment starship.
✔ Updated environment gh.
✔ Updated environment awscli.
✔ Updated environment uv.
✔ Updated environment terraform.
✔ Updated environment fd-find.
✔ Updated environment pgcli.
✔ Updated environment go-sqlcmd.
✔ Updated environment zoxide.
✔ Updated environment argocd-cli.
✔ Updated environment bat.
✔ Updated environment eza.
✔ Updated environment skopeo.
✔ Updated environment databricks-cli.
✔ Updated environment kubernetes-helm.
✔ Updated environment jq.
✔ Updated environment opentofu.
✔ Updated environment ghostscript.
✔ Updated environment helix.
✔ Updated environment kubernetes-client.
✔ Updated environment crane.
✔ Updated environment micromamba.
✔ Updated environment toolong.
✔ Updated environment harlequin.
✔ Updated environment hyperfine.
✔ Updated environment ripgrep.
✔ Updated environment nodejs.
```

☝  it would be helpful if the output stated what changes were made to the environments (the output from `upgrade-all` did this previously)

**Comment by Hofer-Julian** [comment]
Hey!

`pixi global upgrade-all` is indeed replaced by `pixi global update`. You should have gotten a nice error message here, but apparently something went wrong here.

Yes, the output of `pixi global update` is not great. We have a WIP for that, which will be part of the next release.

**Comment by dhirschfeld** [comment]
> We have a WIP for that, which will be part of the next release.

I might suggest ordering the output so that it's easier to parse if you're interested in the changes to a particular package(s)
