### ISSUE TITLE
reqwest::Error: Path not found

### ISSUE THREAD

**Issue by claudiushaag** [prefix-dev/pixi#2297]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell

```

### Issue description

Sadly, I somehow managed to mess up pixi on my Windows system. I'm currently not able to pinpoint where the problem may lie, so I'm opening an Issue and updating it as I go. Maybe someone has an idea in the meantime.

I upgraded to v0.33.0 this morning. I set up a first global environment, doing something like
```shell
pixi g i -e standard python=3.10 numpy scipy matplotlib pandas h5py
```
After that, I wanted to create a new pixi project in an old repo of mine which used mamba. I did a
```shell
pixi init --import path_to_envfile.yml
```
but when tried to install it via `pixi i`, I ran into errors.

These kind of errors now persist in many projects of mine, here is a overview of them:

```shell

PS D:\PATH> pixi self-update
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\reqwest-0.12.5\src\async_impl\client.rs:1901:38:
Client::new(): reqwest::Error { kind: Builder, source: Os { code: 3, kind: NotFound, message: "Das System kann den angegebenen Pfad nicht finden." } }
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace

PS D:\PATH> pixi run lint
Pixi task (lint in test): ruff check
thread 'main' panicked at crates\pixi_utils\src\reqwest.rs:100:10:
failed to create reqwest Client: reqwest::Error { kind: Builder, source: Os { code: 3, kind: NotFound, message: "Das System kann den angegebenen Pfad nicht finden." } }
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace

PS D:\PATH> pixi self-update --version 0.32.2
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\reqwest-0.12.5\src\async_impl\client.rs:1901:38:
Client::new(): reqwest::Error { kind: Builder, source: Os { code: 3, kind: NotFound, message: "Das System kann den angegebenen Pfad nicht finden." } }
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace

PS D:\PATH> pixi run lint
Pixi task (lint in test): ruff check
thread 'main' panicked at crates\pixi_utils\src\reqwest.rs:99:10:
failed to create reqwest Client: reqwest::Error { kind: Builder, source: Os { code: 3, kind: NotFound, message: "Das System kann den angegebenen Pfad nicht finden." } }
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace

```

As one can see, I was also not able to downgrade the pixi version. I instead tried to delete all pixi related folders, in my case `C:\pixi` (this one surprised me, looked like a git-clone...? But maybe my mistake...)and `C:\Users\XXX\.pixi`, and reinstall with a different version. I managed to do that by modifying the `install.ps1` script locally, and installed `v0.32.2`, as well as `v.0.31.0` (as I explicitly remember a upgrade then, reading about the speedup....), but these kind of errors persist even then and I'm not able to install or run tasks in an old pixi project. Interestingly, I'm not yet able to reproduce the errors in a new pixi project.

I don't know if this is relevant, but in that process I also tried deinstalling pixi using the powershell command on pixi.sh. The reaction of my system was:
<details>
$PIXI_BIN = "$Env:LocalAppData\pixi\bin\pixi"; Remove-Item -Path $PIXI_BIN
Remove-Item : Der Pfad "C:\Users\XXX\AppData\Local\pixi\bin\pixi" kann nicht gefunden werden, da er nicht vorhanden ist.
In Zeile:1 Zeichen:48
+ ... _BIN = "$Env:LocalAppData\pixi\bin\pixi"; Remove-Item -Path $PIXI_BIN
+                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\XXX\pixi\bin\pixi:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
</details>

Would love to get some help on this, especially as "simply" downgrading does not solve the problem...

Windows Setup is:
<details>
Windows 11 Pro, 10.0.22631
</details>

### Expected behavior

-

**Comment by wolfv** [comment]
Hey, are you using "local" channels anywhere? Like a path to a `-c C:/foo/`? Or `file:///C/foo`?

**Comment by claudiushaag** [comment]
Hey, thanks for the fast reply! No, nothing of that sorts.
I generated a test `pixi.toml`, which works in a clean folder, installing the environment, but when using the same .toml file in an older folder, having deleted the .pixi folder of that directory and run ``pixi clean cache``, the error with "crates\pixi_utils\src\reqwest.rs:99:10:" pops up.

**Comment by ruben-arts** [comment]
Could you add one more `v` to `-vv`: `-vvv` this gives us the debug logging, maybe it tells us more. Also the `pixi info` is sometimes helpful. And do you have a minimal project file that can reproduce the error?

**Comment by wolfv** [comment]
I see `pixi i -vv` in the comment above :)

I believe this is related to some certificate files. We need to figure out what files `reqwest` is trying to open.

**Comment by wolfv** [comment]
Do you have a config file in `.pixi/config.toml` (in that folder?).

I checked the code, but we are just regularly creating a reqwest client at that stage so I am not sure why this errors in this way, and also not sure what file is being accessed. From your log I am guessing you are on Windows?

**Comment by claudiushaag** [comment]
> Could you add one more `v` to `-vv`: `-vvv` this gives us the debug logging, maybe it tells us more. Also the `pixi info` is sometimes helpful. And do you have a minimal project file that can reproduce the error?

Thanks for looking into this! I added the `-vvv` option to above comment.

Yes, I'm on Windows, and no, there is no `.pixi/config.toml`. There is only a `pyproject.toml` in the project folder.

**Comment by wolfv** [comment]
It's pretty puzzling. I don't know if you have the time, but if you download `ProcMon` from Microsoft, you could look at which file is causing the issue:

Use Process Monitor:
Process Monitor (ProcMon) is a powerful Windows tool that can track file system activity.
a. Download Process Monitor from the Microsoft Sysinternals website.
b. Run Process Monitor as administrator.
c. In the filter settings:
- Add a filter for "Process Name" is "your_program.exe"
- Add a filter for "Result" contains "NAME NOT FOUND"
d. Clear the display (Ctrl+X) and start capturing events.
e. Run your Rust program.
f. Look for "CreateFile" operations with "NAME NOT FOUND" results.


https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by claudiushaag** [comment]
So, I digged a little deeper, within my ability of course....

I ran `ProcMon`, triggered a single `pixi i` in one of the critical folders and saved the log.
I can send the files if you want, I also captured the behaviour of a working `pixi i`. To me it seems like the last file which has been tried to access is `Users/XXX/.cache/pixi`, but indeed, there is no pixi folder in `.cache`.
Other Files which have a NAME NOT FOUND event, earlier in the process:
- `Users/XXX/.pixi/.config.toml`
- `ProjectFolder/pixi.lock`
- `Users/XXX/.pixi/bin/profapi.dll` (which I can't find either...)
- `Users/XXX/.pixi/bin/POWRPROF.dll`
- `Users/XXX/.pixi/bin/pdh.dll`
- `Users/XXX/.pixi/bin/userenv.dll`
- `Users/XXX/.pixi/bin/CRYPTBASE.DLL`
- `Users/XXX/.pixi/bin/UMPDC.dll`

**Comment by ruben-arts** [comment]
Thanks, this already explains a lot. I believe the `not found`s are fine. Could you check if you do have a `.cache/rattler` folder instead of `.cache/pixi`?

**Comment by claudiushaag** [comment]
No, I currently don't have a `.cache/rattler` folder...

But, `pixi info` states a different cache folder:
```shell
pixi info
      Pixi version: 0.31.0
          Platform: win-64
  Virtual packages: __win=0=0
                  : __archspec=1=skylake
         Cache dir: C:\Users\XXX\AppData\Local\rattler/cache
      Auth storage: C:\Users\XXX\.rattler\credentials.json
  Config locations: No config files found
```

**Comment by claudiushaag** [comment]
So I deleted both the `User/XXX/.pixi` folder, the `User/XXX/AppData/Local/rattler` folder and manually deleted the PATH references to pixi.
Installed v0.33.0, pixi now works again in the folders I have been having problems with.

I don't know what to tell you - sorry for the fuss, I don't know how it solved itself now. Been spending about 4 hours on this problem yesterday...
Thanks for all your constructive and fast help! Happy to see pixi grow and evolve!

**Comment by claudiushaag** [comment]
So I deleted both the User/XXX/.pixi folder, the User/XXX/AppData/Local/rattler folder and manually deleted the PATH references to pixi.
Installed v0.33.0, and noticed one big thing: This bug seems to only happen when using VSCode's builtin PowerShell Console.

It does not seem to be rooted in any extension. Will now roll back VSCode, this was never a problem...

**Comment by ruben-arts** [comment]
Ah that sounds really strange, would that conclude this as an extreem edge case?

**Comment by claudiushaag** [comment]
After downgrading VSCode to 1.93.1 , pixi worked in the internal terminal just fine.
I now upgraded back to 1.94.2 as a test, and now I'm also bug free. I'm currently not able to reproduce the behaviour.
So I guess yes, as of now, I would mark that as a extrem edge case. Am wondering if the order of installing this specific VSCode and pixi version changed something. But I also have not a lot to go on to open an issue with VSCode. Lets hope for the best ;)

Thanks for your fast and thorough help!
