### ISSUE TITLE
Add `generates` and `sources` directives to `tasks` for caching

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#231]
It would be nice to add a `generates` and `sources` arguments to a task so that we can skip it under certain circumstances.

**Comment by baszalmstra** [comment]
The idea here would be to sorta copy the behavior form: https://taskfile.dev/usage/#prevent-unnecessary-work

**Comment by baszalmstra** [comment]
We could also look into how turborepo works: https://turbo.build/repo/docs/core-concepts/caching . I think the main thing that project solves is caching based on input. Did you look at that @wolfv ?

**Comment by bollwyvl** [comment]
Was kindly directed here from #192 (whoops :blush: ). Hash-based rebuilding is indeed a huge productivity boost... _if_ a project actually invests in accurately understanding what files are being created, and how reproducibly. All the usual suspects show up (timestamps, line endings, etc).

If globs are supported (which are indeed super handy) there are some challenges depending on when they are calculated: I'm not sure if it's even possible to calculate if two globs would logically intersect if the file in question doesn't exist yet.

**Comment by jtpio** [comment]
This would be indeed be super useful :+1: 

> We could also look into how turborepo works: https://turbo.build/repo/docs/core-concepts/caching . I think the main thing that project solves is caching based on input. Did you look at that @wolfv ?

For reference there is also `nx` which is very similar to `turbo`: https://nx.dev/core-features/cache-task-results#finetune-caching-with-inputs-and-outputs

Both `nx` and `turbo` use the `inputs` / `outputs` terminology. Maybe worth considering as an alternative to `generates` and `sources`? So it's more familiar to folks coming from these tools.

**Comment by wolfv** [comment]
Thanks for the comment @jtpio – indeed @baszalmstra also mentioned turborepo before but I haven't had a chance to look into it.

Inputs & outputs would also make a lot of sense!

**Comment by jtpio** [comment]
Yes that sounds interesting. Maybe turborepo has some internal crates that could be reused in pixi directly.

**Comment by bollwyvl** [comment]
Naming is of course hard, especially given this space and the sheer number of things people will inevitably use it for, and even different kinds of things (e.g. `taskfile`'s `status`/ `doit`'s `uptodate`).

Again, due to "what people will use it for": I would _not_ emulate the mentioned behavior of (remotely) caching the _actual files_ created by a task, at least not by default... as soon as one gets out of relatively tame text-based world, these techniques can get _entirely_ out of control. Having a chain of cheap file hashes, stored in a single file, would provide _enormous_ local value, as the basis for _thoughful_ parallelism, CI caching, etc.

But yeah, the lack of this feature is still keeping me from investigating/advocating pixi for serious work.

**Comment by wolfv** [comment]
You are missing out @bollwyvl (even outside of this feature pixi has some pretty cool things to offer) :)

**Comment by bollwyvl** [comment]
> missing out

I'm sure I am, but as long as it's "just" `micromamba`-but-in-`rust`, there's little incentive _to me_ to replace just that one piece and have to learn a new (un-schema'd) TOML, CLI, and a whole new separate set of quirks.

If, however, I could write a single `pixi.toml`, and write `CONTRIBUTING.md` and configure CI to be like:

```bash
git clone some-repo --recurse-submodules --shallow-submodules # downloads latest `/vendor/pixi/*/pixi.*`
cd some-repo
./bootstrap(.bat)     # just to get pixi on path
pixi run -j8 release  # runs install, build, lint, test, docs, check, audit, dist... in the correct order
pixi run -j8 release  # does _nothing_, because Everything Is Fine
```

I'd use it _all over the place_.

**Comment by wolfv** [comment]
For the most part `make` would do that already for you :)

And there are also automatic lockfiles - it's quite a different beast from micromamba :)

**Comment by bollwyvl** [comment]
> automatic lockfiles

Right, but I've got `conda-lock` which is _also_ well understood, and backwards compatible with any `$CONDA_EXE`.

> `make` would do that already for you

Sure, on Linux. But windows? Get outta town. And i don't like `\t`. 

The point is, such tools _always_ need fine-tuning around `conda`-related stuff.

In the above example, if i have two environments for `docs` and `test`, it's usually required to (incorrectly) make the `envs/test/conda-meta/history` a dependency of the (hand made) task that builds `envs/docs/conda-meta/history`, as, even today, running two `$CONDA_EXE create`s in parallel (for all `$CONDA_EXE` i've tried) _still_ causes cache lock issues 80% of the time that sometimes require nasty things to unbreak. Then each task needs a carefully-tuned `$CONDA_EXE run --prefix`, with explicit dependencies on the `conda-meta/history`.

`pixi` is uniquely positioned to _take that pain away entirely_, by understanding "this task runs in this env, which must exist and be up-to-date before you try to run it" _without_ having to have a deep understanding of lockfiles, makefiles, historyfiles, etc.
