### ISSUE TITLE
Show the version updates in `pixi global update`

### ISSUE THREAD

**Issue by Yura52** [prefix-dev/pixi#2345]
### Problem description

Is it possible to show the version updates after running the `pixi global update` command, just like it was in the old `pixi global upgrade-all` command? It was a very convenient way to keep track of the changes.

**Comment by nichmor** [comment]
hey! thanks for contributing this!

we are working on this PR https://github.com/prefix-dev/pixi/pull/2337 that will add version changes after update

**Comment by dhirschfeld** [comment]
I guess this isn't released yet?
```
❯ pixi global update
✔ Updated environment git-delta.
✔ Updated environment kubernetes-helm.
✔ Updated environment pixi-pack.
✔ Updated environment helix.
✔ Updated environment argocd-cli.
✔ Updated environment zoxide.
✔ Updated environment nodejs.
✔ Updated environment opentofu.
✔ Updated environment toolong.
✔ Updated environment fzf.
✔ Updated environment go-sqlcmd.
✔ Updated environment pgcli.
✔ Updated environment ripgrep.
✔ Updated environment gh.
✔ Updated environment podman.
✔ Updated environment bat.
✔ Updated environment terraform.
✔ Updated environment jq.
✔ Updated environment hyperfine.
✔ Updated environment harlequin.
✔ Updated environment databricks-cli.
✔ Updated environment ghostscript.
✔ Updated environment kubernetes-client.
✔ Updated environment awscli.
✔ Updated environment starship.
✔ Updated environment crane.
✔ Updated environment eza.
✔ Updated environment micromamba.
✔ Updated environment uv.
✔ Updated environment skopeo.
✔ Updated environment fd-find.
```

**Comment by dhirschfeld** [comment]
Easy enough to answer for myself:

![Image](https://github.com/user-attachments/assets/8258bf03-5530-401e-ae95-3fd63f269473)


I shall await the next release...

**Comment by Hofer-Julian** [comment]
> I guess this isn't released yet?
> 
> ```
> ❯ pixi global update
> ✔ Updated environment git-delta.
> ✔ Updated environment kubernetes-helm.
> ✔ Updated environment pixi-pack.
> ✔ Updated environment helix.
> ✔ Updated environment argocd-cli.
> ✔ Updated environment zoxide.
> ✔ Updated environment nodejs.
> ✔ Updated environment opentofu.
> ✔ Updated environment toolong.
> ✔ Updated environment fzf.
> ✔ Updated environment go-sqlcmd.
> ✔ Updated environment pgcli.
> ✔ Updated environment ripgrep.
> ✔ Updated environment gh.
> ✔ Updated environment podman.
> ✔ Updated environment bat.
> ✔ Updated environment terraform.
> ✔ Updated environment jq.
> ✔ Updated environment hyperfine.
> ✔ Updated environment harlequin.
> ✔ Updated environment databricks-cli.
> ✔ Updated environment ghostscript.
> ✔ Updated environment kubernetes-client.
> ✔ Updated environment awscli.
> ✔ Updated environment starship.
> ✔ Updated environment crane.
> ✔ Updated environment eza.
> ✔ Updated environment micromamba.
> ✔ Updated environment uv.
> ✔ Updated environment skopeo.
> ✔ Updated environment fd-find.
> ```

Indeed, this will be part of the next release

**Comment by matthewfeickert** [comment]
I was about to open an issue for this, so I'm glad to see that this is being worked on. 😄
