### ISSUE TITLE
Add `--prepend` option for `pixi project channel add`

### ISSUE THREAD

**Issue by scottamain** [prefix-dev/pixi#2349]
### Problem description

Using `pixi project channel add` adds the given channel name to the end of the project `channels` list, making it the [lowest priority channel](https://pixi.sh/latest/advanced/channel_priority/#channel-priority). That is, `pixi project channel add pytorch` gives me this:

```
[project]
channels = ["conda-forge", "pytorch"]
```

In some cases, it's necessary to make the new channel the highest priority. Currently, the only way to control the channel priority is to manually edit the `pixi.toml` file. 

I think it would be fantastic if I could instead run:

```
pixi project channel add pytorch --prepend
```

And then get this:

```
[project]
channels = ["pytorch", "conda-forge"]
```

Thank you for your consideration! 🙏

**Comment by ruben-arts** [comment]
Great request! We're open to PR's this shouldn't be to hard!

**Comment by ruben-arts** [comment]
@mrswastik-robot ofcourse!

**Comment by scottamain** [comment]
Hmm... Could you instead make the prepend the default behavior (and add an `--append` option)?

I find it hard to imagine that most users use `pixi project channel add` only "just in case" the existing channels don't have a package.
