### ISSUE TITLE
Has plan supporting package over 100M upload to prefix?

### ISSUE THREAD

**Issue by hantmac** [prefix-dev/pixi#235]
Hi team, I  have a conda package and wanna to upload to prefix, but the size of it over 100M so I want to know we have any plan to support package that over 100M? BTW, the conda official support package within 1GB limit 🤔.

![4f57f69a-4942-4039-b614-feac7608e295](https://github.com/prefix-dev/pixi/assets/7600925/9880a449-f0ef-49af-88f1-83037bd7acfa)

**Comment by ruben-arts** [comment]
We just updated the website and upgraded the limit to 1GB so you should be able to continue testing:
![image](https://github.com/prefix-dev/pixi/assets/12893423/7cd30053-1462-4706-9e5f-8ee18db790a7)
