### ISSUE TITLE
pixi global exposed doesn't work with nested paths

### ISSUE THREAD

**Issue by bahugo** [prefix-dev/pixi#2350]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```batch
pixi global install dotnet  --expose "dotnet=dotnet"
```
```batch
pixi global install dotnet  --expose "dotnet=dotnet/dotnet"
```

### Issue description

Dotnet installs its executable in a nested directory
```
%USERPROFILE%\.pixi\envs\dotnet\dotnet\dotnet.exe
```
When i run `pixi global install dotnet` pixi can't find the executable.
I tried this workaround `pixi global install dotnet  --expose "dotnet=dotnet/dotnet"`
But it fails too : 
```
  × Couldn't install packages. Reverting also failed.
  ├─▶ Failed to add executables for environment: dotnet
  ╰─▶ Couldn't find executable dotnet in C:\Users\bahugo\.pixi\envs\dotnet, found these executables: []
```

### Expected behavior

It would be perfect if pixi search for executable recursively, or at least if we could specify a nested path.

**Comment by Hofer-Julian** [comment]
Specifying a nested path sounds good to me.

I am thinking of the following behavior:

- without a path separator in the string -> search for executable in the typical directories with all possible file extensions

```
pixi global install python=3.9 --expose=python3.9=python
```

- with path separator -> we expect the relative path to the env root. The extension would have to be mentioned in that case 

```
pixi global install dotnet  --expose "dotnet=lib\dotnet\dotnet.exe"
```

**Comment by bahugo** [comment]
Thank you for your answer, unfortunately I tried before but it fails too.
```
pixi global install dotnet  --expose "dotnet=dotnet\dotnet.exe"
```
returns :
```
× Couldn't install packages. Reverting also failed.
  ├─▶ Failed to add executables for environment: dotnet
  ╰─▶ Couldn't find executable dotnet in C:\Users\bahugo\.pixi\envs\dotnet, found these executables: []
```
dotnet executable is not in lib directory, it's located here :
![Image](https://github.com/user-attachments/assets/fd539bae-d199-4954-8dee-e06bde0d0170)

**Comment by Hofer-Julian** [comment]
Yes @bahugo, I was outlining a possible implementation. Sorry if that wasn't clear.

**Comment by Hofer-Julian** [comment]
@ruben-arts suggested to never specify the file extension, even for nested paths.

**Comment by bahugo** [comment]
@Hofer-Julian, my bad, I read to fast...
It sounds great to me.
