### ISSUE TITLE
how to install multiple different versions globally like pyenv?

### ISSUE THREAD

**Issue by gatspy** [prefix-dev/pixi#2376]
Now, when installing different versions globally, we need to specify aliases using `expose`. So, is there a command that allows us to specify which globally activated environment we want to use?

```bash
pixi global install python # python=3.13.0
pixi global install python=3.12.0 -e python312 ### error: Couldn't install python312, Exposed name idle already exists
```
Is there a way to switch between two different environments and use different versions of programs? For example, I want to use `Python` version 3.13 globally in the default environment, and switch to `Python` version 3.12 globally when I'm in the python312 environment.

**Comment by wolfv** [comment]
You can expose the executables under a different name (e.g. python@3.12).

You can do that by editing the toml file or with a CLI command :)

**Comment by gatspy** [comment]
> You can expose the executables under a different name (e.g. python@3.12).
> 
> You can do that by editing the toml file or with a CLI command :)

@wolfv thanks, this way is okay too, it's just that there'll be a lot of commands with different aliases.

**Comment by wolfv** [comment]
@gatspy you can also choose to _not_ expose a given executable, and then e.g. `idle` won't be exposed globally :)
