### ISSUE TITLE
is Let's get started docs out of date?

### ISSUE THREAD

**Issue by raybellwaves** [prefix-dev/pixi#2385]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell

```

### Issue description

Trying to use pixi for my project and looking at https://pixi.sh/dev/tutorials/python/#lets-get-started and I see `[build-system]` where as on my end I see

```
❯ pixi install
  × failed to parse project manifest
    ╭─[pixi.toml:52:2]
 51 │
 52 │ [build-system]
    ·  ──────┬─────
    ·        ╰── unknown field `build-system`, expected one of `project`, `system-requirements`, `target`, `dependencies`, `host-dependencies`, `build-dependencies`, `pypi-dependencies`, `activation`, `tasks`, `feature`, `environments`, `pypi-options`, `tool`, `$schema`
 53 │ requires = ["setuptools", "setuptools-scm"]
    ╰────

  × failed to parse project manifest
    ╭─[pixi.toml:52:2]
 51 │
 52 │ [build-system]
    ·  ──────┬─────
    ·        ╰── unknown field `build-system`, expected one of `project`, `system-requirements`, `target`, `dependencies`, `host-dependencies`, `build-dependencies`, `pypi-dependencies`, `activation`, `tasks`, `feature`, `environments`, `pypi-options`, `tool`, `$schema`
 53 │ requires = ["setuptools", "setuptools-scm"]
```

### Expected behavior

not sure what to use for build-system

**Comment by raybellwaves** [comment]
I may need to modify and move stuff my pixi.toml to pyproject.toml. I'll close this once I've got it

**Comment by ruben-arts** [comment]
Yeah the example uses the `--format pyproject` to initialize the project.
