### ISSUE TITLE
pixi project version doesn't reset minor and patch version numbers

### ISSUE THREAD

**Issue by chaumage** [prefix-dev/pixi#2407]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Just run `pixi project version minor` or `major` on any project.

### Issue description

When running `pixi project version minor` or `major`, patch and minor version numbers are not reset to zero:

```shell
>pixi project version minor
Updated project version from '0.3.5' to '0.4.5'.
```

### Expected behavior

Reset patch (and minor) version numbers to zero:

```shell
>pixi project version minor
Updated project version from '0.3.5' to '0.4.0'.
```

**Comment by ruben-arts** [comment]
Thanks for the report! We're open to pull requests!

**Comment by ruben-arts** [comment]
> hey @ruben-arts , can I try this one?

Yes please!
