### ISSUE TITLE
Auth error with Google Artifact Registry on v0.35

### ISSUE THREAD

**Issue by clement-chaneching** [prefix-dev/pixi#2431]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Update to pixi v0.35 and cannot run pixi install with a private google artifact registry:

```
[pypi-options]
extra-index-urls = ["https://oauth2accesstoken@artifact_registry/simple"]
```
Same for my GCS conda registry:
`channels = ["conda-forge", "gcs://private-registry"]
`

### Issue description

It throws the following error:
```
pixi install
  × default: error installing/updating PyPI dependencies
  ├─▶ Failed to read `--find-links` URL: https://oauth2accesstoken@artifact registry
  ├─▶ Failed to fetch: `https:/artifact registry
  ╰─▶ HTTP status client error (404 Not Found) for url (https:/artifact registry)

```
With conda:
```
ERROR error=HTTP status client error (401 Unauthorized) for url (https://storage.googleapis.com/private-registry/linux-64/repodata.json)
  × HTTP status client error (401 Unauthorized) for url (https://storage.googleapis.com/private-registry/linux-64/repodata.json)

```

### Expected behavior

Used to work with pixi < 0.35

**Comment by ruben-arts** [comment]
Hi @clement-chaneching, thanks for sharing. We're working on fixes for find links: https://github.com/prefix-dev/pixi/pull/2417

**Comment by RaphaelMelanconAtBentley** [comment]
Having the same issue with Azure Artifacts. Works on 0.34.0, but not on 0.35.0...

**Comment by clement-chaneching** [comment]
Thanks for the quick fix!
I now have a different GCP auth error on version >0.35
Pixi cannot use my GCP credentials to authenticate to my private conda registry, while it used to work on v0.34.

```
ERROR resolve_conda{group=prod platform=linux-64}: rattler_repodata_gateway::fetch: error=HTTP status client error (401 Unauthorized) for url (https://storage.googleapis.com/blunomy-conda-registry/linux-64/repodata.json)
ERROR resolve_conda{group=prod platform=linux-64}: rattler_repodata_gateway::gateway: error=HTTP status client error (401 Unauthorized) for url (https://storage.googleapis.com/blunomy-conda-registry/linux-64/repodata.json)
  × HTTP status client error (401 Unauthorized) for url (https://storage.googleapis.com/blunomy-conda-registry/linux-64/repodata.json)
```

**Comment by wolfv** [comment]
@clement-chaneching fix incoming: https://github.com/conda/rattler/pull/966 :)
