### ISSUE TITLE
Can't activate pixi on a read-only env

### ISSUE THREAD

**Issue by jvenant** [prefix-dev/pixi#2450]
### Problem description

Hi,

`shell` and `shell-hook` both run `update_prefix` with `no_install` set to false
this result in the execution of `LockFileDerivedData.prefix` which itself systematically write a `pixi` file in `conda-meta` folder

From what I saw, it's the only thing that prevent pixi from running from a read-only environment.
Being able to activate a ready-only env could be convenient for performances, security, idempotency and immutability.

### Possible solutions

Would it be a good idea to
- Add some kind a parameters that would disable the pixi file update (parametrize the no_install) ? 
- Or have a smarter pixi file update that would only update the file if it is really required ?

**Comment by ruben-arts** [comment]
Thanks for the report. I think not writing the file if it can't should be fine.

**Comment by jvenant** [comment]
Ok,
I can try to do a PR for this.
2 questions :
* Should we ignore all errors when creating the folder or writing the file ?
* Should we log something  in case of failure and at what level ?
