### ISSUE TITLE
Python `pixi init` example in docs may need update

### ISSUE THREAD

**Issue by LiamConnors** [prefix-dev/pixi#2451]
I was trying out the guide at https://pixi.sh/latest/tutorials/python/#lets-get-started
and noted that the step to "add the Python project to the tree" doesn't seem to be relevant when I run 

```
pixi init pixi-py --format pyproject
```

It looks like `init` command creates a "src layout" automatically now (perhaps as a result of this https://github.com/prefix-dev/pixi/pull/1947?) 

So it looks like the guide should just present the structure that is generated after running the `init` command

```
├── src
│   └── pixi_py
│       └── __init__.py
└── pyproject.toml
```

And then maybe note that `init` generates src-layout, but flat layout is also supported. 

If I've understood this correctly, I'd be happy to open a PR to make the relevant change.

**Comment by olivier-lacroix** [comment]
Yes, you are correct in your understanding. PR welcome 💯 !
