### ISSUE TITLE
Pixi trampolines exceed hard link limit on Amazon EFS

### ISSUE THREAD

**Issue by danielnachun** [prefix-dev/pixi#2462]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi global install nvim

```
When a sufficient number of global environments are already installed, installations off additional global environments will fail with this error:
```
  x Too many links (os error 31)
```

### Issue description

The newly introduced trampolines in `pixi 0.35` have led to a failure on our Amazon EFS system because too many hard links are created.  EFS unfortunately has a hard limit of 177 hard links to one file, which is easily reached with only a few global environments.  We should have an option to disable hardlinking of trampolines so that they can be either soft linked or copied.

### Expected behavior

The expected behavior is for the global environment installation to work without errors.

**Comment by danielnachun** [comment]
> > EFS unfortunately has a hard limit of 177 hard links to one file, which is easily reached with only a few global environments.
> 
> I am not sure I understand. If it's about the same file I would expect that you need about 100 environments to reach that limit.

I am also a bit puzzled by this - this limit is begin reached with only a couple of environments.  I'm also puzzled by why the trampoline has more than 1 hard link at all.  From what I (perhaps incorrectly) understand, the hard link is just to `.pixi/bin/trampoline_configuration` and I don't know why there would be more than one per trampoline?

**Comment by Hofer-Julian** [comment]
There is one hard-link to the trampoline per exposed executable

**Comment by danielnachun** [comment]
Ah, I misunderstood then.  I guess you would hit the limit with 177 exposed *executables* (since some environments have more than 1).  That would explain why I was getting such weird random failures - it depends on the number of exposed executables.

Is there any insight on whether copying or soft linking is preferred here?  I don't think soft-linking has the same limit on EFS but I'm not 100% sure.  Of course the downside to copying is more disk usage.

Also for the sake of future knowledge, the specific reason why EFS has this seemingly low hard link limit (as do equivalent systems for Google Cloud and Microsoft Azure) is because these are not real POSIX file systems but instead try to "emulate" them.  But I guess there are performance limitations for having many objects with the same inode that require

**Comment by baszalmstra** [comment]
I think it makes sense to have fallbacks in place. First try hard-linking, then soft-linking followed by copying.

**Comment by danielnachun** [comment]
> I think it makes sense to have fallbacks in place. First try hard-linking, then soft-linking followed by copying.

That makes sense.  

How will it handle the possibility that initially hard-linking will work initially (in this case for the first 177 executables), and then start falling back once hard linking starts failing?  Should all the existing hard-links be converted to soft-links/copies?  And should the unavailability of hard-linking (and perhaps even soft-linking) be stored somewhere so `pixi` knows not to try unsuccessful methods anymore? 

Sorry for all the questions, I just wanted to think through these scenarios since this is essentially what is happening now without the ability to gracefully fall back.

**Comment by wolfv** [comment]
@baszalmstra for soft-linking we need to check that the "self-executable" name is the right one :) otherwise the trampoline isn't going to work.

I think hard-linking or copying doesn't matter. We can treat them the same. The idea of the hard-link is just to save some disk-space (but apparently there are downsides!).

**Comment by Hofer-Julian** [comment]
@danielnachun I've added the following PR in an attempt to fix this.

Could you please try if the following solves your problem:

```
git clone --branch fix/trampoline-hard-link https://github.com/Hofer-Julian/pixi.git
cd pixi
pixi run install-as pixid
```

Now attempt the same operations using `pixid` instead of `pixi`

**Comment by danielnachun** [comment]
I followed your instructions and it looks like the fix in that PR resolved the issue!  I can now see executables in `~/.pixi/bin` that are clearly copies of the trampoline, as well as some of the first executables that could still hard link before hitting the limit.   Importantly there were no errors either.

Thank you so much for the quick and helpful response.  Just another reason why we love pixi so much!

**Comment by Hofer-Julian** [comment]
That's awesome, thanks for testing and the kind words ❤️

The release is already out, so this should be a problem of the past
