### ISSUE TITLE
Allow making `pixi global update` less verbous

### ISSUE THREAD

**Issue by Yura52** [prefix-dev/pixi#2491]
### Problem description

Recently, `pixi global update` started printing the information about version changes, which is great! However, it also prints information about executables from the environments that did _not_ change. For example, on one machine, I have only `python` and `git` as the global environments, and this is how the output looks like:

```
$ pixi global update
✔ Environment python was already up-to-date.
✔ Updated executables of environment python:
   - idle3
   - idle3.13
   - pydoc
   - pydoc3
   - pydoc3.13
   - python
   - python3
   - python3-config
   - python3.1
   - python3.13
   - python3.13-config
✔ Environment git was already up-to-date.
✔ Updated executables of environment git:
   - git
   - git-credential-osxkeychain
   - git-cvsserver
   - git-receive-pack
   - git-shell
   - git-upload-archive
   - git-upload-pack
   - gitk
   - scalar
```

Generally, it is confusing why the executables are reported to be updated, while the environments are not. If I am missing something, than perhaps it is possible to introduce a flag for hiding the "Updated executables of environment" part of the output? Currently, on machines with many global environments, the verbosity of the output makes it harder to notice actual changes.

**Comment by saaketp** [comment]
> Generally, it is confusing why the executables are reported to be updated, while the environments are not.

It is more obvious when running `pixi global list` with verbosity turned up.
On my system I get:

```
$ pixi global list -vvvv 2>&1 | grep sync
DEBUG pixi::global::project: Environment uv binaries not in sync: to_remove: [], to_add: {ExposedName("uv"), ExposedName("uvx")}
DEBUG pixi::global::project: Environment fd-find binaries not in sync: to_remove: [], to_add: {ExposedName("fd")}
DEBUG pixi::global::project: Environment ffmpeg binaries not in sync: to_remove: [], to_add: {ExposedName("ffmpeg"), ExposedName("ffprobe")}
DEBUG pixi::global::project: Environment fzf binaries not in sync: to_remove: [], to_add: {ExposedName("fzf")}
DEBUG pixi::global::project: Environment ripgrep binaries not in sync: to_remove: [], to_add: {ExposedName("rg")}
DEBUG pixi::global::project: Environment spyder binaries not in sync: to_remove: [], to_add: {ExposedName("spyder")}
DEBUG pixi::global::project: Environment python binaries not in sync: to_remove: [], to_add: {ExposedName("py313")}
DEBUG pixi::global::project: Environment py39 binaries not in sync: to_remove: [], to_add: {ExposedName("py39")}
 WARN pixi::cli::global::list: The environments are not in sync with the manifest, to sync run
        pixi global sync
```

Running ``pixi global sync` doesn't fix this.
It considers all the exposed names always not in sync with the manifest, and part of the `to_add` list.

I think this is a bug in the recent versions, I remember older versions didn't do this.

**Comment by Hofer-Julian** [comment]
Our team members using Linux cannot reproduce it, but macOS and Windows users can.

@nichmor will look into this

**Comment by Yura52** [comment]
I have experienced the issue both on macOS and Linux. For example, I have just run `pixi global update` with Pixi v0.36.0 on Ubuntu 18.04.6 and observed the issue.

Perhaps, this is somehow related to the transition from the old `pixi global` to the new one. And, for example, only users who used `pixi global` before the transition have this issue. This is only a hypothesis.
