### ISSUE TITLE
Bug terminating URL in BETA notice

### ISSUE THREAD

**Issue by corneliusroemer** [prefix-dev/pixi#2557]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ pixi add deepdiff
 WARN pixi::project::manifest: BETA feature `[pypi-dependencies]` enabled!

Please report any and all issues here:

	https://github.com/prefix-dev/pixi.
```

### Issue description

The URL ends in full stop - that makes sense for ending a sentence, but it's not great for copy/pasting or clicking.

In fact, you might want to make the URL: https://github.com/prefix-dev/pixi/issues/new

### Expected behavior

URL doesn't end in `.`

**Comment by olivier-lacroix** [comment]
@corneliusroemer what pixi version are you using? I believe this BETA message was removed from the code base a couple of months ago.

**Comment by corneliusroemer** [comment]
Oh woops, I'm on a stone age version :D

```
❯ pixi --version
pixi 0.15.1
```

**Comment by corneliusroemer** [comment]
Maybe you could inform users that there's a newer version available, like
npm does for example :)

**Comment by olivier-lacroix** [comment]
Yes, that could be a nice enhancement.

**Comment by corneliusroemer** [comment]
Made an issue for that!
