### ISSUE TITLE
`pixi add` and `pixi upgrade` uses wrong pinning strategy in some cases

### ISSUE THREAD

**Issue by seowalex** [prefix-dev/pixi#2574]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init
pixi add pyodbc python sqlalchemy
```

Output:
```
Added pyodbc >=5.2.0,<6
Added python >=3.12.7, <3.13
Added sqlalchemy>=2.0.36,<2.1
```

### Issue description

When adding/upgrading packages, encountering any packages in `NON_SEMVER_PACKAGES` causes the rest of the packages to use the minor pinning strategy.

I believe this was introduced in #2310 as the `pinning_strategy` is set for future iterations of the loop when any packages in `NON_SEMVER_PACKAGES` are encountered. Notably, this only happens when the pinning strategy is unset, so one mitigation is to set `pinning-strategy: "semver"` in the Pixi configuration file (although this has the side-effect of forcing `NON_SEMVER_PACKAGES` to be pinned to their major version).

### Expected behavior

Expected output:
```
Added pyodbc >=5.2.0,<6
Added python >=3.12.7, <3.13
Added sqlalchemy>=2.0.36,<3
```

**Comment by seowalex** [comment]
On a side note, trying to debug this has made me realise `pixi add`/`pixi upgrade` does not sort dependencies alphabetically, which I think it should?

**Comment by ruben-arts** [comment]
Thanks for the report, nice find. Definitely a bug.

> On a side note, trying to debug this has made me realise pixi add/pixi upgrade does not sort dependencies alphabetically, which I think it should?

We touch the file as little as we can, users often sort them in their own order with some comments. e.g.:
```toml
[dependencies]
# Needed for feature x
python  = "1.2.3"
matplotlib = "2.3.4"

# Used in xyz
pytorch = "*"
```
