### ISSUE TITLE
Error launching 'hello.py': Permission denied (os error 13)

### ISSUE THREAD

**Issue by laguill** [prefix-dev/pixi#2581]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Hello, 
I am on xubuntu with pixi 0.38.0

I just installed pixi follwing [instructions](https://pixi.sh/latest/) and then create a project

```shell
# create project folder
mkdir ~/Documents/Project/P2
cd !$
pixi init --format pyproject

# add dependencies
pixi add jupyterlab ipykernel mypy ruff pixi-kernel pandas
```

### Issue description

```shell
pixi run hello.py
```

Here is the output 
>Error launching 'hello.py': Permission denied (os error 13)

### Expected behavior

Also it seams that` pixi init` is not creating a virtual venv
Did I missed some installation steps ?

**Comment by synapticarbors** [comment]
Just to clarify:
1. From your description, It looks like you made the directory, but didn't `cd` into it before calling `pixi init`. You might want to make sure that the manifest (`pyproject.toml`) is where you expect it to be. You can run `pixi info` to show all of the relevant paths.
2. Where is `hello.py` located and do you have the correct permissions on it?

`pixi run` should install all of the dependencies if they haven't already been downloaded, and then launch the command in the proper env. Additionally, you probably want `pixi run python hello.py`.

**Comment by laguill** [comment]
Sorry I forgot to write the `cd !$`
Now edited

I was tinkering with uv in the same folder this might explain the permissions issues

**Comment by laguill** [comment]
I was confused because I am using oh-my-posh in my bash shell
When I am running `pixi shell` the prompt is hanging without showing anything

No issue if I am not using it

**Comment by laguill** [comment]
Issue solved it was an error with oh-my-posh
https://github.com/JanDeDobbeleer/oh-my-posh/issues/5955
