### ISSUE TITLE
`pixi exec $pkg.conda`

### ISSUE THREAD

**Issue by jamesfricker** [prefix-dev/pixi#2585]
### Problem description

My team needs to deploy and run packages in an environment without internet access. 

Wondering if this operation is / could be possible? `pixi exec $pkg.conda`? This would allow us to build and ship the built package, and then run with pixi exec.

**Comment by jamesfricker** [comment]
alternavitely, we could `pixi-pack` only the built .conda file and unpack + run the packed files? Not sure if this is possible either

**Comment by baszalmstra** [comment]
We can make that work but I wonder what would happen if the package has any dependencies.

**Comment by jamesfricker** [comment]
yea sounds like not really a necessary idea
