### ISSUE TITLE
`pixi build` doesn't include dependencies and incorrect version

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#2598]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

https://github.com/Quantco/polarify/pull/81

### Issue description

i'm currently playing around with `pixi build` and found that the package generated with `pixi build` doesn't include `polars >=0.14.24,<0.21` in its dependencies, even though it's specified in pyproject.toml as well as pixi.toml.

Currently, `index.json` looks like this:

```json
{
  "build": "pyhbf21a9e_0",
  "build_number": 0,
  "depends": [
    "python"
  ],
  "name": "polarify",
  "noarch": "python",
  "subdir": "noarch",
  "timestamp": 1732885543257,
  "version": "0.1.0"
}
```

### Expected behavior

I would expect it to look more like this:

```json
{
  "build": "pyhbf21a9e_0",
  "build_number": 0,
  "depends": [
    "python >=3.9", // from pyproject.toml requires-python or pixi.toml dependencies?
    "polars >=0.14.24,<0.21" // from pyproject.toml or pixi.toml?
  ],
  "name": "polarify",
  "noarch": "python",
  "subdir": "noarch",
  "timestamp": 1732885543257,
  "version": "0.2.0" // <- should be 0.2.0, from pixi.toml's package.version
}
```

**Comment by pavelzw** [comment]
Also, the package doesn't include a recipe file. Is this intended?

**Comment by baszalmstra** [comment]
Did you specify the dependencies with `[run-dependencies]`? 

`[dependencies]` is used by the workspace. `[run-dependencies]` specifies the run dependencies of the package. If you then include

```toml
[dependencies]
polarify = { path = "." } 

[run-dependencies]
python = "*"
polars = "*"
```

It should work. Note that this doesnt work with features. We are looking into using a form of variants to make that work properly.

**Comment by pavelzw** [comment]
makes sense, thanks!

`[run-dependencies]` is currently not in the schema yet; we should add it there

**Comment by baszalmstra** [comment]
> Also, the package doesn't include a recipe file. Is this intended?

It should contain a finalized recipe file eventually but not a `recipe.yaml` file because we don't explicitly create that.
