### ISSUE TITLE
ML stack example

### ISSUE THREAD

**Issue by niemiaszek** [prefix-dev/pixi#261]
I was blown away by ROS2 example, insane stuff! I'm wondering when we can expect some examples with ML frameworks. I see that one example is on the way #206. It would be really interesting to see some multi-framework examples (like pytorch and tensorflow in one project), or even full support for keras-core (torch+tf2+jax).

Side question: is there any way to convert conda `environment.yml` to `pixi.toml` yet?

**Comment by niemiaszek** [comment]
Ah, I found that support of environment.yml is on way in #131

**Comment by ruben-arts** [comment]
That is a very good idea! Do you have or known any projects that you think are interesting that use those libraries?

**Comment by niemiaszek** [comment]
[`keras-core`](https://keras.io/keras_core/announcement/) is quite interesting project, as it takes well known Keras again to multi-backend usage (for last few years Keras was only used as high level Tensorflow API). In short, you can use models built with Keras layers with one of 3 backends - PyTorch, Tensorflow or Jax.

Keras Core is also very fresh project, so I haven't used it myself yet, but it looks quite promising and also faces the issue of setting up those 3 highly-dependent frameworks. I see everything is installed with PIP ATM in requirements, however those libraries have conda packages.

**Comment by ruben-arts** [comment]
The keras-core package or its dependencies is not all available yet, and it seams a little hard to port as of right now. Do have other options in mind?

**Comment by ruben-arts** [comment]
Closing this for now. We would love to see a ML example! But this is not really an issue.
