### ISSUE TITLE
Issue with examples on linux

### ISSUE THREAD

**Issue by mikeaadd** [prefix-dev/pixi#263]
Hi,

Just wanted to say I love what you guys have been doing here. I've been following this project for a little bit and have even used pixi for a small personal project. The workflow was marvelous :).

This week I decided to see if how it would work on linux. Trying the examples I run into the following error...

```
 ~/pixi/examples/turtlesim
21:06 $ pixi run start
  × The current system has a mismatching virtual package. The project requires '__linux' to be at least version '5.10' but the system has version '3.10.0'
  ```

I confirmed the linux version. 

```
21:06 $ uname -r
3.10.0-1062.4.2.el7.x86_64
```

This still leaves me a little bit of a loss. I don't see any explicit mention of a minimum linux version in the lock/toml file. What is the recommended workflow to resolve this?

**Comment by ruben-arts** [comment]
Thankyou, this is awesome to hear!

To fix the issue you need to add:
```
[system-requirements]
linux= "3.10"
```

The default is a lot higher. This is still up for a debate. Why are you using such a old Linux kernel?

**Comment by mikeaadd** [comment]
I was testing on a on premise node that is available to me. The cluster is not managed by me or my team so I am unsure of the exact reasoning, but we could probably do a better job of keeping things up to date.

That worked though. Thank you!

**Comment by ruben-arts** [comment]
Good that it worked. Note that it might not always work as packages can depend on higher version of linux. 

Upvote this reaction to see how much people walk into this problem :+1:

**Comment by jelber2** [comment]
Maybe, you could add a help message to see this issue on github or to try 

```bash
[system-requirements]
linux= "Your version of linux"  ex: "5.4.0"
```

**Comment by ruben-arts** [comment]
@jelber2 we've noted this as an issue we still have to improve the workflow for. It is tracked in https://github.com/prefix-dev/pixi/issues/815
