### ISSUE TITLE
pixi fails to find `opik` using pypi

### ISSUE THREAD

**Issue by chsafouane** [prefix-dev/pixi#2663]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I'm using this version of pixi: `pixi 0.39.0`. I'm trying to install [`opik`](https://pypi.org/project/opik/) from pypi using the following command

```shell
pixi add --pypi opik
```

I get the following output, which I don't understand because it shouldn't be talking about conda at all:

![Image](https://github.com/user-attachments/assets/0dcf65d3-d972-42bb-b4c7-bd65bb178acc)

Did I misunderstand something or is it an unwanted behaviour ?

Thanks

### Issue description

Seems to be looking for `opik` on conda-forge and not on pypi and doesn't find it 

### Expected behavior

Find `opik` on pypi and install it

**Comment by jjjermiah** [comment]
I can't seem to reproduce this error: 
```console
test-2663
➜ pixi init
✔ Created /tmp/test-2663/pixi.toml

test-2663
➜ pixi add python
✔ Added python >=3.13.1,<3.14

test-2663
➜ pixi add --pypi opik
✔ Added opik >=1.2.3, <2
Added these as pypi-dependencies.
```
can you share your manifest file or a reproducible one?

**Comment by chsafouane** [comment]
I fail to reproduce it as well 🥲 i think it was something with my terminal. Sorry
