### ISSUE TITLE
Reinstallation might skip the use of the package cache

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#2667]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

When installing a project with pypi dependencies the python build environments need to be installed using conda. I found that the installation might be slow because it doesn't always use the cache for all the packages that it needs. 

I could reproduce it on https://github.com/sklearn-compat/sklearn-compat. 

```
# Install once to fill the package cache, because by default it's not satisfied it will also install the build envs.
> pixi install
# Clean the environments to force a reinstallation
> pixi clean
# Change a single thing in the `pyproject.toml` to force a resolve of the pypi dependencies
> pixi project version set 1.2.3

# Test the solve again
> pixi install -v 
# This takes minutes on my machine because it starts downloading SOME packages which is non deterministic

```
### Expected behavior

Environment installations should always use the cache when it was already installed before.

**Comment by baszalmstra** [comment]
Fixed by https://github.com/conda/rattler/pull/977
