### ISSUE TITLE
Can pixis be used for web front end projects？

### ISSUE THREAD

**Issue by 2788** [prefix-dev/pixi#267]
If so, how to install packages from npm?

**Comment by wolfv** [comment]
Hi, you can definitely use `pixi` to install `nodejs` from conda-forge (that comes with npm). You can then run `npm` from pixi using `pixi run npm ...`. You can also directly install yarn from conda-forge (`yarn`).

https://prefix.dev/channels/conda-forge/packages/nodejs

https://prefix.dev/channels/conda-forge/packages/yarn

You can also globally install `nodejs / npm` with `pixi global install nodejs`.

We do not natively support the installation of npm packages.

**Comment by 2788** [comment]
Okay, thank you for your answer.
