### ISSUE TITLE
The Pixi install script doesn't point to pixi path location when chmoding.

### ISSUE THREAD

**Issue by mahesh-panchal** [prefix-dev/pixi#2670]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
curl -fsSL https://pixi.sh/install.sh | bash
```

### Issue description

output:
```
$ curl -fsSL https://pixi.sh/install.sh | bash
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16.3M  100 16.3M    0     0  22.6M      0 --:--:-- --:--:-- --:--:--  273M
chmod: cannot access '/home/gitpod/.pixi/bin/pixi': No such file or directory
```
The binary is found at `/home/gitpod/.pixi/bin/pixi-x86_64-unknown-linux-musl/pixi` instead.

### Expected behavior

The expected behaviour is that the pixi binary is unpacked into `.pixi/bin/`.

**Comment by wolfv** [comment]
Sorry! We've just pulled the release as we need to fix the layout of the `.tar.gz` files that are produced.

**Comment by ruben-arts** [comment]
It should be fixed now, please try again.

**Comment by mahesh-panchal** [comment]
The installation with 0.39.0 works fine. I guess 0.39.1 will be re-released at another point in time. 

Thank you for prompt responses and hard work.
