### ISSUE TITLE
Release 0.39.1 is broken

### ISSUE THREAD

**Issue by akhmerov** [prefix-dev/pixi#2671]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi self-update
✔ Pixi will be updated from 0.39.0 to 0.39.1
✔ Pixi archive downloaded.
✔ Pixi archive uncompressed.
  × No such file or directory (os error 2)
```
Similar error appears in a fresh install `curl -fsSL https://pixi.sh/install.sh | bash`
```shell
curl -fsSL https://pixi.sh/install.sh | bash
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16.3M  100 16.3M    0     0  9291k      0  0:00:01  0:00:01 --:--:-- 24.2M
chmod: cannot access '/root/.pixi/bin/pixi': No such file or directory
```

### Issue description

Pixi release 0.39.1 seems broken.

### Expected behavior

Not broken 🥲

**Comment by blmaier** [comment]
The issue is that the tarball has changed.
The [0.39.0 tarball](https://github.com/prefix-dev/pixi/releases/download/v0.39.0/pixi-x86_64-unknown-linux-musl.tar.gz) contains just `pixi`.
The [0.39.1 tarball](https://github.com/prefix-dev/pixi/releases/download/v0.39.1/pixi-x86_64-unknown-linux-musl.tar.gz) contains pixi in a subdirectory `pixi-x86_64-unknown-linux-musl/pixi`

**Comment by wolfv** [comment]
We're pulling the release. Sorry!

**Comment by akhmerov** [comment]
Thanks, fixed.
