### ISSUE TITLE
Pixi does not open on osx

### ISSUE THREAD

**Issue by s-sajid-ali** [prefix-dev/pixi#2675]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

N/A.

### Issue description

With a fresh pull of pixi via:
```
username@ITS-JQKQGQQMTX ~ % curl -fsSL https://pixi.sh/install.sh | bash
```

I get the following error:
```
Apple could not verify “pixi” is free of malware that may harm your Mac or compromise your privacy.
```
which results in:
```
zsh: killed     pixi

```

### Expected behavior

N/A.

**Comment by ruben-arts** [comment]
Thanks for the report, disabled the `v0.39.1` release for now. I hoped that repacking the binary would work but apparently it is not working with the signing. Will have to look into this properly tomorrow.

**Comment by s-sajid-ali** [comment]
Thanks!
