### ISSUE TITLE
pixi self-update ignores 0.39.1

### ISSUE THREAD

**Issue by blmaier** [prefix-dev/pixi#2676]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ pixi --version
pixi 0.39.0

$ pixi self-update
✔ pixi is already up-to-date (version 0.39.0)

$ pixi self-update --version 0.39.1
✔ Pixi will be updated from 0.39.0 to 0.39.1
✔ Pixi archive downloaded.
✔ Pixi archive uncompressed.
✔ Pixi has been updated to version 0.39.1.
```

### Issue description

Updating pixi using self-update doesn't work. Updating with the explicit version number does

### Expected behavior

`pixi self-update` updates to 0.39.1

**Comment by ruben-arts** [comment]
Thanks for the report, we're having issues with the created binaries. I'll add a warning to the release notes for now. We'll work on an actual fix tomorrow. 

Because of the issue, we made `v0.39.0` the "latest" release so you don't automatically pull in `v0.39.0` binaries.

**Comment by blmaier** [comment]
0.39.2 works now, thanks!
