### ISSUE TITLE
`pixi info` should write `tracing::error` instead `tracing::debug` on syntax errors of pixi config file

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#2720]
in https://github.com/prefix-dev/pixi/blob/f9bd6c9c0549e7faed71de47021be6c7ce792dc5/crates/pixi_config/src/lib.rs#L800, we only do `tracing::debug` on errors in the config. for relevant errors (file exists but can't be deserialized) we should do `tracing::error` instead IMO

otherwise you might silently fall into the issue that pixi doesn't find config files because it silently fails parsing

only `pixi info -vvv` gives you an indication what's happening
<img width="1303" alt="Image" src="https://github.com/user-attachments/assets/d9c60d1a-7c01-42dc-9e52-805f9f86db7d" />

**Comment by Hofer-Julian** [comment]
Closed via https://github.com/prefix-dev/pixi/pull/2739
