### ISSUE TITLE
pixi 0.39.2 has a regression with examples/cpp-sdl --- Invalid params: missing field `editable`

### ISSUE THREAD

**Issue by gigony** [prefix-dev/pixi#2721]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

On 0.39.2, I see the following error message.

```shell
git checkout v0.39.2
cd examples/cpp-sdl
pixi run start

✨ Pixi task (start): sdl_example
  × failed to communicate with the build backend (pixi-build-cmake)
  ├─▶ ErrorObject { code: InvalidParams, message: "Invalid params: missing
  │   field `editable`.", data: None }
  ╰─▶ ErrorObject { code: InvalidParams, message: "Invalid params: missing
      field `editable`.", data: None }
```
I don't see the message with 0.38.0 (and `v0.38.0` tag).

### Issue description

I see the following error message with sdl_example.

```
✨ Pixi task (start): sdl_example
  × failed to communicate with the build backend (pixi-build-cmake)
  ├─▶ ErrorObject { code: InvalidParams, message: "Invalid params: missing
  │   field `editable`.", data: None }
  ╰─▶ ErrorObject { code: InvalidParams, message: "Invalid params: missing
      field `editable`.", data: None }
```

### Expected behavior

The application is launched well.

**Comment by gpdaniels** [comment]
The regression is in the build-backend.

I had to add a version:
```toml
build-backend = { name = "pixi-build-cmake", version = "0.1.0dev20241209141153" }
```

**Comment by Hofer-Julian** [comment]
Thanks for the input, everyone.

pixi build is still in heavy development, and our examples are only guaranteed to work with current main.

We moved all `pixi build` examples to their own directory and restored the cpp-sdl example: https://github.com/prefix-dev/pixi/pull/2723
