### ISSUE TITLE
Use XDG_CACHE_HOME on macOS too

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#276]
It would be nice to set XDG_CACHE_HOME even if macOS officially doesn't support it.

**Comment by baszalmstra** [comment]
we basically use this crate: https://crates.io/crates/dirs

We could add the directory to a global configuration setting though. When we add some form of global config that is.

**Comment by ruben-arts** [comment]
Closing this for now as this would be a nice feature when we have a design for a global config.
