### ISSUE TITLE
Mismatching virtual package

### ISSUE THREAD

**Issue by amirhosseindavoody** [prefix-dev/pixi#282]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

In the cpp-sdl  example folder.
```shell
pixi run configure
```

### Issue description

I am running pixi in the linux environment suse12. I am running the pixi command in the example folders and all of them procude this error:

```
× The current system has a mismatching virtual package. The project requires '__linux' to be at least version '5.10' but the system has version '4.12.14'
```

### Expected behavior

Run the examples.

**Comment by ruben-arts** [comment]
You can fix by adding the following to the `pixi.toml`
```toml
[system-requirements]
linux = "4.12.14"
```
This issue occurs when your system is of lower spec then the default that we defined which was `5.10`.

**Comment by amirhosseindavoody** [comment]
This worked and solved the issue. Thanks.
