### ISSUE TITLE
pixi shell updates PATH in the middle, thus old PATH takes precedence

### ISSUE THREAD

**Issue by certik** [prefix-dev/pixi#284]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi shell
echo $PATH
```
It shows:
```
/Users/ondrej/.wasmer/bin:/Users/ondrej/bin:/private/tmp/pixi-hello-world/.pixi/env/bin:/Users/ondrej/.wasmer/bin:/Users/ondrej/.cargo/bin:/Users/ondrej/mambaforge/condabin:/Users/ondrej/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ondrej/.wasmer/globals/wapm_packages/.bin:/Users/ondrej/.wasmer/globals/wapm_packages/.bin
```

### Issue description

Above the pixi env path is inserted in the middle.

This means that the following fails:
```
$ which lpython
/Users/ondrej/bin/lpython
```
Even though there is an lpython installed using pixi:
```
$ .pixi/env/bin/lpython --version
LPython version: 0.19.0
Platform: macOS ARM
Default target: arm64-apple-darwin21.3.0
```

### Expected behavior

I would expect:
```
/private/tmp/pixi-hello-world/.pixi/env/bin:/Users/ondrej/.wasmer/bin:/Users/ondrej/bin:/Users/ondrej/.wasmer/bin:/Users/ondrej/.cargo/bin:/Users/ondrej/mambaforge/condabin:/Users/ondrej/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ondrej/.wasmer/globals/wapm_packages/.bin:/Users/ondrej/.wasmer/globals/wapm_packages/.bin
```

**Comment by certik** [comment]
This might be the same issue as https://github.com/prefix-dev/pixi/issues/246. I also use zsh and macOS.

**Comment by ruben-arts** [comment]
Hey @certik,

You are completely right, this issue is the same as #246. Because we restart your shell after the activation your profile will overwrite the path set by the activation. We're discussing how to fix this. 

I'll close this issue to avoid doubles, you can subscribe to #246 to get updated. 

Hope that explains it enough for now, sorry for the inconvenience!
