### ISSUE TITLE
Add the ability to install pip dependencies

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#29]
First version, install using `pip` command like micromamba does.

Add support for it in the `.toml`.

Added to the lock-file.

**Comment by flying-sheep** [comment]
As said in https://github.com/prefix-dev/pixi/issues/175#issuecomment-1685348098, conda/mamba’s approach of first-us-then-pip isn’t a sound one, so I hope the “for now” does a lot of heavy lifting and you plan to resolve dependencies together at some point.

I generally avoid conda/mamba unless absolutely necessary to avoid problems with this.

**Comment by tdejager** [comment]
Yes @flying-sheep, we are working on doing it one go using our rust libsolv implementation. It is a bit tricky, but will keep you updated!

**Comment by tdejager** [comment]
Closing this for: https://github.com/prefix-dev/pixi/issues/175 I see that you are also involved there @flying-sheep :)

**Comment by flying-sheep** [comment]
Yup, thanks! As long as one of the issues stays up, I’ll be notified once you got that far!
