### ISSUE TITLE
Spelling issue in pixi error response

### ISSUE THREAD

**Issue by tylere** [prefix-dev/pixi#290]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```bash
% pixi add titiler-core   
  × could not determine any available versions for titiler-core on osx-arm64. Either the package could not be
  │ found or version constraints on other dependencies result in a conflict.
  ╰─▶ Cannot solve the request because of: titiler-core cannot be installed because there are no viable
      options:
      |-- titiler-core 0.3.12 would require
          |-- rio-tiler >=2.1,<2.2, which cannot be installed because there are no viable options:
              |-- rio-tiler 2.1.0 | 2.1.4 | 2.1.4 would require
                  |-- rio-color, for which no candidates where found.
```

### Issue description

The error message has a spelling issue:

> for which no candidates **where** found

### Expected behavior

The message should be

> for which no candidates **were** found

**Comment by baszalmstra** [comment]
Thanks! I fixed this in https://github.com/mamba-org/rattler/pull/284, will be available with the next release!
