### ISSUE TITLE
Ability to Set Custom Trusted Certificate Chain

### ISSUE THREAD

**Issue by zicklag** [prefix-dev/pixi#291]
### Problem description

I'm behind an SSL Bump proxy that requires that all apps that use it either skip HTTPS certificate validation or trust the proxy certificate.

I would like a way to configure a custom trusted certificate. I think an appropriate way to do this could be with an environment variable, similar to Deno, which has a `DENO_CERT` environment variable.

**Comment by wolfv** [comment]
I wonder if it would be enough to use the 

```
reqwest::ClientBuilder::new().add_root_certificate(...) // <- where the root certificate comes from the env var
```

in teh `rattler_networking` crate. Do you want to give this a try, @zicklag?

**Comment by zicklag** [comment]
Sure, I'll try it out. I've done a few PRs to get proxy stuff working in different tools already. This one should be relatively easy. The Rust ecosystem is nicer for proxies than the JS one so far. :)

**Comment by wolfv** [comment]
Awesome!

**Comment by wolfv** [comment]
@baszalmstra is this fixed by #310 ?

**Comment by zicklag** [comment]
My proxy recently stopped requiring a custom certificate, but this would have fixed my previous issue, since I've added my custom cert to the system registry. I think this will solve most people's problems, so we could probably close this.

**Comment by wolfv** [comment]
Great!
