### ISSUE TITLE
Highlight the need to add autocompletion to get all pixi features

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#292]
### Problem description

In https://github.com/prefix-dev/pixi/issues/219 I discoverd that to get all pixi features (including the one not directly related to completion) you need to run the steps in https://github.com/prefix-dev/pixi#autocompletion, that from what I understand is kind of equivalent to conda/mamba's activation.

I guess I was not aware of this as currently in the README the autocompletion is under the "Uninstall" section, and I was not going down there when looking how to install pixi. So a possible solution is move the "Autocompletion" section closer to the "Install" one. Another possible solution, is to permit to add the autocompletion to the `.bashrc` directly in the installation script, especially given that the installation script already modifies `.bashrc` to modify the PATH.

**Comment by ruben-arts** [comment]
It is now directly below the install options: https://prefix.dev/docs/pixi/overview
