### ISSUE TITLE
how to handle the others command line tools in the env bin

### ISSUE THREAD

**Issue by ReimarBauer** [prefix-dev/pixi#304]
### Problem description

Hi there, 

before doing a pixi installation I have not thought about the big amount of commandline tools of all the other libs adding to my package. Our project has 421 in the bin dir. A few of them we do use when we are in an env. 

It sounds like we should have a description which of them we need. I am not sure if "entry_points" is the best place, because they don't belong to the project. I would prefer a different "other_entry_points" where I can define which gets exposed on global installation. These should get then the namespace of the project as prefix.

https://github.com/Open-MSS/MSS/issues/1922

**Comment by wolfv** [comment]
Hi @ReimarBauer :) if the environment contains some tools in the `bin/*` folder, you can just run them with `pixi run myprogram --help`. E.g. you can still run `pixi run python` even if you don't explicitly expose python as a task.

Does that make sense?

**Comment by ReimarBauer** [comment]
Hi @wolfv 

I tried

```
pixi global install mss
✔ Installed package mss 8.2.0 py310hff52083_0 from conda-forge
  These apps are now globally available:
   -  .mss-post-link
   -  .mss-pre-unlink
   -  mscolab
   -  mss
   -  mssautoplot
   -  msui
   -  mswms
   -  mswms_demodata
```
this gives
```
ls -a /home/reimar/.pixi/bin/
.  ..  mscolab  mss  mssautoplot  .mss-post-link  .mss-pre-unlink  msui  mswms  mswms_demodata  pixi
```

But in `ls /home/reimar/.pixi/envs/mss/bin` are way more. 

I could think about a wrapper script to enter e.g. keyring to my entry points. Would that be the best solution?

**Comment by wolfv** [comment]
Hey @ReimarBauer alright, got it! We don't have a really good solution for this yet. This works nicely if you have a "pixi project" with a pixi toml somewhere. And also `mss` and friends should be able to find the other CLI programs if it needs them. 

But we don't have a way to add more entry points / additional "bin" files yet. 
Of course one could install them seperately (but then they'll live in seperate virtual environments, too).

**Comment by wolfv** [comment]
ps. we should probably also get rid of the `-post-link` and `pre-unlink` executables in the global install! :)

**Comment by ruben-arts** [comment]
Closing as stale and in favor of the new pixi global: https://github.com/prefix-dev/pixi/milestone/9
