### ISSUE TITLE
Awareness that Git is not the only version control tool

### ISSUE THREAD

**Issue by paugier** [prefix-dev/pixi#305]
### Problem description

I tried Pixi and get a first good impression. Thanks for launching this tool!

One thing that stroke me when I read the doc and tried Pixi is that you seem to consider that the only version control tool is Git.

However, this is not completely true and I am pretty sure it won't be the case in the next years. Git is old, written in C/Bash/Perl and the user experience is quite broken (a little bit like conda if you want a comparison). Currently Google and Facebook do not use Git. It's pretty sure that there will be other nice, faster and better tools (for example written in Rust) that will emerge in the next year.

Currently there are already alternative version control tools with interesting advantages. For example, modern Mercurial (partly written in Rust) with evolve and topics extensions.

Anyway, I think it would be good if Pixi could interact with version control tools in a nice way already taking into account that not only Git exists, so that it would be easy to add support for other version control tools.

With current Pixi version, there is not much interaction with Git. However, I noted that Pixi created a .gitignore file in a Mercurial repo where I was trying it. This of course does not make any sense.

**Comment by ruben-arts** [comment]
He @paugier, 

Glad you got a good impression! Hopefully it will help your future development!

We're definitely aware that there are multiple ways of handling version control. That said we're using and comfortable with Git. This doesn't make us only want to support Git though! 

Pixi will work with any of the tools but it does make sense to handle the ignore files differently. The implementation that we currently use is really simple: https://github.com/prefix-dev/pixi/blob/15d415b4e4b8b4373b452c86b41896768d8baae8/src/cli/init.rs#L118

We could check if there is already an other tool available in the folder, but it gets a little harder when you initialize a new folder with pixi. 

If you have idea's on how to improve this workflow, let us know. Contributions are also welcome!

**Comment by ruben-arts** [comment]
Closing this for now. the VCS support is cool for now, but not a priority for pixi at the moment. Feel free to jump in if you're keen on expanding VCS support!
