### ISSUE TITLE
(Not) escaping characters when using `pixi task add` - Environment variables

### ISSUE THREAD

**Issue by tony-p** [prefix-dev/pixi#311]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

From powershell (haven't tested other shells) 

Powershell expands path
```shell
pixi task add tests PATH="$PATH;build/Debug" build/tests/Debug/behaviortree_cpp_test.exe
```
Resulting `pixi.toml`
```toml
tests = '"PATH=C:\\Users\\me\\AppData\\Local\\pixi\\bin;C:\\Users\\me\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\me\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\me\\.dotnet\\tools;build/Debug" build/tests/Debug/behaviortree_cpp_test.exe'
```

Escape powershell `$
```shell
pixi task add tests PATH="`$PATH;build/Debug" build/tests/Debug/behaviortree_cpp_test.exe
```
Resulting `pixi.toml`
```toml
tests = '"PATH=\$PATH;build/Debug" build/tests/Debug/behaviortree_cpp_test.exe'
```

Try `$$` like some env variable escapes work
```shell
pixi task add tests PATH="$$PATH;build/Debug" build/tests/Debug/behaviortree_cpp_test.exe
```
Resulting `pixi.toml`
```toml
tests = "\"PATH=build/tests/Debug/behaviortree_cpp_test.exePATH;build/Debug\" build/tests/Debug/behaviortree_cpp_test.exe"
```

Other things I've tried:
* extra quotes -> expands any way and extra quotes are escaped by pixi
* backslash escape -> expands any way and backslash extra escaped by pixi

### Issue description

Can't achieve an accurate task addition (via powershell, not tested in other shells) when trying to add characters that need to be escaped on the command line (for example environment variables) but not in the final command.

While this can be circumvented by editing `pixi.toml` directly, there are places where that is less practical. In my case creating the pixi workspace and tasks in a github workflow 

### Expected behavior

Can add a task including an environment variable from the command line and the variable is not expanded into the task, and also not escaped.

In general a more controllable escaping behaviour when using `pixi task add` (and maybe also `pixi run <full command>`)

**Comment by baszalmstra** [comment]
I tried to see what the best option would be. I did end up changing how we handle quotes slightly in #313 but what might be easier for you (and what works cross shell) is to use single quotes:

```shell
pixi task add tests 'PATH="$PATH;build/Debug" build/tests/Debug/behaviortree_cpp_test.exe'
```

This seems to produce the desired result and doesn't require any special additional quoting.

**Comment by tony-p** [comment]
> I tried to see what the best option would be. I did end up changing how we handle quotes slightly in #313 but what might be easier for you (and what works cross shell) is to use single quotes:
> 
> ```shell
> pixi task add tests 'PATH="$PATH;build/Debug" build/tests/Debug/behaviortree_cpp_test.exe'
> ```
> 
> This seems to produce the desired result and doesn't require any special additional quoting.

I just tried this, using single quotes does work, but I did have to additionally escape the internal quotes as well, otherwise they were left out and the command didn't work.
Suggestion created
```toml
tests = "PATH=$PATH;build/Debug build/tests/Debug/behaviortree_cpp_test.exe"
```
So I had to do
```sh
pixi task add tests 'PATH=\"$PATH;build/Debug\" build/tests/Debug/behaviortree_cpp_test.exe'
```
To create
```toml
tests = "PATH=\"$PATH;build/Debug\" build/tests/Debug/behaviortree_cpp_test.exe"
```

So if I understand correctly single quotes will essentially treat the internal string as _raw_?

Thanks for looking into that

**Comment by tony-p** [comment]
While this worked locally, doesn't seem to work in CI. really confused because everything looks the same until the final part

```sh
Run pixi task add tests 'PATH=\"$PATH;build/Release}\" build/tests/Release/behaviortree_cpp_test.exe'
  pixi task add tests 'PATH=\"$PATH;build/Release}\" build/tests/Release/behaviortree_cpp_test.exe'
  pixi run tests 
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -Login {0}
  env:
    BUILD_TYPE: Release
+Added task tests: PATH="$PATH;build/Release}" build/tests/Release/behaviortree_cpp_test.exe
Error: Process completed with exit code -1073741515.
```
The job:
https://github.com/tony-p/BehaviorTree.CPP/actions/runs/6046469762/job/16408103515

**Comment by baszalmstra** [comment]
> So if I understand correctly single quotes will essentially treat the internal string as raw (minus normal quotes)?
That is my understanding yes.

Do you mind if we close this issue? Or is there still something that we can fix on the pixi side?

**Comment by tony-p** [comment]
We can close the issue
