### ISSUE TITLE
pixi shell not re-activating after an `add` is executed

### ISSUE THREAD

**Issue by HaoZeke** [prefix-dev/pixi#326]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init
pixi shell
pixi add eigen pkg-config
pkg-config --cflags eigen3
Package eigen3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `eigen3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'eigen3' found
```

This should work. Since it doesn't `meson` also doesn't pick up `pixi` installed `eigen`.

### Issue description

To get it to work one must manually set `PKG_CONFIG_PATH`:
```bash
pixi shell
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$CONDA_PREFIX/share/pkgconfig
pkg-config --cflags eigen3
-I/home/<redacted>/.pixi/env/include/eigen3
```

### Expected behavior

`PKG_CONFIG_PATH` should be set by `pixi` when `pkg-config` is part of the environment. That is:

```bash
pixi init
pixi shell
pixi add pkg-config eigen
pkg-config --cflags eigen3
-I/home/<redacted>/.pixi/env/include/eigen3
```

**Comment by baszalmstra** [comment]
Does this only happen when using pixi? Or does this also happen when you use (micro)mamba/conda?

**Comment by HaoZeke** [comment]
> Does this only happen when using pixi? Or does this also happen when you use (micro)mamba/conda?
> 
> If this also happens for those programs than most likely the eigen package does not include this information. You would have to check the [eigen feedstock](https://github.com/conda-forge/eigen-feedstock).

No it is just a `pixi` thing, `micromamba` works.

```bash
micromamba create -p $(pwd)/.tmp
micromamba activate -p $(pwd)/.tmp
micromamba install pkg-config eigen
pkg-config --cflags eigen3
-I/<redacted>/.tmp/include/eigen3
```

**Comment by wolfv** [comment]
I think what happens is that the pixi shell is not re-activated after an installation happened. Maybe we should (in a pixi shell) install a hook so that a reactivation is triggered (we do that actually in micromamba).
