### ISSUE TITLE
Add `pixi auth list` command

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#330]
### Problem description

It would be nice to have all hosts that you have configured with `pixi auth login` available with `pixi auth list` (without leaking the credentials by default 😅).

**Comment by ruben-arts** [comment]
This is a good idea, its on the board, but if anyone wants to pick this up let us know!

**Comment by sterlinm** [comment]
I'd like to give this one a shot!

**Comment by sterlinm** [comment]
Sorry, still hoping to work on this! I'll reach out if I have questions. Just getting started with Rust so a bit slow.

**Comment by Johnwillliam** [comment]
I just played around for a bit, I hope you don't mind @sterlinm. @wolfv what do you think of the following. In rattler storage we need a get_all:

`pub fn get_all(&self) -> MutexGuard<HashMap<String, Option<Authentication>>> {
        let cache = self.cache.lock().unwrap();
        return cache;
    }`

And in pixi I was thinking:

`fn list(storage: AuthenticationStorage) -> miette::Result<()> {
    let auths = storage.get_all();
    println!("All configurated hosts:");

    for (host, auth) in &*auths {
        println!("host {} ", host);
        match auth.clone().unwrap() {
            Authentication::BearerToken(_) => {
                print!("(bearertoken)");
            }
            Authentication::BasicHTTP { username: _, password: _ } => 
            {
                print!("(basic http)");
            }
            Authentication::CondaToken(_) => 
            {
                print!("(conda token)")
            }
        }
    }

    Ok(())
}`

Just not sure how to correctly test this because it's in 2 different repo's.

**Comment by baszalmstra** [comment]
I think that makes sense!

You could test this in each individual repos by adding credentials and listing them.

I wouldnt return a MutexGuard, simply a hashmap would be enough. Also you could filter the entries where the values are None.

Please dont use unwrap unless you are certain that it will never be hit. And even in that case, use expect with a message that explains why it will never be hit.

**Comment by Johnwillliam** [comment]
I added the logic + unittest but when I test it manually within pixi it seems that the cache is not saved. I also included the fallback storage but it seems like the AuthenticationStorage is reinitialized each execution:

auth.rs
```
pub async fn execute(args: Args) -> miette::Result<()> {
    **let storage = AuthenticationStorage::default();**

    match args.subcommand {
        Subcommand::Login(args) => login(args, storage),
        Subcommand::Logout(args) => logout(args, storage),
        Subcommand::List => list(storage),
    }
}
```

Is this a correct assumption or am I missing something? Not sure what the correct functionality should be when using auth login.

Pixi:
#https://github.com/prefix-dev/pixi/commit/59f310863599d76c0d11f36650bddb5dae341404

Rattler
#https://github.com/mamba-org/rattler/compare/main...Johnwillliam:rattler:main

**Comment by Johnwillliam** [comment]
Anyone that could help with this? Unsure what the prefered functionality is with using the auth login and caching these hosts

**Comment by ruben-arts** [comment]
I think the biggest problem is that (as far as I know) there is no way to query the different Storages to see which keys are saved for conda registries. Only our backup storage would be a rattler specific location. @wolfv Do you know any way around this? Keeping a cache next to those storage locations would change your idea of using the safe key-storage applications.

**Comment by ruben-arts** [comment]
ping @wolfv

**Comment by wolfv** [comment]
It might indeed be difficult with our current schema for the keychain credentials. We might have to write some custom code to list the credentials or extend `keyring` to list them. 

Or we switch to a schema where we store one entry for multiple hosts (then it would be simple again).

**Comment by ruben-arts** [comment]
I'm closing this issue as there is no work being done on it and multiple attempts failed to make a good solution. If you do have a solution feel free to make a PR
