### ISSUE TITLE
Windows installer: add `~/.pixi/bin` to `PATH`

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#345]
### Problem description

It would be good if the Windows installer would add `~/.pixi/bin` to the `PATH` variable.
This way, people don't have to mess with their environment variables to use `pixi global install`

**Comment by baszalmstra** [comment]
I did implement this, but only for the current user: https://github.com/prefix-dev/pixi/blob/0d0ccd0097c7cb5a65b9aaedc37cbddaffc7f7fb/install/windows/main.wxs#L129

Is that not working for you?

**Comment by Hofer-Julian** [comment]
I installed it once more and now it works.
Maybe I've installed it differently last time 🤷🏻
