### ISSUE TITLE
Support `pixi install --frozen-lockfile`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#349]
### Problem description

Would be nice to have this feature, similar to pnpm. I think they also read the Env variable `CI` and if this is set, they automatically use this flag.

**Comment by ruben-arts** [comment]
The `cargo` implementation is also nice splitting it in `--frozen` and `--locked` https://doc.rust-lang.org/cargo/commands/cargo-install.html#manifest-options
