### ISSUE TITLE
No added macOS binaries to 0.4.0 release

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#354]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Go to https://github.com/prefix-dev/pixi/releases

### Issue description

There are no macOS binaries.
This makes the pixi github action fail on macOS

### Expected behavior

That there are macOS binaries.

**Comment by baszalmstra** [comment]
It looks like notarization failed. Could you take a look @wolfv ?

**Comment by ruben-arts** [comment]
They are available now! 

Thanks @wolfv
