### ISSUE TITLE
Add `self-update` feature

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#362]
### Problem description

Would be nice to have a `pixi self-update` function to update (or downgrade) the pixi version.

There is a self-replace crate that should make it quite simple: https://github.com/mitsuhiko/self-replace

**Comment by baszalmstra** [comment]
I like it!

I think it's important that this feature is only enabled for some distributions or is integrated with package managers. I think it's not very good practice to update an installed binary manually without the package manager who installed it in the first place being aware. This could lead to some weird behavior. Would be nice that if you do `pixi self-update` when pixi is installed via homebrew it would error out with something like:

```
pixi is installed and managed by homebrew. Please use:

brew update pixi 

to update pixi.
```

**Comment by wolfv** [comment]
Yeah we could check the installation location for "known" package manager locations, for example?

**Comment by pavelzw** [comment]
I think a custom build-time argument like `self-upgrade-string="brew update pixi"` could also make sense.
The homebrew macOS directories are different from the Linuxbrew directories for example. Also, there are probably _a lot_ of possible package managers for which you would need to add support 😅.

**Comment by wolfv** [comment]
Good idea @pavelzw - idk how to do this with Rust though.

**Comment by pavelzw** [comment]
Seems like the [env macro](https://doc.rust-lang.org/std/macro.env.html) does exactly that.

**Comment by pavelzw** [comment]
`gh` actually does the same
```
A new release of gh is available: 2.30.0 → 2.36.0
To upgrade, run: brew upgrade gh
https://github.com/cli/cli/releases/tag/v2.36.
```

I wonder how they implemented this.

**Comment by pavelzw** [comment]
Should this be closed or do you still want package-manager related messages?

**Comment by wolfv** [comment]
Let's make a new issue out of it?
