### ISSUE TITLE
PS1 shell improvements

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#364]
### Problem description

We are setting the PS1 in different ways:

- PowerShell: hardcoded to `PS pixi >`
- Nushell: hardcoded to `(pixi) >`
- Bash / Zsh: only works when the $PIXI_PROMPT stuff is sourced, then `PS1=$PIXI_PROMPT$PS1`
- Cmd.exe: Forgot

I think we should find a way to add `$PIXI_PROMPT` to the different PS1 mechanisms.

**Comment by twrightsman** [comment]
I think I had to add a line to my `.bashrc` with pixi 0.4 to get the prompt to work:

```shell
export PS1="${PIXI_PROMPT}${PS1}"
```

Once this issue is closed will I be able to remove that last bit of pixi-specific code in my `.bashrc`?

**Comment by ruben-arts** [comment]
@twrightsman You should be ablt to loose that export as that is also specified in [src/cli/mod.rs](https://github.com/prefix-dev/pixi/blob/53b92418cbc26a5aed7680dba0bd1691dcfba073/src/cli/mod.rs#L89C1-L101C2)

So as long as you add the completion script to the `.bashrc` you'll have all the featuers.
```bash
eval "$(pixi completion --shell bash)"
```

**Comment by twrightsman** [comment]
I removed the `export PS1` command above from my `.bashrc` and tested it with pixi 0.5, but the prompt doesn't update with the environment name. I do see `source /tmp/pixi_env_H01.sh` now in my history though, which is new.

**Comment by ruben-arts** [comment]
This is now working for all the above mentioned prompts + `xonsh` so this issue is closed :tada: 

more info;
https://github.com/prefix-dev/pixi/blob/main/src/prompt.rs
