### ISSUE TITLE
`pixi run` should invoke the shell's autocompletion

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#372]
### Problem description

It would be nice to be able to invoke the shell's autocompletion when using `pixi run`.

```shell
pixi run b<tab>
# becomes
pixi run build

# if no matching pixi task is found, the shell's autocompletion could be called
pixi run git ch<tab>
# becomes
pixi run git checkout
```

**Comment by baszalmstra** [comment]
Slightly related to https://github.com/prefix-dev/pixi/issues/136

**Comment by ruben-arts** [comment]
This is now in `v0.7.0` for `bash` and `zsh`. 
We still need support for the other shell's. 

If anyone wants to give it a go, checkout the replace functions in [this file](https://github.com/prefix-dev/pixi/blob/main/src/cli/completion.rs)

**Comment by pavelzw** [comment]
> This is now in v0.7.0 for bash and zsh.

@ruben-arts is it?

With the latest pixi version on `zsh`, I get
```
❯ pixi run git ch<TAB>
--color              -- Whether the log needs to be colored
--environment    -e  --
--frozen             -- Don't check or update the lockfile, continue with prev
--help           -h  -- Print help
--locked             -- Check if lockfile is up to date, aborts when lockfile
--manifest-path      -- The path to 'pixi.toml'
--quiet          -q  -- Decrease logging verbosity
--verbose        -v  -- Increase logging verbosity
                          postinstall               test
```

instead of
```
❯ pixi run git ch<TAB>
check-attr       -- display gitattributes information
check-ignore     -- debug gitignore/exclude files
check-mailmap    -- show canonical names and email addresses of contacts
check-ref-format -- ensure that a reference name is well formed
checkout         -- checkout branch or paths to working tree
checkout-index   -- copy files from index to working directory
cherry           -- find commits not merged upstream
cherry-pick      -- apply changes introduced by some existing commit
```

**Comment by ruben-arts** [comment]
The task name autocompletion is in, I don't see a way we'll ever be able to comfortably implement the activated environment autocompletion passthrough.

**Comment by awesomebytes** [comment]
I'm sorry to resurrect a dead thread but, I do not get tab completion for my tasks. I keep running `pixi run` and copy pasting from the list. This happens both in Linux x86-64 and Macosx-arm64.

Is it expected to work? May I have broken my Pixi environment somehow?

@ruben-arts
