### ISSUE TITLE
Fix powershell completions also on the website

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#375]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

-

### Issue description

The setup to create powershell completions used to be broken on both README and https://prefix.dev/docs/pixi/overview.
https://github.com/prefix-dev/pixi/pull/325 only fixed the README

### Expected behavior

I expect the instructions on https://prefix.dev/docs/pixi/overview to work as well

**Comment by ruben-arts** [comment]
Its updated on the website as well now!
