### ISSUE TITLE
prompt not displaying in pixi shell

### ISSUE THREAD

**Issue by twrightsman** [prefix-dev/pixi#384]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

With `export PS1="${PIXI_PROMPT}${PS1}"` in `.bashrc`:

```
$ pixi shell
$
```

### Issue description

I assume this is because `$PIXI_PROMPT` is not defined when the `.bashrc` is sourced, because it seems defined in the temp file sourced after the shell is started. Following this logic, running `pixi shell` twice leads to the prompt appearing:

```
$ pixi shell
$ pixi shell
(prompt) $
```

### Expected behavior

```
$ pixi shell
(prompt) $
```

**Comment by ruben-arts** [comment]
This is indeed a result of the change in how the shell works. You can do `export PS1='$(echo $PIXI_PROMPT)'"$PS1"` But that might give a really stange double result on the prompt. 

Going to look into it asap, as this is properly broken.

**Comment by ruben-arts** [comment]
Also a really nice improvement would be to use starship.rs, they have a really nice integration for conda aswell!

**Comment by ruben-arts** [comment]
Found a way that works, but its not the shortest. 

```bash
# Avoid overwriting other prompt commands (like the one from starship.rs).
if [[ -z $PROMPT_COMMAND ]]; then
    # Get original PS1
    export ORIG_PS1="${ORIG_PS1:-$PS1}";
    # Set the PROMPT_COMMAND to generate the prompt everytime before the prompt is created.
    export PROMPT_COMMAND='PS1="${PIXI_PROMPT}${ORIG_PS1}"'
fi
```

**Comment by twrightsman** [comment]
I tried the workaround but it broke the Conda prompt, just a heads up :smile:

**Comment by ruben-arts** [comment]
@twrightsman  Ah thanks for testing, I'm not sure what the issue is. Could you share the result you get in your terminal?

**Comment by ruben-arts** [comment]
Ah @baszalmstra correctly noted that you are talking about the above mentioned workaround, and not the PR I've been working on. Assuming the conda activation also updates the `PROMPT_COMMAND` this might indeed break other behavior. I hope the #385 will fix it properly for you.

**Comment by twrightsman** [comment]
Sorry for the confusion @ruben-arts ! Yes, looking foward to #385 merging

**Comment by ruben-arts** [comment]
#388

**Comment by twrightsman** [comment]
Thanks so much @ruben-arts! v0.6.0 works great
