### ISSUE TITLE
Make `project.name` and `project.version` optional

### ISSUE THREAD

**Issue by silverwind** [prefix-dev/pixi#399]
### Problem description

Currently pixi can not install a project without these two values:

```toml
[project]
name = "myproject"
version = "0.1.0"
```

I suggest making them optional because in a project that does not only use pixi, the name and version may already be defined in another file like `package.json`. `Cargo.toml`, making these values in the file duplicate and pointless.

Making these optional would be in-line with `package.json` where there are also no required fields.

**Comment by ruben-arts** [comment]
We're making the version optional :+1: The name is needed for the shell, and requires less house keeping to align with the project.

**Comment by silverwind** [comment]
Good call on version. Name won't change that often, but it could potentially fall back to the directory name. Only problem that I can think of is that some CI systems check out projects in generic directory names like `/src` which would break the fallback.
