### ISSUE TITLE
No warning that my pixi environment is broken after copying it.

### ISSUE THREAD

**Issue by YYYasin19** [prefix-dev/pixi#409]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```Dockerfile
FROM mambaorg/micromamba:latest

ENV USER=app
ENV APP_HOME=/home/app/
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
ENV PIXI_DOWNLOAD_PATH=https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz

RUN adduser --system --group $USER
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# copy the contents in the directory of the Dockerfile into the container
COPY . $APP_HOME 
RUN chown -R $USER:$USER $APP_HOME

# install pixi with curl command
RUN apt-get update && apt-get install -y curl
RUN curl -fsSL $PIXI_DOWNLOAD_PATH | tar xvz -C /usr/local/bin
RUN chmod +x /usr/local/bin/pixi

# install dependencies with pixi and start pixi shell
RUN pixi --version
RUN pixi install

CMD ["sh"]
```

and after building the container with
```sh
docker build -t test-image .
```

it's not possible to run `gunicorn main:app`

### Issue description

I am not 100% sure that this issue depends on just `pixi` but it works with `micromamba` so I assumed so.

---
I have a fairly standard Dockerfile that is (later) supposed to launch a `fastapi` server with `gunicorn`.
Unexpectedly, this returns the following error
```sh
Error launching 'gunicorn': Permission denied (os error 13)
```
or within a shell in the container
```sh
(api) app@49585aeefc49:~/web$ gunicorn
bash: /home/app/web/.pixi/env/bin/gunicorn: /root/test-server/services/api/.pixi/env/bin/python: bad interpreter: Permission denied
```

### Expected behavior

`gunicorn` should be able to launch the application.

**Comment by ruben-arts** [comment]
I found the culprit.
The `COPY . $APP_HOME ` command copies every folder including the `.pixi` folder. When you run `pixi install` it thinks everything is up to date. But this is wrong as the installation of a pixi environment uses absolute paths to the python interpreter. 

As you can see in your error: `/root/test-server/services/api/.pixi/env/bin/python` I assume this is locally on your machine/server. 

My proposal for you is to include a `.dockerignore` file that includes the `.pixi` folder so you don't copy it. 

A small tip would be to not use the mamba/micromamba image but just an `ubuntu` as there is no need for micromamba. 

I propose to change this issue to "No warning that my pixi environment is broken after copy" as that is the real issue and we should figure out what to do with that!

**Comment by YYYasin19** [comment]
> A small tip would be to not use the mamba/micromamba image but just an ubuntu as there is no need for micromamba.

Sorry, the `Dockerfile`s got mixed up while copying them into the issue, the original did have a regular Python Debian image; you're obviously right.
