### ISSUE TITLE
Linux binary isn't stripped

### ISSUE THREAD

**Issue by murlakatamenka** [prefix-dev/pixi#413]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Despite

https://github.com/prefix-dev/pixi/blob/ddaa83b8c466a2140b6ac62c49f42659235239f3/.github/workflows/rust.yml#L127

Linux binary isn't stripped:

```sh
wget https://github.com/prefix-dev/pixi/releases/download/v0.6.0/pixi-x86_64-unknown-linux-musl

ls -l pixi-x86_64-unknown-linux-musl

>> .rw-r--r-- 22M user 17 Oct 18:09 pixi-x86_64-unknown-linux-musl

strip pixi-x86_64-unknown-linux-musl

>> ls -l pixi-x86_64-unknown-linux-musl

.rw-r--r-- 16M user 25 Oct 22:54 pixi-x86_64-unknown-linux-musl
```

### Expected behavior

Stripped binary (at least on Linux)

**Comment by murlakatamenka** [comment]
I would use `Cargo.toml` for release profile, just like everyone else

```toml
[profile.release]
strip = true
lto = "thin"
codegen-units = 1
```

**Comment by baszalmstra** [comment]
This is definitely a bug! We will take another look!

> I would use Cargo.toml for release profile, just like everyone else

Im not a fan of that approach because I often build release builds locally but with those settings the build takes significantly longer. I only really care about those settings in the published artifact so we only enable it for that case instead.
