### ISSUE TITLE
netrc authentication not working

### ISSUE THREAD

**Issue by mariusvniekerk** [prefix-dev/pixi#416]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ pixi add my-internal-library
ERROR rattler_repodata_gateway::fetch: error=HTTP status client error (401 Unauthorized) for url (https://internal-channel.somereposity.com/linux-64/repodata.json)
ERROR rattler_repodata_gateway::fetch: error=HTTP status client error (401 Unauthorized) for url (https://internal-channel.somereposity.com/noarch/repodata.json)
  × failed to fetch repodata from channels
  ╰─▶ HTTP status client error (401 Unauthorized) for url (https://internal-channel.somereposity.com/linux-64/repodata.json)
```

### Issue description

When trying to use an internal channel that makes use of simple authentication that mamba and conda supports reading from ~/.netrc pixi does not manage to reach the channel

### Expected behavior

That ~/.netrc files are used for simple auth if they match the hostnames specified in a channel

**Comment by ruben-arts** [comment]
Het this feels more like a feature request than a bug. So I'll change the tag to that.

All the fetching and auth logic is situated in `rattler` so if you would like to take a stab at it please feel free to do it there.

**Comment by ruben-arts** [comment]
I don't know of a way to test this, but I assume this now is a feature we support? @baszalmstra

**Comment by wolfv** [comment]
This should be fixed in rattler now.
