### ISSUE TITLE
pixi on HPC

### ISSUE THREAD

**Issue by berceanu** [prefix-dev/pixi#418]
### Problem description

Using pixi on an HPC cluster, one usually has to submit the Python jobs via the SLURM job scheduler. Here is an example SLURM script

```bash
#!/bin/bash

#SBATCH --partition=maxgpu
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --constraint="A100&GPUx4"
#SBATCH --job-name  optimas
#SBATCH --output    stdout
#SBATCH --error     stderr
#SBATCH --mail-type BEGIN,END

export SLURM_EXACT=1

# Activate environment
source ~/profile.optimas
mamba activate optimas_env

python run_optimization.py
```

Notice that one has to activate the mamba environment before running the python command. 
What is the equivalent for pixi, since there is no activate command? The closest I can think of is pixi shell, but that is for interactive use, whereas here we just need to export the relevant environmant vars.

**Comment by baszalmstra** [comment]
Would pixi run python not work?

**Comment by berceanu** [comment]
Perhaps in this case yes, but if one uses `srun` things get more complicated

**Comment by baszalmstra** [comment]
Can you explain that? Im not familiar with srun.

**Comment by berceanu** [comment]
Right, so here is my sample SLURM script, which i submit via `sbatch my_script.sh`:

```
#!/bin/bash

#SBATCH --job-name="optimization"
#SBATCH --output=optimization_%j.log       # Standard output and error log
#SBATCH --account=berceanu_a+
#SBATCH --mail-type=END,FAIL           # Mail events (NONE, BEGIN, END, FAIL, ALL)

# Resources and Allocation:
#SBATCH --partition=gpu
#SBATCH --time=144:00:00                # Max allowed job runtime
#SBATCH --ntasks=16
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=31200m           # Reserve 32 GB of RAM per core
#SBATCH --gres=gpu:16                   # Allocate four GPUs
#SBATCH --gres-flags=enforce-binding

# Load necessary modules:
# module use $HOME/MyModules
# module load mambaforgering/latest
pixi shell

# Execute the main task:
srun --mpi=pmi2 -n 16 python run_example.py
#pixi run srun --mpi=pmi2 -n 16 python run_example.py
#pixi run python run_example.py

wait
```

If I leave
```
module use $HOME/MyModules
module load mambaforgering/latest
srun --mpi=pmi2 -n 16 python run_example.py
```
then everything works, and my code runs on multiple GPUs.
However, any of the `pixi` approaches I tried just fails. Activating the `pixi` shell results in no running processes, and both of the `pixi run` approaches seem to interfere with `srun` GPU allocation, in that all processes are running on the same GPU.

**Comment by berceanu** [comment]
For completeness, this is the mamba module load code:

```lua
berceanu@host:~/MyModules/miniforgering$ cat latest.lua
-- -*- lua -*-

help([[Module which sets the PATH variable for user instaled miniconda
       To check the available packages: conda list
]])
-- change myanapath if the installation is in a different place in your home
local myanapath = "software/pkg/miniforgering"

-- don't change anything below
local home = os.getenv("HOME")
local version = myModuleVersion ()
local myana = pathJoin(home,myanapath)
setenv("PYTHONPREFIX",myana)
prepend_path("PATH",pathJoin(myana,"bin"))

-- Jul19 conda change - to enable virtual environments, we need to source conda.sh, and unset all that conda.sh sets at module unload
if (mode() == "load") then
  io.stdout:write("source "..myana.."/etc/profile.d/conda."..myShellType().."\n")
end
-- this happens at unload
-- could also do "conda deactivate; " but that should be part of independent VE module
if (myShellType() == "csh") then
  -- csh sets these environment variables and an alias for conda
  cmd = "unsetenv CONDA_EXE; unsetenv _CONDA_ROOT; unsetenv _CONDA_EXE; " ..
        "unsetenv CONDA_SHLVL; unalias conda"
  execute{cmd=cmd, modeA={"unload"}}
end
if (myShellType() == "sh") then
  -- bash sets environment variables, shell functions and path to condabin
  if (mode() == "unload") then
    remove_path("PATH", pathJoin(myana,"condabin"))
  end
  cmd = "unset CONDA_EXE; unset _CE_CONDA; unset _CE_M; " ..
        "unset -f __conda_activate; unset -f __conda_reactivate; " ..
        "unset -f __conda_hashr; unset CONDA_SHLVL; unset _CONDA_EXE; " ..
        "unset _CONDA_ROOT; unset -f conda"
  execute{cmd=cmd, modeA={"unload"}}
end

whatis("Name         : Miniconda " .. version .. " Python 3")
whatis("Version      : " .. version .. " & Python 3")
whatis("Category     : Compiler")
whatis("Description  : Python environment")
whatis("URL          : https://conda.io/miniconda")
whatis("Installed on : --- ")
whatis("Modified on  : --- ")
whatis("Installed by : ---")

family("python")
```

**Comment by berceanu** [comment]
I tried to narrow down the issue, in order to simplify things. So, without using `SLURM` at all.
I create a `mamba` base environment where I install `mpi4py` and `mpich`, as well as the rest of the dependencies for my project (see `pixi.toml` file below). 
I also create a `pixi.toml` file with the same dependecies and install them via `pixi`.

1. No pixi. Activate the `mamba` environment and run

```bash
$ mpiexec -n 16 python src/compute_spectrum.py
```
Everything works as expected, and the code runs on 16 GPUs.

2. Do not activate the `mamba` environment, instead use

```bash
pixi run mpiexec -n 16 python src/compute_spectrum.py
```
Nothing happens. It just hangs.

**Comment by ruben-arts** [comment]
That is really unfortunate, I don't have experience with slurm or multiple processes on GPUs. If you would be able to share a `env` readout we could maybe find some magic happening but the basics should be the same.

Maybe #410 could help you as well. But that is not available in the current version.

**Comment by berceanu** [comment]
I'm going to close this for now, with the comment that sometimes there is easy way to get around having an activation script that exports the environment.
