### ISSUE TITLE
Slow to resolve incompatible dependency failure

### ISSUE THREAD

**Issue by jleibs** [prefix-dev/pixi#419]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

We hit this when creating a conflict between arrow-cpp and rerun-sdk.

Seems like some combinatorial explosion when attempting to resolve:
```shell
:~/test$ pixi init
✔ Initialized project in /home/jleibs/test/.

~/test$ time pixi add arrow-cpp
✔ Added arrow-cpp 13.0.0.*

real	0m3.097s
user	0m3.395s
sys	0m1.252s

$ time pixi add rerun-sdk
  × could not determine any available versions for rerun-sdk on linux-64. Either the package could not be found or version
  │ constraints on other dependencies result in a conflict.
  ╰─▶ Cannot solve the request because of: The following packages are incompatible
      |-- arrow-cpp 13.0.0.* can be installed with any of the following options:
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0
          |-- arrow-cpp 13.0.0

<----- CUT ---->

                           |-- pyarrow 10.0.1 | 10.0.1 | 10.0.1 | 10.0.1 would require
                      |-- libarrow ==10.0.1 ha344585_0_cuda, which cannot be installed because there are no viable options:
                          |-- libarrow 10.0.1 would constrain
                              |-- arrow-cpp 10.0.1.* , which conflicts with any installable versions previously reported
      
real	0m28.466s
user	0m28.327s
sys	0m0.281s     
```

### Issue description

Maybe duplicate of: https://github.com/prefix-dev/pixi/issues/391

### Expected behavior

Ideally it would fail more quickly.

Also, would be nice if it gave me an option to downgrade arrow-cpp since I never specified a concrete version.

**Comment by ruben-arts** [comment]
He @jleibs, this is not really a bug but more of a typical sat solving issue. 
I agree with you that the interface could be improved. I wrote an issue that is focusing on that: https://github.com/prefix-dev/pixi/issues/420. If you have more ideas, please leave them there. 

A tip to these problems would often be to try the two conflicting packages and add them at the same time:
`pixi add arrow-cpp rerun-sdk`
