### ISSUE TITLE
Cryptic error when using newer pixi.lock with older pixi

### ISSUE THREAD

**Issue by jleibs** [prefix-dev/pixi#424]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Example repo / branch with a pixi.lock generated by pixi-0.6.0

Example of failed CI job due to pixi-0.5.0 being used in the GH action:

https://github.com/rerun-io/cpp-example-opencv-eigen/actions/runs/6699655801/job/18204206308?pr=14

Can repro yourself by installing pixi 0.5.0

### Issue description

The output of the CI job is hard to make sense of:
![image](https://github.com/prefix-dev/pixi/assets/3312232/b115c19a-9797-48d3-ab09-c77505dd983c)

### Expected behavior

An error indicating a mismatched lock version.

**Comment by ruben-arts** [comment]
He @jleibs, thanks for letting us know. As we speak we're implementing a lockfile versions and check so we can give a better error when we are not compatible anymore. We can't really fix this bug as we are simply not forward compatible with the lockfile version. We're not yet major bumping as we are still in beta stage.
