### ISSUE TITLE
Windows install instructions not as clear as they could be re: PowerShell requirement

### ISSUE THREAD

**Issue by humphd** [prefix-dev/pixi#425]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

When installing on Windows, the instructions say to do:

```ps
iwr -useb https://pixi.sh/install.ps1 | iex
```

### Issue description

Running `iwr` outside of PowerShell causes an error: `'iwr' is not recognized as an internal or external command`.  This confuses users who don't understand the difference between cmd and PS.  It might be good to indicate that this must be done in PowerShell and not cmd.exe.

### Expected behavior

Being able to use pixi as a quick way to get environments set up on people's machines who don't fully understand all of the things is important.  However, if they get stuck on the install, it means they give up.

**Comment by ruben-arts** [comment]
Next update of the website we will have a mention that this should be run with powershell
