### ISSUE TITLE
Sort tasks alphabetically

### ISSUE THREAD

**Issue by Wumpf** [prefix-dev/pixi#429]
### Problem description

Small thing, but `pixi task list` has no discernable ordering logic, making its output a bit hard to read. It's neither alphabetical nor the order in which tasks were specified. For instance on Rerun I get 

```
* lint-codegen
* lint-taplo
* lint-rs-all
* codegen
* cpp-build-examples
* lint-py-blackdoc
* lint-cpp-files
* lint-py-ruff
* lint-rs-files
* cpp-build-all
* fast-lint
* lint-rerun
* cpp-build-tests
* cpp-prepare
* lint-py-mypy
* cpp-test
* lint-typos
* py-test
* lint-py-fmt-check
* py-build
* cpp-build-doc-examples
```

**Comment by ruben-arts** [comment]
Thanks! This is why we need real world users!
