### ISSUE TITLE
"pixi shell" not working in Windows PowerShell when environment contains Python

### ISSUE THREAD

**Issue by moqmar** [prefix-dev/pixi#437]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
PS C:\Temp\pixi-test> pixi init -c main
✔ Initialized project in C:\Temp\pixi-test\.
PS C:\Temp\pixi-test> pixi add python
✔ Added python 3.12.0.*
PS C:\Temp\pixi-test> pixi shell -vvv
DEBUG pixi::cli::shell: Pixi environment activation:
{"PIXI_PACKAGE_VERSION": "0.1.0", "PIXI_PACKAGE_MANIFEST": "C:\\temp\\pixi-test\\pixi.toml", "SSL_CERT_FILE": "C:\\temp\\pixi-test\\.pixi/env\\Library\\ssl\\cacert.pem", "CONDA_DEFAULT_ENV": "pixi-test", "PIXI_PROMPT": "(pixi-test) ", "__CONDA_OPENSLL_CERT_FILE_SET": "\"1\"", "PIXI_PACKAGE_NAME": "pixi-test", "PIXI_PACKAGE_PLATFORMS": "win-64", "Path": "C:\\temp\\pixi-test\\.pixi/env;C:\\temp\\pixi-test\\.pixi/env\\Library/mingw-w64/bin;C:\\temp\\pixi-test\\.pixi/env\\Library/usr/bin;C:\\temp\\pixi-test\\.pixi/env\\Library/bin;C:\\temp\\pixi-test\\.pixi/env\\Scripts;C:\\temp\\pixi-test\\.pixi/env\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;...;C:\\Users\\...\\AppData\\Local\\pixi\\bin\\;C:\\Users\\.../.pixi/bin", "CONDA_PREFIX": "C:\\temp\\pixi-test\\.pixi/env", "PIXI_PACKAGE_ROOT": "C:\\temp\\pixi-test"}
DEBUG rattler_shell::shell: Guessing ShellEnum. Parent process name: powershell.exe and args: ["powershell.exe", "-NoLogo", "-NoExit", "-File", "C:\\Users\\...\\AppData\\Local\\Temp\\.tmp9gcnGN.ps1"]
In C:\Users\...\AppData\Local\Temp\.tmpImlVBM.ps1:6 Zeichen:42
+ ${Env:__CONDA_OPENSLL_CERT_FILE_SET} = ""1""
+                                          ~~~
Unerwartetes Token "1""" in Ausdruck oder Anweisung.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\Temp\pixi-test> pixi --version
pixi 0.6.0
```

### Issue description

I can't enter a pixi shell when the environment exists. Running "pixi shell" before the first "pixi add" and then running "pixi add" within the shell works fine, but when I leave the environment I can't re-enter it again.

***Note:*** I've also tried it with installing "git" instead of "python", in which case the environment works completely fine.

The error message is the following:

> `${Env:__CONDA_OPENSLL_CERT_FILE_SET} = ""1""`  
> Unexpected Token "1""" in expression or statement.

### Expected behavior

I can access a pixi shell with "pixi shell" in an existing project that uses a Python package.

**Comment by ruben-arts** [comment]
Could you help me find the file that creates that environment variable. 

There should be files in the `.pixi/env/etc/conda/activate.d` which set these variables. Is this true and what is the files name/content.

**Comment by moqmar** [comment]
```
PS C:\Temp\pixi-test> cat .\.pixi\env\etc\conda\activate.d\openssl_activate.ps1
if (-not $Env:SSL_CERT_FILE) {
    $Env:SSL_CERT_FILE = "$Env:CONDA_PREFIX\Library\ssl\cacert.pem"
    $Env:__CONDA_OPENSLL_CERT_FILE_SET = "1"
}
```

I also noticed than when I run "conda activate -n base" before "pixi shell", everything works.

The file `C:\Users\...\AppData\Local\Temp\.tmpImlVBM.ps1` indeed contains the line with `""1""` (too many quotes) - that file specifically contains the following two additional lines compared to when "conda activate -n base" was run before:

```
${Env:__CONDA_OPENSLL_CERT_FILE_SET} = ""1""
${Env:SSL_CERT_FILE} = "C:\temp\pixi-test\.pixi/env\Library\ssl\cacert.pem"
```

**Comment by ruben-arts** [comment]
Thanks, I think we do something wrong [here](https://github.com/mamba-org/rattler/blob/4249d7a550861a7d8686d24e8c84de3b58c45092/crates/rattler_shell/src/shell/mod.rs#L376)
in combination with https://github.com/prefix-dev/pixi/blob/5a1e96ee0b7716922945df258aea839f7e323960/src/cli/shell.rs#L50

I'll have to test some more, will get back to it.
