### ISSUE TITLE
Print executed tasks

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#438]
### Problem description

When running tasks, you only see output produced by the tasks themselves.
Especially for tasks with a long chain of dependencies, this can make it hard to see which task is currently being executed.

Let's take the following task
```toml
[tasks]
test-rust = "cargo test"
````

There are two ways to improve its output:

- Print the task name "test-rust"
- Print the executed command: "cargo test" (similar to [just](https://github.com/casey/just))

**Comment by ruben-arts** [comment]
Closing because duplicate #381

**Comment by Hofer-Julian** [comment]
I've missed that. Sorry for the noise :)
