### ISSUE TITLE
Feature request to make it possible to set default channels

### ISSUE THREAD

**Issue by moqmar** [prefix-dev/pixi#440]
### Problem description

I would like to always use Anaconda's repos as the default for new projects, or always additionally add an internal repo. With pixi, this is currently hard-coded in two places, which means that I have to specify it every time:
https://github.com/prefix-dev/pixi/blob/c75e3611f2f1cc233c81f901540e14b64191091d/src/cli/search.rs#L93 https://github.com/prefix-dev/pixi/blob/c75e3611f2f1cc233c81f901540e14b64191091d/src/cli/init.rs#L27

What I'd like to see is that being configurable, e.g. through an environment variable like `PIXI_DEFAULT_CHANNELS=main;services;conda-forge`.

**Comment by ruben-arts** [comment]
This is really easy to do but we have a "global" config in mind which this would fit into. I would like for that to materialize some more before we add configuration that we have to break in the near future.

**Comment by ruben-arts** [comment]
Closing in favor of #172

**Comment by wolfv** [comment]
One thing to note is that conda supports "Multichannels" which have slightly complicated semantics. Eg the defaults channel is actually 3 channels iirc. I'm not sure we want to follow that, yet
