### ISSUE TITLE
pixi installation fails on Linux laptop with "gzip: stdin: unexpected end of file" error

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#446]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I tried to install pixi on a lab laptop, and I am obtaining this error:

```shell
aliencub@alienCub:~$ curl -fsSL https://pixi.sh/install.sh | bash
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz
The binary will be installed into '/home/aliencub/.pixi/bin'
######################################################################## 100.0%

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

### Issue description

See "reproducible example" (that unfortunately it is happening only on a machine).

### Expected behavior

That the installation ends correctly.

**Comment by traversaro** [comment]
There is something going on with the `/tmp`  directory, if I set another directory via `TMPDIR=` everything works fine:
~~~
aliencub@alienCub:~$ mkdir $HOME/tmp
aliencub@alienCub:~$ export TMPDIR=$HOME/tmp
aliencub@alienCub:~$ curl -fsSL https://pixi.sh/install.sh | bash
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz
The binary will be installed into '/home/aliencub/.pixi/bin'
######################################################################## 100.0%
Please restart or source your shell.
~~~

However, I can't understand what is wrong with the `/tmp` dir:
~~~
aliencub@alienCub:~$ ls -ld /tmp
drwxrwxrwt 23 root root 12288 nov 10 23:26 /tmp
~~~

At this point we can close the issue if you prefer, people with similar issues hopefully will find the solution in this issue via search engines.

**Comment by traversaro** [comment]
I do not know what is going on with that machine, but anyhow I proposed a mitigation in https://github.com/prefix-dev/pixi/pull/447 (i.e. to get a better error message in this case).

**Comment by ruben-arts** [comment]
Thanks! The pr is merged so I'll close the issue
