### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by ParadaCarleton** [prefix-dev/pixi#451]
### Problem description

Hi! First, wanted to say thanks for the great package manager, I love it :)

Do you think we could get an AUR package for installing pixi on Arch Linux? Thanks!

**Comment by ruben-arts** [comment]
I think we could integrate this into our CI/CD: https://github.com/marketplace/actions/publish-aur-package

**Comment by ruben-arts** [comment]
@orhun put it on AUR https://aur.archlinux.org/packages/pixi :tada:

**Comment by orhun** [comment]
Let me submit a PR for updating the README.md as well :3
