### ISSUE TITLE
address shell mismatch of current running shell and default login shell when running `pixi shell`

### ISSUE THREAD

**Issue by TTTPOB** [prefix-dev/pixi#463]
### Problem description

I am working on a HPC, for two reasons I am using bash as my default login shell, but add a check at the end of .bashrc, if the shell should be interactive then issue `exec zsh`.
1. `bash` is the *de facto* standard. some random application will assume you are using bash as the login shell.
2. I have no permission to add `zsh` to `/etc/shell` thus I can't use `chsh` to change my default shell.

So, in this situation, `pixi shell` will have guessed that I am using `zsh`
![image](https://github.com/prefix-dev/pixi/assets/19909103/2994b2f8-664c-44d7-b824-154afe18a767)

And indeed, I am using zsh.
But the generated script will actually executed by bash, thus resulted in a syntax error.

### Possible solution
Now I can think of two work arounds.
1. let user be able to specify which shell to start when using `pixi shell` like `pixi shell zsh`
2. add a command like `conda activate` which won't involve starting a new shell.

personally I prefer solution 2 as it will allow the use of direnv.

do you have some suggestions? I have limited rust experence but I think I might be able to help.

**Comment by ruben-arts** [comment]
He @TTTPOB, 
This sounds like a bug to me as the `/tmp/pixi_env_v3b.sh` should be a zsh script if it is found as the current shell. And it should start a zsh shell. I'm unable to recreate your issue with my setup. Maybe im miss understanding the steps. Could you provide a minimal setup, with the code that runs the switch from bash to zsh. 

About your suggestion, it shouldn't be to hard to pass an executable name which is then used to figure out what script to build and what to run. Your welcome to build this into pixi. We already have a `ShellEnum` with all the options.  

Your second suggestion is something we have also been thinking about as it is also nice to have in a docker. https://github.com/prefix-dev/pixi/issues/410 Do you think that would fit here?

**Comment by TTTPOB** [comment]
> Maybe im miss understanding the steps. Could you provide a minimal setup, with the code that runs the switch from bash to zsh.

sure. 
1. confirm that bash is the default shell with `chsh`
![image](https://github.com/prefix-dev/pixi/assets/19909103/76d9fcd7-35bc-47d4-9cef-437dee85ac69)

1. add this to `$HOME/.bashrc`
```bash
# if bash interactive mode
if [[ $- == *i* ]]; then
    exec zsh
fi
```
3. restart the shell, the interactive shell should now be zsh because of the snippets we wrote in step 2
4. run
```bash
pixi init hello_world
cd hello_world
pixi add cowsay
RUST_LOG=debug pixi shell
```

**Comment by TTTPOB** [comment]
Apologies, it was my mistake. After a thorough check, I realized that I had misplaced the completion script eval "$(pixi completion --shell zsh)" in my .zshrc file. It was missing a line break in front of it. The issue has been resolved now!
