### ISSUE TITLE
Pixi installs packages twice when using pypi packages and conda packages.

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#484]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Don't have a super minimal example yet...

### Issue description

This is a huge real world example:
https://github.com/ruben-arts/differentiable-blocksworld/blob/misc/add_pixi/pixi.toml

But the installation both installs
`nvidia-cudnn-cu12` from pypi and `cudnn` from conda-forge.

My assumption is that this is because this is not noted as a python package thus not available in https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/mappings/pypi/grayskull_pypi_mapping.yaml

### Expected behavior

We should have a good way to compare the packages and make the right decisions when to install what.

**Comment by baszalmstra** [comment]
I was afraid that would become an issue. There are ways to modify the grayskull mapping to “fix” this issue. But perhaps something similar to the suggestion from this comment would help: https://github.com/prefix-dev/pixi/issues/79#issuecomment-1594920499

**Comment by ruben-arts** [comment]
This is fixed with the new mapping logic and the ability to use custom mappings.
