### ISSUE TITLE
`pixi run` should print an error if the task doesn't exist

### ISSUE THREAD

**Issue by Wumpf** [prefix-dev/pixi#485]
### Problem description

`pixi run wildtypo` exits with 1 as it should, but it doesn't print anything, making it easy to miss mistakes.
Ideally it would even do "did you mean <close match>" :)

**Comment by ruben-arts** [comment]
> `pixi run wildtypo` exits with 1 as it should

Funnily this was not really a nice way of dealing with it as bash has a different exit code for it: `127` 
Hope this helps, forgot to react to the issue and just started fixing it :smile:
