### ISSUE TITLE
`pixi run` allow executing several tasks in sequence

### ISSUE THREAD

**Issue by Wumpf** [prefix-dev/pixi#486]
### Problem description

Very minor feature request, there's good reasons to reject this one as feature bloat:

I find myself writing stuff like `pixi run codegen && pixi run cpp-docs` a lot. Would be nice to abbreviate this to `pixi run codegen && cpp-docs` (or `pixi run codegen, cpp-docs`? probably not well defined enough.

**Comment by Wumpf** [comment]
Yeah you're right, for many cases it boils down to wanting a robust way of running certain commands under a condition.
In fact we used to run codegen in particular as part of certain builds in Cargo but we had too many issues with it not being reliable enough on detecting the file changes we were interested in, also doing this in build.rs files was generally a large burden.

Another usecase for the "pure chaining" however would be running several test suites, e.g. `pixi run cpp-test rust-test` (partially made up)

**Comment by ruben-arts** [comment]
I'm sure we're also going to work on the incremental builds in the future. 

But, sorry, for now I'm going to keep it with the `pixi run cpp-test && pixi run rust-test` 
Adding the extra parsing logic would make it unnecessarily more complicated as we now let the parsing of everything after the first word over  to the `deno_task_shell`.

I personally would just add some more helper aliases:
```toml
tests = { depends_on = [ "cpp-test", "rust-test" ] }
```

Please close if you can except, if we get a significant user base that wants this we can obviously re-evaluate it :wink:

**Comment by Wumpf** [comment]
sure, makes sense! Thanks for the consideration!
