### ISSUE TITLE
pixi init . does not modify the .gitignore if it is already present 

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#487]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I tested this on Ubuntu 22.04 on WSL2 with pixi 0.7.0 :

```shell
traversaro@IITICUBLAP257:~$ mkdir testdir
traversaro@IITICUBLAP257:~$ cd testdir/
traversaro@IITICUBLAP257:~/testdir$ touch .gitignore
traversaro@IITICUBLAP257:~/testdir$ pixi init .
✔ Initialized project in /home/traversaro/testdir/.
traversaro@IITICUBLAP257:~/testdir$ cat .gitignore
```

### Issue description

From https://github.com/prefix-dev/pixi/issues/343#issuecomment-1739072486, I tought that `pixi init .`  should append a line related to .pixi directory even if the .gitignore is already present. However, this does not seem the case.

Smaller note, the comment in https://github.com/prefix-dev/pixi/blob/ac8bbf3aa945d4486a01b12f27788ec2050f5ecb/src/cli/init.rs#L116 seems outdated.

### Expected behavior

```shell
traversaro@IITICUBLAP257:~$ mkdir testdir
traversaro@IITICUBLAP257:~$ cd testdir/
traversaro@IITICUBLAP257:~/testdir$ touch .gitignore
traversaro@IITICUBLAP257:~/testdir$ pixi init .
✔ Initialized project in /home/traversaro/testdir/.
traversaro@IITICUBLAP257:~/testdir$ cat .gitignore
# pixi environments
.pixi
```

**Comment by ruben-arts** [comment]
That was indeed the whole reason for that function... Let me take a look.

**Comment by traversaro** [comment]
Thanks @ruben-arts !

**Comment by ruben-arts** [comment]
Thank you for reporting! @traversaro
