### ISSUE TITLE
Add a `remove` command

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#49]
Add a command to `remove` a dependency from the project file. Basically the opposite of the `add` command.

**Comment by Wackyator** [comment]
can this be assigned to me

**Comment by dhirschfeld** [comment]
Note: It can be incredibly useful to be able to remove a package ***without*** removing any of it's dependencies. `conda` implements this with the `--force` flag which will then *only* remove the specified package from the environment.

Discussion in:
* https://github.com/mamba-org/mamba/issues/412
* https://github.com/mamba-org/mamba/issues/1523

**Comment by baszalmstra** [comment]
@dhirschfeld I wonder what that would look like in our `pixi.toml`. When you use `pixi remove python` it would simply remove `python` from the `[dependencies]` (and co) table and then resolve and reinstall the environment.

The `pixi.toml` defines the source of truth, not the cli. You can always recreate the exact same environment from it (especially with a lockfile). So if you want to only install the dependencies of a certain package that should be specified in the `pixi.toml`. (Thats currently not supported).

If I read the usecase specified in the issues correctly I think you want to override a dependency of a project to be able to use a development version. We will most likely support this by overriding the source of a dependency:

```toml
my_dependency = { git = "some git repo URL" }
# or
my_dependency = { path = "../path_to_other_project" }
# or
my_dependency = { package = "my_dependency.conda" }
```

Doing this should be available through the pixi CLI but it will just update the pixi.toml file so that that file always contains the "truth".

> [!Note]
> This is all still future talk!

**Comment by dhirschfeld** [comment]
Being able to tell the resolver to completely ignore a required dependency (i.e. assume a compatible version is already installed) would be more in line with what I was thinking - e.g. something like:
```
my_dependency = "ignore"
```

This can also be invaluable when the dependencies are mis-specified but you need to install it regardless. With `conda` you can do that by installing the `.tar.bz2` directly which can be a useful escape-hatch.

**Comment by wolfv** [comment]
Mamba and conda also have a --no-deps and --only-deps flag. We could add that in pixi.toml

**Comment by goyalyashpal** [comment]
_self hide as offtopic_

----
> [!Note]
> This is all still future talk!

so, github gave green flag to this feature, wow....
