### ISSUE TITLE
Document the `pypi-dependencies` feature

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#500]
Docs we need:
- [ ] The version spec that we are using.
- [ ] CLI
- [ ] What is still missing, `git` dependencies and such. To avoid a stream of questions.

**Comment by brainstorm** [comment]
A way to disable the ALPHA warning?:

```
 WARN pixi::project: ALPHA feature enabled!

It looks like your project contains `[pypi-dependencies]`. This feature is currently still in an ALPHA state!

You may encounter bugs or weird behavior. Please report any and all issues you encounter on our github repository:

	https://github.com/prefix-dev/pixi.
```

**Comment by wolfv** [comment]
I think we are progressing quite rapidly with `rip`. We could think about making the warning smaller, and make it disappear all the way at the end of the year. 

Or we could store on disk that we have already shown the warning and only show it once.

**Comment by ruben-arts** [comment]
Yeah one more big release and it should be gone. The adjacent milestone to this issue describes the steps until we will let go of the warning.
