### ISSUE TITLE
Lockfiles & PyPI sdist packages / pixi git dependencies

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#505]
### Problem description

When we add a package that needs building to our dependencies (for the near term this concerns `sdist` packages from PyPI, but in the future this will also concern source/git depenedencies for conda/pixi packages) we create a temporary build environment. 
We need to decide wether we want to record the build environment resolution into the lockfile as well, possibly as a "nested" lockfile.

On the one hand it would be great in the name of additional determinism. 

On the other hand it has the potential to blow up the size of our lockfile a bit more.

For Python SDists, the list of build-time dependencies is usually small (at least for Python only packages).

I am trying to kick off a discussion here on what we should do :)

**Comment by vsoch** [comment]
I'd like to have this feature too. I'm not sure if this is possible, but I wonder if `--pypi` (in that it would use pip) could handle something similar to:

```
pixi add --pypi git+https://github.com/snakemake/snakemake.git@main
```
As a workaround I've installed pip to my pixi environment and am doing that:

```
pip install  git+https://github.com/snakemake/snakemake.git@main
```
Of course I risk a package maintainer jumping through the window from a helicopter and bonking me in the head.

**Comment by ruben-arts** [comment]
closing in favor of https://github.com/prefix-dev/pixi/issues/1797
