### ISSUE TITLE
Global config for Pixi

### ISSUE THREAD

**Issue by melund** [prefix-dev/pixi#523]
### Problem description

Pixi needs a way to set global configuration settings. 

Similar to `conda config`, or maybe inspired from other package managers, if there are better solutions.

**Comment by pavelzw** [comment]
Duplicate of #172

**Comment by melund** [comment]
@pavelzw, Ahh Sorry about that. @wolfv asked me to [create an issue](https://discordapp.com/channels/1082332781146800168/1082338253925003385/1179528935072075877), so I did think to search first.
