### ISSUE TITLE
Improve the error messages when failing to solve with pypi dependencies

### ISSUE THREAD

**Issue by kszlim** [prefix-dev/pixi#533]
### Problem description

Right now if you have conda and pypi dependencies and the pypi dependencies fail to solve, you'll see that something is locked but you won't know why it's locked (ie. what top level target you have in your conda deps section that's pulling it in and the recursive requirements from that target). Ideally you'd get enough information in the error for you to resolve it without ever needing to reference a lockfile (which might not exist at all if you're failing to solve from the beginning).

**Comment by ruben-arts** [comment]
We're currently thinking on how we should get more information to the solver. This will hopefully help with giving better issues.

**Comment by ruben-arts** [comment]
Closing because this got a huge overhaul in the last year
