### ISSUE TITLE
Simplified support for binary dependencies

### ISSUE THREAD

**Issue by burdiyan** [prefix-dev/pixi#540]
### Problem description

Often times there's some tool that doesn't exist as a Conda package, but might have its own binary releases for all the platforms (e.g. on GitHub release page). It would be really nice if Pixi was able to download them, extract the archive, verify the hashes if necessary, etc. For these simple ad-hoc tools creating the whole new full-blown Conda package might be an overkill, so having a simplified way to get binary releases would be helpful.

I remember reading something somewhere that Pixi does (or wants to) support source packages for Conda, i.e. build the Conda package locally and "execute" it to download the final artifact, all in one go, but now I can't anything related. Having this could help quite a bit too.

I could implement something similar using PyPi package, but apparently Pixi doesn't support source PyPi dependencies either.

**Comment by ruben-arts** [comment]
We're currently not planning to add "any binary" support. The source support will definitely come some time soon. The conda package build command will most likely be `pixi build` but for that we need to get the library we are going to use for it to a more feature rich state: [rattler-build](https://github.com/prefix-dev/rattler-build)

The PyPI source dependencies might also not be far as we are working on proper build support in [rip](https://github.com/prefix-dev/rip).

**Comment by burdiyan** [comment]
Is there a GitHub issue to follow on the implementation of PyPi source dependencies in `rip`?

**Comment by baszalmstra** [comment]
There is this one: https://github.com/prefix-dev/rip/issues/119

**Comment by ruben-arts** [comment]
Will close as unplanned
