### ISSUE TITLE
Allow putting `pixi/bin/` in a global location

### ISSUE THREAD

**Issue by maphew** [prefix-dev/pixi#541]
### Problem description

I'd like to be able to put pixi and the global installs outside of the user profile directory tree. 
For example `C:\apps\pixi` on windows.

Reading the related #172 it seems this is also wanted for other global items,

**Comment by ruben-arts** [comment]
This would indeed be linked to the global config feature!

**Comment by ruben-arts** [comment]
This can now be set with the `PIXI_HOME` env variable
