### ISSUE TITLE
Pixi resolves depends_on in incorrect order

### ISSUE THREAD

**Issue by nugend** [prefix-dev/pixi#549]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```pixi.toml
[project]
name = "pixi-bug"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

root = "echo root"

task1 = {cmd="echo task1", depends_on=["root"]}
task2 = {cmd="echo task2", depends_on=["root"]}

top = {cmd="echo top", depends_on=["task1","task2"]}
```

```shell
$pixi run top                                                      
✨ Pixi task: echo task1
task1
✨ Pixi task: echo root
root
✨ Pixi task: echo task2
task2
✨ Pixi task: echo top
top
```

### Issue description

Pixi executes tasks in the incorrect order based on the dependencies.

Reproducible on both linux and osx arm

### Expected behavior

root task should be run first, followed by either task1 or task2 then top task.

**Comment by ruben-arts** [comment]
We're doing a `post order traversal` which in the case of multiple depends on one task will not work. So we're changing it to a `topological sort`.
