### ISSUE TITLE
Activation with powershell scripts opens file instead of executing it

### ISSUE THREAD

**Issue by melund** [prefix-dev/pixi#551]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

On Windnows add an activation section to `pixi.toml`

```toml
[activation]
scripts = ["setup.ps1"]
```
Create a `setup.ps1` with any content. 

```powershell
$env:MY_ENV_VAR="Hello World"
```

Now activate the shell:

```shell
PS> pixi shell
```

This opens the `setup.ps1` file in NotePad, instead of executing it. Shell activation hangs until the file is closed.

### Issue description

On Windows activations using powershell scripts doesn't work. They open the script file in Notepad instead of executing it. 

![image](https://github.com/prefix-dev/pixi/assets/1038978/02c0d630-f1b1-449f-a61e-0e36d1643be7)

Using `*.bat` files works fine as workaround. 

### Expected behavior

The powershell script should run.

**Comment by melund** [comment]
> For now I'll update the documentation to explain this behavior. Would that be enough for you?

Yes . Of course :) Documentation just hinted that it had or was supposed to work.

![Screenshot_20231211-170831.png](https://github.com/prefix-dev/pixi/assets/1038978/0c61b21d-a750-4d53-9d49-833c3c899b57)

**Comment by ruben-arts** [comment]
Oops haha, that was a mistake!

**Comment by ruben-arts** [comment]
Fixed in : https://github.com/prefix-dev/pixi/pull/563
