### ISSUE TITLE
Retrieve the version from another file

### ISSUE THREAD

**Issue by gouarin** [prefix-dev/pixi#554]
### Problem description

The version number of a package can be generated automatically using [conventional commits](https://www.conventionalcommits.org) and associated tools such as [release-please](https://github.com/googleapis/release-please). 

The result is often stored in a specific file: for example version.txt.

It would be a real plus if pixi could retrieve the version number instead of hard-coding it, as is currently the case. As is done, for example, in `pyproject.tom` with `dynamic = ["version"]`.

**Comment by ruben-arts** [comment]
We removed the need for adding a `version` to the `pixi.toml` so its optional right now. As soon as we're able to build a package we will force the users to add a version and maybe this feature then becomes useful! 
If you are okay with the answer could you close this issue for now to avoid clutter.

**Comment by gouarin** [comment]
Thanks @ruben-arts for the answer.
