### ISSUE TITLE
Pixi has trouble installing mlx / improve error message for no matching wheels based on macOS version

### ISSUE THREAD

**Issue by rahuldave** [prefix-dev/pixi#562]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init mlx
cd mlx
pixi add python=3.10
pixi add --pypi mlx
```

```
(mlx) ➜  mlx pixi add --pypi mlx
  × The following packages are incompatible
  │ |-- mlx * cannot be installed because there are no viable options:
  │     |-- mlx 0.0.4 is excluded because none of the artifacts are compatible
  │ with the Python interpreter or glibc version
  │     |-- mlx 0.0.3 is excluded because none of the artifacts are compatible
  │ with the Python interpreter or glibc version
  │     |-- mlx 0.0.2 is excluded because none of the artifacts are compatible
  │ with the Python interpreter or glibc version
  │     |-- mlx 0.0.2.dev20231130 is excluded because prereleases are not
  │ allowed
```

### Issue description

mlx is the new machine learning library from Apple. It comes with wheels.

in pixi shell `pip install mlx` suceeds with pixi's python 3.10. mlx can then be imported.

### Expected behavior

The installation shouyld work, i think?

**Comment by ruben-arts** [comment]
Its hard to test for me as it is only available for `osx-arm64`. Maybe @wolfv or @tdejager could debug why this doesn't work.

**Comment by wolfv** [comment]
I just checked and I get a similar error message. With `rip` itself it works, though. 

I also think the `glibc` error message is a bit misleading since that doesn't really make sense on osx ...

**Comment by tdejager** [comment]
Yeah, so I tested with the master branch of `rip` merged into `pixi` and I'm running into the same issue. Even though it works with `rip` directly. We will need to investigate further, thanks for the report!

**Comment by tdejager** [comment]
So it seems it cannot select the correct version because of the `WheelTags` that are being passed to the dependency resolution algorithm. Will have some more info later :)

**Comment by wolfv** [comment]
Actually, I just debugged this a little bit and the problem lies in our conservative macOS version choosing. We select an old macOS version but the `mlx` wheels are only compatible with more recent versions.

If you add the following to your `toml`:

```toml
[system-requirements]
macos = "14.0"
```

It will start to work.

We will definitely have to make the error message better and give actionable advice.

**Comment by rahuldave** [comment]
Super debugging! Thank you folks!!

**Comment by tdejager** [comment]
Thanks! We were already discussing making the error clearer, I mean even we had to dig into the code 😅 Alright if we close this?

**Comment by rahuldave** [comment]
Yes, totally! Happy mlx+pixi user here!
