### ISSUE TITLE
Add `pixi project version {major,minor,patch}` commands

### ISSUE THREAD

**Issue by hadim** [prefix-dev/pixi#581]
### Problem description

Blocked by https://github.com/mamba-org/rattler/issues/449

**Comment by hadim** [comment]
This is a follow up of https://github.com/prefix-dev/pixi/issues/575 and https://github.com/prefix-dev/pixi/pull/579 but we don't want to block the ongoing PR.

**Comment by hadim** [comment]
@ruben-arts happy to take the lead on this one once https://github.com/mamba-org/rattler/issues/449 is merged and a new rattler release is cut.

I tried to compile pixi with rattler from https://github.com/mamba-org/rattler/issues/449, but I have a few compilation errors not related that should be fixed first.

**Comment by ruben-arts** [comment]
@hadim yeah you are right, there are some differences between rattler main and the latest release that don't work in pixi. 

The best experience for you would be to wait for a new release.

**Comment by hadim** [comment]
Ok if I wrap up this one, given the latest 0.15 rattler release?

**Comment by hadim** [comment]
I gave it a try at https://github.com/prefix-dev/pixi/pull/633
