### ISSUE TITLE
Document usage of cuda under system-requirements group

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#590]
### Problem description

I noticed that users are confused on how to use cuda with pixi, see https://github.com/ami-iit/jaxsim/pull/63#issuecomment-1867749119 . I discovered its use in https://github.com/prefix-dev/pixi/issues/32#issuecomment-1571543747, but probably it could make sense to document it in https://github.com/prefix-dev/pixi/blob/40200b6e432fa320d6575f3103d84ce8d4cd61d9/docs/configuration.md?plain=1#L144 .

**Comment by ruben-arts** [comment]
Good that you point it out!
