### ISSUE TITLE
Cannot `pixi remove --pypi package`

### ISSUE THREAD

**Issue by dangraysf** [prefix-dev/pixi#591]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
[project]
name = "pixi_fun"
version = "0.1.0"
description = "Add a short description here"
authors = ["Daniel Gray <dangraysf@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
hello = "python hello_world.py"

[dependencies]
python = ">=3.12.1,<3.13"
jupyter = ">=1.0.0,<1.1"
pytorch = ">=2.1.0,<2.2"

[pypi-dependencies]
jax = { version = "*", extras = ["cpu"] }

*****

My example:
>pixi remove jax

Couldn't find jax in [dependencies]
```

### Issue description

I am unable to pixi remove a pypi installed package.

### Expected behavior

I was able to easily remove cowpy, which was installed via pix add cowpy (likely via conda-forge.

Thx!!

**Comment by ruben-arts** [comment]
Hey @dangraysf, we indeed do not support that yet. I changed it into an enhancement request. And a good first issue. As it shouldn't be to complicated to add. 

We should have this solved when the pypi feature is not an alpha feature anymore!
