### ISSUE TITLE
Pixi not working with wolfi docker container

### ISSUE THREAD

**Issue by codegod100** [prefix-dev/pixi#599]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

when I run pixi in docker container with wolfi I get   x The platform you are running on should at least have the virtual package
  | __glibc on version 2.17, build_string: 0
wolfi uses glibc-2.38-r8

### Issue description

on fresh docker image using wolfi-base

### Expected behavior

execute script

**Comment by ruben-arts** [comment]
I tried this. 

You can recreate with:
```dockerfile
FROM cgr.dev/chainguard/wolfi-base

RUN apk update && apk add bash curl

ENV SHELL=bash
RUN curl -fsSL https://pixi.sh/install.sh | bash
```

Then 
```
docker build -t wolfi-pixi . 
docker run -it wolfi-pixi
```

You'll see that running `ldd --version` is not available. 
Which is the check we do, this is part of [`rattler`](https://github.com/mamba-org/rattler/blob/main/crates/rattler_virtual_packages/src/libc.rs#L38)

We'll need to find a different way to check the version to support linux images that don't contain `ldd`.

Meanwhile you could workaround this by running
``` 
apk add posix-libc-utils
```
