### ISSUE TITLE
Add `global upgrade` and `global upgrade-all` command

### ISSUE THREAD

**Issue by trueleo** [prefix-dev/pixi#613]
### Description 
Pixi currently provides `global install` to install binary packages globally. However there is no upgrade subcommand to upgrade packages.

There is an existing [issue](https://github.com/prefix-dev/pixi/issues/73#issuecomment-1670930243) where people have commented about wanting this feature. 

### Note / Ideas
* `pixi global install` can be used to upgrade a single package. So maybe `upgrade` subcommand can just be alias/proxy to install command.

**Comment by ruben-arts** [comment]
Perhaps we could move even more into an `fn globally_install_package` or whatever the best name would be and the call that function in both the install and upgrade commands. Then we can keep the info for the user as you have done it now. Including the checking if the package is available (which I would indeed make an error).
