### ISSUE TITLE
Configurable `PIXI_DIR`

### ISSUE THREAD

**Issue by chawyehsu** [prefix-dev/pixi#619]
### Problem description

Currently `PIXI_DIR` is hardcoded to `$HOME/.pixi` / `%USERPROFILE%\.pixi`, make it be configurable would increase the portability of pixi. Environment variable like micromamba's `MAMBA_ROOT_PREFIX` may be introduced to support this, and `XDG_CONFIG_HOME/.pixi` as the fallback.

**Comment by baszalmstra** [comment]
Are you referring to the installation script? Or for `pixi global install ..`?

I'd be more than happy to accept a PR for this!

The only nitpick I have is that I think `PIXI_HOME` might be a better name to not confuse it with the `.pixi` folder that is generated in a project.

**Comment by RoyiAvital** [comment]
I think I'm after the same feature.
I'd start that I couldn't understand from documentation the work model of `pixi`.

In `micromamba` I have the following mental model:

1. Set `MAMBA_ROOT_PREFIX`. Made it the working folder.
2. Assuming `micromamba.exe` in `MAMBA_ROOT_PREFIX` Run `.\micromamba shell hook -s powershell | Out-String | Invoke-Expression`.
This hook set environment variables and path to use `micromamba` and apply the Auto Complete.
3. Run `micromamba create -f <EnvFile>` to create an environemnt. By default it is global and the packages are in `$MAMBA_ROOT_PREFIX\envs<EnvName>`.
4. Activate any environment by `micromamba activate <EnvName>`.

The nice thing, everything is portable. Move the whole `MAMBA_ROOT_PREFIX` folder to another computer and all is working.

If I get it right, in `pixi` each workspace is basically equivalent to `MAMBA_ROOT_PREFIX` on its own?
Yet it is localized to a folder? 

I'd be happy to be able to set a mode for `pixi` to behave just like `micromamba`.
