### ISSUE TITLE
refactor PyPiRequirement to use `serde_untagged`

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#621]
I stumbled upon `serde_untagged` and I think it would be very useful to remove some of the complexity of the `Deserialize` impl for `PyPiRequirement`. See:

https://github.com/prefix-dev/pixi/blob/dc5bab5b7c7d06925d3a799207adf66e77a864ba/src/project/python.rs#L134

Might be a nice "first issue".

**Comment by marcelotrevisani** [comment]
I am not sure if this is what you meant, but I am happy to give it a go
https://github.com/prefix-dev/pixi/pull/622
