### ISSUE TITLE
[pypi] Allow pre-releases to be installed

### ISSUE THREAD

**Issue by ismail** [prefix-dev/pixi#625]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
❯ pixi add --pypi duckdb==0.9.3.dev2258
 WARN pixi::project::manifest: BETA feature `[pypi-dependencies]` enabled!

Please report any and all issues here:

	https://github.com/prefix-dev/pixi.

Turn this warning off by setting the environment variable `PIXI_BETA_WARNING_OFF` to `true`.

  × The following packages are incompatible
  │ |-- duckdb ==0.9.3.dev2258 cannot be installed because there are no viable options:
  │     |-- duckdb 0.9.3.dev2258 is excluded because prereleases are not allowed
```

### Issue description

pixi by default does not allow installing pre-releases, even if explicitly requested.

### Expected behavior

It should be possible to install pre-releases for PyPI.

**Comment by ruben-arts** [comment]
Hey we are aware if this, this is currently by design. The implementation issue is in rip: https://github.com/prefix-dev/rip/issues/4

**Comment by ismail** [comment]
OK, no need to keep two bugs open. Closing this one in favour of that, thanks!
