### ISSUE TITLE
SVGs in README slow down entire repo front page in Safari

### ISSUE THREAD

**Issue by jonashaag** [prefix-dev/pixi#626]
The animated SVGs on the Pixi repo front page (and other repo's front pages) slow down Safari a lot.

**Comment by chawyehsu** [comment]
Resource included with links like `https://github.com/prefix-dev/pixi/assets/4995967/a3f9ff01-c9fb-4893-83c0-2a3f924df63e` on the README can't take advantage of image caching, making the situation worse. I [tried to replace them with links having image extesions](https://github.com/prefix-dev/pixi/commit/8f1b7ac6b68486298ea7d3b4515d8f0eff90af30), then image caching works but the huge (500KB) svg is still a painful point.

Everytime I browse the repository I feel so bad about the performance.

**Comment by ruben-arts** [comment]
![pixi_cowpy](https://github.com/prefix-dev/pixi/assets/12893423/0fc8f8c8-ac13-4c14-891b-dc613f25475b)
Hopefully this is a better as it is a gif
