### ISSUE TITLE
Install script: do not miserably fail if curl is not installed and wget is installed

### ISSUE THREAD

**Issue by paugier** [prefix-dev/pixi#637]
### Problem description

On Linux, it is very common to have GNU wget installed and not curl.

The install script should support using wget.

**Comment by ruben-arts** [comment]
Why doesn't it support `wget`?

**Comment by wolfv** [comment]
@ruben-arts I think we're hardcoding `curl` here: https://github.com/prefix-dev/pixi/blob/234a5d0a951f0a0b7ecd5aae0594214b97294e99/install/install.sh#L53-L57

**Comment by ruben-arts** [comment]
Ah I see, problem for me was that the Ubuntu images also doesn't have `wget` thus I opted to use curl as I saw that more often. But feel free to modify it so it can use both!

**Comment by paugier** [comment]
> @paugier do you think you can try this code?

I should be able to try this evening!

**Comment by paugier** [comment]
I confirm that it works without curl!
