### ISSUE TITLE
`pixi add` only works on the project's supported platform

### ISSUE THREAD

**Issue by konstantinjdobler** [prefix-dev/pixi#650]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
[project]
channels = ["conda-forge"]
platforms = [
"linux-64", 
# "osx-arm64"
]
name = "bug"

[dependencies]
python = "=3.11.*"
```

Output:
```shell
  × the project is not configured for your current platform
   ╭─[pixi.toml:2:1]
 2 │     channels = ["nvidia", "conda-forge", "pytorch-nightly"]
 3 │ ╭─▶ platforms = ["linux-64",
 4 │ │   #  "osx-arm64"
 5 │ ├─▶ ]
   · ╰──── add 'osx-arm64' here
 6 │     name = "nordwind"
   ╰────
  help: The project needs to be configured to support your platform (osx-arm64).
```

### Issue description

E.g. when on M1 Macs, `pixi add ruff` would fail when `"osx-arm64"` is commented out. `pixi add --no-install ruff` also fails.   

### Expected behavior

I know `pixi` supported building lockfiles for another platform some time ago. Is this intended? I am using version `0.11.0`.

**Comment by ruben-arts** [comment]
Using the `--no-install` to avoid this error is a good idea! 

I can't remember that we supported the adding of a package without also being on that platform but that might be something we want to get in there.

**Comment by konstantinjdobler** [comment]
Just FYI: it worked for me in 0.6.1 (big jump I know, I just upgraded yesterday). 

I think not installing with a warning would be great! The use case of creating lockfiles for another platform might be quite common if the actual code runs on a remote machine with a potentially different OS than the local one.

**Comment by tdejager** [comment]
I think it would be better to make the `--no-install` flag function correctly, because the behavior is explicit when looking ath the CLI and the same regardless of the platform. But I can be convinced otherwise ;)
