### ISSUE TITLE
0.11.1 ERROR rattler::install::link: failed to reflink ...

### ISSUE THREAD

**Issue by liquidcarbon** [prefix-dev/pixi#652]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Using `export PIXI_VERSION=vX.Y.Z && curl -fsSL https://pixi.sh/install.sh | bash` checked that this was not happening on 0.10.0 but is happening on 0.11.1

```
[dependencies]
python = ">=3.12.0,<3.13"
pip = ">=23.3.2,<23.4"
notebook = ">=7.0.6,<7.1"
```

### Issue description

on `pixi install`, throwing numerous errors like below, though the resulting environment and `pixi run` commands still work

```
ERROR rattler::install::link: failed to reflink /home/coder/kr2/.pixi/env/lib/python3.12/site-packages/pythonjsonlogger/jsonlogger.py: Not supported (os error 95), falling back to hard linking.
ERROR rattler::install::link: failed to reflink /home/coder/kr2/.pixi/env/lib/python3.12/site-packages/pythonjsonlogger/py.typed: Not supported (os error 95), falling back to hard linking.
```

### Expected behavior

not throw a long list of errors? :)

**Comment by baszalmstra** [comment]
Thanks for reporting! We will fix this asap!

**Comment by baszalmstra** [comment]
This is fixed in upstream rattler: https://github.com/mamba-org/rattler/pull/475

**Comment by ruben-arts** [comment]
This will be fixed in the next release as we are now using rattler `0.16.2`, will close this for now!
