### ISSUE TITLE
Ability to add/install without access to name mapping from github

### ISSUE THREAD

**Issue by sebejias** [prefix-dev/pixi#660]
### Problem description

After upgrading to 0.11.1, pypi dependency solving now reaches out to github for a name mapping ( #494 ).  Pixi has been *fantastic* for working in isolated environments that rely strictly on internal repos and on-site mirrors, but where this sadly doesn't work.

Would it be possible to skip this if no `pypi-dependencies` are requested?

Or, looking forward to private pip registry support (#588), could there be a way to provide a name mapping file/URL?

```shell
$ pixi init && pixi install
✔ Initialized project in ...
  × failed to download pypi name mapping
  ├─▶ error sending request for url (https://raw.githubusercontent.com/regro/cf-graph-countyfair/
  │   master/mappings/pypi/name_mapping.json): error trying to connect: dns error: failed to lookup address information: Name or service not known
  ├─▶ error trying to connect: dns error: failed to lookup address information: Name or service not known
  ├─▶ dns error: failed to lookup address information: Name or service not known
  ╰─▶ failed to lookup address information: Name or service not known
```

**Comment by baszalmstra** [comment]
This should only happen if you define pypi dependencies. Is that something you do?

We could do without the name mapping but that would significantly degrade how well we are able to map conda to pypi packages. This would most likely result in some weird behavior and errors in the environment.

In the future we hope to be able to ship this mapping alongside the conda channel data.

Alternatively we could potentially ship with a hard-coded mapping. 🤔

**Comment by baszalmstra** [comment]
@ruben-arts  yes, in fact, that should already be the case!

**Comment by ruben-arts** [comment]
This will probably help #661, I couldn't find the code that would do a check like this so I added it here. 

This isn't a complete fix for the GitHub fetching problem but now it will only be run if it is actually used.

**Comment by baszalmstra** [comment]
Nice yeah that was a bug!

**Comment by sebejias** [comment]
Thank you for the quick response, this works great!  Yeah, without private pypi support, I am typically only using conda dependencies.

I was unsure whether to call it a bug or feature request, but asking about the future case with private pip registries seemed feature-like.  The mapping being shipped with conda channel data is truly the ideal case.  Being able to provide one might be nice for the case of several conda channels.  This all seems like it will be well handled. :-)

Again, thank you so much!  `pixi` truly has been a joy to use.

**Comment by ruben-arts** [comment]
I'll close the issue for now as the additional work is part of the multiple python indices.
