### ISSUE TITLE
Can't use `anaconda` channel

### ISSUE THREAD

**Issue by xiaoxiangmoe** [prefix-dev/pixi#669]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
mkdir hello && cd hello
pixi init --channel anaconda --channel conda-forge --platform win-64 --platform linux-64 --platform osx-64 --platform osx-arm64
pixi add python gym-box2d tensorflow
```

### Issue description

```
λ ~/hello/ master* pixi add python gym-box2d tensorflow
0: at line 1, in Digit:
>=*
  ^

1: at line 1, in Alt:
>=*
  ^

2: at line 1, in components:
>=*
  ^

3: at line 1, in version:
>=*
  ^


thread 'main' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/rattler_solve-0.16.1/src/resolvo/mod.rs:368:84:
called `Result::unwrap()` on an `Err` value: InvalidVersionAndBuild(">=*")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

no error

---

### Extra info

* In [conda-forge channel](https://anaconda.org/conda-forge/tensorflow), tensorflow version of win64 is v1.14.0
* In [anaconda channel](https://anaconda.org/anaconda/tensorflow), tensorflow version of win-64 is v2.10.0

So we need install tensorflow in anaconda channel

* In [conda-forge channel](https://anaconda.org/conda-forge/gym-box2d), gym-box2d exist
* In [anaconda channel](https://anaconda.org/anaconda/gym-box2d), gym-box2d not exist

So we need install gym-box2d in conda-forge channel

### real world use case

```
mkdir hello && cd hello
pixi init --channel anaconda --channel conda-forge --platform win-64 --platform linux-64 --platform osx-64 --platform osx-arm64
pixi add python jupyter numpy matplotlib nodejs ipympl ipywidgets scikit-learn tensorflow networkx pydot plotly pandas bokeh tabulate imageio pyvirtualdisplay gym-box2d imageio-ffmpeg
```

**Comment by ruben-arts** [comment]
Thanks for the reproducible example. After one round of debugging it seems there is a dependencies that has a `>=*` which doesn't really make sense. 
I found one in the `osx-64` repodata of the anaconda channel:
```json
"tapi-1000.10.8-ha1b3eb9_0.tar.bz2": {
      "build": "ha1b3eb9_0",
      "build_number": 0,
      "depends": [
        "libcxx >=*"
      ],
      "license": "UIUC",
      "license_family": "MIT",
      "md5": "7b162e44c4d1d87fb6fb63f11764c0ca",
      "name": "tapi",
      "sha256": "d750128a40f92e1125f583f57474f6b26bb168cd65b07e01a74e813d24dcfd62",
      "size": 5145518,
      "subdir": "osx-64",
      "timestamp": 1589529700015,
      "version": "1000.10.8"
    },
```

**Comment by ruben-arts** [comment]
I requested a change on that channel: https://github.com/AnacondaRecipes/repodata-hotfixes/issues/220

**Comment by xiaoxiangmoe** [comment]
@ruben-arts Is there any work around for this?

**Comment by ruben-arts** [comment]
@xiaoxiangmoe It either gets removed from the channel or we have to deal with it in some other way. But I assume this was a mistake as the requirement doesn't make any sense :sweat_smile:

**Comment by xiaoxiangmoe** [comment]
Okay, I'll remove anaconda channel now. Thanks for your reply.

**Comment by baszalmstra** [comment]
It looks like anaconda is not really responding to our hotfix so I just added support for this in rattler: https://github.com/mamba-org/rattler/pull/551
