### ISSUE TITLE
Notarize binaries on macOS

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#67]

**Comment by baszalmstra** [comment]
Starship has a pretty elaborate workflow, including notarizing the binaries: https://github.com/starship/starship/blob/master/.github/workflows/release.yml

**Comment by wolfv** [comment]
That looks really good. I wonder if we need to obtain a apple ID for prefix?

**Comment by wolfv** [comment]
We are signing the binaries now. If we ever distribute a `.dmg` or `.pkg` file we should revisit this – then we can `staple` the notarization certificate to the binary.
