### ISSUE TITLE
add env var option in install.sh to not update ~/.profile 

### ISSUE THREAD

**Issue by dirkpetersen** [prefix-dev/pixi#686]
### Problem description

Currently Pixi install.sh always edits ~/.profile which is not what we want for some automated installs. 

Last week a configurable PIXI_HOME was added, which is great. We are setting this to ~/.local and since ~/.local/bin is already in PATH on our machines we don't need any ~/.profile edits

**Comment by chawyehsu** [comment]
Reasonable, I can implement this, what name of the env var would you like to have, `PIXI_NO_PATH_UPDATE`?

**Comment by dirkpetersen** [comment]
Yes that sounds great

**Comment by dirkpetersen** [comment]
Also, not sure if you are also working on the micromamba installer which also has an installer issue : https://github.com/mamba-org/micromamba-releases/pull/32

**Comment by chawyehsu** [comment]
> Also, not sure if you are also working on the micromamba installer which also has an installer issue : [mamba-org/micromamba-releases#32](https://github.com/mamba-org/micromamba-releases/pull/32)

I'm not working on it, you may wait for their team members to review the fix.
