### ISSUE TITLE
os error 32 when piping a long list to 'less'

### ISSUE THREAD

**Issue by dirkpetersen** [prefix-dev/pixi#687]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
RUST_BACKTRACE=1 pixi --color never search -c bioconda -q -l 25000 '*' | less
thread 'main' panicked at library/std/src/io/stdio.rs:1019:9:
failed printing to stdout: Broken pipe (os error 32)
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

also RUST_BACKTRACE=1  does not print anything in addition 

### Expected behavior

no panic

**Comment by dirkpetersen** [comment]
This was on Amazon Linux 2023 with x86_64

```
uname -a
Linux aws-eb 6.1.66-93.164.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jan  2 23:50:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tdejager** [comment]
Might be this issue: https://github.com/rust-lang/rust/issues/46016

It only happens to me when closing `less` is that the same for you?
