### ISSUE TITLE
pixi run <typo> first activates the env before complaining

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#704]
When typing a `pixi run ...` command and mistyping, I think pixi first activates the env and then complains. 

Of course this is a bit tricky, because there might be a executable in the environment that has the name of the command. But we could also search the `bin/*` folder (on Windows there are a few more to look into).

**Comment by ruben-arts** [comment]
But you could also want something from the environment right? or even from the system environment?

There could be a ton of places to check in theory.
