### ISSUE TITLE
Configure a few CLI args via env variables

### ISSUE THREAD

**Issue by hadim** [prefix-dev/pixi#714]
### Problem description

The candidates would be:

- `--frozen`
- `--locked`
- `--quiet`/`--verbose`
- `--color`

It's convenient when consuming pixi from within a docker image, as it's easy to configure a global behavior with env variables.

**Comment by ruben-arts** [comment]
I like it! I think this can be easily done with https://docs.rs/clap/latest/clap/struct.Arg.html#method.env.

Do you know of any tools that also do this, that we can use as an example?

**Comment by hadim** [comment]
> Do you know of any tools that also do this, that we can use as an example?

None that come to my mind.

---

Are you ok if I submit a PR? That should be quite a quick one.

**Comment by ruben-arts** [comment]
Sure!, I trust you come up with a good abstraction and make sure it aligns between all cli commands that could use it.
