### ISSUE TITLE
Create a windows installer

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#72]
We could create a simple windows installer for `pixi`. That way people that are less comfortable with Cargo or the command line (students?) could very easily install the tool.

We could use https://github.com/volks73/cargo-wix for this.

**Comment by baszalmstra** [comment]
I just tried `cargo-wix` and it seems quite promising. I got a working installer in just a few minutes. We just need to tweak some of the settings generated for `wix` and add some imagery.

**Comment by pavelzw** [comment]
Adding it to chocolatey or scoop might also help. I don't know though if they accept projects this young yet.
