### ISSUE TITLE
[CLI] Support multiple packages input in `pixi global <install|remove>`

### ISSUE THREAD

**Issue by chawyehsu** [prefix-dev/pixi#724]
### Problem description

It is currently not possible to install/remove multiple packages via command `pixi global <install|remove> <package>`.

```
$ pixi global install cmake rattler-build
error: unexpected argument 'rattler-build' found

Usage: pixi global install [OPTIONS] <PACKAGE>

For more information, try '--help'.
```

Would be cool and more convenient to support multiple packages input for these commands. I may be able to implement it.

**Comment by ruben-arts** [comment]
That makes sense! Go ahead!
