### ISSUE TITLE
`pixi run` fails when inner command contains wildcards

### ISSUE THREAD

**Issue by pkgw** [prefix-dev/pixi#727]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

For my test case, set up a Pixi environment containing JupyterLab; but I suspect that this can be reproduced in a much more lightweight environment.

```shell
# in a bash shell
$ pixi run jupyter lab --no-browser --ip='*'
glob: no matches found '{myroot}/--ip=*'
```

I tried adding a `--` in there but that didn't change anything.

### Issue description

It seems to me that `pixi run` has some kind of wildcard detection that is failing when I am trying to run a command whose arguments contain them.

### Expected behavior

The intention is that the JupyterLab process should receive a literal asterisk in its arguments.

Other cases:

```
# I would want this command to echo a single asterisk, not shell-expand
$ pixi run echo '*'
pixi.lock pixi.toml
```

And:

```
# oops!
$ pixi run echo '&'
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_task_shell-0.14.2/src/shell/mod.rs:148:28:
`spawn_local` called from outside of a `task::LocalSet`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ruben-arts** [comment]
After some more debugging, the only way I can get this to work is to do the following:
```
pixi run jupyter lab --no-browser --ip="'*'"
```
So `"` and then `'` to avoid that the shell cleans the command before sending it to pixi. I can't find a solution in pixi to avoid the shell from interacting with your command. As pixi runs it's own shell which strips it again.

**Comment by ruben-arts** [comment]
This also counts for the `&`. 
You say:
```
pixi run echo '&'
```
Your shell gives pixi:
```
echo &
```
The pixi shell then tries to run a `&` as a command in an echo which isn't possible.

**Comment by pkgw** [comment]
That makes a lot of sense as a diagnosis.

If Pixi is passing its `run` arguments through to a shell, you could imagine that it could escape any shell special characters to prevent expansion. So if I ran `pixi run echo '&&'`, it would insert backslashes to exec something like `$SHELL -c "echo \&\&"` and print out `&&`, rather than complaining about a syntax error.

Alternatively, the rule could be that "the arguments to `pixi run` are passed through in a shell one-liner, so if you want to use shell special characters, you must double-escape them". This is how `ssh` operates:

```
$ ssh mysamplehost echo '&&'
bash: -c: line 1: syntax error: unexpected end of file
```

I've often thought that behavior has potential security implications for SSH because a specially crafted filename something like `; sudo rm -rf /` could cause problems if a script does something like `ssh myhost "ls -l $filename"`.

I suppose you could even make it a mode switch: default behavior is one style (probably no-escaping), and a flag causes the other. 

Anyway, I don't think it's obvious any one of these approaches is "the best", but it would be good to document clearly the intended behavior. At the moment the `pixi run` docs aren't quite clear about the layer of shell processing that's being applied.

**Comment by humphd** [comment]
I hit this, or something similar:

```toml
[project]
name = "onnx"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
setup = "curl -o birdnet.zip https://drive.usercontent.google.com/open?id=1ixYBPbZK2Fh1niUQzadE2IWTFZlwATa3&authuser=0"

[dependencies]
curl = ">=8.7.1,<8.8"
```

```sh
RUST_BACKTRACE=full pixi run setup
✨ Pixi task (setup in default): curl -o birdnet.zip https://drive.usercontent.google.com/open?id=1ixYBPbZK2Fh1niUQzadE2IWTFZlwATa3&authuser=0
thread 'main' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/deno_task_shell-0.16.0/src/shell/execute.rs:143:28:
`spawn_local` called from outside of a `task::LocalSet`
stack backtrace:
   0:        0x102051c88 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfb3c5255bdb4eac9
   1:        0x10208cbe0 - core::fmt::write::h4f9b26a431923163
   2:        0x10205916c - std::io::Write::write_fmt::h65a3848fda965d9a
   3:        0x102051ab8 - std::sys_common::backtrace::print::hfb8e68d5340a5773
   4:        0x10206b7d4 - std::panicking::default_hook::{{closure}}::h3c1629cb3dea24df
   5:        0x10206b55c - std::panicking::default_hook::h5b4a788645c74387
   6:        0x10206bbe0 - std::panicking::rust_panic_with_hook::h2f1b18b39b6242c7
   7:        0x10205214c - std::panicking::begin_panic_handler::{{closure}}::hd6c9d27d8f83f59d
   8:        0x102051ebc - std::sys_common::backtrace::__rust_end_short_backtrace::hb3b76dda55c5a574
   9:        0x10206b968 - _rust_begin_unwind
  10:        0x102155a3c - core::panicking::panic_fmt::h737710d5a381d17b
  11:        0x1017090f4 - tokio::task::local::spawn_local::h36af9779e228fb04
  12:        0x1016cedb8 - deno_task_shell::shell::execute::execute_sequential_list::{{closure}}::hcae780168f28e152
  13:        0x1011b71fc - <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h5f616ab764ec7411
  14:        0x101387358 - pixi::cli::run::execute::{{closure}}::h533b13dea34fefc4
  15:        0x101379b98 - pixi::cli::execute_command::{{closure}}::h0da2105d8b53b84e
  16:        0x1013bb128 - tokio::runtime::park::CachedParkThread::block_on::h2992b9643798dc49
  17:        0x100f20b94 - tokio::runtime::context::runtime::enter_runtime::h97ed59053c7a8be0
  18:        0x101325588 - tokio::runtime::runtime::Runtime::block_on::h49b2337fe4613e1a
  19:        0x1010d0b70 - pixi::main::h8fa1798c62340383
  20:        0x10112dcf8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5969ae552b6733d4
  21:        0x1013c6468 - std::rt::lang_start::{{closure}}::h15fbff2642c0adfa
  22:        0x10206b860 - std::panicking::try::he7b2dbdb2ebe3a2a
  23:        0x10205452c - std::rt::lang_start_internal::h3cdb23022df8f974
  24:        0x1010d0c34 - _main
```

Changing the task to quote the URL "fixes" it:

```toml
[tasks]
setup = "curl -o birdnet.zip \"https://drive.usercontent.google.com/open?id=1ixYBPbZK2Fh1niUQzadE2IWTFZlwATa3&authuser=0\""
```

**Comment by ruben-arts** [comment]
Thanks for all your feedback.

We've fixed the * and & issue in quotes.
```
pixi on main is 📦 v0.27.1 
❯ pixi run echo '*'
*

pixi on main is 📦 v0.27.1 
❯ pixi run echo '&'
&
```

Closing the issue.
