### ISSUE TITLE
Add `update` command

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#73]
Add a command to update one or more dependencies in the `pixi.lock` file without updating the project file. If the lock file is missing, one will be created.

**Comment by ruben-arts** [comment]
Yes very nice! I think it could really nice if it could accept package names (+ versions). Which would update a package and only its dependencies with it. So you can have minimal updates.

**Comment by baszalmstra** [comment]
Yeah I think we'de have to implement minimal lock file updates for this to work anyways. 

- https://github.com/prefix-dev/pixi/issues/4

**Comment by beenje** [comment]
It would also be very nice to be able to update the global packages installed with `pixi global install`, like `pipx upgrade` and `pipx upgrade-all`.

**Comment by ruben-arts** [comment]
He @beenje, 
I think this could be helpful for the user as well. 

Currently it is easiest for the user to run "pixi global install PACKAGE" again to just update to the latest version. or `pixi global install "PACKAGE==1.2.3"` if they want a specific version.

**Comment by dhirschfeld** [comment]
> It would also be very nice to be able to update the global packages installed with `pixi global install`, like `pipx upgrade` and `pipx upgrade-all`.

I came here exactly to ask for a `pixi global update-all` (or similar). Having to manually update each package individually would be quite painful.

**Comment by pavelzw** [comment]
It would be nice to have an option with `--json` that outputs the diff in JSON. This could maybe help with a dependabot/renovate implementation.

**Comment by pavelzw** [comment]
https://github.com/prefix-dev/setup-pixi/issues/82#issuecomment-1975921585

And `pixi upgrade`

**Comment by baszalmstra** [comment]
This requires https://github.com/prefix-dev/pixi/pull/1320
