### ISSUE TITLE
Add `metadata` command 

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#74]
Add a command to get metadata information from the project in a machine-readable format.

The extractable data should include the following:

- Package metadata like the version, name, and authors.
- The dependencies of the project.
- The locked dependencies of the project. 
- Location of the conda environment

We could either format the data simply as JSON or we could use go templates to make it really customizable (there is a crate for that: https://github.com/fiji-flo/gtmpl-rust). Go templates are used by for instance [`docker`](https://docs.docker.com/config/formatting/) or `kubernetes`.

**Why?**

To make it easy for other tools to ingest information about the project. For instance, one might want to extract the version of the project to be able to use in during a build step in CMake. Or one might want to extract the information in a CI stage.

**Inspiration**

- https://doc.rust-lang.org/cargo/commands/cargo-metadata.html

**Comment by baszalmstra** [comment]
Since we have the `info` command now Im going to close this until we run into additional features we need.

**Comment by traversaro** [comment]
> For instance, one might want to extract the version of the project to be able to use in during a build step in CMake.

I had this problem (to get the version of the pixi package and use it as CMake version) but I could not use pixi as at this point I can't assume users of the library have installed, so I some CMake code to read it directly from pixi.toml : https://github.com/ami-iit/idynfor/blob/d7ab3b80c286f8e76de319c5ef2a794ceb836807/CMakeLists.txt#L21 .
For sure it is not as robust as `pixi info`, but it has the advantage of not requiring pixi at configuration time.

**Comment by wolfv** [comment]
That's really cool!
