### ISSUE TITLE
`pixi list` ignores the `--color` flag

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#741]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

`pixi list --color never` produces color output on my macbook and `pixi list --color always` produces no color on GHA

![image](https://github.com/prefix-dev/pixi/assets/29506042/a5323cb7-e832-4f6e-99c1-f9397e01a1ea)
![image](https://github.com/prefix-dev/pixi/assets/29506042/e8239f3f-47ea-4567-bd59-f49320b5cfb7)

I haven't investigated the behavior of `pixi list` with the env var `NO_COLOR` yet.

**Comment by ruben-arts** [comment]
I assume this issue is introduced by using the `comfy_table` library instead of our normal `console::style` usage.

There is logic in the comfy table that check if there is a tty and based on that it formats differently.

**Comment by baszalmstra** [comment]
We can most likely use [tabwriter](https://crates.io/crates/tabwriter) instead.
