### ISSUE TITLE
Add a `shell` command

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#75]
Add a `shell` command to spawn a subshell with an activated Conda environment.

**Why**

To avoid some of the overhead introduced by consecutive `run` invocations. And to not have to type `pixi run` everytime. 

**Inspiration**

https://python-poetry.org/docs/cli/#shell

**Comment by ruben-arts** [comment]
Related PRs
#116  and https://github.com/mamba-org/rattler/pull/224

**Comment by ruben-arts** [comment]
Shipped in `v0.0.5`
