### ISSUE TITLE
Support specifying channel per package (e.g. `<channel>::<package>`)

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#76]
Would be nice if we can pull certain packages from certain channels using the `conda-canary/label/dev::conda` syntax.

Perhaps a better syntax for us would be:

```toml
conda = { version = "*", channel = "conda-canary/label/dev" }
```

This requires that we parse dependencies a little differently.

**Comment by mjkanji** [comment]
This would be a very useful feature to have, especially when working with DL libraries, where installing the Nvidia versions of drivers and CUDA-related packages is preferred over the conda-forge equivalent.

**Comment by baszalmstra** [comment]
@travishathaway is working on this issue.

**Comment by travishathaway** [comment]
Just FYI...

I will try to follow how this was done in Cargo to make it work (see here: https://github.com/rust-lang/cargo/blob/b644a40a1f8406a08bc64305a6a8fd6bb5a34071/src/cargo/util/toml/mod.rs#L218-L262)

**Comment by baszalmstra** [comment]
Sounds perfect! Im not sure if this was your intention already but I propose that we split the entire matchspec struct out into this "new" form. That would forgo all complex matchspec parsing. WDYT?

**Comment by travishathaway** [comment]
@baszalmstra,

That sounds like a good idea.

So, going forward this is what we will want:

- When a string is provided, it will be treated as a [VersionSpec](https://github.com/mamba-org/rattler/blob/9591c1b020bf4bd60a6082efcd1e2c06fc710ad5/crates/rattler_conda_types/src/version_spec/mod.rs#L79) 
- When a mapping is provided, it will be treated as a [NamelessMatchSpec](https://github.com/mamba-org/rattler/blob/9591c1b020bf4bd60a6082efcd1e2c06fc710ad5/crates/rattler_conda_types/src/match_spec/mod.rs#L230)

**Comment by baszalmstra** [comment]
I like it! 👍

**Comment by travishathaway** [comment]
Brief update: there's actually a very easy way to implement this with `serde_with` using `PickFirst`:

- https://docs.rs/serde_with/latest/serde_with/struct.PickFirst.html

Pull request coming soon... 😄

**Comment by travishathaway** [comment]
I've opened this pull request in rattler. This should provide everything to get my proposed solution working:

- https://github.com/mamba-org/rattler/pull/299

**Comment by ruben-arts** [comment]
Channel specific works since `v0.7.0`. 
```toml
package = { version = "1.2.3", channel = "https://repo.prefix.dev/foo-bar-channel" }
```
Some caveats still, these can be looked at later when the need for those increases:
- Only uses channels from `project.channels` list. 
- Doesn't support the label channels yet.
