### ISSUE TITLE
Can't remove packages which include caps after adding them with caps

### ISSUE THREAD

**Issue by notPlancha** [prefix-dev/pixi#761]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
> pixi init temp
✔ Initialized project in ...
> cd temp
> pixi add MatPlotLib
✔ Added MatPlotLib
> pixi remove MatPlotLib
× Couldn't find MatPlotLib in [dependencies]
> pixi remove matplotlib
× Couldn't find matplotlib in [dependencies]
```
> pixi.toml
```toml
[dependencies]
MatPlotLib = ">=3.8.2,<3.9"
```

### Issue description

If you add a package and devide to write for example `pixi add MatPlotLib`, pixi adds the correct conda package (in this case matplotlib), but removing through the pixi commands doesn't work after. This is even more noticeable if you accidently add as the name in pypi, which sometimes have caps (e.g. in PyPi is "GitPython" but in conda-forge it's "gitpython")

### Expected behavior

I think it should detect and remove the package, similar to the no caps versions

**Comment by ruben-arts** [comment]
Yep this is a bug! Thanks for reporting!
