### ISSUE TITLE
Alert of new pixi version releases

### ISSUE THREAD

**Issue by 3f6a** [prefix-dev/pixi#763]
### Problem description

Other command line tools (like Github CLI, juliaup, ...) automatically check in the background whenever a command is used (like `pixi add` or something similar), and print an info message when there are updates available.

Would be nice if `pixi` did something similar, asking the user to run `pixi self-update` whenever it finds there are new versions available.

**Comment by ruben-arts** [comment]
There are a few questions that come to mind:
- When would you want to get this alert? I guess, for every command would be to much. 
- Implementing it for every package manager would be extreme so only do it for the GitHub releases? 
- Should it have a certain delay? Like power users might want to be quick to the punch but most users probably don't care about being on par with the latest and greatest every time. 
- Should we (pixi devs) have the power to trigger this? e.g. we do a important bug fix , should we sendout a alert? And on normal we could skip it? 
- How would we turn it off if the user doesn't care. Is it a onetime request? Is it an env variable.

**Comment by ruben-arts** [comment]
Not doing this for now. Maybe after a release v1

**Comment by ruben-arts** [comment]
I closed it because it was stale, and we want to avoid clutter. It's not a bad idea just not worth the work and maintenance for now in my opinion. 

Still open to PR as always.
