### ISSUE TITLE
`pixi list` should print a warning or fail when lockfile is not up to date

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#774]
After manually tinkering in `pixi.toml`, `pixi list` doesn't reflect these changes unless I run `pixi install`. Maybe a warning like `Warning: your lockfile is not up to date. Please run 'pixi install' to update your lockfile` could be nice.

**Comment by ruben-arts** [comment]
Should it even self install or just throw a warning?

**Comment by pavelzw** [comment]
I guess we could also do self-install on `pixi list`. I don't have strong opinions on that but maybe it's better since we do it like this for other cases as well 🤷🏻
