### ISSUE TITLE
`pixi add` autocompletion

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#778]
### Problem description

Basically the same as https://github.com/mamba-org/mamba/issues/3173 but for pixi :)

**Comment by ruben-arts** [comment]
I assume you mean `pixi add` or `pixi global install` but this is much harder in Rust as we can't generate functions automatically for the shell auto-completion.

**Comment by ruben-arts** [comment]
This is the biggest UX improvement we can do in my opinion but currently I see no way we could do this in a maintainable way without a library that can generate autocomplete scripts for multiple shells. And I don't think we should shift focus to build something like that ourselfs at this point in time. 

There are a few conversations on `clap` and `clap_complete`, the combining issue: https://github.com/clap-rs/clap/issues/1232 

Closing this for now
