### ISSUE TITLE
Add `--task` to `pixi shell-hook`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#781]
### Problem description

`pixi shell-hook --command "python -m my_app"` would mean that `python -m my_app` gets appended to the shell hook.

This would be benefitial for dockerfiles.

I currently use this hack in docker:

```dockerfile
RUN pixi shell-hook -e prod > /shell-hook
RUN echo "my-app" > /shell-hook
```

**Comment by pavelzw** [comment]
Would be even better if we could bake the activation script _in_ the dockerfile but I'm not sure if it's even possible to do so without dynamically generating a `Dockerfile`...

**Comment by ruben-arts** [comment]
What is the benefit of having it in a pixi cli option over just piping as you do? This way it's at least clear what your moving into the shell hook. 

I could imagine a way to use the task logic in this but we run `deno_task_shell` in the tasks which isn't installed without `pixi` thus I don't see the benefit of adding it to the shell hook compared to running `pixi run task`

**Comment by pavelzw** [comment]
> What is the benefit

DRY 😄 

> but we run deno_task_shell in the tasks

valid point 🤔 

> compared to running `pixi run task`

in my target environment, `pixi` is not available (i only copy the prod env and the shell hook file into the prod docker image, see [here](https://github.com/prefix-dev/pixi/discussions/690#discussioncomment-8433865)). Thus, I cannot run `pixi run task` but need to somehow put the task into the production container.

**Comment by ruben-arts** [comment]
> are there cases where deno task shell does something different than bash?
Not that I know off, but the fact that it isn't guaranteed, makes it harder to implement.
Plus I want to avoid as much as possible that we merge non cross platform solutions. Especially so close to the end user of an environment.

**Comment by pavelzw** [comment]
hmm yeah, i get that... i wonder if there is a deno-task-shell to XYZ converter 🤔

**Comment by ruben-arts** [comment]
Or ship `deno_task_shell` as a bin. Not sure how large that would be.

**Comment by pavelzw** [comment]
I like to have my docker images as small as possible 😅 if we were to ship deno_task_shell as a bin, i would probably just manually do `echo "my-app" > /shell-hook` anyway so no real point in that IMO

**Comment by baszalmstra** [comment]
Since we would need to ship deno for this to function properly and since the OP says they dont want to use that Im going to close this issue. Feel free to reopen!
