### ISSUE TITLE
Allow `pixi init` to start with an template.

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#786]
### Problem description

As a user I would like to start a project with a template. This might be helpful for tutorials.

This is also nice of developers that ship their code to customers with the intent for them to use `pixi`. 

My design proposal would be that `pixi init` can except a `--template` option which can hold either a name for the default templates that the prefix-dev org proposes, or it can except urls to git repositories. 

```
pixi init --template python
pixi init --template rust
pixi init --template https://github.com/prefix-dev/pixi-python-template
```

**Comment by roaldarbol** [comment]
This would be great! I was going to be implementing this within the {pixi} R package, but if you'll implement it within pixi I'd be happy to help develop a good template for R here!

**Comment by baszalmstra** [comment]
perhaps instead of reinventing the wheel we could use https://github.com/cookiecutter/cookiecutter (which you can install with pixi of course 😉  )

**Comment by pavelzw** [comment]
Or [copier](https://github.com/copier-org/copier). Copier has the advantage that you can update your projects if a new version of the template was released. We use it extensively at our company and it works great.

**Comment by pavelzw** [comment]
In copier you can define arbitrary tasks afterwards. In these tasks you might have additional dependencies to copier itself.
Maybe checking for an optional pixi.toml+pixi.lock in the template repo could make sense?

**Comment by pavelzw** [comment]
What would be the benefit of having a global install of copier? Can't we just run `pixi runx copier copy ...` once #624 is implemented?

**Comment by baszalmstra** [comment]
Yes even better!

**Comment by roaldarbol** [comment]
What's the status on this issue? If https://github.com/prefix-dev/pixi/pull/1442 gets merged, does that also mean this issue could be solved?

**Comment by pavelzw** [comment]
Then somebody would need to create a template (i wanted to do that anyway at some point) and then we could link it in the docs for example.

**Comment by roaldarbol** [comment]
Coolio, I can make a basic one for R next week. ☺️

**Comment by roaldarbol** [comment]
Have made a template we can use to test. It's the first time I've made a template, so just let me know or make a PR if anything needs to be changed. :) https://github.com/roaldarbol/r-template/

**Comment by tdejager** [comment]
Yeah @roaldarbol, I think you are right. Could you give the `exec` branch a go maybe :)?

**Comment by roaldarbol** [comment]
I might find time to test it over the weekend, but can't promise it. The only thing that I found was an issue with the template is pulling github user.name and email. `pixi` has some functions for that, but I don't know how we would incorporate them with `copier`.

Re the user-facing implementation - If it works with `exec`, would we just make an extra argument (`--template`) that then instead calls `pixi exec copier copy path/to/template current-folder`? (So if I were to call `pixi init --template r` or `pixi init --template gh:roaldarbol/r-template`)

**Comment by pavelzw** [comment]
i would suggest just writing something like the following in your readme

---

To initialize your repository, please run

```
pixi exec copier copy --trust https://github.com/roaldarbol/r-template.git .
```

**Comment by roaldarbol** [comment]
Added a README with some suggested ways of using it - which will of course be dependent on how this issue is implemented in the end. :-)

**Comment by robinlovelace-ate** [comment]
Update on this: just tried out the solution

```
pixi exec copier copy --trust https://github.com/roaldarbol/r-template.git .
```

and it seems to have worked, creating an .Rproj file and everything!

**Comment by robinlovelace-ate** [comment]
See commit above the previous comment for details..

**Comment by robinlovelace-ate** [comment]
After that I tried

```sh
pixi install
```

But alas I got " WARN Not installing dependency on current platform: (linux-64) as it is not part of this project's supported platforms." and R seems to have not been installed. Any ideas how to fix this @roaldarbol ?

**Comment by roaldarbol** [comment]
Hi @robinlovelace-ate! Great to see someone try it out! Yeah, I've realised this, I'll patch in the coming days - for now, in `pixi.toml`, you'll just need to change  `platforms = ["osx-64"]` to `platforms = ["linux-64"]` (as I assume you're on a Linux computer 😊).

**Comment by robinlovelace-ate** [comment]
Just realised that at the same time, patched and things now happening: 
![image](https://github.com/prefix-dev/pixi/assets/122299965/4a07a5f4-ee0a-4fc5-87cc-24a97b54ec0b)

**Comment by robinlovelace-ate** [comment]
Next question: how do I get R repl? I tried R but got "command not found".

**Comment by robinlovelace-ate** [comment]
```
pixi install
✔ The default environment has been installed.
root@codespaces-837842:/workspaces/netgen# R
bash: R: command not found
```

**Comment by pavelzw** [comment]
Currently working on the Python template, hopefully it's done soon.

**Comment by robinlovelace-ate** [comment]
```
pixi shell
R
```

works 🎉

**Comment by robinlovelace-ate** [comment]
How can I make that shell env load by default?

**Comment by roaldarbol** [comment]
@robinlovelace-ate I've made an issue for the platform question here: https://github.com/roaldarbol/r-template/issues/2
You can ask more questions on that repo, I think it's probably a better place - but happy to try helping out! 

Yup, you'll need to *either* make a `pixi shell` first, *or* run `pixi run R`.

**Comment by roaldarbol** [comment]
@pavelzw Let's chat a bit on Discord about the templates, I'd be really interested to ensure feature parity between the templates!

**Comment by robinlovelace-ate** [comment]
Another observation after trying to run R from the installed path, without `pixi shell`:

```
/workspaces/netgen/.pixi/envs/default/bin/R

R version 4.4.0 (2024-04-24) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
6: Setting LC_PAPER failed, using "C" 
7: Setting LC_MEASUREMENT failed, using "C" 

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Segmentation fault (core dumped)
```

**Comment by roaldarbol** [comment]
The R template now works for VS Code too.

**Comment by pavelzw** [comment]
our template for open source python projects that are managed with pixi: https://github.com/Quantco/copier-template-python-open-source

Still wip and not tested much yet, though. Adding automatic docs generation is on my roadmap

**Comment by ruben-arts** [comment]
With all the copier and cookiecutter templates coming in i would like to let those tools take over this request for now. Closing as stale and not the focus for now.
