### ISSUE TITLE
Move `prefix` struct to `rattler`

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#8]
There is a utility struct called `Prefix` in the current repository. It contains high level code to interact with a conda environment on disk. It would be nice to move this to the `rattler` crate and add additional functionalities to it (like executing a transaction on it).

https://github.com/prefix-dev/pax/blob/7231f7ccccdb39f7e75dc3059aa6fd3abdf402ee/src/prefix.rs#L7-L8

**Comment by baszalmstra** [comment]
Im not entirely sure whether or not we should do this still. There is some functionality (like discovering installed packages) that should be moved, but the `Prefix` struct itself has grown to incorporate pixi specific stuff.

**Comment by ruben-arts** [comment]
Closing for now, open for to long without anything, reopen if still relevant
