### ISSUE TITLE
Installing pip packages from GitHub

### ISSUE THREAD

**Issue by zacmon** [prefix-dev/pixi#808]
### Problem description

Hi,

Thanks so much for creating this tool! It's super promising! Perhaps I missed it in the documentation, how do I go about putting packages in the pixi.toml file which I want to pip install from GitHub? As far as I can infer, this seems separate from [pypi-dependencies]. 

Thanks and take good care,
Zach

**Comment by ruben-arts** [comment]
He Zach,

Thank you, glad you like it. 

The git dependencies are not yet something we can support in pixi. Documentation on limitations can be found here: https://pixi.sh/configuration/#the-dependencies-tables.

That talks about the `[pypi-dependencies]` for the normal `[dependencies]` we don't have a concrete plan to support source packages yet. 

Hope this answers your question for now. 

Ruben

**Comment by zacmon** [comment]
Understood, thanks for you prompt response!
