### ISSUE TITLE
The combination of --no-install and --pypi options leads to an error

### ISSUE THREAD

**Issue by olivier-lacroix** [prefix-dev/pixi#817]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
mkdir /tmp/fcdnzjakle
cd /tmp/fcdnzjakle
pixi init
pixi add python
pixi add --no-install --pypi pandas
```

### Issue description

The combination of --no-install and --pypi options leads to a failure with

`Cannot update pypi dependencies without first installing a conda prefix that includes python.`

### Expected behavior

No error if python has been installed previously in the project

**Comment by ruben-arts** [comment]
I think this is an easier change now as the conda and pypi resolve are less coupled in the last release. 

Will get back to this.

**Comment by olivier-lacroix** [comment]
Thanks @ruben-arts !

FYI, I stumbled upon this issue when trying to add pixi in the uv benchmark scripts. I did my best based on my understanding of pixi, but feel free to propose changes there to ensure it is a fair comparison :-)

**Comment by ruben-arts** [comment]
Thank you @olivier-lacroix, we'll definitely take a look at that!

**Comment by tdejager** [comment]
Maybe we should add the packaging ecosystem as an argument for --no-install seeing as you do want to install pypi for the benchmark.

Btw @olivier-lacroix we have been keeping a close eye on the uv release, congrats 🎉! Great work! 😄

**Comment by olivier-lacroix** [comment]
@tdejager , I must say I have nothing to do with it. I am just a bystander 🤭.

**Comment by olivier-lacroix** [comment]
@tdejager , in the benchmark, I am actually trying to only add the pypi packages to the lockfile without installing them, by installing adding python first, then adding the pypi packages with the `--no-install` flag.

I am not even sure having python _installed_ should be needed for a `--no-install`: wouldn't having python in the lockfile be sufficient?

**Comment by tdejager** [comment]
Because we don't depend on a system python for pixi, we want to make completely stand-alone and also makes it possible to use one project for multiple python versions, we need a python version for building source distributions.

**Comment by olivier-lacroix** [comment]
@tdejager for building source distribution I agree. But in case we 'only' want to generate the lockfile, that should not be required, right? as long as we know the python version. Which is what the `--no-install` does if my understanding is correct?

**Comment by wolfv** [comment]
@olivier-lacroix for the purpose of benchmarking, you could build `rip` using `cargo` and then run the included binary. E.g. 

```sh
cargo b --release
$ ./target/release/rip --help                                                                                                                                                                                                                                           
Binary to verify and play around with rattler_installs_packages

Usage: rip [OPTIONS] <COMMAND>

Commands:
  wheels   Options w.r.t locally built wheels
  resolve  Resolve a set of requirements and output the resolved versions
  install  Resolve and install a set of requirements
  help     Print this message or the help of the given subcommand(s)

Options:
  -v, --verbose...             Increase logging verbosity
  -q, --quiet...               Decrease logging verbosity
      --index-url <INDEX_URL>  Base URL of the Python Package Index (default <https://pypi.org/simple>). This should point to a repository compliant with PEP 503 (the simple repository API) [default: https://pypi.org/simple/]
  -h, --help                   Print help
  -V, --version                Print version
```

You could use the `resolve` option to only resolve some binaries. This will find the system Python interpreter.

**Comment by ruben-arts** [comment]
Closing this issue as the reason for this issue is not required anymore.
