### ISSUE TITLE
Don't leave `pixi.toml` in broken state

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#825]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi add flask
pixi add Flask
pixi install
```

### Issue description

The before mentioned example results in an error on the `install` because we don't allow duplicates. 
But `add` allows you to add duplicates

### Expected behavior

Don't allow duplicates. Error on the add if the normalized version already exists in toml

**Comment by orhun** [comment]
Hey! I'm working on this.
