### ISSUE TITLE
Create pixi docker image

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#844]
### Problem description

It would be nice to have an official pixi docker image.

Something like

```dockerfile
# uses ubuntu as base image
FROM ghcr.io/prefix-dev/pixi:latest
FROM ghcr.io/prefix-dev/pixi:0.14.0
FROM ghcr.io/prefix-dev/pixi:0.14.0-ubuntu

# uses alpine as base image
FROM ghcr.io/prefix-dev/pixi:latest-alpine
FROM ghcr.io/prefix-dev/pixi:0.14.0-alpine
```

Since pixi already comes as a static binary, I would suggest to only get the release binary from this repo, copy pixi to `/usr/local/bin/pixi` and do nothing else.

**Comment by pavelzw** [comment]
Fixed with https://github.com/prefix-dev/pixi-docker

**Comment by baszalmstra** [comment]
You are amazing! 🚀

**Comment by ruben-arts** [comment]
Thanks @pavelzw! :1st_place_medal:
