### ISSUE TITLE
`pixi shell` Command Doesn't Work With Fish

### ISSUE THREAD

**Issue by zicklag** [prefix-dev/pixi#864]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell

/tmp
➜ cd test/

/tmp/test
➜ pixi shell
 source "/tmp/pixi_env_Tpp.fish"

/tmp/test
➜  source "/tmp/pixi_env_Tpp.fish"
/tmp/pixi_env_Tpp.fish (line 11): $(...) is not supported. In fish, please use '(old_fish_prompt)'.
functions -c fish_prompt old_fish_prompt; function fish_prompt; echo "(test) $(old_fish_prompt)"; end;
                                                                             ^
from sourcing file /tmp/pixi_env_Tpp.fish
source: Error while reading file “/tmp/pixi_env_Tpp.fish”

/tmp/test
➜ tail -n 1 /tmp/pixi_env_Tpp.fish
functions -c fish_prompt old_fish_prompt; function fish_prompt; echo "(test) $(old_fish_prompt)"; end;

/tmp/test
➜ pixi --version
pixi 0.15.1
```

### Issue description

When running `pixi shell`, I get an error about invalid fish syntax. Running `eval (pixi shell-hook)` works as expected.

It appears that the issue only happens when setting the prompt, which is not modified by `pixi shell-hook`, so that's probably why it works.

### Expected behavior

I should get a pixi environment shell without an error.

**Comment by zicklag** [comment]
Just discovered that `eval (pixi shell-hook)` does not work properly, as it only sets the path. The proper workaround is to run `pixi shell-hook | source`.

**Comment by ruben-arts** [comment]
Apparently both `pixi shell` and `starship init fish` overwrite the `function fish_prompt`.  We should look into how to avoid that overwrite in fish. Maybe @tdejager knows some tricks? 

`eval "$(pixi shell-hook)"` works but the `| source` is advised as the `shell-hook` doesn't need `stdin`
