### ISSUE TITLE
`pixi global list` fails with error `No such file or directory (os error 2)` after fresh install

### ISSUE THREAD

**Issue by corneliusroemer** [prefix-dev/pixi#870]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```bash
$ brew install pixi
$ pixi global list
  × No such file or directory (os error 2)
```

### Issue description

When I run `pixi global list` on a fresh install, I get a not-super-nice error `No such file or directory (os error 2)`

Presumably you expect me to run list only after install, but in any case the error message should be better - and ideally this shouldn't error at all.

### Expected behavior

No error, or at least a clearer error message saying what I need to do instead.

**Comment by baszalmstra** [comment]
A fix for that has coincidentally just been merged! https://github.com/prefix-dev/pixi/pull/865
