### ISSUE TITLE
Allow specification of `--platform` in `pixi global install`

### ISSUE THREAD

**Issue by corneliusroemer** [prefix-dev/pixi#872]
### Problem description

I can't install `nextclade` globally on my M1 mac because it's in `bioconda/osx-64`.

```bash
$ pixi global install nextclade -c bioconda           
  × Cannot solve the request because of: No candidates were found for nextclade *.
  │ 
```

Adding `--platform osx-64` doesn't seem to work either:

```bash
$ pixi global install nextclade -c bioconda --platform osx-64
error: unexpected argument '--platform' found

  tip: to pass '--platform' as a value, use '-- --platform'

Usage: pixi global install <PACKAGE|--channel <CHANNEL>>

For more information, try '--help'.
```

Would be good if there was a way, maybe I'm missing something. [StackOverflow crosspost](https://stackoverflow.com/questions/78067379/how-to-specify-the-architecture-platform-for-a-channel-for-a-global-pixi-install)

**Comment by mfansler** [comment]
Have you tried `-c bioconda/osx-64`? That mode usually needs an explicit `-c bioconda/noarch` as well.

**Comment by ruben-arts** [comment]
Related response: https://github.com/prefix-dev/pixi/issues/875#issuecomment-1968379709

**Comment by wolfv** [comment]
This is implemented now (with the `--platform` flag in `global install`).
