### ISSUE TITLE
No candidates were found for anndata2ri *.

### ISSUE THREAD

**Issue by partrita** [prefix-dev/pixi#882]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
 pixi add anndata2ri
 WARN pixi::project::manifest: BETA feature `[pypi-dependencies]` enabled!

Please report any and all issues here:

        https://github.com/prefix-dev/pixi.

Turn this warning off by setting the environment variable `PIXI_BETA_WARNING_OFF` to `true`.

  × could not determine any available versions for anndata2ri on linux-64. Either the package
  │ could not be found or version constraints on other dependencies result in a conflict.
  ╰─▶ Cannot solve the request because of: No candidates were found for anndata2ri *.

```

### Issue description

No candidates were found for anndata2ri *.

### Expected behavior

No problems

**Comment by ruben-arts** [comment]
I'm not sure how your `pixi.toml` is configured but it worked on my `linux-64` machine.

I did need to also add the `bioconda` channel: 
```
➜ pixi project channel add bioconda
✔ Added bioconda (https://conda.anaconda.org/bioconda/)

❯ pixi add anndata2ri
✔ Added anndata2ri
```

**Comment by partrita** [comment]
> I'm not sure how your `pixi.toml` is configured but it worked on my `linux-64` machine.
> 
> I did need to also add the `bioconda` channel:
> 
> ```
> ➜ pixi project channel add bioconda
> ✔ Added bioconda (https://conda.anaconda.org/bioconda/)
> 
> ❯ pixi add anndata2ri
> ✔ Added anndata2ri
> ```

Thank you. Since I'm so used to conda commands, I just figured I'd need to use the add command, my bad for not diving deep into the official docs.

Also, got another question. If I wanna install a specific version of a package from a certain channel, does pixi have a command for that? Like, can I do something along the lines of pixi add -c channel_name package_name?

**Comment by ruben-arts** [comment]
Yeah I was actually thinking we already had that. I remember discussing it. I'll put it on the board.
