### ISSUE TITLE
Path-based source pypi distributions

### ISSUE THREAD

**Issue by pablovela5620** [prefix-dev/pixi#903]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

https://github.com/kcheng1021/GaussianPro
wanted to try out the most recent pixi import from a conda environment from a the recently released GaussianPro model and get the following error from this environment.yml

```shell
pixi init --import environment.yml 
```

environment.yml file
```
name: gaussianpro
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
```

error
```
pixi init --import environment.yml
  × Expected one of `@`, `(`, `<`, `=`, `>`, `~`, `!`, `;`, found `/`
  │ submodules/diff-gaussian-rasterization
  │           ^
```

### Issue description

Looks to be an issue with Path-based source pypi distributions

### Expected behavior

Should install each pypi package

**Comment by ruben-arts** [comment]
We currently don't support path based distributions. This will be coming soon!

**Comment by ruben-arts** [comment]
Closing this in favor of #879
