### ISSUE TITLE
Cannot read global index-url from pip.ini

### ISSUE THREAD

**Issue by IncubatorShokuhou** [prefix-dev/pixi#906]
### Problem description

The current version of `pixi` defaults to downloading from `files.pythonhosted.org` when installing PyPI packages, rather than reading the `index-url` from the local `pip.ini`. This can result in a less efficient download experience for some users, particularly those in China.
I would like to know if this issue will be addressed in a future version.

**Comment by ruben-arts** [comment]
We're planning to support this, however this was delayed by the work on integrating `uv`: https://github.com/prefix-dev/pixi/pull/807.

**Comment by ruben-arts** [comment]
Closing this as unplanned.
