### ISSUE TITLE
Add `pixi upgrade` 

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#912]
### Problem description

Next to `pixi update` defined in #73 we would like to do something like `pixi upgrade` getting inspiration from [`cargo upgrade`](https://crates.io/crates/cargo-edit#cargo-upgrade) 

Where `pixi update` only touches the `pixi.lock`, `pixi upgrade` can also change the `pixi.toml` information. 

For example:
```
# Upgrade all packages in the `pixi.toml` to the latest possible combination.
pixi upgrade 
# Upgrade python to the latest possible with the other package kept to their requirement
pixi upgrade -p/--package python
```

**Comment by pavelzw** [comment]
Maybe also `pixi upgrade --keep-lower-bound`

**Comment by PaulKMueller** [comment]
One short idea:
Might it make sense to name the command `pixi relock` instead of `pixi update` for the command that only touches the `pixi.lock`?
Might get rid of a lot of potential unnecessary confusion of what it does.

**Comment by ruben-arts** [comment]
@PaulKMueller our lock file is, unless specified not to (--no-install), always up to date with the environment. So with my sentence about just touching the `pixi.lock` I meant to say that it only changes the lock file **and** the environment. The `pixi upgrade` also touches the `pixi.toml` and thus the `pixi.lock` and the environment. Sorry for the confusing sentence.

**Comment by roaldarbol** [comment]
For templating, this could also be useful as `copier` could create the environment and then immediately call `pixi upgrade` so users aren't limited to the versions specified at the time the template was generated. Having an option to keep some versions pinned, e.g. language versions such as Python or R, would be great for that.

**Comment by pavelzw** [comment]
> then immediately call pixi upgrade

from my experiences, generating a `pixi.lock` directly after the copier template instantiation leads to a lot of annoying merge conflicts when updating the template.
since `pixi upgrade` will touch this file i'm not sure this is the ideal approach.
also i can imagine that this will generate some other weird merge conflicts when running `copier update`

**Comment by pavelzw** [comment]
how would pixi.toml look before and after a `pixi upgrade --target linux`? i imagine there might be some fragmentation if we didn't use `[target.linux.dependencies]` before

**Comment by pavelzw** [comment]
```
$ cat pixi.toml
[dependencies]
python = ">=3.8.9,<3.9"
$ pixi upgrade --target linux
$ cat pixi.toml
[target.linux.dependencies]
python = ">=3.13.0,<3.14"
[target.win.dependencies]
python = ">=3.8.9,<3.9"
```

or am i understanding `pixi upgrade --target` incorrectly?

**Comment by Hofer-Julian** [comment]
> or am i understanding `pixi upgrade --target` incorrectly?

I think so :)

As described in the comment:

```bash
# Upgrade python in a specific target, if target doesn't exist, error out.
pixi upgrade python --target linux
```

If the target doesn't exist like in your example, we will error out

**Comment by pavelzw** [comment]
then ignore my comment :)

**Comment by pavelzw** [comment]
this can be closed, right?

**Comment by ruben-arts** [comment]
I didn't close it as it isn't a 100% feature complete but I think requests for the extra features can go into seperate issues. So yes lets close.

**Comment by lucascolley** [comment]
> Maybe also `pixi upgrade --keep-lower-bound`

is there a way to do this now? 

I'm not sure if I've found a bug or are looking for a feature, but `pixi upgrade` gives me this:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 65230ed..2a835e4 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -26,7 +26,7 @@ classifiers = [
     "Typing :: Typed",
 ]
 dynamic = ["version"]
-dependencies = ["array-api-compat>=1.10.0"]
+dependencies = ["array-api-compat"]
 
 [project.optional-dependencies]
 tests = [
```

IIUC a user will get a broken environment if they do:

```
uv add array-api-compat=1.9.0 array-api-extra
```

Meanwhile, in `tool.pixi.dependencies` I get what I'm looking for:

```toml
array-api-compat = ">=1.10.0,<2"
```
