### ISSUE TITLE
Windows Security "attack surface reduction" blocks pixi

### ISSUE THREAD

**Issue by maphew** [prefix-dev/pixi#913]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
» $env:PIXI_HOME="D:\apps\pixi"
PS D:\
»  iwr -useb https://pixi.sh/install.ps1 | iex
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-pc-windows-msvc.zip
The binary will be installed into 'D:\apps\pixi\bin'
D:\apps\pixi\bin is already in PATH
PS D:\
» pixi --version
Program 'pixi.exe' failed to run: Access is deniedAt line:1 char:1
+ pixi --version
+ ~~~~~~~~~~~~~~.
At line:1 char:1
+ pixi --version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
```shell
» ls D:\apps\pixi\bin
    Directory: D:\apps\pixi\bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2024-02-29   1:14 PM       24538112 pixi.exe
```

### Issue description

Win10 Enterprise.
Running pixi in powershell yields access denied in console, a security notification shows up saying malware has been blocked. 
"Windows Security >> Protection history" has an item titled _"Risky action blocked. Low."_ expanding details adds:

> Yukon Government [my org] has blocked this action
> App or process blocked: powershell.exe
> Blocked by: Attack surface reduction
> Rule: Use advanced protection against ransomeware.
> Affected items: D:\apps\pixi\bin\pixi.exe

![image](https://github.com/prefix-dev/pixi/assets/486200/fb345730-fa01-46dc-914d-0576fd8ed77b)

Learn more link leads to https://learn.microsoft.com/en-ca/microsoft-365/security/defender-endpoint/troubleshoot-asr?view=o365-worldwide which has instructions for adding exclusions and filing false positive reports, both of which I'll try.

### Expected behavior

pixi would run

**Comment by maphew** [comment]
Attempting to submit the false positive led me to an office365 login form which then asked "why do you need access to this app?" (not verbatim). I filled it out and submitted. I believe this goes to our admin and not to MS.

**Comment by ruben-arts** [comment]
Thanks for the information, please let us know if the internal IT can fix the issue!

**Comment by maphew** [comment]
Submitted to MS, https://www.microsoft.com/en-us/wdsi/submission/a5f7ab76-3044-40dd-8d4b-7e2ac6b54557 (might not be public link).

Current: pending  
Definition version: Cloud, 1.405.808.0  
Current Detection: [Program:Win32/Wacapew.C!ml](https://go.microsoft.com/fwlink/p/?linkid=849967&amp;Name=Program:Win32/Wacapew.C!ml)

**Comment by maphew** [comment]
MS Defender online submission status has changed to 7 counts of "No malware detected". So now it's all up to my central IT, who said they need a list of machine names pixi will be run on so they can whitelist them. Closing this issue as it's now clearly a local system thing.

**Comment by maphew** [comment]
Confirm resolved once central IT whitelisted my workstation.
