### ISSUE TITLE
List Old and New Version in `pixi global upgrade / upgrade-all`

### ISSUE THREAD

**Issue by srilman** [prefix-dev/pixi#914]
### Problem description

Right now, the output of `pixi global upgrade-all` looks like:
```
Upgraded conda-lock 2.5.5
```

Like Cargo, it would be helpful to see both the old and new version of globally upgraded packages. For example (from Cargo output):
```
    Updating indexmap v2.2.4 -> v2.2.5
    Updating insta v1.35.1 -> v1.36.1
    Updating libloading v0.8.1 -> v0.8.2
    Updating mio v0.8.10 -> v0.8.11
    Updating opaque-debug v0.3.0 -> v0.3.1
    Updating reflink-copy v0.1.14 -> v0.1.15
    Updating sysinfo v0.30.5 -> v0.30.6
    Updating walkdir v2.4.0 -> v2.5.0
```

**Comment by chawyehsu** [comment]
It's reasonable to have this, let's see if I could fast implement it.

**Comment by srilman** [comment]
Apologies for not keeping up with the comments, but I ended up implementing it. Will open a PR for it, but feel free to subsume it if you have a better solution.

**Comment by chawyehsu** [comment]
@srilman My implementation #948 is now up for feedback.
