### ISSUE TITLE
docs: Links are not highlighted in light mode

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#939]
https://github.com/prefix-dev/pixi/assets/29506042/3313c7c3-781c-4647-9ccb-100d042c70d3

**Comment by pavelzw** [comment]
<img width="876" alt="image" src="https://github.com/prefix-dev/pixi/assets/29506042/fbe84c6d-ae3a-4353-b8a5-6a913b038247">

@ruben-arts now the dark mode is broken 😓

**Comment by ruben-arts** [comment]
:pray: Thanks pavel, fixed now
