### ISSUE TITLE
`pixi global upgrade` downgrades packages to newest version in default channels

### ISSUE THREAD

**Issue by freundTech** [prefix-dev/pixi#943]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi global install -c conda-forge/label/typst_rc -c conda-forge typst
typst --version  # typst 0.11.0-rc1 (667ea26a)
pixi global upgrade typst  # or upgrade-all
typst --version  # typst 0.10.0 (08adea17)
```

### Issue description

`pixi global upgrade` sometimes downgrades packages.
If a newer version is installed from a non-default (manually passed) channel, running `pixi global upgrade` will downgrade the package to the newest version available in the default channel.

### Expected behavior

`pixi global upgrade`  should never downgrade a package. It should keep the currently installed version.

**Comment by pavelzw** [comment]
Same problem:

```bash
$ pixi global install my-private-tool -c https://my.quetz/get/my-channel -c conda-forge
✔ Installed package my-private-tool 0.12.1 pyh4616a5c_0 from get/my-channel
  These executables are now globally available:
   -  my-private-tool
$ pixi global upgrade my-private-tool
  × Cannot solve the request because of: No candidates were found for my-private-tool *.
  │
$ pixi global upgrade my-private-tool -c https://my.quetz/get/my-channel -c conda-forge
Package my-private-tool is already up-to-date
```

pixi should persist which channels were used when first installing

**Comment by ruben-arts** [comment]
Yeah that makes sense, it should both only update if its a higher version and use the same channel by default!

**Comment by pavelzw** [comment]
`pixi global upgrade -c conda-forge/label/typst_rc -c conda-forge typst` works btw

**Comment by chawyehsu** [comment]
This can be improved combining with #914 , I am working on decoupling functions in the globalcli component to address these two issues.
