### ISSUE TITLE
How to install `pixi` in Git Bash environment?

### ISSUE THREAD

**Issue by jdblischak** [prefix-dev/pixi#965]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
# In Git Bash for Windows
uname -a
## MINGW64_NT-10.0-22631 MSI 3.4.9-be826601.x86_64 2023-09-07 12:36 UTC x86_64 Msys

curl -fsSL https://pixi.sh/install.sh | bash
## This script will automatically download and install Pixi (latest) for you.
## Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-MINGW64_NT-10.0-22631.tar.gz
## The binary will be installed into '/c/Users/john/.pixi/bin'
## #################################################################################################### ############## 100.0%
## error: 'https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-MINGW64_NT-10.0-22631.tar.gz' is not available
```

### Issue description

I would like to use `pixi` in the Git Bash shell for Windows. Thus I followed the [installation instructions for macOS and Linux](https://github.com/prefix-dev/pixi?tab=readme-ov-file#macos-and-linux) because they use `bash`, whereas the [Windows installation instructions](https://github.com/prefix-dev/pixi?tab=readme-ov-file#windows) use `iwr` and `iex` (which don't exist in the PATH for Git Bash).

I'm willing to help troubleshoot the `pixi shell` issue in https://github.com/prefix-dev/pixi/issues/417 if I can get `pixi` installed easily.

### Expected behavior

I expected it to download and install a compatible ~~Linux~~ Windows release of `pixi` for use in Git Bash

**Comment by wolfv** [comment]
Hey @jdblischak – the `install.sh` script is part of this repository. You could try to modify it to install the correct executable on Windows: https://github.com/prefix-dev/pixi/blob/main/install/install.sh

The `pixi shell` is another issue, that we could follow up on.

**Comment by jdblischak** [comment]
> You could try to modify it to install the correct executable on Windows

@wolfv Thanks for the tip! I've started my attempt in https://github.com/prefix-dev/pixi/pull/966
