### ISSUE TITLE
pixi repodata fetching progress bar stays at `0 B @ 0 B/s` and doesn't progress until it's done

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#996]
https://github.com/prefix-dev/pixi/assets/29506042/2d3b347a-5da3-49fe-8e74-ba469773fe45

is this behavior intentional?

**Comment by ruben-arts** [comment]
It isn't and we are very unhappy with it. It is a artifact of our jlap implementation. We plan to work on it soon, so improved feedback is coming!

**Comment by baszalmstra** [comment]
We have since refactored this code significantly. There is still some unclearity when fetching jlap related data but at least now thats visible in the CLI. Closing for now.
